pluginFn['/js/plugins/v2/bpmn.js'] = function(lucid, window) {
	(function(){function m(b,f,a,d){lucid.plugin.initBlockClass({className:b,name:f,searchKeywords:["bpmn","business","event"].concat(a),defaultSize:{w:60,h:60},getLinkPoints:function(a){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(a,b){var c=a.BoundingBox,f=d(a,b);f.unshift({FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:c.x+c.w,y:c.y+c.h/2},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(c.x,c.y,c.w,c.h,0,2*Math.PI)},
{Action:"close"}]});return f}})}function h(b,f,a,d){lucid.plugin.initBlockClass({className:b,name:f,searchKeywords:["bpmn","business","event"].concat(a),defaultSize:{w:60,h:60},getLinkPoints:function(a){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(a,b){var c=a.BoundingBox,f=d(a,b);f.unshift({FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:c.x+c.w-3,y:c.y+c.h/2},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(c.x+
3,c.y+3,c.w-6,c.h-6,0,2*Math.PI)},{Action:"close"}]});f.unshift({FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:c.x+c.w,y:c.y+c.h/2},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(c.x,c.y,c.w,c.h,0,2*Math.PI)},{Action:"close"}]});return f}})}function k(b,f,a,d){lucid.plugin.initBlockClass({className:b,name:f,searchKeywords:["bpmn","business","event"].concat(a),defaultSize:{w:60,h:60},getLinkPoints:function(a){return[{x:.5,y:0},{x:.5,y:1},
{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(a,b){var c=a.BoundingBox,f=d(a,b);f.unshift({FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth+2,Actions:[{Action:"move",x:c.x+c.w,y:c.y+c.h/2},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(c.x,c.y,c.w,c.h,0,2*Math.PI)},{Action:"close"}]});return f}})}function l(b,f,a,d){lucid.plugin.initBlockClass({className:b,name:f,searchKeywords:["bpmn","business","gateway","decision"].concat(a),defaultSize:{w:75,h:75},getLinkPoints:function(a){return[{x:.5,
y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(a,b){var c=a.BoundingBox,f=d(a,b);f.unshift({FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,NoRounding:!0,Actions:[{Action:"move",x:c.x,y:c.y+c.h/2},{Action:"line",x:c.x+c.w/2,y:c.y},{Action:"line",x:c.x+c.w,y:c.y+c.h/2},{Action:"line",x:c.x+c.w/2,y:c.y+c.h},{Action:"close"}]});return f}})}function t(b,f,a,d){lucid.plugin.initBlockClass({className:b,name:f,searchKeywords:"bpmn business task rectangle square activity".split(" ").concat(a),
defaultSize:{w:160,h:120},getLinkPoints:function(a){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},onInit:function(a){lucid.plugin.addBlockTextArea(a,{id:"Text",value:f,getBoundingBox:function(a){return{x:a.x+20,y:a.y,w:a.w-40,h:a.h}}})},getRenderData:function(a,b){var c=a.BoundingBox,f=d(a,b);f.unshift({FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:c.x,y:c.y},{Action:"line",x:c.x+c.w,y:c.y},{Action:"line",x:c.x+c.w,y:c.y+c.h},{Action:"line",x:c.x,
y:c.y+c.h},{Action:"close"}]});return f}})}function r(b,f){return[]}function u(b,f){var a=b.BoundingBox,d=a.x+a.w/2,e=a.y+a.h/2,g=.8*(a.w/2-5),c=.45*(a.h/2-5),a=d-g,g=d+g,p=e-c,c=e+c;return[{FillColor:lucid.color.darken(b.FillColor,.25),StrokeColor:b.LineColor,LineWidth:b.LineWidth,NoRounding:!0,Actions:[{Action:"move",x:a,y:p},{Action:"line",x:g,y:p},{Action:"line",x:g,y:c},{Action:"line",x:a,y:c},{Action:"close"}]},{StrokeColor:b.LineColor,LineWidth:b.LineWidth,NoRounding:!0,Actions:[{Action:"move",
x:a,y:p},{Action:"line",x:d,y:e},{Action:"line",x:g,y:p}]}]}function x(b,f){function a(a,b,d,c,e){var f=Math.cos(b);b=Math.sin(b);return[{Action:"move",x:c+f*a,y:e+b*a},{Action:"line",x:c+f*(a-d),y:e+b*(a-d)}]}for(var d=b.BoundingBox,e=d.x+d.w/2,g=d.y+d.h/2,d=.8*(Math.min(d.w,d.h)/2-5),c=2*d,p=.2*d,h=2*Math.PI,k=Math.PI/6,c=[{Action:"move",x:e+d,y:g},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(e-d,g-d,c,c,0,h)},{Action:"close"}],n=0;n<h;n+=k)c=c.concat(a(d,n,p,e,g));c=c.concat([{Action:"move",
x:e,y:g},{Action:"line",x:e,y:g-.6*d},{Action:"move",x:e,y:g},{Action:"line",x:e+.35*d,y:g}]);return[{FillColor:lucid.color.darken(b.FillColor,.25),StrokeColor:b.LineColor,LineWidth:b.LineWidth,Actions:c}]}function y(b,f){for(var a=b.BoundingBox,d=a.x+a.w/2,e=a.y+a.h/2,g=.7*(a.w/2-5),c=.6*(a.h/2-5),h=d-g,g=d+g,k=e-c,e=e+c,c=.6*(a.w/2-5),a=d-c,d=d+c,c=[],m=(e-k)/5,n=1;4>=n;n++){var l=k+m*n;c.push({Action:"move",x:a,y:l});c.push({Action:"line",x:d,y:l})}return[{FillColor:lucid.color.darken(b.FillColor,
.25),StrokeColor:b.LineColor,LineWidth:b.LineWidth,NoRounding:!0,Actions:[{Action:"move",x:h,y:k},{Action:"line",x:g,y:k},{Action:"line",x:g,y:e},{Action:"line",x:h,y:e},{Action:"line",x:h,y:k}]},{StrokeColor:b.LineColor,LineWidth:b.LineWidth,NoRounding:!0,Actions:c}]}function v(b,f){var a=b.BoundingBox,d=a.x+a.w/2,e=a.y+a.h/2,g=.8*(a.w/2-5),a=.6*(a.h/2-5);return[{FillColor:lucid.color.darken(b.FillColor,.25),StrokeColor:b.LineColor,LineWidth:b.LineWidth,NoRounding:!0,Actions:[{Action:"move",x:d-
g,y:e-.5*a},{Action:"line",x:d+.4*g,y:e-.5*a},{Action:"line",x:d+.4*g,y:e-a},{Action:"line",x:d+g,y:e},{Action:"line",x:d+.4*g,y:e+a},{Action:"line",x:d+.4*g,y:e+.5*a},{Action:"line",x:d-g,y:e+.5*a},{Action:"close"}]}]}function w(b,f){var a=b.BoundingBox,d=a.x+a.w/2,e=a.y+a.h/2,g=.8*(a.w/2-5),a=.8*(a.h/2-5);return[{FillColor:lucid.color.darken(b.FillColor,.25),StrokeColor:b.LineColor,LineWidth:b.LineWidth,NoRounding:!0,Actions:[{Action:"move",x:d,y:e-a},{Action:"line",x:d+.33*g,y:e-.55*a},{Action:"line",
x:d+g,y:e-.55*a},{Action:"line",x:d+.66*g,y:e},{Action:"line",x:d+g,y:e+.55*a},{Action:"line",x:d+.33*g,y:e+.55*a},{Action:"line",x:d,y:e+a},{Action:"line",x:d-.33*g,y:e+.55*a},{Action:"line",x:d-g,y:e+.55*a},{Action:"line",x:d-.66*g,y:e},{Action:"line",x:d-g,y:e-.55*a},{Action:"line",x:d-.33*g,y:e-.55*a},{Action:"close"}]}]}function z(b,f){var a=b.BoundingBox,d=a.x+a.w/2,e=a.y+a.h/2,g=.75*(a.w/2-5),a=.5*(a.h/2-5);return[{FillColor:lucid.color.darken(b.FillColor,.25),StrokeColor:b.LineColor,LineWidth:b.LineWidth,
NoRounding:!0,Actions:[{Action:"move",x:d,y:e},{Action:"line",x:d+g,y:e-a},{Action:"line",x:d+g,y:e+a},{Action:"line",x:d,y:e},{Action:"line",x:d,y:e+a},{Action:"line",x:d-g,y:e},{Action:"line",x:d,y:e-a},{Action:"close"}]}]}function A(b,f){var a=b.BoundingBox,d=a.x+a.w/2,e=a.y+a.h/2,g=.7*(a.w/2-5),a=.7*(a.h/2-5);return[{FillColor:lucid.color.darken(b.FillColor,.25),StrokeColor:b.LineColor,LineWidth:b.LineWidth,NoRounding:!0,Actions:[{Action:"move",x:d-.9*g,y:e+a},{Action:"line",x:d-.3*g,y:e-.4*a},
{Action:"line",x:d+.3*g,y:e+.1*a},{Action:"line",x:d+.9*g,y:e-a},{Action:"line",x:d+.4*g,y:e+.5*a},{Action:"line",x:d-.2*g,y:e-.05*a},{Action:"close"}]}]}function B(b,f){var a=b.BoundingBox;return[{FillColor:lucid.color.darken(b.FillColor,.25),StrokeColor:b.LineColor,LineWidth:b.LineWidth,NoRounding:!0,Actions:[{Action:"move",x:a.x+.33*a.w,y:a.y+.27*a.h},{Action:"line",x:a.x+.5*a.w,y:a.y+.45*a.h},{Action:"line",x:a.x+.67*a.w,y:a.y+.27*a.h},{Action:"line",x:a.x+.73*a.w,y:a.y+.33*a.h},{Action:"line",
x:a.x+.55*a.w,y:a.y+.5*a.h},{Action:"line",x:a.x+.73*a.w,y:a.y+.67*a.h},{Action:"line",x:a.x+.67*a.w,y:a.y+.73*a.h},{Action:"line",x:a.x+.5*a.w,y:a.y+.55*a.h},{Action:"line",x:a.x+.33*a.w,y:a.y+.73*a.h},{Action:"line",x:a.x+.27*a.w,y:a.y+.67*a.h},{Action:"line",x:a.x+.45*a.w,y:a.y+.5*a.h},{Action:"line",x:a.x+.27*a.w,y:a.y+.33*a.h},{Action:"close"}]}]}var q={global:this,provide:function(b){b=b.split(".");q.global[b[0]]=q.global[b[0]]||{};var f=q.global[b[0]];b.slice(1).reduce(function(a,b){a[b]||
(a[b]={});return a[b]},f)},require:function(){},inherits:function(b,f){function a(){}a.prototype=f.prototype;b.superClass_=f.prototype;b.prototype=new a;b.prototype.constructor=b;b.base=function(a,b,g){var c=Array.prototype.slice.call(arguments,2);return f.prototype[b].apply(a,c)}},base:function(b,f,a){var d=arguments.callee.caller;if(q.STRICT_MODE_COMPATIBLE||q.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");
if(d.superClass_)return d.superClass_.constructor.apply(b,Array.prototype.slice.call(arguments,1));for(var e=Array.prototype.slice.call(arguments,2),g=!1,c=b.constructor;c;c=c.superClass_&&c.superClass_.constructor)if(c.prototype[f]===d)g=!0;else if(g)return c.prototype[f].apply(b,e);if(b[f]===d)return b.constructor.prototype[f].apply(b,e);throw Error("goog.base called from a method of one name to a method of a different name");}};q.provide("plugin.bpmn");m("BPMNStartEvent","Start Event",["start"],
r);m("BPMNStartMessageEvent","Start Message Event",["message","email","mail"],u);m("BPMNStartTimerEvent","Start Timer Event",["time","timer","clock"],x);m("BPMNStartRuleEvent","Start Rule Event",["rule"],y);m("BPMNStartLinkEvent","Start Link Event",["link","goto"],v);m("BPMNStartMultipleEvent","Start Multiple Event",["multiple","star"],w);h("BPMNIntermediateEvent","Intermediate Event",["intermediate"],r);h("BPMNIntermediateMessageEvent","Intermediate Message Event",["message","email","mail"],u);h("BPMNIntermediateTimerEvent",
"Intermediate Timer Event",["time","timer","clock"],x);h("BPMNIntermediateRuleEvent","Intermediate Rule Event",["rule"],y);h("BPMNIntermediateLinkEvent","Intermediate Link Event",["link","goto"],v);h("BPMNIntermediateMultipleEvent","Intermediate Multiple Event",["multiple","star"],w);h("BPMNIntermediateCompensationEvent","Intermediate Compensation Event",["compensation","paid","income","receivable","money"],z);h("BPMNIntermediateErrorEvent","Intermediate Error Event",["error"],A);h("BPMNIntermediateCancelEvent",
"Intermediate Cancel Event",["cancel"],B);k("BPMNEndEvent","End Event",["End"],r);k("BPMNEndMessageEvent","End Message Event",["message","email","mail"],u);k("BPMNEndLinkEvent","End Link Event",["link","goto"],v);k("BPMNEndMultipleEvent","End Multiple Event",["multiple","star"],w);k("BPMNEndCompensationEvent","End Compensation Event",["compensation","paid","income","receivable","money"],z);k("BPMNEndErrorEvent","End Error Event",["error"],A);k("BPMNEndTerminateEvent","End Terminate Event",["stop",
"end","terminate"],function(b,f){var a=b.BoundingBox,d=a.x+a.w/2,e=a.y+a.h/2,g=.7*(a.w/2-5),a=.7*(a.h/2-5);return[{FillColor:lucid.color.darken(b.FillColor,.25),StrokeColor:b.LineColor,LineWidth:b.LineWidth,NoRounding:!0,Actions:[{Action:"move",x:d+g,y:e},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(d-g,e-a,2*g,2*a,0,2*Math.PI)},{Action:"close"}]}]});k("BPMNEndCancelEvent","End Cancel Event",["cancel"],B);l("BPMNDataBasedGateway","Exclusive Data-Based Gateway",["exclusive","data"],r);
l("BPMNDataBasedGateway2","Exclusive Data-Based Gateway",["exclusive","data"],function(b,f){var a=b.BoundingBox;return[{StrokeColor:b.LineColor,LineWidth:b.LineWidth+2,NoRounding:!0,Actions:[{Action:"move",x:a.x+.3*a.w,y:a.y+.3*a.h},{Action:"line",x:a.x+.7*a.w,y:a.y+.7*a.h},{Action:"move",x:a.x+.3*a.w,y:a.y+.7*a.h},{Action:"line",x:a.x+.7*a.w,y:a.y+.3*a.h}]}]});l("BPMNEventBasedGateway","Exclusive Event-Based Gateway",["exclusive","event"],function(b,f){var a=b.BoundingBox;return[{StrokeColor:b.LineColor,
LineWidth:b.LineWidth,Actions:[{Action:"move",x:a.x+.8*a.w,y:a.y+.5*a.h},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x+.2*a.w,a.y+.2*a.h,.6*a.w,.6*a.h,0,2*Math.PI)},{Action:"close"}]},{StrokeColor:b.LineColor,LineWidth:b.LineWidth,Actions:[{Action:"move",x:a.x+.75*a.w,y:a.y+.5*a.h},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x+.25*a.w,a.y+.25*a.h,.5*a.w,.5*a.h,0,2*Math.PI)},{Action:"close"}]},{FillColor:lucid.color.darken(b.FillColor,.25),StrokeColor:b.LineColor,
LineWidth:b.LineWidth,NoRounding:!0,Actions:[{Action:"move",x:a.x+.5*a.w,y:a.y+.3*a.h},{Action:"line",x:a.x+.6*a.w,y:a.y+.4*a.h},{Action:"line",x:a.x+.7*a.w,y:a.y+.4*a.h},{Action:"line",x:a.x+.65*a.w,y:a.y+.5*a.h},{Action:"line",x:a.x+.7*a.w,y:a.y+.6*a.h},{Action:"line",x:a.x+.6*a.w,y:a.y+.6*a.h},{Action:"line",x:a.x+.5*a.w,y:a.y+.7*a.h},{Action:"line",x:a.x+.5*a.w,y:a.y+.7*a.h},{Action:"line",x:a.x+.4*a.w,y:a.y+.6*a.h},{Action:"line",x:a.x+.3*a.w,y:a.y+.6*a.h},{Action:"line",x:a.x+.35*a.w,y:a.y+
.5*a.h},{Action:"line",x:a.x+.3*a.w,y:a.y+.4*a.h},{Action:"line",x:a.x+.4*a.w,y:a.y+.4*a.h},{Action:"close"}]}]});l("BPMNInclusiveGateway","Inclusive Gateway",["inclusive"],function(b,f){var a=b.BoundingBox;return[{StrokeColor:b.LineColor,LineWidth:b.LineWidth+2,Actions:[{Action:"move",x:a.x+.7*a.w,y:a.y+.5*a.h},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x+.3*a.w,a.y+.3*a.h,.4*a.w,.4*a.h,0,2*Math.PI)},{Action:"close"}]}]});l("BPMNComplexGateway","Complex Gateway",["complex"],function(b,
f){var a=b.BoundingBox;return[{StrokeColor:b.LineColor,LineWidth:b.LineWidth+2,NoRounding:!0,Actions:[{Action:"move",x:a.x+.5*a.w,y:a.y+.2*a.h},{Action:"line",x:a.x+.5*a.w,y:a.y+.8*a.h},{Action:"move",x:a.x+.2*a.w,y:a.y+.5*a.h},{Action:"line",x:a.x+.8*a.w,y:a.y+.5*a.h},{Action:"move",x:a.x+.3*a.w,y:a.y+.3*a.h},{Action:"line",x:a.x+.7*a.w,y:a.y+.7*a.h},{Action:"move",x:a.x+.3*a.w,y:a.y+.7*a.h},{Action:"line",x:a.x+.7*a.w,y:a.y+.3*a.h}]}]});l("BPMNParallelGateway","Parallel Gateway",["parallel"],function(b,
f){var a=b.BoundingBox;return[{StrokeColor:b.LineColor,LineWidth:b.LineWidth+2,NoRounding:!0,Actions:[{Action:"move",x:a.x+.5*a.w,y:a.y+.2*a.h},{Action:"line",x:a.x+.5*a.w,y:a.y+.8*a.h},{Action:"move",x:a.x+.2*a.w,y:a.y+.5*a.h},{Action:"line",x:a.x+.8*a.w,y:a.y+.5*a.h}]}]});lucid.line.addEndpointStyles("bpmn",{"BPMN Conditional":function(b,f,a,d,e,g){a={StrokeColor:a,LineWidth:d,FillColor:"#ffffff",NoRounding:!0,Actions:[]};d=Math.atan2(f.y,f.x);a.Actions.push({Action:"move",x:b.x,y:b.y});a.Actions.push({Action:"line",
x:b.x+10*Math.cos(d+.75*Math.PI),y:b.y+10*Math.sin(d+.75*Math.PI)});a.Actions.push({Action:"line",x:b.x-15*f.x,y:b.y-15*f.y});a.Actions.push({Action:"line",x:b.x+10*Math.cos(d-.75*Math.PI),y:b.y+10*Math.sin(d-.75*Math.PI)});a.Actions.push({Action:"close"});return[a]}});t("BPMNTask","Task",[],r);t("BPMNMultipleInstanceTask","Multiple Instance Task",["instance","multiple"],function(b,f){var a=b.BoundingBox;return[{FillColor:lucid.color.darken(b.FillColor,.25),StrokeColor:b.LineColor,LineWidth:b.LineWidth,
NoRounding:!0,Actions:[{Action:"move",x:a.x+.38*a.w,y:a.y+.75*a.h},{Action:"line",x:a.x+.44*a.w,y:a.y+.75*a.h},{Action:"line",x:a.x+.44*a.w,y:a.y+.95*a.h},{Action:"line",x:a.x+.38*a.w,y:a.y+.95*a.h},{Action:"close"},{Action:"move",x:a.x+.47*a.w,y:a.y+.75*a.h},{Action:"line",x:a.x+.53*a.w,y:a.y+.75*a.h},{Action:"line",x:a.x+.53*a.w,y:a.y+.95*a.h},{Action:"line",x:a.x+.47*a.w,y:a.y+.95*a.h},{Action:"close"},{Action:"move",x:a.x+.56*a.w,y:a.y+.75*a.h},{Action:"line",x:a.x+.62*a.w,y:a.y+.75*a.h},{Action:"line",
x:a.x+.62*a.w,y:a.y+.95*a.h},{Action:"line",x:a.x+.56*a.w,y:a.y+.95*a.h},{Action:"close"}]}]});t("BPMNSubTask","Collapsed Sub-Process",["sub","process"],function(b,f){var a=b.BoundingBox;return[{StrokeColor:b.LineColor,LineWidth:b.LineWidth,NoRounding:!0,Actions:[{Action:"move",x:a.x+.42*a.w,y:a.y+.75*a.h},{Action:"line",x:a.x+.58*a.w,y:a.y+.75*a.h},{Action:"line",x:a.x+.58*a.w,y:a.y+.95*a.h},{Action:"line",x:a.x+.42*a.w,y:a.y+.95*a.h},{Action:"close"},{Action:"move",x:a.x+.5*a.w,y:a.y+.8*a.h},{Action:"line",
x:a.x+.5*a.w,y:a.y+.9*a.h},{Action:"move",x:a.x+.45*a.w,y:a.y+.85*a.h},{Action:"line",x:a.x+.55*a.w,y:a.y+.85*a.h}]}]});t("BPMNLoopTask","Standard Loop Task",["loop","while","repeat"],function(b,f){var a=b.BoundingBox,d=a.x+.5*a.w+.2*a.w*Math.cos(7*Math.PI/12),e=a.y+.75*a.h+.2*a.h*Math.sin(7*Math.PI/12);return[{StrokeColor:b.LineColor,LineWidth:b.LineWidth+2,Actions:[{Action:"move",x:d,y:e-.04*a.h},{Action:"line",x:d,y:e},{Action:"line",x:d-.04*a.w,y:e},{Action:"move",x:d,y:e},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x+
.4*a.w,a.y+.75*a.h,.2*a.w,.2*a.h,7*Math.PI/12,29*Math.PI/12)}]}]});lucid.plugin.onActivate(function(){lucid.line.enableEndpointStyles("bpmn")});lucid.plugin.createToolGroups({"BPMN Events":"BPMNStartEvent BPMNIntermediateEvent BPMNEndEvent BPMNStartMessageEvent BPMNIntermediateMessageEvent BPMNEndMessageEvent BPMNStartTimerEvent BPMNIntermediateTimerEvent BPMNStartRuleEvent BPMNIntermediateRuleEvent BPMNStartLinkEvent BPMNIntermediateLinkEvent BPMNEndLinkEvent BPMNStartMultipleEvent BPMNIntermediateMultipleEvent BPMNEndMultipleEvent BPMNIntermediateCompensationEvent BPMNEndCompensationEvent BPMNIntermediateErrorEvent BPMNEndErrorEvent BPMNIntermediateCancelEvent BPMNEndCancelEvent BPMNEndTerminateEvent".split(" "),
"BPMN Gateways":"BPMNDataBasedGateway BPMNDataBasedGateway2 BPMNEventBasedGateway BPMNInclusiveGateway BPMNComplexGateway BPMNParallelGateway".split(" "),"BPMN Tasks":["BPMNTask","BPMNMultipleInstanceTask","BPMNLoopTask","BPMNSubTask"]});lucid.plugin.createExchangeGroup("BPMNDataBasedGateway BPMNDataBasedGateway2 BPMNEventBasedGateway BPMNInclusiveGateway BPMNComplexGateway BPMNParallelGateway".split(" "));lucid.plugin.createExchangeGroup(["BPMNTask","BPMNMultipleInstanceTask","BPMNLoopTask","BPMNSubTask"]);
lucid.plugin.createExchangeGroup("BPMNStartEvent BPMNIntermediateEvent BPMNEndEvent BPMNStartMessageEvent BPMNIntermediateMessageEvent BPMNEndMessageEvent BPMNStartTimerEvent BPMNIntermediateTimerEvent BPMNStartRuleEvent BPMNIntermediateRuleEvent BPMNStartLinkEvent BPMNIntermediateLinkEvent BPMNEndLinkEvent BPMNStartMultipleEvent BPMNIntermediateMultipleEvent BPMNEndMultipleEvent BPMNIntermediateCompensationEvent BPMNEndCompensationEvent BPMNIntermediateErrorEvent BPMNEndErrorEvent BPMNIntermediateCancelEvent BPMNEndCancelEvent BPMNEndTerminateEvent".split(" "));
var C="BPMNIntermediateEvent BPMNEndEvent BPMNIntermediateMessageEvent BPMNEndMessageEvent BPMNIntermediateTimerEvent BPMNIntermediateRuleEvent BPMNIntermediateLinkEvent BPMNEndLinkEvent BPMNIntermediateMultipleEvent BPMNEndMultipleEvent BPMNIntermediateCompensationEvent BPMNEndCompensationEvent BPMNIntermediateErrorEvent BPMNEndErrorEvent BPMNIntermediateCancelEvent BPMNEndCancelEvent BPMNEndTerminateEvent BPMNDataBasedGateway BPMNDataBasedGateway2 BPMNEventBasedGateway BPMNInclusiveGateway BPMNComplexGateway BPMNParallelGateway BPMNTask BPMNMultipleInstanceTask BPMNLoopTask BPMNSubTask".split(" ");
lucid.plugin.createNextBlockGroup(C,"BPMNStartEvent BPMNStartMessageEvent BPMNStartTimerEvent BPMNStartRuleEvent BPMNStartLinkEvent BPMNStartMultipleEvent".split(" "));lucid.plugin.createNextBlockGroup(C);lucid.plugin.onDeactivate(function(){lucid.line.disableEndpointStyles("bpmn")})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/bpmn.js.map
};
