pluginFn['/js/plugins/v2/computation.js'] = function(lucid, window) {
	(function(){function e(a,b,c){return{Action:"line",x:a.x+a.w*b,y:a.y+a.h*c}}function l(a,b,c){return{Action:"move",x:a.x+a.w*b,y:a.y+a.h*c}}function y(a,b,c,d,k,f,g){return{Action:"curve",Control:[{x1:a.x+a.w*b,y1:a.y+a.h*c,x2:a.x+a.w*d,y2:a.y+a.h*k,x3:a.x+a.w*f,y3:a.y+a.h*g}]}}function h(){return{Action:"close"}}function L(a,b){var c=.9*Math.min(b.w,b.h);b=lucid.math.Box.create(b.x+(b.w-c)/2,b.y+(b.h-c)/2,c,c);var c=function(a,b,c){return l(a,b/150,c/150)},d=function(a,b,c){return e(a,b/150,c/150)};
switch(a){case "CMP_GoogleSheetsInputBlock":return[[c(b,25,55),d(b,25,125),d(b,125,125),d(b,125,55),d(b,102,55),d(b,102,40),d(b,140,40),d(b,140,47.5),d(b,140,140),d(b,131,140),d(b,19.5,140),d(b,10,140),d(b,10,47.5),d(b,10,40),d(b,48,40),d(b,48,60),d(b,25,60),h(),c(b,82,75),d(b,82,5),d(b,68,5),d(b,68,75),d(b,48,75),d(b,75,115),d(b,102,75),d(b,82,75),h()]];case "CMP_GoogleSheetsOutputBlock":return[[c(b,25,74),d(b,25,125),d(b,125,125),d(b,125,74),d(b,101,74),d(b,101,59),d(b,140,59),d(b,140,66.5),d(b,
140,132.5),d(b,140,140),d(b,10,140),d(b,10,132.5),d(b,10,66.5),d(b,10,59),d(b,49,59),d(b,49,74),d(b,25,74),h(),c(b,82,40),d(b,82,110),d(b,68,110),d(b,68,40),d(b,48,40),d(b,75,0),d(b,102,40),d(b,82,40),h()]];case "CMP_GoogleSheetsListBlock":return[[c(b,140,20),d(b,40,20),d(b,40,38),d(b,140,38),d(b,140,20),h(),c(b,30,20),d(b,10,20),d(b,10,38),d(b,30,38),d(b,30,20),h(),c(b,140,66),d(b,40,66),d(b,40,84),d(b,140,84),d(b,140,66),h(),c(b,30,66),d(b,10,66),d(b,10,84),d(b,30,84),d(b,30,66),h(),c(b,140,112),
d(b,40,112),d(b,40,130),d(b,140,130),d(b,140,112),h(),c(b,30,112),d(b,10,112),d(b,10,130),d(b,30,130),d(b,30,112),h()]];case "CMP_GoogleSheetsDynamicTextBlock":return[[c(b,6.818181818,75),d(b,28.0909091,109),d(b,47.7272727,109),d(b,20.4545455,75),d(b,47.7272727,41),d(b,34.0909091,41),d(b,.818181818,75),h(),c(b,129.545455,75),d(b,102.2727273,109),d(b,115.909091,109),d(b,143.181818,75),d(b,115.909091,41),d(b,102.2727273,41),d(b,129.545455,75),h(),c(b,81.8181818,20),d(b,54.5454545,130),d(b,68.1818182,
130),d(b,95.4545455,20),d(b,81.8181818,20),h()]];case "CMP_AdditionSquareBlock":return[[c(b,68,68),d(b,35,68),d(b,35,82),d(b,68,82),d(b,68,115),d(b,82,115),d(b,82,82),d(b,115,82),d(b,115,68),d(b,82,68),d(b,82,35),d(b,68,35),d(b,68,68),h(),c(b,5,5),d(b,145,5),d(b,145,15),d(b,5,15),d(b,5,5),h(),c(b,5,135),d(b,145,135),d(b,145,145),d(b,5,145),d(b,5,135),h(),c(b,5,5),d(b,5,145),d(b,15,145),d(b,15,5),d(b,5,5),h(),c(b,135,5),d(b,135,145),d(b,145,145),d(b,145,5),d(b,135,5),h()]];default:return[[]]}}function t(a,
b){var c=b.BoundingBox,d=!lucid.object.isObject(b.FillColor)&&lucid.object.areEqual(lucid.color.hex(b.FillColor),lucid.color.hex("#FFFFFF"));return L(a,c).map(function(a){return{FillColor:d?"#F3F3F3":lucid.color.lighten(b.FillColor,.35),StrokeColor:d?"#F3F3F3":lucid.color.lighten(b.FillColor,.35),LineWidth:1,NoRounding:!0,Actions:a}})}function B(){lucid.computation.GoogleSheetCacher.clearCache();setTimeout(B,lucid.computation.GoogleSheetCacher.timeout)}function C(a){var b=a;a=[];for(var c=[],d=/\$([A-Za-z]+)([0-9]*)\b((.|[\n\r])*)/,
k=b.search(d);-1<k;)a.push(b.slice(0,k)),b=d.exec(b.slice(k)),c.push(b[1]+b[2]),b=b[3],k=b.search(d);0<b.length&&a.push(b);return{TextSegments:a,Cells:c}}function M(a){var b=lucid.plugin.getProperty(a,"FormatValue",!0),c="";b.TextSegments.forEach(function(d,k){c+=d;if(b.Cells.length>k){var f=lucid.plugin.getProperty(a,"Cell_"+b.Cells[k],!0);if(null===f||void 0===f)f="Loading";c+=f}});lucid.plugin.setPropertyIfChanged(a,"CMP_TXT_DisplayValue",c,!0)}function N(a){lucid.plugin.getProperty(a,"FormatValue",
!0).Cells.forEach(function(b,c){"val"==b?lucid.plugin.setPropertyIfChanged(a,"Cell_val",lucid.plugin.getProperty(a,"CMP_TXT_Value",!0)||0,!0):D(a,function(c){lucid.plugin.setPropertyIfChanged(a,"Cell_"+b,c,!0)},void 0,b)})}var m={global:this,provide:function(a){a=a.split(".");m.global[a[0]]=m.global[a[0]]||{};var b=m.global[a[0]];a.slice(1).reduce(function(a,b){a[b]||(a[b]={});return a[b]},b)},require:function(){},inherits:function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;
a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){var g=Array.prototype.slice.call(arguments,2);return b.prototype[c].apply(a,g)}},base:function(a,b,c){var d=arguments.callee.caller;if(m.STRICT_MODE_COMPATIBLE||m.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var k=
Array.prototype.slice.call(arguments,2),f=!1,g=a.constructor;g;g=g.superClass_&&g.superClass_.constructor)if(g.prototype[b]===d)f=!0;else if(f)return g.prototype[b].apply(a,k);if(a[b]===d)return a.constructor.prototype[b].apply(a,k);throw Error("goog.base called from a method of one name to a method of a different name");}};m.provide("plugin.common.TextAreaOverflowUtils");plugin.common.TextAreaOverflowUtils.getOnOverflowCallback=function(a,b,c){return function(d,k,f,g,e){if("number"!==typeof g||"number"!==
typeof e||(g+6)%3!=(e+6)%3)g=lucid.plugin.getProperty(null,"Version")||0,e=Math.abs(lucid.text.getTextAreaRotation(d,k)),k!=(c||"Text")||0!==f||5>g||0!==e||plugin.common.TextAreaOverflowUtils.resizeToFitText(d,k,f,a,b)}};plugin.common.TextAreaOverflowUtils.resizeToFitText=function(a,b,c,d,k){var f=lucid.plugin.getProperty(a,"BoundingBox"),g=d(f,a);d=lucid.text.getTextAreaVAlignment(a,b);d="middle"==d?{x:.5,y:.5}:"bottom"==d?{x:.5,y:1}:{x:.5,y:0};b=lucid.text.getTextAreaSpaceSize(a,b,c);b=lucid.math.Box.resizeAboutRelativePoint(g,
d,b);k=k(b,a);b=k.h>f.h;c=lucid.block.getDefaultSize(a).h;k=lucid.math.Box.resizeAboutRelativePoint(f,d,{w:f.w,h:b?Math.max(k.h,f.h):Math.max(k.h,Math.min(f.h,c))});lucid.plugin.setProperty(a,"BoundingBox",k)};m.provide("plugin.computation");m.require("plugin.common.TextAreaOverflowUtils");lucid.computation={};lucid.computation.Environment=function(){this.readyNodes=[];this.nodes=[]};lucid.computation.Environment.prototype.addReadyNode=function(a){this.readyNodes.push(a)};lucid.computation.Environment.prototype.createNode=
function(a){a=new lucid.computation.Node(a,this);this.nodes.push(a);return a};lucid.computation.Environment.prototype.run=function(){var a=this.readyNodes;this.readyNodes=[];a.forEach(function(a){a.run()})};lucid.computation.Environment.prototype.finished=function(){return 1>this.readyNodes.length};lucid.computation.Node=function(a,b){this.inputs={};this.namedOutputs={};this.generalOutputs=[];this.calculation=a;this.environment=b};lucid.computation.Node.prototype.connectInput=function(a){var b=new lucid.computation.Input(this,
null);return this.inputs[a]=b};lucid.computation.Node.prototype.connectOutput=function(a,b){a?this.namedOutputs[a]=b:this.generalOutputs.unshift(b)};lucid.computation.Node.prototype.trigger=function(){var a=!0,b;for(b in this.inputs)null==this.inputs[b].getValue()&&(a=!1);a&&this.environment.addReadyNode(this)};lucid.computation.Node.prototype.run=function(){var a={},b;for(b in this.inputs)a[b]=this.inputs[b].getValue();var c=this.calculation.call(this.calculation,a),d;for(d in c)"general"==d?this.generalOutputs.forEach(function(a){a.setValue(c[d])}):
d in this.namedOutputs&&this.namedOutputs[d].setValue(c[d])};lucid.computation.Target=function(){};lucid.computation.Target.prototype.setValue=function(a){};lucid.computation.Input=function(a,b){this.node=a;this.value=null;this.setValue(b)};lucid.computation.Input.prototype.setValue=function(a){this.value!==a&&(this.value=a,this.node.trigger())};lucid.computation.Input.prototype.getValue=function(){return this.value};lucid.computation.functions={};lucid.computation.functions.adder=function(a){var b=
{general:0};for(key in a)b.general+=a[key];return b};lucid.computation.functions.multiplier=function(a){var b={general:1};for(key in a)b.general*=a[key];return b};lucid.computation.functions.identity=function(a){for(key in a)return{general:a[key]}};lucid.computation.functions.getFunctionByName=function(a){if(0==a.indexOf("lucid.computation.functions")&&(a=a.slice(28),a in lucid.computation.functions))return lucid.computation.functions[a];throw"Unknown function "+a+" in computation plugin";};var E=
function(a,b){return 0==a%1?a.toString():a.toFixed(b)},F=[{name:"Default",func:E},{name:"Currency",func:function(a,b){return"$"+a.toFixed(b)}},{name:"Percent",func:function(a,b){return(100*a).toFixed(b)+"%"}},{name:"Scientific",func:function(a,b){return a.toPrecision(b)}}];lucid.computation.parseNumber=function(a){a=a.replace("$","").replace(",","").trim();var b=Number(a);return isNaN(b)?"%"!=a.substr(a.length-1)||(a=Number(a.substr(0,a.length-1)),isNaN(a))?null:a/100:b};lucid.computation.getFormattedNumber=
function(a,b,c){var d=F.filter(function(b){return b.name==a});return(0<d.length?d[0].func:E).call(null,b,c)};lucid.computation.getNumberLabels=function(a){a=lucid.plugin.getProperty(a,"TextAreas");var b=[],c;for(c in a)if(a[c]&&a[c].Value){var d=lucid.computation.parseNumber(a[c].Value.t);d&&b.push(d)}return b};lucid.computation.getNumber=function(a,b){b=b||1;var c=lucid.computation.getNumberLabels(a);return 1>c.length?b:c[0]};lucid.computation.getOrientedLineEnds=function(a){var b=lucid.plugin.getProperty(a,
"Endpoint1");a=lucid.plugin.getProperty(a,"Endpoint2");return{startEnd:"None"==b.Style?b:a,endEnd:"None"==b.Style?a:b}};lucid.computation.Annotation=function(a,b,c){this.items=a;this.message=b;this.type=c};lucid.computation.CompiledPage=function(a){this.environment=a;this.warnings=[];this.inputTargets={};this.outputTargets={}};lucid.computation.CompiledPage.prototype.addWarnings=function(a){this.warnings=this.warnings.concat(a)};lucid.computation.CompiledPage.prototype.addInput=function(a,b,c){a in
this.inputTargets||(this.inputTargets[a]={});this.inputTargets[a][b]=c};lucid.computation.CompiledPage.prototype.addOutputNode=function(a,b,c){a in this.outputTargets||(this.outputTargets[a]={});this.outputTargets[a][b]=c};lucid.computation.CompiledPage.prototype.refresh=function(a,b,c){"string"===typeof c&&(c=lucid.computation.parseNumber(c)||0);a in this.inputTargets&&b in this.inputTargets[a]&&this.inputTargets[a][b].setValue(c)};lucid.computation.CompiledPage.prototype.run=function(){for(;!this.environment.finished();)this.environment.run();
return!0};lucid.computation.CompiledPage.prototype.getLiveItemIds=function(){return Object.keys(this.inputTargets).concat(Object.keys(this.outputTargets))};lucid.computation.ValueOutput=function(a,b){this.block=a;this.key=b};lucid.computation.ValueOutput.prototype.setValue=function(a){var b=lucid.plugin.getProperty(this.block,"CMP_TXT_"+this.key,!0);if(b!=a){lucid.plugin.setProperty(this.block,"CMP_TXT_"+this.key,a,!0);var c=lucid.plugin.getProperty(this.block,"ChangeCallback",!0);c&&c(b,a,this.key)}};
lucid.computation.Compiler=function(a){this.page=a};lucid.computation.Compiler.prototype.compile=function(){var a=function(a){return!!lucid.plugin.getProperty(a,"Annotations",!0)};lucid.plugin.getAllLineIds(a).concat(lucid.plugin.getAllBlockIds(a)).forEach(function(a){lucid.plugin.setProperty(a,"Annotations",void 0,!0)});var a=this.getActiveElements(),b=a.blocks,c=a.lines;b.concat(c);var a=this.validateBlocks(b),d=this.validateLines(c);if(0<a.length+d.length)return a.concat(d);a=this.findDeadlocks(b,
c);if(0<a.length)return a;var k=new lucid.computation.Environment,f=new lucid.computation.CompiledPage(k),g={};b.forEach(function(a){var b=lucid.computation.functions.getFunctionByName(lucid.plugin.getProperty(a,"CMP_GetCalculation"));g[a]={node:k.createNode(b),targeted:!1}}.bind(this));c.forEach(function(a){var d=lucid.computation.getOrientedLineEnds(a);if(d.startEnd.Block){var e=this.findAttachedBlocks(c,a,d.endEnd);if(0<e.length){var p=k.createNode(lucid.computation.functions.multiplier),h=p.connectInput("block"),
l=p.connectInput("label");f.addInput(a,"label",l);b.forEach(function(a){a==d.startEnd.Block&&g[a].node.connectOutput(null,h)}.bind(this));e.forEach(function(b,c){b in g&&(p.connectOutput(null,g[b].node.connectInput(a+c.toString())),g[b].targeted=!0)}.bind(this))}}}.bind(this));var a=[],e;for(e in g)lucid.plugin.getProperty(e,"CMP_FixedInput")&&g[e].targeted&&a.push(new lucid.computation.Annotation([e],"Block with fixed IO type input cannot be a target of data","Error")),lucid.plugin.setPropertyIfChanged(e,
"CMP_IsInput",!g[e].targeted,!0),g[e].targeted?(d=new lucid.computation.ValueOutput(e,"Value"),g[e].node.connectOutput(null,d),f.addOutputNode(e,"value",g[e].node)):(d=g[e].node.connectInput("value"),f.addInput(e,"value",d));return 0<a.length?a:f};lucid.computation.Compiler.prototype.findAttachedBlocks=function(a,b,c){var d=[],k=lucid.computation.getOrientedLineEnds(b);k.endEnd.Block&&d.push(k.endEnd.Block);this.getAllLinesTouching(b).filter(function(a){return null==c||c!=a}.bind(this)).forEach(function(c){d=
d.concat(this.findAttachedBlocks(a,c,b))}.bind(this));return d};lucid.computation.Compiler.prototype.validateBlocks=function(a){return[]};lucid.computation.Compiler.prototype.getAllLinesTouching=function(a){var b=lucid.plugin.getLinesAttachedTo(a),c=lucid.plugin.getProperty(a,"Endpoint1").Line;a=lucid.plugin.getProperty(a,"Endpoint2").Line;c&&0>b.indexOf(c)&&b.push(c);a&&0>b.indexOf(a)&&b.push(a);return b};lucid.computation.Compiler.prototype.validateLines=function(a){var b=[];a.forEach(function(c){var d=
lucid.plugin.getProperty(c,"Endpoint1"),k=lucid.plugin.getProperty(c,"Endpoint2");"None"!=d.Style&&"None"!=k.Style?b.push(new lucid.computation.Annotation([c],"Action line must have exactly one arrow","Error")):"None"==d.Style&&"None"==k.Style&&b.push(new lucid.computation.Annotation([c],"Action line must have exactly one arrow","Error"));var e="None"==d.Style?d:k,g="None"==d.Style?k:d;g.Line&&(k=a.filter(function(a){return a==g.Line}.bind(this))[0],d=lucid.plugin.getProperty(k,"Endpoint1"),k=lucid.plugin.getProperty(k,
"Endpoint2"),d=d.Line==c?d:k,d.Line==c&&"None"==d.Style||b.push(new lucid.computation.Annotation([c],"Action lines cannot merge","Error")));d=lucid.computation.getNumberLabels(c);e.Line&&0<d.length?b.push(new lucid.computation.Annotation([c],"Branched line cannot have weighting","Error")):1<d.length&&b.push(new lucid.computation.Annotation([c],"Line cannot have multiple weightings","Error"))}.bind(this));return b};lucid.computation.Compiler.prototype.getActiveElements=function(){var a=lucid.plugin.getAllBlockIds(function(a){return-1<
lucid.plugin.getBlockClassName(a).indexOf("CMP_")&&lucid.plugin.getItemPageId(a)==this.page}.bind(this)),b={};a.forEach(function(a){for(var c=lucid.plugin.getLinesAttachedTo(a);0<c.length;){var d=[];c.forEach(function(c){c in b?0>b[c].indexOf(a)&&(b[c].push(a),d=d.concat(this.getAllLinesTouching(c))):(b[c]=[a],d=d.concat(this.getAllLinesTouching(c)))}.bind(this));c=d}}.bind(this));var c=[],d;for(d in b)1<b[d].length&&c.push(d);return{blocks:a,lines:c}};lucid.computation.Compiler.prototype.findDeadlocks=
function(a,b){var c=a.concat(b);if(1>c.length)return[];var d={},k={},e={};c.forEach(function(a){d[a]=!1;k[a]=!1});var g=function(a){var b=lucid.plugin.getLinesAttachedTo(a);lucid.array.removeDuplicates(b);b=lucid.array.filter(b,function(b){b=lucid.computation.getOrientedLineEnds(b).startEnd;return(b.Line||b.Block)==a});if(lucid.plugin.isBlock(a))return b;var c=lucid.computation.getOrientedLineEnds(a).endEnd;return(c=c.Line||c.Block)?b.concat([c]):b},p={};c.forEach(function(a){p[a]=g(a)});var h=function(a,
b){if(d[a])return[b.slice(b.indexOf(a))];if(e[a])return[];d[a]=!0;var c;c=p[a]?lucid.array.flatMap(p[a],function(c){return h(c,b.concat([a]))}):[];d[a]=!1;k[a]=!0;return c},l=[],G;for(G in c){var n=c[G];if(!k[n]){var l=l.concat(h(n,[])),m;for(m in k)k[m]&&(e[m]=!0),k[m]=!1}}return lucid.array.map(l,function(a){return new lucid.computation.Annotation(a,"Loop detected!","Error")})};lucid.computation.panels={};lucid.computation.panels.annotationsPanel=function(a){var b=lucid.template.builder();a={tag:"table",
children:[{tag:"tbody",children:lucid.array.map(a,function(a){return{tag:"tr",children:[{tag:"td",text:a.type},{tag:"td",text:a.message}]}})}]};b.add(a);return b};lucid.computation.panels.gsheetsReactivatePanel=function(a){a=lucid.template.builder();a.addButton({label:"Connect to Sheets",onClick:function(){lucid.computation.googleapp.doWithAuth("ping",[],function(a){lucid.computation.googleapp.reconnectedAlert||(lucid.computation.googleapp.reconnectedAlert=!0,lucid.dialog.alert("We've successfully connected to Google Sheets."))},
function(a){lucid.dialog.alert("We were unable to connected to Google Sheets.")},!0)}});return a};lucid.plugin.onDocumentLoaded(function(){var a=lucid.template.builder(),b=a.add();lucid.plugin.addCustomPanel("Context Panel",null,[{content:a}],null,{isContextPanel:!0,checkShow:function(c){c=c.filter(function(a){return a.isBlock&&0==a.className.indexOf("CMP_")||!!lucid.plugin.getProperty(a.id,"Annotations",!0)});if(1!=c.length)return!1;c=c[0];var d=lucid.template.builder();return(c=lucid.plugin.getProperty(c.id,
"Annotations",!0))?(d=lucid.computation.panels.annotationsPanel(c),a.getElement(b).setContent(d),!0):!1},refreshProperties:"gs_SheetId gs_SheetIdVerified gs_Cell gs_WorksheetId gs_Worksheets gs_SelectionOptions gs_HideControls".split(" ")})});var H=function(){lucid.plugin.getAllBlockIds(function(a){return!!lucid.plugin.getProperty(a,"CMP_UpdateFunction",!0)&&!lucid.plugin.getProperty(a,"CMP_Suspended",!0)}).forEach(function(a){lucid.plugin.getProperty(a,"CMP_UpdateFunction",!0).call(void 0,a);lucid.computation.recalculateAll&&
lucid.computation.recalculateAll()});setTimeout(H,100)};lucid.computation.recompileAll=void 0;lucid.computation.recalculateAll=void 0;lucid.plugin.onDocumentLoaded(function(){function a(a){var b={};a.forEach(function(a){a.items.forEach(function(c){c in b||(b[c]=[]);b[c].unshift({message:a.message,type:a.type})})}.bind(this));for(var k in b)lucid.plugin.setPropertyIfChanged(k,"Annotations",b[k],!0)}H();var b={};lucid.computation.recompileAll=function(){b={};for(var c=lucid.plugin.getAllPages(),d=0;d<
c.length;d++){var k=c[d],e=(new lucid.computation.Compiler(k)).compile();b[k]=e;e.run?(e.getLiveItemIds().forEach(function(a){var b=e;if(lucid.plugin.isBlock(a)){var c=lucid.plugin.getProperty(a,"CMP_TXT_Value",!0);c||(c=lucid.plugin.getProperty(a,"Value").t);b.refresh(a,"value",c,!0)}else!lucid.plugin.isLine(a)||1<lucid.computation.getNumberLabels(a).length||b.refresh(a,"label",lucid.computation.getNumber(a,1),!0)}.bind(this)),e.run()):a(e)}};lucid.computation.recalculateAll=function(){var c=lucid.plugin.getActivePageId(),
d=b[c];d&&(d.run?(d.getLiveItemIds().forEach(function(a){if(lucid.plugin.isBlock(a)){var b=lucid.plugin.getProperty(a,"CMP_TXT_Value",!0);d.refresh(a,"value",b,!0)}else!lucid.plugin.isLine(a)||1<lucid.computation.getNumberLabels(a).length||d.refresh(a,"label",lucid.computation.getNumber(a,1),!0)}.bind(this)),d.run()):a(d))};lucid.computation.recompileAll()});lucid.computation.renderErrors=function(){var a=function(a){return a.some(function(a){return"Error"==a.type})?"#FF0000":"#FFFF00"},b=function(b,
c){var d=lucid.plugin.getProperty(b,"Annotations",!0);d&&lucid.plugin.setPropertyIfChanged(b,c,a(d))},c=lucid.plugin.getAllBlockIds(function(a){return!!lucid.plugin.getProperty(a,"Annotations",!0)}),d;for(d in c)b(c[d],"FillColor");var c=lucid.plugin.getAllLineIds(function(a){return!!lucid.plugin.getProperty(a,"Annotations",!0)}),e;for(e in c)b(c[e],"LineColor")};lucid.computation.renderDynamicProperties=function(){lucid.plugin.getAllBlockIds().concat(lucid.plugin.getAllLineIds()).forEach(function(a){if(!lucid.plugin.getProperty(a,
"CMP_IsEditing",!0)){var b=lucid.plugin.getAllProperties(a,!0),c;for(c in b)if(0==c.indexOf("CMP_")){var d=b[c];0==c.indexOf("CMP_TXT_")?lucid.plugin.setTextIfChanged(a,c.slice(8),d):lucid.plugin.setPropertyIfChanged(a,c.slice(4),d)}lucid.plugin.prerenderActions(a)}})};lucid.computation.isRenderingProperties=!1;lucid.computation.renderProperties=function(){lucid.computation.isRenderingProperties=!0;lucid.computation.renderDynamicProperties();lucid.computation.renderErrors();lucid.computation.isRenderingProperties=
!1};lucid.plugin.provideRenderProperties(lucid.computation.renderProperties);var O=[lucid.ActionType.CreateBlock,lucid.ActionType.CreateLine,lucid.ActionType.SetProperty,lucid.ActionType.RemoveBlock,lucid.ActionType.RemoveLine,lucid.ActionType.CreatePage,lucid.ActionType.RemovePage],P=[lucid.ActionType.EditText];lucid.plugin.onAction(function(a){lucid.computation.isRenderingProperties||lucid.computation.recompileAll&&(-1<O.indexOf(a.Action)?lucid.computation.recompileAll():-1<P.indexOf(a.Action)&&
lucid.computation.recalculateAll())});var n={defaultSize:{w:200,h:150},registerProperties:function(a){lucid.plugin.registerProperty(a,"TextWrap","fit");lucid.plugin.registerProperty(a,"InsetMargin",5);lucid.plugin.registerProperty(a,"CMP_FixedInput",!1);lucid.plugin.registerProperty(a,"CMP_IsEditable",!0);lucid.plugin.registerProperty(a,"CMP_GetCalculation","lucid.computation.functions.adder");lucid.plugin.registerProperty(a,"CMP_HasLabel",!0);lucid.plugin.registerProperty(a,"CMP_Formatter",F[0].name);
lucid.plugin.registerProperty(a,"CMP_FormattingDigits",2);lucid.plugin.hookPropertyPostSave(a,"Value",function(b,c){lucid.plugin.getProperty(a,"CMP_IsInput",!0)&&lucid.plugin.getProperty(a,"CMP_IsEditable")&&lucid.plugin.setProperty(a,"CMP_TXT_Value",c.t,!0)})},onInit:function(a){lucid.plugin.addBlockTextArea(a,{id:"Text",value:"LABEL",vAlign:"bottom",getBoundingBox:function(b){if(!lucid.plugin.getProperty(a,"CMP_HasLabel"))return null;b=lucid.math.Box.pad({x:b.x,y:b.y,w:b.w,h:.4*b.h},-lucid.plugin.getProperty(a,
"InsetMargin")||0);b.hideOverflow=!0;return b}});lucid.plugin.addBlockTextArea(a,{id:"Value",value:"0",vAlign:"middle",getBoundingBox:function(b){var c=.6;lucid.plugin.getProperty(a,"CMP_HasLabel")||(c=1);b=lucid.math.Box.pad({x:b.x,y:b.y+b.h*(1-c),w:b.w,h:b.h*c},-lucid.plugin.getProperty(a,"InsetMargin")||0);b.hideOverflow=!0;return b},beforeTextEdit:function(){var b=lucid.plugin.getProperty(a,"CMP_IsInput",!0)&&lucid.plugin.getProperty(a,"CMP_IsEditable");b&&lucid.plugin.setProperty(a,"CMP_IsEditing",
!0,!0);return b},afterTextEdit:function(){lucid.plugin.setProperty(a,"CMP_IsEditing",!1,!0)}});lucid.plugin.setProperty(a,"CMP_IsInput",!1,!0);n.registerProperties(a)},linkPoints:function(){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderDataKey:function(a){return["FillColor","LineColor","LineWidth"]},baseRenderActions:function(a,b){return[{FillColor:b.FillColor,StrokeColor:b.LineColor,LineWidth:b.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",
x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]}]},prerenderActions:function(a){var b=lucid.plugin.getProperty(a,"Value"),b=(b=b&&b.t)&&lucid.computation.parseNumber(b);if(null!==b&&void 0!==b){var c=lucid.plugin.getProperty(a,"CMP_Formatter"),d=lucid.plugin.getProperty(a,"CMP_FormattingDigits");lucid.plugin.setPropertyIfChanged(a,"Value",lucid.computation.getFormattedNumber(c,b,d))}}},u=function(a,b){var c=lucid.object.clone(n);lucid.object.extend(c,a);return c};lucid.plugin.initBlockClass(u({className:"CMP_AdditionSquareBlock",
name:"Combination Block",searchKeywords:["block","square","rectangle","box"],getRenderData:function(a,b){var c=a.BoundingBox;if("sample"==b){var d=c.w>c.h?c.w:c.h,c=c.x<c.y?c.x:c.y,c={x:c,y:c,w:d,h:d},d=v(c),c=[{FillColor:"#FFFFFF",StrokeWidth:2,Actions:[l(c,.527,.5),e(c,.527,.321),e(c,.455,.321),e(c,.455,.5),e(c,.277,.5),e(c,.277,.571),e(c,.455,.571),e(c,.455,.75),e(c,.527,.75),e(c,.527,.571),e(c,.705,.571),e(c,.705,.5),h()]}];return d.concat(c)}return n.baseRenderActions(c,a).concat(t("CMP_AdditionSquareBlock",
a))}}));var v=function(a){return[{FillColor:"#319F58",line:!1,Actions:[l(a,.107,.107),y(a,.107,.048,.1551,0,.214,0),e(a,.643,0),e(a,.893,.25),e(a,.893,.893),y(a,.893,.952,.845,1,.786,1),e(a,.214,1),y(a,.155,1,.107,.952,.107,.893),e(a,.107,.107),h()]},{FillColor:"#85CBA9",line:!1,Actions:[l(a,.643,0),e(a,.893,.25),e(a,.643,.25),h()]},{FillColor:"#25783F",line:!1,Actions:[l(a,.893,.456),e(a,.893,.25),e(a,.643,.25),h()]}]},q=function(a){a=lucid.plugin.getProperty(a,"gs_SheetId");var b=/(https?:\/\/)?docs.google.com\/spreadsheets\/d\/([^/]*)(\/.*)?/.exec(a);
return b?b[2]:a},w=function(a){try{for(var b=a.search(/[0-9]/),c=Number(a.substring(b)),d=a.substring(0,b).toLowerCase(),b=a=0;b<d.length;b++){var e=d.charCodeAt(b);a=26*a+(e-97+1)}return{r:c,c:a}}catch(f){return null}};lucid.computation.googleapp={id:lucid.config.google_sheets&&lucid.config.google_sheets.appId,mode:lucid.config.google_sheets&&lucid.config.google_sheets.mode,clientId:lucid.config.google_sheets&&lucid.config.google_sheets.clientId,scopes:lucid.config.google_sheets&&lucid.config.google_sheets.scopes,
accessToken:void 0,accessExisted:!1,accessSuspended:!1,reconnectedAlert:!1};lucid.computation.googleapp.makeGoogleSheetCall=function(a,b,c,d){$.ajax({type:"POST",headers:{Accept:"application/json; charset=utf-8",Authorization:"Bearer "+lucid.computation.googleapp.accessToken,"Content-Type":"application/json"},url:"https://script.googleapis.com/v1/scripts/"+lucid.computation.googleapp.id+":run",data:JSON.stringify({"function":a,parameters:b,sessionState:"",devMode:"dev"==lucid.computation.googleapp.mode}),
crossDomain:!0,dataType:"json",success:function(a){a.response?c(a.response.result):a.error&&d&&d(a.error)},error:function(a){d&&d(a)}})};lucid.computation.googleapp.doWithAuth=function(a,b,c,d,e){var f=lucid.plugin.getAllBlockIds(function(a){return 0==lucid.plugin.getBlockClassName(a).indexOf("CMP_Google")}),g=function(e){lucid.computation.googleapp.accessToken=e;lucid.computation.googleapp.accessSuspended=!1;lucid.computation.googleapp.accessExisted=!0;f.forEach(function(a){lucid.plugin.setPropertyIfChanged(a,
"CMP_Suspended",null,!0);var b=lucid.plugin.getProperty(a,"CMP_UpdateFunction",!0);b&&b(a)});lucid.computation.googleapp.doWithAuth(a,b,c,d)},p=function(a){lucid.computation.googleapp.accessSuspended||(lucid.computation.googleapp.accessSuspended=!0,lucid.computation.googleapp.reconnectedAlert=!1,f.forEach(function(a){lucid.plugin.setPropertyIfChanged(a,"CMP_Suspended",!0,!0)}),d&&d(a),setTimeout(lucid.computation.googleapp.doWithAuth.bind(void 0,"ping",[],function(){lucid.computation.googleapp.reconnectedAlert||
(lucid.computation.googleapp.reconnectedAlert=!0,lucid.dialog.alert("We've successfully connected to Google Sheets"))}),6E4))};if(void 0==lucid.computation.googleapp.accessToken||null==lucid.computation.googleapp.accessToken)var h=lucid.plugin.getGoogleAuthorizer(lucid.computation.googleapp.scopes.join(" "),lucid.computation.googleapp.clientId,g,function(a){lucid.computation.googleapp.accessSuspended&&!e||lucid.dialog.confirm(lucid.computation.googleapp.accessExisted?e?"Try to reconnect with Google Sheets?":
"Whoops!  We can't seem to see Google Sheets any more.  Should we try to reconnect?":"A Google Sheets shape is requesting access to Google Sheets.  Allow Lucidchart to access Google Sheets?",function(){h.authorize(g,p,!1)},p,["Yes","No"])});else lucid.computation.googleapp.makeGoogleSheetCall(a,b,c,function(e){401==e.status?(lucid.computation.googleapp.accessToken=void 0,lucid.computation.googleapp.doWithAuth(a,b,c,d)):d&&d(e)})};lucid.computation.GoogleSheetCacher={};lucid.computation.GoogleSheetCacher.cache=
{};lucid.computation.GoogleSheetCacher.pending={};lucid.computation.GoogleSheetCacher.colorCache={};lucid.computation.GoogleSheetCacher.colorPending={};lucid.computation.GoogleSheetCacher.timeout=Number(lucid.config.google_sheets&&lucid.config.google_sheets.timeOutLengthMs)||1E3;lucid.computation.GoogleSheetCacher.cellKey=function(a,b,c){return"R"+c.r+"C"+c.c+":"+a+":"+b};lucid.computation.GoogleSheetCacher.rangeKey=function(a,b,c,d){return"Range"+("R"+c.r+"C"+c.c)+"To"+("R"+d.r+"C"+d.c)+":"+a+":"+
b};lucid.computation.GoogleSheetCacher.clearCache=function(){lucid.computation.GoogleSheetCacher.cache={};lucid.computation.GoogleSheetCacher.colorCache={}};lucid.computation.GoogleSheetCacher.running=!1;lucid.computation.GoogleSheetCacher.setCacheCell=function(a,b){lucid.computation.GoogleSheetCacher.running||(lucid.computation.GoogleSheetCacher.running=!0,setTimeout(B,lucid.computation.GoogleSheetCacher.timeout));b!==lucid.computation.GoogleSheetCacher.cache[a]&&(lucid.computation.GoogleSheetCacher.cache[a]=
b)};lucid.computation.GoogleSheetCacher.getCell=function(a,b,c,d,e,f){var g=lucid.computation.GoogleSheetCacher.cellKey(a,b,c);g in lucid.computation.GoogleSheetCacher.cache?e(lucid.computation.GoogleSheetCacher.cache[g]):lucid.computation.GoogleSheetCacher.pending[d]||(lucid.computation.GoogleSheetCacher.pending[d]=!0,lucid.computation.googleapp.doWithAuth("getCellValues",[a,b,c.r,c.c,1,1],function(a){delete lucid.computation.GoogleSheetCacher.pending[d];a=String(a[0][0]);lucid.computation.GoogleSheetCacher.setCacheCell(g,
a);e(a)},function(a){delete lucid.computation.GoogleSheetCacher.pending[d];f&&f(a)}))};lucid.computation.GoogleSheetCacher.getRange=function(a,b,c,d,e,f,g){var h=lucid.computation.GoogleSheetCacher.rangeKey(a,b,c,d);if(h in lucid.computation.GoogleSheetCacher.cache)f(lucid.computation.GoogleSheetCacher.cache[h]);else if(!lucid.computation.GoogleSheetCacher.pending[e]){lucid.computation.GoogleSheetCacher.pending[e]=!0;var l=Math.min(c.r,d.r),m=Math.min(c.c,d.c);lucid.computation.googleapp.doWithAuth("getCellValues",
[a,b,l,m,Math.max(c.r,d.r)-l+1,Math.max(c.c,d.c)-m+1],function(a){delete lucid.computation.GoogleSheetCacher.pending[e];lucid.computation.GoogleSheetCacher.setCacheCell(h,a);f(a)},function(a){delete lucid.computation.GoogleSheetCacher.pending[e];g&&g(a)})}};lucid.computation.GoogleSheetCacher.setCell=function(a,b,c,d){var e=lucid.computation.GoogleSheetCacher.cellKey(a,b,c);lucid.computation.googleapp.doWithAuth("setCellValues",[a,b,c.r,c.c,[[d]]],function(a){lucid.computation.GoogleSheetCacher.clearCache();
lucid.computation.GoogleSheetCacher.setCacheCell(e,d)})};lucid.computation.GoogleSheetCacher.setCacheColor=function(a,b){lucid.computation.GoogleSheetCacher.colorCache[a]=b};lucid.computation.GoogleSheetCacher.getColors=function(a,b,c,d,e,f){var g=lucid.computation.GoogleSheetCacher.cellKey(a,b,c);g in lucid.computation.GoogleSheetCacher.colorCache?e(lucid.computation.GoogleSheetCacher.colorCache[g]):lucid.computation.GoogleSheetCacher.colorPending[d]||(lucid.computation.GoogleSheetCacher.colorPending[d]=
!0,lucid.computation.googleapp.doWithAuth("getCellColors",[a,b,c.r,c.c,1,1],function(a){delete lucid.computation.GoogleSheetCacher.colorPending[d];a=a[0][0];lucid.computation.GoogleSheetCacher.setCacheColor(g,a);e(a)},function(a){delete lucid.computation.GoogleSheetCacher.colorPending[d];f&&f(a)}))};var z=function(a,b,c,d){var e=q(a),f=lucid.plugin.getProperty(a,"gs_WorksheetId");d=d||lucid.plugin.getProperty(a,"gs_Cell");var g=w(d);e&&g&&void 0!=f&&null!=f&&lucid.computation.GoogleSheetCacher.getColors(e,
f,g,a+":"+d,b,c)},D=function(a,b,c,d){var e=q(a),f=lucid.plugin.getProperty(a,"gs_WorksheetId");d=d||lucid.plugin.getProperty(a,"gs_Cell");var g=w(d);e&&g&&void 0!=f&&null!=f&&lucid.computation.GoogleSheetCacher.getCell(e,f,g,a+":"+d,b,c)},I=function(a){var b=q(a),c=lucid.plugin.getProperty(a,"gs_WorksheetId"),d=w(lucid.plugin.getProperty(a,"gs_Cell")),e=lucid.plugin.getProperty(a,"CMP_TXT_Value",!0);if("number"==typeof e){var f=lucid.plugin.getProperty(a,"CMP_Formatter");a=lucid.plugin.getProperty(a,
"CMP_FormattingDigits");e=lucid.computation.getFormattedNumber(f,e,a)}b&&void 0!=c&&null!=c&&d&&e&&lucid.computation.GoogleSheetCacher.setCell(b,c,d,e)},Q=function(a){return function(b){var c=q(a);lucid.plugin.setPropertyIfChanged(a,"gs_SheetIdVerified",!1);c&&lucid.computation.googleapp.doWithAuth("getWorksheets",[c],function(b){if(q(a)==c){lucid.plugin.setPropertyIfChanged(a,"gs_SheetIdVerified",!0);lucid.plugin.setPropertyIfChanged(a,"gs_Worksheets",b);var e=lucid.plugin.getProperty(a,"gs_WorksheetId");
0==b.filter(function(a){return a.id==e}).length&&(lucid.plugin.setPropertyIfChanged(a,"gs_WorksheetId",b[0].id),(b=lucid.plugin.getProperty(a,"CMP_UpdateFunction",!0))&&b(a))}})}},J=function(a,b){lucid.plugin.setPropertyIfChanged(a,"CMP_TXT_Value",b,!0);var c=lucid.plugin.getProperty(a,"ChangeCallback",!0),d=lucid.plugin.getProperty(a,"CMP_TXT_Value",!0);c&&c(d,b,"Value")},A=function(a,b){lucid.plugin.setProperty(a,"CMP_FillColor",b.background,!0)},r=function(a,b){var c=0;return function(d,e,f,g){g||
(c&&clearTimeout(c),c=setTimeout(function(){I(a);c=0},b))}},x=function(a,b){if(void 0===b||!0===b)n.onInit(a);lucid.plugin.hookPropertyPostSave(a,"gs_SheetId",Q(a));for(var c="",d=lucid.plugin.getAllBlockIds(),e=0;!c&&e<d.length;e++)lucid.plugin.getProperty(d[e],"gs_SheetIdVerified")&&(c=lucid.plugin.getProperty(d[e],"gs_SheetId"));c?lucid.plugin.setPropertyIfChanged(a,"gs_SheetId",c):lucid.plugin.setProperty(a,"gs_SheetId","");lucid.plugin.setProperty(a,"gs_Worksheets",[]);lucid.plugin.setProperty(a,
"gs_Cell","")};lucid.plugin.initBlockClass(u({className:"CMP_GoogleSheetsInputBlock",name:"Google Sheets Input",searchKeywords:"google sheets block square rectangle box".split(" "),getRenderData:function(a,b){var c=a.BoundingBox;if("sample"==b){var d=c.w>c.h?c.w:c.h,c=c.x<c.y?c.x:c.y,c={x:c,y:c,w:d,h:d},d=v(c),c=[{FillColor:"#FFFFFF",StrokeWidth:2,Actions:[l(c,.25,.429),e(c,.75,.429),e(c,.75,.821),e(c,.25,.821),h()]},{FillColor:"#319F58",StrokeWidth:2,Actions:[l(c,.286,.464),e(c,.714,.464),e(c,.714,
.786),e(c,.286,.786),h()]},{FillColor:"#429F5B",line:!1,Actions:[l(c,.393,.429),e(c,.607,.429),e(c,.607,.464),e(c,.393,.464),h()]},{FillColor:"#FFFFFF",line:!1,Actions:[l(c,.464,.286),e(c,.536,.286),e(c,.536,.571),e(c,.464,.571),h()]},{FillColor:"#FFFFFF",line:!1,Actions:[l(c,.357,.536),e(c,.5,.714),e(c,.643,.536),h()]}];return d.concat(c)}return n.baseRenderActions(c,a).concat(t("CMP_GoogleSheetsInputBlock",a))},onInit:function(a){x(a);lucid.plugin.setProperty(a,"CMP_FixedInput",!0);lucid.plugin.setProperty(a,
"CMP_IsEditable",!1);lucid.plugin.setProperty(a,"CMP_UpdateFunction",function(a){D(a,function(c){J(a,c)});z(a,function(c){A(a,c)})},!0)}}));lucid.plugin.initBlockClass(u({className:"CMP_GoogleSheetsOutputBlock",name:"Google Sheets Output",searchKeywords:"google sheets block square rectangle box".split(" "),getRenderData:function(a,b){var c=a.BoundingBox;if("sample"==b){var d=c.w>c.h?c.w:c.h,c=c.x<c.y?c.x:c.y,c={x:c,y:c,w:d,h:d},d=v(c),c=[{FillColor:"#FFFFFF",StrokeWidth:2,Actions:[l(c,.25,.429),e(c,
.75,.429),e(c,.75,.821),e(c,.25,.821),h()]},{FillColor:"#319F58",StrokeWidth:2,Actions:[l(c,.286,.464),e(c,.714,.464),e(c,.714,.786),e(c,.286,.786),h()]},{FillColor:"#429F5B",line:!1,Actions:[l(c,.393,.429),e(c,.607,.429),e(c,.607,.464),e(c,.393,.464),h()]},{FillColor:"#FFFFFF",line:!1,Actions:[l(c,.464,.393),e(c,.536,.393),e(c,.536,.678),e(c,.464,.678),h()]},{FillColor:"#FFFFFF",line:!1,Actions:[l(c,.357,.393),e(c,.5,.214),e(c,.643,.393),h()]}];return d.concat(c)}return n.baseRenderActions(c,a).concat(t("CMP_GoogleSheetsOutputBlock",
a))},onInit:function(a){x(a);lucid.plugin.hookPropertyPostSave(a,"gs_WorksheetId",r(a,100));lucid.plugin.hookPropertyPostSave(a,"gs_Cell",r(a,100));lucid.plugin.hookPropertyPostSave(a,"Value",r(a,100));lucid.plugin.setProperty(a,"ChangeCallback",r(a,500),!0);lucid.plugin.setProperty(a,"CMP_UpdateFunction",function(a){z(a,function(c){A(a,c)})},!0)}}));lucid.plugin.initBlockClass(u({className:"CMP_GoogleSheetsListBlock",name:"Google Sheets Dropdown",searchKeywords:"google sheets block square rectangle box".split(" "),
getRenderData:function(a,b){var c=a.BoundingBox;if("sample"==b){var d=c.w>c.h?c.w:c.h,c=c.x<c.y?c.x:c.y,c={x:c,y:c,w:d,h:d},d=v(c),c=[{FillColor:"#FFFFFF",line:!1,Actions:[l(c,.321,.393),e(c,.75,.393),e(c,.75,.429),e(c,.321,.429),h()]},{FillColor:"#FFFFFF",line:!1,Actions:[l(c,.321,.536),e(c,.75,.536),e(c,.75,.571),e(c,.321,.571),h()]},{FillColor:"#FFFFFF",line:!1,Actions:[l(c,.321,.679),e(c,.75,.679),e(c,.75,.714),e(c,.321,.714),h()]},{FillColor:"#FFFFFF",line:!1,Actions:[l(c,.25,.393),e(c,.286,
.393),e(c,.286,.429),e(c,.25,.429),h()]},{FillColor:"#FFFFFF",line:!1,Actions:[l(c,.25,.536),e(c,.286,.536),e(c,.286,.571),e(c,.25,.571),h()]},{FillColor:"#FFFFFF",line:!1,Actions:[l(c,.25,.679),e(c,.286,.679),e(c,.286,.714),e(c,.25,.714),h()]}];return d.concat(c)}return n.baseRenderActions(c,a).concat(t("CMP_GoogleSheetsListBlock",a))},onInit:function(a){x(a);var b=function(){var b=lucid.plugin.getProperty(a,"gs_SelectionRange")||"",d=b.indexOf(":");if(!(0>d)){var e=w(b.substring(0,d)),d=w(b.substring(d+
1)),f=q(a),g=lucid.plugin.getProperty(a,"gs_WorksheetId");f&&void 0!=g&&null!=g&&e&&d&&(lucid.computation.GoogleSheetCacher.getRange(f,g,e,d,a+":"+b,function(b){b=b.reduce(function(a,b){return a.concat(b)},[]);b=b.map(function(a){return String(a)});lucid.plugin.setPropertyIfChanged(a,"gs_SelectionOptions",b);var c=lucid.plugin.getProperty(a,"CMP_TXT_Value",!0);0>b.indexOf(c)&&0<b.length&&(lucid.plugin.setProperty(a,"CMP_TXT_Value",b[0],!0),lucid.plugin.setProperty(a,"TextValue",b[0]),I(a))}),z(a,
function(b){A(a,b)}))}};lucid.plugin.setProperty(a,"CMP_IsEditable",!1);lucid.plugin.setProperty(a,"gs_SelectionRange","");lucid.plugin.setProperty(a,"gs_SelectionOptions",[]);lucid.plugin.setProperty(a,"TextValue","");lucid.plugin.hookPropertyPostSave(a,"gs_WorksheetId",b);lucid.plugin.hookPropertyPostSave(a,"gs_Cell",r(a,100));lucid.plugin.hookPropertyPostSave(a,"gs_SelectionRange",b);lucid.plugin.hookPropertyPostSave(a,"TextValue",function(b,d){J(a,d)});lucid.plugin.setProperty(a,"CMP_UpdateFunction",
b,!0);lucid.plugin.setProperty(a,"ChangeCallback",r(a,500),!0)}}));var K=function(a,b,c){b=lucid.plugin.getProperty(b,"InsetMargin")||0;return lucid.math.Box.safePad(a,-b)},R=function(a,b){var c=lucid.plugin.getProperty(b,"InsetMargin")||0;return lucid.math.Box.safePad(a,c)};lucid.plugin.initBlockClass(u({className:"CMP_GoogleSheetsDynamicTextBlock",name:"Google Sheets Markup Block",searchKeywords:["sheets","google","text","dynamic"],disabledPropertyControls:"LineWidth FillColor LineColor FillType StrokeStyle Rounding".split(" "),
onInit:function(a){x(a,!1);lucid.plugin.setProperty(a,"MarkupHasWatermark",!0);lucid.plugin.addBlockTextArea(a,{id:"DisplayValue",value:"Text",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){return lucid.math.Box.pad({x:b.x,y:b.y,w:b.w,h:b.h},-(lucid.plugin.getProperty(a,"InsetMargin")||0))}},{docVersionInstated:5,value:function(b){return K(b,a,!0)}}]),wantReturn:!0,beforeTextEdit:function(){var b=lucid.plugin.getProperty(a,"CMP_IsEditable");
b&&lucid.plugin.setProperty(a,"CMP_IsEditing",!0,!0);return b},afterTextEdit:function(){var b=lucid.plugin.getAllProperties(a,!0),c;for(c in b)0==c.indexOf("Cell_")&&lucid.plugin.setProperty(a,c,void 0,!0);lucid.plugin.setProperty(a,"CMP_IsEditing",!1,!0)}});lucid.plugin.setProperty(a,"DisplayValue","Text");lucid.plugin.setProperty(a,"FormatValue",C("Text"),!0);lucid.plugin.setProperty(a,"Value",0);lucid.plugin.setProperty(a,"CMP_TXT_Value",0,!0);lucid.plugin.hookPropertyPostSave(a,"DisplayValue",
function(b,c){if(!(5<=(lucid.plugin.getProperty(null,"Version")||0))){var d="y",e="h",f=lucid.plugin.getProperty(a,"BoundingBox"),g=lucid.text.getTextAreaRotation(a,"Text"),h=lucid.math.Box.pad({x:f.x,y:f.y,w:f.w,h:f.h},-(lucid.plugin.getProperty(a,"InsetMargin")||0));0!==g%Math.PI&&(h=lucid.math.Box.rotate(h,g),d="x",e="w");var g=lucid.plugin.getProperty(a,"InsetMargin")||0,l=lucid.plugin.getProperty(a,"TextVAlign"),h=lucid.text.getSize(a,"Text",h);h.h+=2*g;h.h>f[e]&&("middle"==l?f[d]-=(h.h-f[e])/
2:"bottom"==l&&(f[d]-=h.h-f[e]),f[e]=h.h,lucid.plugin.setProperty(a,"BoundingBox",f))}});lucid.plugin.hookPropertyPostSave(a,"DisplayValue",function(b,c){var d=C(c.t);lucid.plugin.setPropertyIfChanged(a,"FormatValue",d,!0)});lucid.plugin.setProperty(a,"CMP_UpdateFunction",function(a){N(a);M(a)},!0);lucid.plugin.setProperty(a,"CMP_IsEditable",!1);lucid.plugin.setProperty(a,"gs_Worksheets",[]);n.registerProperties(a)},onTextAreaOverflowChange:"undefined"!==typeof window?plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(K,
R):void 0,onCreate:function(a){lucid.help.item.accomplish("default.text.add");lucid.plugin.editBlockTextArea(a,"FormatValue")},getRenderDataKey:function(a){return["FillColor","LineColor","LineWidth"]},getRenderData:function(a,b,c){var d=a.BoundingBox;if("sample"==b)return a=d.w>d.h?d.w:d.h,d=d.x<d.y?d.x:d.y,d={x:d,y:d,w:a,h:a},a=v(d),d=[{FillColor:"#FFFFFF",line:!1,Actions:[l(d,.321,.393),e(d,.179,.517),e(d,.321,.679),e(d,.393,.679),e(d,.25,.517),e(d,.393,.393),e(d,.321,.393),h(),l(d,.75,.517),e(d,
.607,.679),e(d,.679,.679),e(d,.821,.517),e(d,.679,.393),e(d,.607,.393),e(d,.75,.517),h(),l(d,.42,.786),e(d,.473,.786),e(d,.58,.286),e(d,.527,.286),e(d,.402,.786),h()]}],a.concat(d);b=lucid.plugin.getProperty(c,"MarkupHasWatermark")?t("CMP_GoogleSheetsDynamicTextBlock",a):[];return n.baseRenderActions(d,a).concat(b)}}));lucid.plugin.createToolGroups({"Google Sheets":["CMP_GoogleSheetsInputBlock","CMP_GoogleSheetsOutputBlock","CMP_GoogleSheetsListBlock","CMP_GoogleSheetsDynamicTextBlock","CMP_AdditionSquareBlock"]})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/computation.js.map
};
