pluginFn['/js/plugins/v2/default.js'] = function(lucid, window) {
	(function(){function p(){return lucid.plugin.getProperty(null,"Version")||0}function l(b,a){return b.x+b.w*a}function m(b,a){return b.y+b.h*a}function k(b,a,c){return{Action:"line",x:l(b,a),y:m(b,c)}}function n(b,a,c){return{Action:"move",x:l(b,a),y:m(b,c)}}function q(){return{Action:"close"}}function t(b){return[n(b,0,0),k(b,1,0),k(b,1,1),k(b,0,1),q()]}function u(b){var a=b.BoundingBox,c=a.w>a.h?a.w:a.h,a=a.x<a.y?a.x:a.y,a={x:a,y:a,w:c,h:c};return[{LineColor:"#000000ff",FillColor:"#000000ff",LineWidth:b.LineWidth,
Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+.2*a.h},{Action:"line",x:a.x+.9*a.w,y:a.y+.1*a.h},{Action:"line",x:a.x+.55*a.w,y:a.y+.1*a.h},{Action:"line",x:a.x+.55*a.w,y:a.y+.9*a.h},{Action:"line",x:a.x+.65*a.w,y:a.y+a.h},{Action:"line",x:a.x+.35*a.w,y:a.y+a.h},{Action:"line",x:a.x+.45*a.w,y:a.y+.9*a.h},{Action:"line",x:a.x+.45*a.w,y:a.y+.1*a.h},{Action:"line",x:a.x+.1*a.w,y:a.y+.1*a.h},{Action:"line",x:a.x,y:a.y+.2*a.h},{Action:"close"}]}]}var h=
{global:this,provide:function(b){b=b.split(".");h.global[b[0]]=h.global[b[0]]||{};var a=h.global[b[0]];b.slice(1).reduce(function(a,d){a[d]||(a[d]={});return a[d]},a)},require:function(){},inherits:function(b,a){function c(){}c.prototype=a.prototype;b.superClass_=a.prototype;b.prototype=new c;b.prototype.constructor=b;b.base=function(c,b,f){var g=Array.prototype.slice.call(arguments,2);return a.prototype[b].apply(c,g)}},base:function(b,a,c){var d=arguments.callee.caller;if(h.STRICT_MODE_COMPATIBLE||
h.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(d.superClass_)return d.superClass_.constructor.apply(b,Array.prototype.slice.call(arguments,1));for(var e=Array.prototype.slice.call(arguments,2),f=!1,g=b.constructor;g;g=g.superClass_&&g.superClass_.constructor)if(g.prototype[a]===d)f=!0;else if(f)return g.prototype[a].apply(b,e);if(b[a]===d)return b.constructor.prototype[a].apply(b,
e);throw Error("goog.base called from a method of one name to a method of a different name");}};h.provide("plugin.common.DocVersionedProps");plugin.common.DocVersionedProps.getValueForDocVersion=function(b,a){var c=lucid.plugin.getProperty(null,"Version")||0,d=lucid.array.findRight(b,function(a){return a.docVersionInstated<=c});return d&&d.value||a};h.provide("plugin.common.TextAreaOverflowUtils");plugin.common.TextAreaOverflowUtils.getOnOverflowCallback=function(b,a,c){return function(d,e,f,g,h){if("number"!==
typeof g||"number"!==typeof h||(g+6)%3!=(h+6)%3)g=lucid.plugin.getProperty(null,"Version")||0,h=Math.abs(lucid.text.getTextAreaRotation(d,e)),e!=(c||"Text")||0!==f||5>g||0!==h||plugin.common.TextAreaOverflowUtils.resizeToFitText(d,e,f,b,a)}};plugin.common.TextAreaOverflowUtils.resizeToFitText=function(b,a,c,d,e){var f=lucid.plugin.getProperty(b,"BoundingBox"),g=d(f,b);d=lucid.text.getTextAreaVAlignment(b,a);d="middle"==d?{x:.5,y:.5}:"bottom"==d?{x:.5,y:1}:{x:.5,y:0};a=lucid.text.getTextAreaSpaceSize(b,
a,c);a=lucid.math.Box.resizeAboutRelativePoint(g,d,a);e=e(a,b);a=e.h>f.h;c=lucid.block.getDefaultSize(b).h;e=lucid.math.Box.resizeAboutRelativePoint(f,d,{w:f.w,h:a?Math.max(e.h,f.h):Math.max(e.h,Math.min(f.h,c))});lucid.plugin.setProperty(b,"BoundingBox",e)};h.provide("plugin.common.util");plugin.common.util.getRenderRectangleActionsFromBB=function(b){return[{Action:"move",x:b.x,y:b.y},{Action:"line",x:b.x+b.w,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+b.h},{Action:"close"}]};
plugin.common.util.getDefaultLinkPoints=function(b){return[{x:.5,y:0},{x:1,y:.5},{x:.5,y:1},{x:0,y:.5}]};h.provide("plugin.default");h.require("plugin.common.DocVersionedProps");h.require("plugin.common.TextAreaOverflowUtils");h.require("plugin.common.util");(function(){var b=function(a,c){var d=lucid.plugin.getProperty(c,"InsetMargin")||0;return lucid.math.Box.safePad(a,-d)};lucid.plugin.initBlockClass({className:"DefaultTextBlockNew",name:"Text",defaultSize:{w:240,h:60},searchKeywords:["text"],
disabledPropertyControls:"LineWidth FillColor LineColor FillType StrokeStyle Rounding".split(" "),onInit:function(a){lucid.plugin.addBlockTextArea(a,{id:"Text",value:"Text",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(c){return lucid.math.Box.pad({x:c.x,y:c.y,w:c.w,h:c.h},-(lucid.plugin.getProperty(a,"InsetMargin")||0))}},{docVersionInstated:5,value:function(c){return b(c,a)}}]),wantReturn:!0});lucid.plugin.setProperty(a,"Transparent",
1);lucid.plugin.hookPropertyPostSave(a,"Text",function(c,d){if(!(5<=p())){var b="y",f="h",g=lucid.plugin.getProperty(a,"BoundingBox"),h=lucid.text.getTextAreaRotation(a,"Text"),k=lucid.math.Box.pad({x:g.x,y:g.y,w:g.w,h:g.h},-(lucid.plugin.getProperty(a,"InsetMargin")||0));0!==h%Math.PI&&(k=lucid.math.Box.rotate(k,h),b="x",f="w");var h=lucid.plugin.getProperty(a,"InsetMargin")||0,l=lucid.plugin.getProperty(a,"TextVAlign"),k=lucid.text.getSize(a,"Text",k);k.h+=2*h;k.h>g[f]&&("middle"==l?g[b]-=(k.h-
g[f])/2:"bottom"==l&&(g[b]-=k.h-g[f]),g[f]=k.h,lucid.plugin.setProperty(a,"BoundingBox",g))}})},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(b,function(a,c){var d=lucid.plugin.getProperty(c,"InsetMargin")||0;return lucid.math.Box.safePad(a,d)}),getLinkPoints:function(){return lucid.coreEx.includeCoreExFeatures()?[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]:[]},onCreate:function(a){lucid.help.item.accomplish("default.text.add");lucid.plugin.editBlockTextArea(a,
"Text")},afterEditText:function(a){-1==lucid.text.plainText(lucid.plugin.getProperty(a,"Text")).search(/\S/)&&lucid.plugin.deleteItem(a)},getRenderDataKey:function(a){return["FillColor","LineColor","LineWidth"]},getRenderData:function(a,c){return"sample"===c?u(a):[{Actions:plugin.common.util.getRenderRectangleActionsFromBB(a.BoundingBox)}]}})})();(function(){lucid.plugin.initBlockClass({className:"MinimalTextBlock",defaultSize:{w:240,h:60},disabledPropertyControls:"LineWidth FillColor LineColor FillType StrokeStyle Rounding".split(" "),
noLines:!0,onInit:function(b){lucid.plugin.addBlockTextArea(b,{id:"Text",value:"",getBoundingBox:function(a){return a},wantReturn:!0,afterTextEdit:function(){/\S/.test(lucid.text.plainText(lucid.plugin.getProperty(b,"Text")))||lucid.plugin.deleteItem(b)}})},getRenderData:function(b){return[{Actions:plugin.common.util.getRenderRectangleActionsFromBB(b.BoundingBox)}]}})})();(function(){var b=function(a,c){var d=lucid.plugin.getProperty(c,"InsetMargin")||0;return lucid.math.Box.safePad(a,-d)};lucid.plugin.initBlockClass({className:"DefaultSquareBlock",
name:"Block",defaultSize:{w:160,h:160},searchKeywords:["block","square","rectangle","box","text"],onInit:function(a){var c=plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(a){return{x:a.x+20,y:a.y,w:a.w-40,h:a.h}}},{docVersionInstated:2,value:function(c){return{x:c.x,y:c.y,w:c.w,h:c.h,fitShape:lucid.plugin.getProperty(a,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(c){return b(c,a)}}]);lucid.plugin.addBlockTextArea(a,{id:"Text",
value:"Text",getBoundingBox:c,wantReturn:!0});1<p()&&(lucid.plugin.registerProperty(a,"TextWrap","fit"),lucid.plugin.registerProperty(a,"InsetMargin",5))},variants:{SquareBlockTransparent:{defaultSize:{w:240,h:60},tooltip:"Text Area",searchKeywords:["text"],defaultProperties:function(){return{FillColor:"#ffffff00",LineColor:"#00000000"}}}},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(b,function(a,c){var d=lucid.plugin.getProperty(c,"InsetMargin")||0;return lucid.math.Box.safePad(a,
d)}),getLinkPoints:function(){return lucid.coreEx.includeCoreExFeatures()?[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]:[]},getRenderDataKey:function(a){return["FillColor","LineColor","LineWidth"]},getRenderData:function(a,c){var d;if(d="sample"==c)if(lucid.string.isString(a.LineColor)&&lucid.string.isString(a.FillColor)){d=a.LineColor.substring(7,9);var b=a.FillColor.substring(7,9);d="00"===d&&"00"===b}else d=!1;d?d=u(a):(d=a.BoundingBox,d=[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,
Actions:[{Action:"move",x:d.x,y:d.y},{Action:"line",x:d.x+d.w,y:d.y},{Action:"line",x:d.x+d.w,y:d.y+d.h},{Action:"line",x:d.x,y:d.y+d.h},{Action:"close"}]}]);return d}})})();(function(){var b=function(a,c){var d=lucid.plugin.getProperty(c,"InsetMargin")||0;return lucid.math.Box.safePad(a,-d)};lucid.plugin.initBlockClass({className:"DefaultNoteBlock",name:"Note",defaultSize:{w:160,h:160},searchKeywords:["note"],unthemed:!0,defaultProperties:function(){return{FillColor:"#ffffaa"}},onInit:function(a){lucid.plugin.setProperty("TextAlign",
"left");lucid.plugin.addBlockTextArea(a,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(a){var d=.2*(a.h>a.w?a.w:a.h);return{x:a.x+.5*d,y:a.y+.1*a.h+.1*d,w:a.w-d,h:.8*a.h}}},{docVersionInstated:2,value:function(c){return{x:c.x,y:c.y,w:c.w,h:c.h,fitShape:lucid.plugin.getProperty(a,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(c){return b(c,a)}}]),wantReturn:!0});1<p()&&(lucid.plugin.registerProperty(a,
"TextWrap","fit"),lucid.plugin.registerProperty(a,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(b,function(a,c){var d=lucid.plugin.getProperty(c,"InsetMargin")||0;return lucid.math.Box.safePad(a,d)}),getLinkPoints:function(){return lucid.coreEx.includeCoreExFeatures()?[{x:.5,y:0},{x:1,y:.5},{x:.5,y:1},{x:0,y:.5}]:[]},getRenderDataKey:function(a){return["FillColor","LineColor","LineWidth"]},getRenderData:function(a,c){var d=a.BoundingBox,b=.2*
(d.h>d.w?d.w:d.h),f=lucid.color.darken(a.FillColor,.3);"sample"==c&&(b*=2);return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:d.x,y:d.y},{Action:"line",x:d.x+d.w-b,y:d.y},{Action:"line",x:d.x+d.w,y:d.y+b},{Action:"line",x:d.x+d.w,y:d.y+d.h},{Action:"line",x:d.x,y:d.y+d.h},{Action:"close"}]},{FillColor:f,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:d.x+d.w-b,y:d.y},{Action:"line",x:d.x+d.w,y:d.y+b},{Action:"line",x:d.x+d.w-
.8*b,y:d.y+.8*b},{Action:"close"}]}]}})})();(function(){var b=function(a,c){var b=lucid.plugin.getProperty(c,"InsetMargin")||0;return lucid.math.Box.safePad(a,-b)};lucid.plugin.initBlockClass({className:"DefaultNoteBlockV2",name:"Note",defaultSize:{w:160,h:160},searchKeywords:["note"],unthemed:!0,defaultProperties:function(){return{FillColor:"#ffdf71"}},onInit:function(a){lucid.plugin.setProperty("TextAlign","left");lucid.plugin.addBlockTextArea(a,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,
value:function(a){var b=.2*(a.h>a.w?a.w:a.h);return{x:a.x+.5*b,y:a.y+.1*a.h+.1*b,w:a.w-b,h:.8*a.h}}},{docVersionInstated:2,value:function(c){return{x:c.x,y:c.y,w:c.w,h:c.h,fitShape:lucid.plugin.getProperty(a,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(c){return b(c,a)}}]),wantReturn:!0});1<p()&&(lucid.plugin.registerProperty(a,"TextWrap","fit"),lucid.plugin.registerProperty(a,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(b,
function(a,c){var b=lucid.plugin.getProperty(c,"InsetMargin")||0;return lucid.math.Box.safePad(a,b)}),getLinkPoints:function(){return lucid.coreEx.includeCoreExFeatures()?[{x:.5,y:0},{x:1,y:.5},{x:.5,y:1},{x:0,y:.5}]:[]},getRenderDataKey:function(a){return["FillColor","LineWidth"]},disabledPropertyControls:["LineColor"],getRenderData:function(a,c){var b=a.BoundingBox,e=.2*(b.h>b.w?b.w:b.h),f=lucid.color.darken(a.FillColor,.15);"sample"==c&&(e*=2);return[{FillColor:a.FillColor,StrokeColor:f,LineWidth:a.LineWidth,
NoRounding:!0,Actions:[{Action:"move",x:b.x,y:b.y},{Action:"line",x:b.x+b.w-e,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+e},{Action:"line",x:b.x+b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+b.h},{Action:"close"}]},{FillColor:f,StrokeColor:f,LineWidth:0,NoRounding:!0,Actions:[{Action:"move",x:b.x+b.w-e,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+e},{Action:"line",x:b.x+b.w-e,y:b.y+e},{Action:"close"}]}]}})})();lucid.plugin.initBlockClass({className:"DefaultRedNoteBlock",name:"Important Note",defaultSize:{w:160,
h:160},searchKeywords:["note","important","red"],unthemed:!0,onInit:function(b){lucid.plugin.setProperty("TextAlign","left");lucid.plugin.addBlockTextArea(b,{id:"Text",value:'<span style="color:#ffffff; font-weight:bold;">Important Note</span>',getBoundingBox:function(a){var b=.2*(a.h>a.w?a.w:a.h);return{x:a.x+.5*b,y:a.y+.1*a.h+.1*b,w:a.w-b,h:.8*a.h}},wantReturn:!0})},getLinkPoints:function(){return lucid.coreEx.includeCoreExFeatures()?[{x:.5,y:0},{x:1,y:.5},{x:.5,y:1},{x:0,y:.5}]:[]},getRenderDataKey:function(b){return["FillColor",
"LineColor","LineWidth"]},getRenderData:function(b,a){var c=b.BoundingBox,d=.2*(c.h>c.w?c.w:c.h),e=lucid.color.darken(b.FillColor,.3);"sample"==a&&(d*=2);return[{FillColor:b.FillColor,StrokeColor:b.LineColor,LineWidth:b.LineWidth,Actions:[{Action:"move",x:c.x,y:c.y},{Action:"line",x:c.x+c.w-d,y:c.y},{Action:"line",x:c.x+c.w,y:c.y+d},{Action:"line",x:c.x+c.w,y:c.y+c.h},{Action:"line",x:c.x,y:c.y+c.h},{Action:"close"}]},{FillColor:e,StrokeColor:b.LineColor,LineWidth:b.LineWidth,Actions:[{Action:"move",
x:c.x+c.w-d,y:c.y},{Action:"line",x:c.x+c.w,y:c.y+d},{Action:"line",x:c.x+c.w-.8*d,y:c.y+.8*d},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"ImageSearchBlock",name:"External Image",defaultSize:{w:120,h:120},unthemed:!0,disabledPropertyControls:["FillType","FillColor","LineColor","LineWidth"],getRenderData:function(b,a){var c=b.BoundingBox,d=b.URL,e=b.ThumbURL;e&&""!=e||(e=d);if("sample"==a||"preview"==a)d=e;return[{Image:d,BoundingBox:c}]},onInit:function(b){lucid.plugin.registerProperty(b,
"URL","",function(a){""!=a&&null!=a&&lucid.useragent.is_chrome()&&(lucid.useragent.is_win()||lucid.useragent.is_linux())&&(a=lucid.imageProxyUrl(a));return a});lucid.plugin.registerProperty(b,"ThumbURL","",function(a){""!=a&&-1<a.indexOf("::")&&(a="http://"+a.substr(a.indexOf("::")+2));return a})},isImageBlock:function(){return!0}});lucid.plugin.initBlockClass({className:"ImageSearchBlock2",name:"External Image",defaultSize:{w:120,h:120},unthemed:!0,getRenderDataKey:function(b){return["FillColor",
"LineColor","LineWidth","URL","ThumbURL"]},getRenderData:function(b,a){var c=b.BoundingBox,d=b.URL,e=b.ThumbURL;e&&""!=e||(e=d);return"sample"==a||"preview"==a?[{Image:e,BoundingBox:c}]:[{FillColor:b.FillColor,StrokeColor:b.LineColor,LineWidth:b.LineWidth,Actions:[{Action:"move",x:c.x,y:c.y},{Action:"line",x:c.x+c.w,y:c.y},{Action:"line",x:c.x+c.w,y:c.y+c.h},{Action:"line",x:c.x,y:c.y+c.h},{Action:"close"}]}]},onInit:function(b){lucid.plugin.registerProperty(b,"ThumbURL","",function(a){""!=a&&-1<
a.indexOf("::")&&(a="http://"+a.substr(a.indexOf("::")+2));return a})},onCreate:function(b){lucid.plugin.replaceWithUserImage(b,{})},isImageBlock:function(){return!0}});lucid.plugin.initBlockClass({className:"HotspotBlock",name:"Hotspot",searchKeywords:["ui","interface","hotspot"],defaultSize:{w:120,h:120},hotspot:!0,unthemed:!0,defaultProperties:function(){return{FillColor:"#00ff9966"}},getRenderDataKey:function(b){return["FillColor"]},getRenderData:function(b,a){var c=b.BoundingBox;return[{FillColor:b.FillColor,
Actions:[{Action:"move",x:c.x,y:c.y},{Action:"line",x:c.x+c.w,y:c.y},{Action:"line",x:c.x+c.w,y:c.y+c.h},{Action:"line",x:c.x,y:c.y+c.h},{Action:"close"}]}]}});var r={};lucid.plugin.initBlockClass({className:"PresentationFrameBlock",name:"PresentationFrame",defaultSize:{w:460,h:260},isFrame:!0,nwSelectable:{getMoveHandleRenderData:function(b){var a=.3*b.w,c=.15*b.h,d={x:l(b,.35),y:m(b,.1),w:a,h:c},e={x:l(b,.35),y:m(b,.75),w:a,h:c},f={x:l(b,.1),y:m(b,.35),w:c,h:a},a={x:l(b,.75),y:m(b,.35),w:c,h:a},
c={x:l(b,.45),y:m(b,.24),w:.1*b.w,h:.52*b.h},g={x:l(b,.24),y:m(b,.45),w:.52*b.w,h:.1*b.h},h=n(b,1,.5);b={Action:"curve",Control:lucid.math.ellipseArcControlPoints(l(b,0),m(b,0),1*b.w,1*b.h,0*Math.PI,2*Math.PI)};return[{FillColor:"#f78d1e",NoRounding:!0,LineWidth:0,Actions:[h,b]},{FillColor:"#fff",NoRounding:!0,LineWidth:0,Actions:[n(d,0,1),k(d,1,1),k(d,.5,0),q()]},{FillColor:"#fff",NoRounding:!0,LineWidth:0,Actions:[n(e,0,0),k(e,1,0),k(e,.5,1),q()]},{FillColor:"#fff",NoRounding:!0,LineWidth:0,Actions:[n(f,
1,0),k(f,1,1),k(f,0,.5),q()]},{FillColor:"#fff",NoRounding:!0,LineWidth:0,Actions:[n(a,0,0),k(a,0,1),k(a,1,.5),q()]},{FillColor:"#fff",NoRounding:!0,LineWidth:0,Actions:t(c)},{FillColor:"#fff",NoRounding:!0,LineWidth:0,Actions:t(g)}]},resizeHandleColor:"#f78d1e"},unthemed:!0,noLines:!0,rLock:!0,disabledPropertyControls:"bold center ClipTextToPage Endpoint1 Endpoint2 FillColor FillType FlipX FlipY font fontFace font Hyphenate InsetMargin italic justified left LineColor lineSpacing LineWidth Link Lock Opacity pageBreak right Rounding Shadow Shape strike StrokeStyle textColor textSize TextVAlign TightWrap underline".split(" "),
showResizeHandles:function(){return!0},onInit:function(b){r[b]=1;lucid.plugin.addBlockTextArea(b,{id:"Text",value:"",readOnly:!0,getBoundingBox:function(a){return{x:a.x-15,y:a.y-15+1,w:30,h:30,fitShape:lucid.plugin.getProperty(b,"InsetMargin")||0}}})},onDelete:function(b){delete r[b]},getRenderData:function(b,a){var c=b.BoundingBox,d=lucid.plugin.isSelected(b.id),e=c.x-15,f=c.y-15,c=[{FillColor:d?"#fbc62d20":"#00000000",StrokeColor:"#f78d1e99",NoRounding:!0,LineWidth:d?6:2,Actions:[{Action:"move",
x:c.x,y:c.y},{Action:"line",x:c.x+c.w,y:c.y},{Action:"line",x:c.x+c.w,y:c.y+c.h},{Action:"line",x:c.x,y:c.y+c.h},{Action:"close"}]},{FillColor:"#f78d1e",Actions:[{Action:"move",x:e+30,y:f+15},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(e,f,30,30,0,2*Math.PI)}]}];return d?c:lucid.math.dashLine(c,[20,10])}});lucid.plugin.onSelectionChange(function(b){var a=lucid.object.createSet(b);lucid.object.forEach(r,function(b,d){a[d]&&!lucid.plugin.getProperty(d,"selected",!0)?(lucid.plugin.setProperty(d,
"selected",!0,!0),lucid.plugin.refreshBlockView(d)):!a[d]&&lucid.plugin.getProperty(d,"selected",!0)&&(lucid.plugin.setProperty(d,"selected",!1,!0),lucid.plugin.refreshBlockView(d))})});lucid.plugin.onLoad(function(){lucid.help.section.add("General",[{id:"default.block.add",content:{lucidUrl:"general/addBlock"},title:"Add a shape",keywords:"add shapes more insert object stencil".split(" "),accomplish:function(a){lucid.plugin.onCurrentUserAction(function(b){"CreateBlock"==b.Action&&a()})}},{id:"default.block.format",
content:{lucidUrl:"general/formatBlock"},title:"Format a shape",keywords:"format style shape object color gradient shadow image line border transparent new document".split(" "),accomplish:function(a){var b=lucid.object.createSet("LineColor","LineWidth","StrokeStyle","FillColor");lucid.plugin.onCurrentUserAction(function(d){"SetProperty"==d.Action&&d.Property in b&&lucid.plugin.isBlock(d.id)&&a()})}},{id:"default.text.add",content:{lucidUrl:"general/addText"},title:"Add text",keywords:["words","font",
"edit"]},{id:"default.line.add",content:{lucidUrl:"general/addLine"},title:"Draw a line",keywords:"elbow square straight arrow curve create".split(" "),accomplish:function(a){lucid.plugin.onCurrentUserAction(function(b){"CreateLine"==b.Action&&a()})}},{id:"default.line.format",content:{lucidUrl:"general/formatLine"},title:"Format a line",keywords:"edit curve thick straight color text".split(" "),accomplish:function(a){var b=lucid.object.createSet("LineColor","LineWidth","StrokeStyle","FillColor"),
d=lucid.object.createSet("Endpoint1","Endpoint2");lucid.plugin.onCurrentUserAction(function(e){"SetProperty"==e.Action&&(e.Property in b||e.Property in d&&e.Value&&e.OldValue&&(e.Value.Style||"None")!=(e.OldValue.Style||"None"))&&lucid.plugin.isLine(e.id)&&a()})}},{id:"default.image",content:{lucidUrl:"general/addImage"},title:"Add an image",keywords:"picture fill insert add drop place".split(" "),accomplish:function(a){lucid.plugin.onCurrentUserAction(function(b){("CreateBlock"==b.Action&&b.Properties&&
b.Properties.FillColor&&b.Properties.FillColor.url||"SetProperty"==b.Action&&"FillColor"==b.Property&&b.Value&&b.Value.url&&lucid.plugin.isBlock(b.id))&&a()})}},{id:"default.page.settings",content:{lucidUrl:"general/pageSettings"},title:"Change page settings",keywords:"format margin layout landscape portrait width height background snap grid size".split(" "),accomplish:function(a){var b=lucid.object.createSet("DPI","FillColor","GridSpacing","Margin","Value");lucid.plugin.onCurrentUserAction(function(d){"SetProperty"==
d.Action&&d.Property in b&&lucid.plugin.isPage(d.id)&&a()})}},{id:"default.download",content:{lucidUrl:"general/download"},title:"Download your diagram",keywords:"export save pdf png jpeg tiff illustrator svg vector photoshop powerpoint word insert".split(" "),accomplish:function(a){lucid.plugin.onDownloadSuccess(function(b){"print"!=b&&a()})}}]);var b=[{id:"default.share",content:{lucidUrl:"general/share"},title:"Share your diagram",keywords:"share collaborate invite team users permission".split(" "),
accomplish:function(a){lucid.plugin.onShare(a)}},{id:"default.link",content:{lucidUrl:"general/link"},title:"Add links to shapes or text",keywords:"add;link;connect;url;email;jump;external page;external;hyperlink".split(";"),accomplish:function(a){var b=lucid.object.createSet("ext","pg","ml");lucid.plugin.onCurrentUserAction(function(d){"SetProperty"==d.Action&&"Link"==d.Property&&d.Value instanceof Array&&d.Value.some(function(a){return a.tp in b})&&lucid.plugin.isBlock(d.id)&&a()})}},{id:"default.layer",
content:{lucidUrl:"general/layer"},title:"Use layers",keywords:[],accomplish:function(a){lucid.plugin.onCurrentUserAction(function(b){"CrGr"==b.Action&&b.Properties.IsState&&a()})}},{id:"default.hotspot",content:{lucidUrl:"general/hotspot"},title:"Add interaction",keywords:"hotspot state interaction link layer wireframe mockup dynamic page".split(" "),accomplish:function(a){lucid.plugin.onCurrentUserAction(function(b){("CreateBlock"==b.Action&&b.Properties&&b.Properties.Link&&b.Properties.Link.length||
"SetProperty"==b.Action&&"Link"==b.Property&&b.Value&&b.Value.length)&&a()})}},{id:"default.visio.import",content:{lucidUrl:"general/importVisioDiagram"},title:"Import Visio files",keywords:"import visio vsd vdx vsdx gliffy microsoft migrate upload".split(" ")},{id:"default.visio.export",content:{lucidUrl:"general/exportVisioDiagram"},title:"Export Visio files",keywords:"visio document file export vdx microsoft".split(" "),accomplish:function(a){lucid.plugin.onDownloadSuccess(function(b){"visio"==
b&&a()})}}];lucid.config.on_premise&&b.shift();lucid.help.section.add("Advanced",b)});var v={name:"Line",className:"Group",toolBoxId:"defaultLine",helperImage:lucid.net.cashyURL("/app/ng2/chart/shapethumbs/line-shape-28px-@2x.png"),tooltip:"Line",defaultSize:{w:100,h:2},defaultProperties:function(){return{Objects:[{id:"KmiZvl75mHjc",IsLine:!0,Action:{Action:"CreateLine",Properties:{Endpoint1:{x:400,y:460},Endpoint2:{x:500,y:460},ZOrder:0}}}],Base:{x:0,y:0},Size:{w:300,h:0},Plugins:[],ApplyTheme:!0}}};
lucid.plugin.createToolGroups({Standard:[{className:"DefaultSquareBlock",variant:"SquareBlockTransparent",tooltip:"Text",helperImage:lucid.net.cashyURL("/app/ng2/chart/shapethumbs/text-shape-28px-@2x.png")},"DefaultSquareBlock","DefaultNoteBlockV2","HotspotBlock",v]});lucid.plugin.onDocumentLoaded(function(){5>p()&&lucid.plugin.createToolGroups({Standard:[{className:"DefaultTextBlockNew",helperImage:lucid.net.cashyURL("/app/ng2/chart/shapethumbs/text-shape-28px-@2x.png")},"DefaultSquareBlock","DefaultNoteBlockV2",
"HotspotBlock",v]})},!0);lucid.coreEx.includeCoreExFeatures()&&lucid.plugin.createNextBlockGroup(["DefaultSquareBlock","DefaultTextBlockNew"]);lucid.plugin.initBlockClass({className:"DefaultTextBlock",name:"Text",defaultSize:{w:240,h:60},noSearch:!0,onInit:function(b){lucid.plugin.addBlockTextArea(b,{id:"Text",value:"Text",getBoundingBox:function(a){return{x:a.x+20,y:a.y,w:a.w-40,h:a.h}}})},afterEditText:function(b){-1==lucid.text.plainText(lucid.plugin.getProperty(b,"Text")).search(/\S/)&&lucid.plugin.deleteItem(b)},
getRenderData:function(b,a){var c=b.BoundingBox;return[{Actions:[{Action:"move",x:c.x,y:c.y},{Action:"line",x:c.x+c.w,y:c.y},{Action:"line",x:c.x+c.w,y:c.y+c.h},{Action:"line",x:c.x,y:c.y+c.h},{Action:"close"}]}]}})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/default.js.map
};
