pluginFn['/js/plugins/v2/freehand.js'] = function(lucid, window) {
	(function(){function r(a,c,d){function b(a){return{p1:a.p2,p2:a.p1,n1:a.n2,n2:a.n1}}var g={FillColor:c.FillColor,StrokeColor:c.StrokeColor,LineWidth:c.LineWidth,Actions:[]};"prop"==g.FillColor&&(g.FillColor=a.FillColor);"prop"==g.StrokeColor&&(g.StrokeColor=a.LineColor);"prop"==g.LineWidth&&(g.LineWidth=a.LineWidth);for(var n=[],e=lucid.array.shallowCopy(c.Lines);0<e.length;){var h=[e.shift()],m;do for(var l=m=0;l<e.length;l++){var k=h[0],p=h[h.length-1],f=e[l];if(k.p1==f.p1&&p.p2==f.p2){e.splice(l--,
1);(f.n1||f.n2)&&h.push(b(f));h.push("close");m++;break}else if(k.p1==f.p2&&p.p2==f.p1){e.splice(l--,1);(f.n1||f.n2)&&h.push(f);h.push("close");m++;break}else k.p1==f.p1?(e.splice(l--,1),h.unshift(b(f)),m++):p.p2==f.p1?(e.splice(l--,1),h.push(f),m++):k.p1==f.p2?(e.splice(l--,1),h.unshift(f),m++):p.p2==f.p2&&(e.splice(l--,1),h.push(b(f)),m++)}while(0<m&&"close"!=h[h.length-1]);n.push(h)}lucid.array.forEach(n,function(b){g.Actions.push(q(c.Points[b[0].p1],a.BoundingBox,d));g.Actions[g.Actions.length-
1].Action="move";lucid.array.forEach(b,function(b){if("close"==b)g.Actions.push({Action:"close"});else{var e=c.Points[b.p1],h=c.Points[b.p2],f=q(h,a.BoundingBox,d);b.n1||b.n2?(e=lucid.math.Point.add(e,b.n1||{x:0,y:0}),b=lucid.math.Point.add(h,b.n2||{x:0,y:0}),h=q(e,a.BoundingBox,d),b=q(b,a.BoundingBox,d),g.Actions.push({Action:"curve",Control:[{x1:h.x,y1:h.y,x2:b.x,y2:b.y,x3:f.x,y3:f.y}]})):g.Actions.push({Action:"line",x:f.x,y:f.y})}})});return g}function q(a,c,d){return{x:0==d.BoundingBox.w?0:c.x+
c.w*(a.x-d.BoundingBox.x)/d.BoundingBox.w,y:0==d.BoundingBox.h?0:c.y+c.h*(a.y-d.BoundingBox.y)/d.BoundingBox.h}}var k={global:this,provide:function(a){a=a.split(".");k.global[a[0]]=k.global[a[0]]||{};var c=k.global[a[0]];a.slice(1).reduce(function(a,b){a[b]||(a[b]={});return a[b]},c)},require:function(){},inherits:function(a,c){function d(){}d.prototype=c.prototype;a.superClass_=c.prototype;a.prototype=new d;a.prototype.constructor=a;a.base=function(a,d,n){var e=Array.prototype.slice.call(arguments,
2);return c.prototype[d].apply(a,e)}},base:function(a,c,d){var b=arguments.callee.caller;if(k.STRICT_MODE_COMPATIBLE||k.DEBUG&&!b)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(b.superClass_)return b.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var g=Array.prototype.slice.call(arguments,2),n=!1,e=a.constructor;e;e=e.superClass_&&e.superClass_.constructor)if(e.prototype[c]===
b)n=!0;else if(n)return e.prototype[c].apply(a,g);if(a[c]===b)return a.constructor.prototype[c].apply(a,g);throw Error("goog.base called from a method of one name to a method of a different name");}};k.provide("plugin.freehand");lucid.plugin.initBlockClass({className:"FreehandBlock",name:"Freehand Drawing",defaultSize:{w:240,h:240},onInit:function(a){lucid.plugin.registerProperty(a,"Stencil",{BoundingBox:{x:0,y:0,w:1,h:1},Shapes:[],Text:{},LinkPoints:[]},function(c){var d=lucid.plugin.getStencil(c);
d.Container&&lucid.plugin.makeHollow(a);for(var b=lucid.plugin.getBlockTextAreas(a),g=0;g<b.length;g++)b[g]in d.Text||lucid.plugin.deleteTextArea(b[g]);lucid.object.forEach(d.Text,function(b,c){lucid.plugin.addBlockTextArea(a,{id:c,value:lucid.plugin.getProperty(a,c)||b.Default,getBoundingBox:function(a){return{x:a.x+a.w*(b.x-d.BoundingBox.x)/d.BoundingBox.w,y:a.y+a.h*(b.y-d.BoundingBox.y)/d.BoundingBox.h,w:a.w*b.w/d.BoundingBox.w,h:a.h*b.h/d.BoundingBox.h}},wantReturn:!0,rotation:b.rotation,vAlignOverflow:!0})});
return c})},getLinkPoints:function(a){var c=lucid.plugin.getStencil(lucid.plugin.getProperty(a,"Stencil")),d=[];c&&lucid.array.forEach(c.LinkPoints||[],function(a){d.push({x:(a.x-c.BoundingBox.x)/c.BoundingBox.w,y:(a.y-c.BoundingBox.y)/c.BoundingBox.h})});return d},getRenderDataKey:function(){return["FillColor","LineColor","LineWidth","Stencil"]},getRenderData:function(a,c){var d=[],b=lucid.plugin.getStencil(a.Stencil);lucid.array.forEach(b.Shapes||[],function(c){d.push(r(a,c,b))});return d}})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/freehand.js.map
};
