pluginFn['/js/plugins/v2/ipad.js'] = function(lucid, window) {
	(function(){function d(b,a,m,g,d,c,h,n,q){m=lucid.config.assets_base_url+"/app/webroot/img/ipad/"+m;var l=m.substring(0,m.lastIndexOf(".")),k=m.substring(m.lastIndexOf(".")),t=l+"_tn"+k,p=m.split("/"),p=p[p.length-1],p=p.split(".")[0].replace(/-/g,"_"),p="Image_ipad_"+p;n=n||[];n=n.concat(lucid.string.trim(a.replace(/as|with|ipad/gi,"").replace(/\W/g," ").replace(/\s+/g," ")).split(" "));n.unshift("ipad");var r=null;!c.l&&!c.r||c.minWidth?c.minWidth&&(r=c.minWidth):r=(c.l||0)+(c.r||0);x[p]=!0;lucid.plugin.initBlockClass({className:p,
name:a,searchKeywords:n,defaultSize:{w:g,h:d},hLock:c&&!c.minWidth&&(c.fixed||!c.l&&!c.r),vLock:!c||!c.vResize,minWidth:r,maxWidth:1024,noLines:!0,snapSpacing:4,unthemed:!0,disabledPropertyControls:"FillColor FillType LineColor LineWidth FlipX FlipY".split(" "),onInit:h,isImageBlock:function(){return!0},getRenderData:function(a,b){var e=a.BoundingBox,g=[];if("sample"==b)return[{Image:t,BoundingBox:{x:0,y:0,w:23,h:23}}];if(c&&c.simpleSelect&&a.Cols&&a.Selected){var d=a.Cols,h=Math.round(e.w/d),f=a.Selected;
g.push({Image:m,BoundingBox:e});g.push({Image:l+"_l_s"+k,BoundingBox:{x:e.x+(f-1)*h,y:e.y,w:c.l,h:e.h}});g.push({Image:l+"_s"+k,BoundingBox:{x:e.x+(f-1)*h+c.l,y:e.y,w:h-(c.l+c.r),h:e.h}});g.push({Image:l+"_r_s"+k,BoundingBox:{x:e.x+f*h-c.r,y:e.y,w:c.r,h:e.h}});return g}if(c&&a.Cols){d=a.Cols;h=Math.round(e.w/d);g.push({Image:l+"_l"+k,BoundingBox:{x:e.x,y:e.y,w:c.l,h:e.h}});for(var n=0;n<d;n++)g.push({Image:m,BoundingBox:{x:e.x+n*h+c.l,y:e.y,w:h-(c.l+c.r),h:e.h}}),n<d-1&&g.push({Image:l+"_i"+k,BoundingBox:{x:e.x+
(n+1)*h-c.r,y:e.y,w:c.l+c.r,h:e.h}});g.push({Image:l+"_r"+k,BoundingBox:{x:e.x+d*h-c.r,y:e.y,w:c.r,h:e.h}});a.Selected&&(f=a.Selected,g.push({Image:l+"_"+(1==f?"l_s"+k:"il_s"+k),BoundingBox:{x:e.x+(f-1)*h,y:e.y,w:c.l,h:e.h}}),1<f&&g.push({Image:l+"_d_s"+k,BoundingBox:{x:e.x+(f-1)*h-.5*c.d,y:e.y,w:c.d,h:e.h}}),g.push({Image:l+"_s"+k,BoundingBox:{x:e.x+(f-1)*h+c.l,y:e.y,w:h-(c.l+c.r),h:e.h}}),g.push({Image:l+"_"+(f==d?"r_s"+k:"ir_s"+k),BoundingBox:{x:e.x+f*h-c.r,y:e.y,w:c.r,h:e.h}}),f<d&&g.push({Image:l+
"_d_s"+k,BoundingBox:{x:e.x+f*h-.5*c.d,y:e.y,w:c.d,h:e.h}}));return g}if(c&&a.Rows){var d=function(a,b,h,d){var m=e.x+(c.l||0),f=e.w-((c.l||0)+(c.r||0));d=d||"";c.l&&g.push({Image:a+"_l"+d+k,BoundingBox:{x:e.x,y:b,w:c.l,h:h}});g.push({Image:a+d+k,BoundingBox:{x:m,y:b,w:f,h:h}});c.r&&g.push({Image:a+"_r"+d+k,BoundingBox:{x:e.x+e.w-c.r,y:b,w:c.r,h:h}})},h=a.Rows,f=a.Selected,q=a.rowHeight;c.t&&d(l+"_t",e.y,c.t);for(n=0;n<h-(c.t?1:0);n++)d(l,e.y+(c.t||0)+n*q,q,n+1==f?"_s":null);c.b&&d(l+"_b",e.y+(c.t||
0)+n*q,c.b);return g}return c&&c.l&&c.r?[{Image:l+"_l"+k,BoundingBox:{x:e.x,y:e.y,w:c.l,h:e.h}},{Image:m,BoundingBox:{x:e.x+c.l,y:e.y,w:e.w-(c.l+c.r),h:e.h}},{Image:l+"_r"+k,BoundingBox:{x:e.x+e.w-c.r,y:e.y,w:c.r,h:e.h}}]:c&&c.t&&c.b?[{Image:l+"_t"+k,BoundingBox:{x:e.x,y:e.y,w:e.w,h:c.t}},{Image:m,BoundingBox:{x:e.x,y:e.y+c.t,w:e.w,h:e.h-(c.t+c.b)}},{Image:l+"_b"+k,BoundingBox:{x:e.x,y:e.y+e.h-c.b,w:e.w,h:c.b}}]:null!=a.Toggle?0==a.Toggle?[{Image:m,BoundingBox:e}]:[{Image:l.split("_")[0]+"_on"+k,
BoundingBox:e}]:[{Image:m,BoundingBox:e}]}});q||(u[b]?u[b].push(p):u[b]=[p])}var v={global:this,provide:function(b){b=b.split(".");v.global[b[0]]=v.global[b[0]]||{};var a=v.global[b[0]];b.slice(1).reduce(function(a,b){a[b]||(a[b]={});return a[b]},a)},require:function(){},inherits:function(b,a){function d(){}d.prototype=a.prototype;b.superClass_=a.prototype;b.prototype=new d;b.prototype.constructor=b;b.base=function(b,d,c){var h=Array.prototype.slice.call(arguments,2);return a.prototype[d].apply(b,
h)}},base:function(b,a,d){var g=arguments.callee.caller;if(v.STRICT_MODE_COMPATIBLE||v.DEBUG&&!g)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(g.superClass_)return g.superClass_.constructor.apply(b,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),c=!1,h=b.constructor;h;h=h.superClass_&&h.superClass_.constructor)if(h.prototype[a]===g)c=!0;else if(c)return h.prototype[a].apply(b,
f);if(b[a]===g)return b.constructor.prototype[a].apply(b,f);throw Error("goog.base called from a method of one name to a method of a different name");}};v.provide("plugin.ipad");var u={},x={};lucid.plugin.onDocumentLoaded(function(){function b(a,b){for(var c=lucid.plugin.getProperty(b[0],a),d=1;d<b.length;d++)if(c!=lucid.plugin.getProperty(b[d],a))return null;return c}function a(a,b){for(var c=lucid.plugin.getProperty(b[0],a),d=1;d<b.length;d++){var g=lucid.plugin.getProperty(b[d],a);g<c&&(c=g)}return c}
function d(c,f,m,l,k,t){function p(a,b){r&&r.setMax(a);b||lucid.array.forEach(k,function(b){lucid.plugin.setPropertyIfChanged(b,m,a)})}g&&c.spacer();g=!0;var r;"spinner"==f?(c.addGrid({width:6,content:{text:l+":",classes:"crop ralign"}}),c.openGrid({width:3,suffix:3}),c.addInput({type:"spinner",min:1,max:100,step:1,value:b(m,k),defaultVal:" ",onChange:p}),c.close(),0<t.length&&(c.spacer(),c.addGrid({width:6,content:{text:"Selected:",classes:"crop ralign"}}),c.openGrid({width:3,suffix:3}),r=c.addInput({type:"spinner",
min:1,max:b(m,k)||a(m,t),step:1,value:b("Selected",t),defaultVal:" ",onChange:function(a,b){lucid.array.forEach(t,function(b){lucid.plugin.setPropertyIfChanged(b,"Selected",a)})}}),c.close())):"checkbox"==f&&(c.addGrid({width:6,content:{text:l+":",classes:"crop ralign"}}),c.openGrid({width:6}),c.addInput({type:"buttonset",buttons:lucid.array.realMap([{label:"On",val:1},{label:"Off",val:0}],function(a){return{label:a.label,value:a.val,selected:function(){return!b(m,k)==!a.val},action:function(){!b(m,
k)!=!a.val&&lucid.array.forEach(k,function(b){lucid.plugin.setPropertyIfChanged(b,m,a.val)})}}})}),c.close())}var g=!1,f=lucid.template.builder(),c=f.add({classes:"ios_inputs"});lucid.plugin.addCustomPanel("Context Panel",null,[{content:f}],null,{isContextPanel:!0,checkShow:function(a){a=lucid.array.filter(a,function(a){return a.isBlock});if(!lucid.array.every(a,function(a){return a.className in x}))return!1;var b=!1,q=lucid.template.builder(),l=[],k=[],t=[],p=[],r=[];g=!1;lucid.array.forEach(a,function(a){null!=
lucid.plugin.getProperty(a.id,"Rows")&&(l.push(a.id),null!=lucid.plugin.getProperty(a.id,"Selected")&&k.push(a.id),b=!0);null!=lucid.plugin.getProperty(a.id,"Cols")&&(t.push(a.id),null!=lucid.plugin.getProperty(a.id,"Selected")&&p.push(a.id),b=!0);null!=lucid.plugin.getProperty(a.id,"Toggle")&&(r.push(a.id),b=!0)});0<l.length&&d(q,"spinner","Rows","Rows",l,k);0<t.length&&d(q,"spinner","Cols","Buttons",t,p);0<r.length&&d(q,"checkbox","Toggle","Toggle",r);f.getElement(c).setContent(q);return b}})});
var w=function(b,a,d){return function(g,f){var c,h;lucid.array.forEach(lucid.plugin.getBlockTextAreas(b),function(n){c=1*n.split("_")[1];if(c==g||c==f){h=c!=f?a:d;var q=lucid.text.restyle(lucid.plugin.getProperty(b,n),{color:h});lucid.plugin.setProperty(b,n,q)}})}};d("iOS 6 iPad Elements","iPad","ipad.png",1008,1280,{fixed:!0});lucid.plugin.initBlockClass({className:"iPadGrayBackgroundBlock",name:"Gray Background",searchKeywords:["ipad","gray","background"],defaultSize:{w:776,h:1033},snapSpacing:4,
getRenderData:function(b){b=b.BoundingBox;return[{FillColor:"#d3d5db",NoRounding:!0,Actions:[{Action:"move",x:b.x,y:b.y},{Action:"line",x:b.x+b.w,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+b.h},{Action:"close"}]}]}});u["iOS 6 iPad Elements"]||(u["iOS 6 iPad Elements"]=[]);u["iOS 6 iPad Elements"].push({className:"iPadGrayBackgroundBlock",name:"Gray Background"});d("iOS 6 iPad Elements","Top Bar","top_bar.png",768,20,{l:64,r:64});d("iOS 6 iPad Elements","Gray Bar","bar_gray.png",
768,44,!1,function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:20px;color:#717880;">Label</span>',getBoundingBox:function(a){return{x:a.x+.25*a.w,y:a.y+.5*a.h-15,w:.5*a.w,h:30}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPad Elements","Black Bar (Semi-Transparent)","bar_semi_trans_black.png",768,44,!1,function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:20px;color:#FFFFFF;">Label</span>',
getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-15,w:.8*a.w,h:30}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPad Elements","Black Bar","bar_black.png",768,44,!1,function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:20px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-15,w:.8*a.w,h:30}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPad Elements","Safari Top","safari_top.png",
768,58,{l:256,r:240,minWidth:768},function(b){lucid.plugin.addBlockTextArea(b,{id:"Title",value:'<span style="font-weight:bold;font-size:13px;color:#43495b;">Page Title</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+4,w:.8*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Input",value:'<span style="font-size:14px;color:#666666;">http://www.lucidchart.com</span>',getBoundingBox:function(a){return{x:a.x+246,y:a.y+26,w:a.w-480,h:22}},wantReturn:!1,
readOnly:!1,align:"left"})});d("iOS 6 iPad Elements","Search Bar","search.png",340,32,{l:24,r:24});d("iOS 6 iPad Elements","Alert Dialog","alert_dialog.png",296,168,{fixed:!0},function(b){lucid.plugin.addBlockTextArea(b,{id:"Alert",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Alert</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.137*a.h,w:.8*a.w,h:.12*a.h}},wantReturn:!1,readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Message",value:'<span style="font-size:16px;color:#FFFFFF;">Sample Message</span>',
getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.298*a.h,w:.8*a.w,h:.274*a.h}},wantReturn:!0,readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Button1",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">OK</span>',getBoundingBox:function(a){return{x:a.x+.0676*a.w,y:a.y+.64*a.h,w:.405*a.w,h:.214*a.h}},wantReturn:!1,readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Button2",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Cancel</span>',
getBoundingBox:function(a){return{x:a.x+.52*a.w,y:a.y+.64*a.h,w:.405*a.w,h:.214*a.h}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPad Elements","Dialog","dialog.png",288,144,{t:40,b:24,vResize:!0},function(b){lucid.plugin.addBlockTextArea(b,{id:"Alert",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Welcome</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.08*a.w,w:.8*a.w,h:.0694*a.w}},wantReturn:!1,readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,
{id:"Message",value:'<span style="font-size:16px;color:#FFFFFF;">Sample Message</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.1736*a.w,w:.8*a.w,h:.9*a.h-.208*a.w}},wantReturn:!0,readOnly:!1,align:"center"})});d("iOS 6 iPad Elements","Popover","popover.png",352,320,{t:64,b:32,vResize:!0});d("iOS 6 iPad Elements","Table","table.png",407,92,{t:24,b:24,l:24,r:24},function(b){function a(a){lucid.plugin.addBlockTextArea(b,{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:17px;color:#000000;">Label '+
a+"</span>",getBoundingBox:function(d){for(var f=0,c=lucid.plugin.getProperty(b,"Rows"),h=0;h<a-1;h++)f+=lucid.plugin.getProperty(b,"rowHeight",!0);return a>c?null:{x:d.x+12,y:d.y+Math.round(lucid.plugin.getProperty(b,"rowHeight",!0)*(a-.5))-10,w:d.w-36,h:20}},wantReturn:!1,readOnly:!1,align:"left"})}lucid.plugin.setProperty(b,"rowHeight",44,!0);lucid.plugin.registerProperty(b,"Rows",2,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||
a(c);f=g*lucid.plugin.getProperty(b,"rowHeight",!0);c=lucid.plugin.getProperty(b,"BoundingBox");c.h!=f&&(c.h=f,lucid.plugin.setProperty(b,"BoundingBox",c))})});d("iOS 6 iPad Elements","Vertical Tabs","vtab.png",302,132,{l:44},function(b){function a(a){lucid.plugin.addBlockTextArea(b,{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:17px;color:#'+(1==a?"FFFFFF":"000000")+';">Label '+a+"</span>",getBoundingBox:function(d){var f=lucid.plugin.getProperty(b,"Rows");return a>f?null:{x:d.x+46,
y:d.y+Math.round(lucid.plugin.getProperty(b,"rowHeight",!0)*(a-.5))-10,w:d.w-56,h:20}},wantReturn:!1,readOnly:!1,align:"left"})}lucid.plugin.setProperty(b,"rowHeight",44,!0);lucid.plugin.registerProperty(b,"Selected",1,null,w(b,"000000","FFFFFF"));lucid.plugin.registerProperty(b,"Rows",3,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||a(c);f=g*lucid.plugin.getProperty(b,"rowHeight",!0);c=lucid.plugin.getProperty(b,"BoundingBox");c.h!=
f&&(c.h=f,lucid.plugin.setProperty(b,"BoundingBox",c))})});d("iOS 6 iPad Controls","Black Button","button_black.png",60,36,{l:8,r:8},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-7,w:.8*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPad Controls","Blue Button","button_blue.png",60,36,{l:8,r:8},function(b){lucid.plugin.addBlockTextArea(b,
{id:"Label",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-7,w:.8*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPad Controls","Gray-Blue Button","button_grayblue.png",60,36,{l:8,r:8},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-7,w:.8*
a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPad Controls","Red Button","button_red.png",60,36,{l:8,r:8},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-7,w:.8*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPad Controls","Gray Back Button","back_button_gray.png",58,36,{l:16,r:8},function(b){lucid.plugin.addBlockTextArea(b,
{id:"Back",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Back</span>',getBoundingBox:function(a){return{x:a.x+8,y:a.y+.5*a.h-7,w:a.w-12,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPad Controls","Black Back Button","back_button_black.png",58,36,{l:16,r:8},function(b){lucid.plugin.addBlockTextArea(b,{id:"Back",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Back</span>',getBoundingBox:function(a){return{x:a.x+8,y:a.y+.5*a.h-7,w:a.w-12,h:14}},
wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPad Controls","Sort Handle","sort_handle.png",32,32,{fixed:!0});d("iOS 6 iPad Controls","Dropdown","dropdown.png",152,32,{l:16,r:36},function(b){lucid.plugin.addBlockTextArea(b,{id:"Dropdown",value:'<span style="font-size:12px;color:#000000;">Select One</span>',getBoundingBox:function(a){return{x:a.x+.079*a.w,y:a.y+.156*a.h,w:a.w-.303*a.w,h:.5625*a.h}},wantReturn:!1,readOnly:!1,align:"left"})});d("iOS 6 iPad Controls","Email Name","email_name.png",
112,32,{l:16,r:16},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-size:15px;color:#000000;">Lucidchart</span>',getBoundingBox:function(a){return{x:a.x+.107*a.w,y:a.y+.219*a.h,w:a.w-.286*a.w,h:.5625*a.h}},wantReturn:!1,readOnly:!1,align:"left"})});d("iOS 6 iPad Controls","Previous/Next","prev_next.png",92,32,{fixed:!0});d("iOS 6 iPad Controls","Portrait Keyboard","keyboard_portrait.png",768,264,{fixed:!0});d("iOS 6 iPad Controls","Landscape Keyboard","keyboard_landscape.png",
1024,352,{fixed:!0});d("iOS 6 iPad Controls","Large Tabbed Buttons","large_tabbed_button.png",304,44,{l:10,r:10,d:1},function(b){function a(a){lucid.plugin.addBlockTextArea(b,{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:18px;color:#'+(1==a?"FFFFFF":"7F7F7F")+';">Label</span>',getBoundingBox:function(d){var f=lucid.plugin.getProperty(b,"Cols"),c=d.w/f;return a>f?null:{x:d.x+Math.round(c*(a-.9)),y:d.y+.5*d.h-10,w:.8*c,h:20}},wantReturn:!1,readOnly:!1,align:"center"})}lucid.plugin.registerProperty(b,
"Cols",3,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||a(c)});lucid.plugin.registerProperty(b,"Selected",1,null,w(b,"7F7F7F","FFFFFF"))});d("iOS 6 iPad Controls","Sort Buttons","sort_button.png",168,36,{l:6,r:6,d:1},function(b){function a(a){lucid.plugin.addBlockTextArea(b,{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Label</span>',getBoundingBox:function(d){var f=lucid.plugin.getProperty(b,"Cols"),
c=d.w/f;return a>f?null:{x:d.x+Math.round(c*(a-.9)),y:d.y+.5*d.h-7,w:.8*c,h:14}},wantReturn:!1,readOnly:!1,align:"center"})}lucid.plugin.registerProperty(b,"Selected",1);lucid.plugin.registerProperty(b,"Cols",3,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||a(c)})});d("iOS 6 iPad Controls","Tab Bar","tab_bar.png",768,52,{l:8,r:8,minWidth:768,simpleSelect:!0},function(b){function a(a){lucid.plugin.addBlockTextArea(b,{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:10px;color:#'+
(2==a?"FFFFFF":"A8A8A8")+';">Label</span>',getBoundingBox:function(d){var f=lucid.plugin.getProperty(b,"Cols"),c=d.w/f;return a>f?null:{x:d.x+Math.round(c*(a-.9)),y:d.y+42-5,w:.8*c,h:10}},wantReturn:!1,readOnly:!1,align:"center"})}lucid.plugin.registerProperty(b,"Cols",4,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||a(c)});lucid.plugin.registerProperty(b,"Selected",2,null,w(b,"A8A8A8","FFFFFF"))});d("iOS 6 iPad Controls","Slider","slider.png",
220,24,{l:124,r:8});d("iOS 6 iPad Controls","Switch","switch_off.png",96,32,{fixed:!0},function(b){lucid.plugin.registerProperty(b,"Toggle",0)});d("iOS 6 iPad Icons","Blue Add Icon","add_icon_blue.png",32,32,{fixed:!0});d("iOS 6 iPad Icons","Green Add Icon","add_icon_green.png",32,32,{fixed:!0});d("iOS 6 iPad Icons","Remove Icon","remove_icon.png",32,32,{fixed:!0});d("iOS 6 iPad Icons","Arrow Icon","arrow_icon.png",32,32,{fixed:!0});d("iOS 6 iPad Icons","Arrow","arrow.png",32,32,{fixed:!0});d("iOS 6 iPad Icons",
"Checkmark","checkmark.png",16,16,{fixed:!0});d("iOS 6 iPad Icons","Check","check_off.png",32,32,{fixed:!0},function(b){lucid.plugin.registerProperty(b,"Toggle",0)});d("iOS 6 iPad Icons","Location","location_dot.png",32,32,{fixed:!0});d("iOS 6 iPad Icons","Mark As Read","mark_as_read.png",16,16,{fixed:!0});d("iOS 6 iPad Icons","Green Pin","pin_green.png",32,40,{fixed:!0});d("iOS 6 iPad Icons","Red Pin","pin_red.png",32,40,{fixed:!0});d("iOS 6 iPad Icons","Radio Button","radio_off.png",32,32,{fixed:!0},
function(b){lucid.plugin.registerProperty(b,"Toggle",0)});d("iOS 6 iPad Icons","Checkbox","checkbox_off.png",32,32,{fixed:!0},function(b){lucid.plugin.registerProperty(b,"Toggle",0)});d("iOS 6 iPad Icons","Indicator","indicator.png",32,32,{l:16,r:16},function(b){lucid.plugin.addBlockTextArea(b,{id:"Count",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">2</span>',getBoundingBox:function(a){return{x:a.x+8,y:a.y+7,w:a.w-16,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});lucid.plugin.createToolGroups(u)})();
//# sourceMappingURL=/js/plugins/v2/source-maps/ipad.js.map
};
