pluginFn['/js/plugins/v2/iphone.js'] = function(lucid, window) {
	(function(){function d(b,a,d,g,f,c,h,k,n){d=lucid.config.assets_base_url+"/app/webroot/img/iphone/"+d;g=Math.round(g/2);f=Math.round(f/2);c&&(c.l&&(c.l=Math.round(c.l/2)),c.r&&(c.r=Math.round(c.r/2)),c.t&&(c.t=Math.round(c.t/2)),c.b&&(c.b=Math.round(c.b/2)),c.d&&(c.d=Math.round(c.d/2)),c.minWidth&&(c.minWidth=Math.round(c.minWidth/2)));var m=d.substring(0,d.lastIndexOf(".")),l=d.substring(d.lastIndexOf(".")),r=m+"_tn"+l,p=d.split("/"),p=p[p.length-1],p=p.split(".")[0].replace(/-/g,"_"),p="Image_iphone_"+
p;k=k||[];k=k.concat(lucid.string.trim(a.replace(/as|with|iphone/gi,"").replace(/\W/g," ").replace(/\s+/g," ")).split(" "));k.unshift("iphone");var q=null;!c.l&&!c.r||c.minWidth?c.minWidth&&(q=c.minWidth):q=(c.l||0)+(c.r||0);w[p]=!0;lucid.plugin.initBlockClass({className:p,name:a,searchKeywords:k,defaultSize:{w:g,h:f},hLock:c&&!c.minWidth&&(c.fixed||!c.l&&!c.r),vLock:!c||!c.vResize,minWidth:q,maxWidth:480,noLines:!0,snapSpacing:4,unthemed:!0,disabledPropertyControls:"FillColor FillType LineColor LineWidth FlipX FlipY".split(" "),
onInit:h,isImageBlock:function(){return!0},getRenderData:function(a,b){var e=a.BoundingBox,f=[];if("sample"==b)return[{Image:r,BoundingBox:{x:0,y:0,w:23,h:23}}];if(c&&c.simpleSelect&&a.Cols&&a.Selected){var g=a.Cols,h=Math.round(e.w/g),k=a.Selected;f.push({Image:d,BoundingBox:e});f.push({Image:m+"_l_s"+l,BoundingBox:{x:e.x+(k-1)*h,y:e.y,w:c.l,h:e.h}});f.push({Image:m+"_s"+l,BoundingBox:{x:e.x+(k-1)*h+c.l,y:e.y,w:h-(c.l+c.r),h:e.h}});f.push({Image:m+"_r_s"+l,BoundingBox:{x:e.x+k*h-c.r,y:e.y,w:c.r,
h:e.h}});return f}if(c&&a.Cols){g=a.Cols;h=Math.round(e.w/g);f.push({Image:m+"_l"+l,BoundingBox:{x:e.x,y:e.y,w:c.l,h:e.h}});for(var n=0;n<g;n++)f.push({Image:d,BoundingBox:{x:e.x+n*h+c.l,y:e.y,w:h-(c.l+c.r),h:e.h}}),n<g-1&&f.push({Image:m+"_i"+l,BoundingBox:{x:e.x+(n+1)*h-c.r,y:e.y,w:c.l+c.r,h:e.h}});f.push({Image:m+"_r"+l,BoundingBox:{x:e.x+g*h-c.r,y:e.y,w:c.r,h:e.h}});a.Selected&&(k=a.Selected,f.push({Image:m+"_"+(1==k?"l_s"+l:"il_s"+l),BoundingBox:{x:e.x+(k-1)*h,y:e.y,w:c.l,h:e.h}}),1<k&&f.push({Image:m+
"_d_s"+l,BoundingBox:{x:e.x+(k-1)*h-.5*c.d,y:e.y,w:c.d,h:e.h}}),f.push({Image:m+"_s"+l,BoundingBox:{x:e.x+(k-1)*h+c.l,y:e.y,w:h-(c.l+c.r),h:e.h}}),f.push({Image:m+"_"+(k==g?"r_s"+l:"ir_s"+l),BoundingBox:{x:e.x+k*h-c.r,y:e.y,w:c.r,h:e.h}}),k<g&&f.push({Image:m+"_d_s"+l,BoundingBox:{x:e.x+k*h-.5*c.d,y:e.y,w:c.d,h:e.h}}));return f}if(c&&a.Rows){var g=function(a,b,d,g){var h=e.x+(c.l||0),k=e.w-((c.l||0)+(c.r||0));g=g||"";c.l&&f.push({Image:a+"_l"+g+l,BoundingBox:{x:e.x,y:b,w:c.l,h:d}});f.push({Image:a+
g+l,BoundingBox:{x:h,y:b,w:k,h:d}});c.r&&f.push({Image:a+"_r"+g+l,BoundingBox:{x:e.x+e.w-c.r,y:b,w:c.r,h:d}})},h=a.Rows,k=a.Selected,p=a.rowHeight;c.t&&g(m+"_t",e.y,c.t);for(n=0;n<h-(c.t?1:0);n++)g(m,e.y+(c.t||0)+n*p,p,n+1==k?"_s":null);c.b&&g(m+"_b",e.y+(c.t||0)+n*p,c.b);return f}return c&&c.l&&c.r?[{Image:m+"_l"+l,BoundingBox:{x:e.x,y:e.y,w:c.l,h:e.h}},{Image:d,BoundingBox:{x:e.x+c.l,y:e.y,w:e.w-(c.l+c.r),h:e.h}},{Image:m+"_r"+l,BoundingBox:{x:e.x+e.w-c.r,y:e.y,w:c.r,h:e.h}}]:c&&c.t&&c.b?[{Image:m+
"_t"+l,BoundingBox:{x:e.x,y:e.y,w:e.w,h:c.t}},{Image:d,BoundingBox:{x:e.x,y:e.y+c.t,w:e.w,h:e.h-(c.t+c.b)}},{Image:m+"_b"+l,BoundingBox:{x:e.x,y:e.y+e.h-c.b,w:e.w,h:c.b}}]:null!=a.Toggle?0==a.Toggle?[{Image:d,BoundingBox:e}]:[{Image:m.split("_")[0]+"_on"+l,BoundingBox:e}]:[{Image:d,BoundingBox:e}]}});n||(v[b]?v[b].push(p):v[b]=[p])}var u={global:this,provide:function(b){b=b.split(".");u.global[b[0]]=u.global[b[0]]||{};var a=u.global[b[0]];b.slice(1).reduce(function(a,b){a[b]||(a[b]={});return a[b]},
a)},require:function(){},inherits:function(b,a){function d(){}d.prototype=a.prototype;b.superClass_=a.prototype;b.prototype=new d;b.prototype.constructor=b;b.base=function(b,d,c){var h=Array.prototype.slice.call(arguments,2);return a.prototype[d].apply(b,h)}},base:function(b,a,d){var g=arguments.callee.caller;if(u.STRICT_MODE_COMPATIBLE||u.DEBUG&&!g)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");
if(g.superClass_)return g.superClass_.constructor.apply(b,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),c=!1,h=b.constructor;h;h=h.superClass_&&h.superClass_.constructor)if(h.prototype[a]===g)c=!0;else if(c)return h.prototype[a].apply(b,f);if(b[a]===g)return b.constructor.prototype[a].apply(b,f);throw Error("goog.base called from a method of one name to a method of a different name");}};u.provide("plugin.iphone");var v={},w={};lucid.plugin.onDocumentLoaded(function(){function b(a,
b){for(var c=lucid.plugin.getProperty(b[0],a),d=1;d<b.length;d++)if(c!=lucid.plugin.getProperty(b[d],a))return null;return c}function a(a,b){for(var c=lucid.plugin.getProperty(b[0],a),d=1;d<b.length;d++){var f=lucid.plugin.getProperty(b[d],a);f<c&&(c=f)}return c}function d(c,f,t,m,l,r){function p(a,b){q&&q.setMax(a);b||lucid.array.forEach(l,function(b){lucid.plugin.setPropertyIfChanged(b,t,a)})}g&&c.spacer();g=!0;var q;"spinner"==f?(c.addGrid({width:6,content:{text:m+":",classes:"crop ralign"}}),
c.openGrid({width:3,suffix:3}),c.addInput({type:"spinner",min:1,max:100,step:1,value:b(t,l),defaultVal:" ",onChange:p}),c.close(),0<r.length&&(c.spacer(),c.addGrid({width:6,content:{text:"Selected:",classes:"crop ralign"}}),c.openGrid({width:3,suffix:3}),q=c.addInput({type:"spinner",min:1,max:b(t,l)||a(t,r),step:1,value:b("Selected",r),defaultVal:" ",onChange:function(a,b){lucid.array.forEach(r,function(b){lucid.plugin.setPropertyIfChanged(b,"Selected",a)})}}),c.close())):"checkbox"==f&&(c.addGrid({width:6,
content:{text:m+":",classes:"crop ralign"}}),c.openGrid({width:6}),c.addInput({type:"buttonset",buttons:lucid.array.realMap([{label:"On",val:1},{label:"Off",val:0}],function(a){return{label:a.label,value:a.val,selected:function(){return!b(t,l)==!a.val},action:function(){!b(t,l)!=!a.val&&lucid.array.forEach(l,function(b){lucid.plugin.setPropertyIfChanged(b,t,a.val)})}}})}),c.close())}var g=!1,f=lucid.template.builder(),c=f.add({classes:"ios_inputs"});lucid.plugin.addCustomPanel("Context Panel",null,
[{content:f}],null,{isContextPanel:!0,checkShow:function(a){a=lucid.array.filter(a,function(a){return a.isBlock});if(!lucid.array.every(a,function(a){return a.className in w}))return!1;var b=!1,n=lucid.template.builder(),m=[],l=[],r=[],p=[],q=[];g=!1;lucid.array.forEach(a,function(a){null!=lucid.plugin.getProperty(a.id,"Rows")&&(m.push(a.id),null!=lucid.plugin.getProperty(a.id,"Selected")&&l.push(a.id),b=!0);null!=lucid.plugin.getProperty(a.id,"Cols")&&(r.push(a.id),null!=lucid.plugin.getProperty(a.id,
"Selected")&&p.push(a.id),b=!0);null!=lucid.plugin.getProperty(a.id,"Toggle")&&(q.push(a.id),b=!0)});0<m.length&&d(n,"spinner","Rows","Rows",m,l);0<r.length&&d(n,"spinner","Cols","Buttons",r,p);0<q.length&&d(n,"checkbox","Toggle","Toggled",q);f.getElement(c).setContent(n);return b}})});var x=function(b,a,d){return function(g,f){var c,h;lucid.array.forEach(lucid.plugin.getBlockTextAreas(b),function(k){c=1*k.split("_")[1];if(c==g||c==f){h=c!=f?a:d;var n=lucid.text.restyle(lucid.plugin.getProperty(b,
k),{color:h});lucid.plugin.setProperty(b,k,n)}})}};d("iOS 6 iPhone Elements","iPhone 4","iphone_4.png",768,1504,{fixed:!0});d("iOS 6 iPhone Elements","Black Background","bg_black.png",640,960,!1);d("iOS 6 iPhone Elements","Gray Background","bg_gray.png",640,960,!1);d("iOS 6 iPhone Elements","Dark Striped Background","bg_stripe_drk.png",640,960,!1);d("iOS 6 iPhone Elements","Light Striped Background","bg_stripe_lt.png",640,960,!1);d("iOS 6 iPhone Elements","White Background","bg_white.png",640,960,
!1);d("iOS 6 iPhone Elements","Top Bar (Application)","top_bar_app.png",640,40,!1);d("iOS 6 iPhone Elements","Top Bar (Home)","top_bar_home.png",640,40,!1);d("iOS 6 iPhone Elements","Gray-Blue Bar","bar_top.png",640,88,!1,function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.25*a.w,y:a.y+.5*a.h-10,w:.5*a.w,h:20}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Elements",
"Black Bar (Semi-Transparent)","bar_semi_trans_black.png",640,88,!1,function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-10,w:.8*a.w,h:20}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Elements","Blue Bar (Semi-Transparent)","bar_semi_trans_blue.png",640,112,!1,function(b){lucid.plugin.addBlockTextArea(b,{id:"Information",value:'<span style="font-size:18px;color:#FFFFFF;"><span style="font-weight:bold;">47 km</span> 37 minutes</span>',
getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-10,w:.8*a.w,h:20}},wantReturn:!0,readOnly:!1,align:"center"})});d("iOS 6 iPhone Elements","Bottom Bar","bar_bottom.png",640,88,!1,null,null,!0);d("iOS 6 iPhone Elements","Search Bar","search.png",624,64,{l:48,r:48});d("iOS 6 iPhone Elements","Table","table.png",608,184,{t:45,b:45,l:48,r:48},function(b){function a(a){lucid.plugin.addBlockTextArea(b,{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:18px;color:#000000;">Label '+
a+"</span>",getBoundingBox:function(d){for(var f=0,c=lucid.plugin.getProperty(b,"Rows"),h=0;h<a-1;h++)f+=lucid.plugin.getProperty(b,"rowHeight",!0);return a>c?null:{x:d.x+12,y:d.y+Math.round(lucid.plugin.getProperty(b,"rowHeight",!0)*(a-.5))-10,w:d.w-36,h:20}},wantReturn:!1,readOnly:!1,align:"left"})}lucid.plugin.setProperty(b,"rowHeight",44,!0);lucid.plugin.registerProperty(b,"Rows",2,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||
a(c);f=g*lucid.plugin.getProperty(b,"rowHeight",!0);c=lucid.plugin.getProperty(b,"BoundingBox");c.h!=f&&(c.h=f,lucid.plugin.setProperty(b,"BoundingBox",c))})});d("iOS 6 iPhone Elements","Table With Buttons","table_w_buttons.png",608,184,{t:45,b:45,l:32,r:32},function(b){function a(a){lucid.plugin.addBlockTextArea(b,{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:18px;color:#000000;">Label '+a+"</span>",getBoundingBox:function(a){return function(d){for(var c=0,h=lucid.plugin.getProperty(b,
"Rows"),k=0;k<a-1;k++)c+=lucid.plugin.getProperty(b,"rowHeight",!0);return a>h?null:{x:d.x+12,y:d.y+Math.round(lucid.plugin.getProperty(b,"rowHeight",!0)*(a-.5))-10,w:d.w-24,h:20}}}(a),wantReturn:!1,readOnly:!1,align:"center"})}lucid.plugin.setProperty(b,"rowHeight",44,!0);lucid.plugin.registerProperty(b,"Rows",2,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||a(c);f=g*lucid.plugin.getProperty(b,"rowHeight",!0);c=lucid.plugin.getProperty(b,
"BoundingBox");c.h!=f&&(c.h=f,lucid.plugin.setProperty(b,"BoundingBox",c))})});d("iOS 6 iPhone Elements","Table With Icons","table_w_icons.png",608,184,{t:45,b:45,l:96,r:48},function(b){function a(a){lucid.plugin.addBlockTextArea(b,{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:18px;color:#000000;">Label '+a+"</span>",getBoundingBox:function(a){return function(d){for(var c=0,h=lucid.plugin.getProperty(b,"Rows"),k=0;k<a-1;k++)c+=lucid.plugin.getProperty(b,"rowHeight",!0);return a>h?
null:{x:d.x+45,y:d.y+Math.round(lucid.plugin.getProperty(b,"rowHeight",!0)*(a-.5))-10,w:d.w-72,h:20}}}(a),wantReturn:!1,readOnly:!1,align:"left"})}lucid.plugin.setProperty(b,"rowHeight",44,!0);lucid.plugin.registerProperty(b,"Rows",2,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||a(c);f=g*lucid.plugin.getProperty(b,"rowHeight",!0);c=lucid.plugin.getProperty(b,"BoundingBox");c.h!=f&&(c.h=f,lucid.plugin.setProperty(b,"BoundingBox",c))})});
d("iOS 6 iPhone Elements","List","list.png",640,232,{t:58,b:56,minWidth:200,r:48},function(b){function a(a){lucid.plugin.addBlockTextArea(b,{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:18px;color:#000000;">Label '+a+"</span>",getBoundingBox:function(a){return function(d){for(var c=0,h=lucid.plugin.getProperty(b,"Rows"),k=0;k<a-1;k++)c+=lucid.plugin.getProperty(b,"rowHeight",!0);return a>h?null:{x:d.x+12,y:d.y+Math.round(lucid.plugin.getProperty(b,"rowHeight",!0)*(a-.5))-10,w:d.w-
36,h:20}}}(a),wantReturn:!1,readOnly:!1,align:"left"})}lucid.plugin.setProperty(b,"rowHeight",56,!0);lucid.plugin.registerProperty(b,"Rows",2,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||a(c);f=g*lucid.plugin.getProperty(b,"rowHeight",!0);c=lucid.plugin.getProperty(b,"BoundingBox");c.h!=f&&(c.h=f,lucid.plugin.setProperty(b,"BoundingBox",c))})});d("iOS 6 iPhone Elements","Safari Top","safari_top.png",640,120,!1,function(b){lucid.plugin.addBlockTextArea(b,
{id:"Title",value:'<span style="font-weight:bold;font-size:12px;color:#3c4651;">Page Title</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+12-7,w:.8*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Input",value:'<span style="font-size:12px;color:#666666;">www.lucidchart.com</span>',getBoundingBox:function(a){return{x:a.x+14,y:a.y+38-7,w:168,h:14}},wantReturn:!1,readOnly:!1,align:"left"})});d("iOS 6 iPhone Elements","Safari URL","safari_url.png",
640,120,!1,function(b){lucid.plugin.addBlockTextArea(b,{id:"Title",value:'<span style="font-weight:bold;font-size:12px;color:#3c4651;">Page Title</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+12-7,w:.8*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Input",value:'<span style="font-size:12px;color:#000000;">www.lucidchart.com</span>',getBoundingBox:function(a){return{x:a.x+14,y:a.y+38-7,w:202,h:14}},wantReturn:!1,readOnly:!1,align:"left"})},
null,!0);d("iOS 6 iPhone Elements","Safari Google","safari_google.png",640,120,!1,function(b){lucid.plugin.addBlockTextArea(b,{id:"Title",value:'<span style="font-weight:bold;font-size:12px;color:#3c4651;">Page Title</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+12-7,w:.8*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Input",value:'<span style="font-size:12px;color:#000000;">Lucid Online Diagramming</span>',getBoundingBox:function(a){return{x:a.x+
18,y:a.y+38-7,w:202,h:14}},wantReturn:!1,readOnly:!1,align:"left"})},null,!0);d("iOS 6 iPhone Elements","Safari Bottom","safari_bottom.png",640,88,!1);d("iOS 6 iPhone Elements","Blue Search","search_blue.png",640,88,!1,null,null,!0);d("iOS 6 iPhone Elements","Gray Search","search_gray.png",640,88,!1,null,null,!0);d("iOS 6 iPhone Elements","Gray Gradient List","gray_grad_list.png",640,184,!1,function(b){lucid.plugin.addBlockTextArea(b,{id:"Text",value:'<span style="font-size:12px;color:#000000;">Text</span>',
getBoundingBox:function(a){return{x:a.x+.05*a.w,y:a.y+.5*a.h-7,w:.9*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"left"})});d("iOS 6 iPhone Elements","Alert Bar","alert_bar.png",640,960,{fixed:!0});d("iOS 6 iPhone Elements","Alert Dialog","alert_dialog.png",592,336,{fixed:!0},function(b){lucid.plugin.addBlockTextArea(b,{id:"Alert",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Alert</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+30-7,w:.8*a.w,h:14}},wantReturn:!1,
readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Message",value:'<span style="font-size:12px;color:#FFFFFF;">Sample Message</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+70-7,w:.8*a.w,h:14}},wantReturn:!0,readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Button1",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">OK</span>',getBoundingBox:function(a){return{x:a.x+.0676*a.w,y:a.y+.64*a.h,w:.405*a.w,h:.214*a.h}},wantReturn:!1,readOnly:!1,
align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Button2",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Cancel</span>',getBoundingBox:function(a){return{x:a.x+.52*a.w,y:a.y+.64*a.h,w:.405*a.w,h:.214*a.h}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Elements","Dialog","dialog.png",576,288,{t:80,b:48,vResize:!0},function(b){lucid.plugin.addBlockTextArea(b,{id:"Alert",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Welcome</span>',getBoundingBox:function(a){return{x:a.x+
.1*a.w,y:a.y+.08*a.w,w:.8*a.w,h:.0694*a.w}},wantReturn:!1,readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Message",value:'<span style="font-size:16px;color:#FFFFFF;">Sample Message</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.1736*a.w,w:.8*a.w,h:.9*a.h-.208*a.w}},wantReturn:!0,readOnly:!1,align:"center"})});d("iOS 6 iPhone Elements","Scroll Pane","scroll_pane.png",640,960,{fixed:!0});d("iOS 6 iPhone Elements","Alpha List","alpha_list.png",32,800,{fixed:!0});d("iOS 6 iPhone Elements",
"Shiny","shiny.png",272,720,{fixed:!0},null,null,!0);d("iOS 6 iPhone Controls","Black Button","button_black.png",120,72,{l:16,r:16},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-7,w:.8*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Controls","Blue Button","button_blue.png",120,72,{l:16,r:16},function(b){lucid.plugin.addBlockTextArea(b,
{id:"Label",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-7,w:.8*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Controls","Gray-Blue Button","button_grayblue.png",120,72,{l:16,r:16},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-
7,w:.8*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Controls","Red Button","button_red.png",120,72,{l:16,r:16},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-7,w:.8*a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Controls","Large Light Button","button_lg_light.png",560,96,{l:32,r:32},function(b){lucid.plugin.addBlockTextArea(b,
{id:"Label",value:'<span style="font-weight:bold;font-size:18px;color:#000000;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-10,w:.8*a.w,h:20}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Controls","Large Dark Button","button_lg_dark.png",560,96,{l:32,r:32},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-
10,w:.8*a.w,h:20}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Controls","Large Green Button","button_lg_green.png",560,96,{l:32,r:32},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-10,w:.8*a.w,h:20}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Controls","Large Red Button","button_lg_red.png",560,96,{l:32,r:32},function(b){lucid.plugin.addBlockTextArea(b,
{id:"Label",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-10,w:.8*a.w,h:20}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Controls","Large Yellow Button","button_lg_yellow.png",560,96,{l:32,r:32},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:18px;color:#000000;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*
a.h-10,w:.8*a.w,h:20}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Controls","Extra-Large Green Button","button_xl_green.png",608,112,{l:32,r:32},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-10,w:.8*a.w,h:20}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Controls","Back Button","back_button.png",104,72,{l:32,r:16},
function(b){lucid.plugin.addBlockTextArea(b,{id:"Back",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Back</span>',getBoundingBox:function(a){return{x:a.x+8,y:a.y+.5*a.h-7,w:a.w-12,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Controls","Previous/Next","prev_next.png",184,64,{fixed:!0});d("iOS 6 iPhone Controls","Sort Handle","sort_handle.png",64,64,{fixed:!0});d("iOS 6 iPhone Controls","Slider","slider.png",440,48,{l:288,r:16});d("iOS 6 iPhone Controls",
"Active Dropdown","dropdown_active.png",304,64,{l:32,r:72},function(b){lucid.plugin.addBlockTextArea(b,{id:"Dropdown",value:'<span style="font-size:12px;color:#000000;">Select One</span>',getBoundingBox:function(a){return{x:a.x+10,y:a.y+.5*a.h-7,w:a.w-46,h:14}},wantReturn:!1,readOnly:!1,align:"left"})},null,!0);d("iOS 6 iPhone Controls","Dropdown","dropdown.png",304,64,{l:32,r:72},function(b){lucid.plugin.addBlockTextArea(b,{id:"Dropdown",value:'<span style="font-size:12px;color:#000000;">Select One</span>',
getBoundingBox:function(a){return{x:a.x+10,y:a.y+.5*a.h-7,w:a.w-46,h:14}},wantReturn:!1,readOnly:!1,align:"left"})});d("iOS 6 iPhone Controls","Email Name","email_name.png",224,64,{l:32,r:32},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-size:12px;color:#000000;">Lucidchart</span>',getBoundingBox:function(a){return{x:a.x+12,y:a.y+.5*a.h+1-7,w:a.w-32,h:14}},wantReturn:!1,readOnly:!1,align:"left"})});d("iOS 6 iPhone Controls","Switch","switch_off.png",192,64,{fixed:!0},
function(b){lucid.plugin.registerProperty(b,"Toggle",0)});d("iOS 6 iPhone Controls","Switch (On)","switch_on.png",192,64,{fixed:!0},null,null,!0);d("iOS 6 iPhone Controls","Blue Keyboard Button","keyboard_button_blue.png",160,88,{fixed:!0},function(b){lucid.plugin.addBlockTextArea(b,{id:"Label",value:'<span style="font-weight:bold;font-size:18px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.5*a.h-10,w:.8*a.w,h:20}},wantReturn:!1,readOnly:!1,align:"center"})});
d("iOS 6 iPhone Controls","Portrait Keyboard","keyboard_letters.png",640,432,{fixed:!0});d("iOS 6 iPhone Controls","Landscape Keyboard","keyboard_landscape.png",960,324,{fixed:!0});d("iOS 6 iPhone Controls","Numbers Keyboard","keyboard_numbers.png",640,432,{fixed:!0},null,null,!0);d("iOS 6 iPhone Controls","Symbols Keyboard","keyboard_symbols.png",640,432,{fixed:!0},null,null,!0);d("iOS 6 iPhone Controls","Large Tabbed Buttons","large_tabbed_button.png",608,88,{l:20,r:20,d:2},function(b){function a(a){lucid.plugin.addBlockTextArea(b,
{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:18px;color:#'+(1==a?"FFFFFF":"7F7F7F")+';">Label</span>',getBoundingBox:function(a){return function(d){var c=lucid.plugin.getProperty(b,"Cols"),h=d.w/c;return a>c?null:{x:d.x+Math.round(h*(a-.9)),y:d.y+.5*d.h-10,w:.8*h,h:20}}}(a),wantReturn:!1,readOnly:!1,align:"center"})}lucid.plugin.registerProperty(b,"Cols",3,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||a(c)});lucid.plugin.registerProperty(b,
"Selected",1,null,x(b,"7F7F7F","FFFFFF"))});d("iOS 6 iPhone Controls","Sort Buttons","sort_button.png",336,72,{l:12,r:12,d:2},function(b){function a(a){lucid.plugin.addBlockTextArea(b,{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Label</span>',getBoundingBox:function(a){return function(d){var c=lucid.plugin.getProperty(b,"Cols"),h=d.w/c;return a>c?null:{x:d.x+Math.round(h*(a-.9)),y:d.y+.5*d.h-7,w:.8*h,h:14}}}(a),wantReturn:!1,readOnly:!1,align:"center"})}lucid.plugin.registerProperty(b,
"Cols",3,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||a(c)});lucid.plugin.registerProperty(b,"Selected",1)});d("iOS 6 iPhone Controls","Tab Bar","tab_bar.png",640,96,{l:16,r:16,minWidth:640,simpleSelect:!0},function(b){function a(a){lucid.plugin.addBlockTextArea(b,{id:"Label_"+a,value:'<span style="font-weight:bold;font-size:9px;color:#'+(2==a?"FFFFFF":"A8A8A8")+';">Label</span>',getBoundingBox:function(a){return function(d){var c=
lucid.plugin.getProperty(b,"Cols"),h=d.w/c;return a>c?null:{x:d.x+Math.round(h*(a-.9)),y:d.y+42-5,w:.8*h,h:10}}}(a),wantReturn:!1,readOnly:!1,align:"center"})}lucid.plugin.registerProperty(b,"Cols",4,null,function(d,g){for(var f=lucid.plugin.getBlockTextAreas(b),c=1;c<=g;c++)lucid.array.contains(f,"Label_"+c)||a(c)});lucid.plugin.registerProperty(b,"Selected",2,null,x(b,"A8A8A8","FFFFFF"))});d("iOS 6 iPhone Controls","Multi Picker","picker_multi.png",640,456,{fixed:!0},function(b){lucid.plugin.addBlockTextArea(b,
{id:"Option1_1",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">Jun</span>',getBoundingBox:function(a){return{x:a.x+54,y:a.y+24-13,w:100,h:26}},wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option2_1",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">11</span>',getBoundingBox:function(a){return{x:a.x+180,y:a.y+24-13,w:100,h:26}},wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option1_2",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">Jul</span>',
getBoundingBox:function(a){return{x:a.x+54,y:a.y+66-13,w:100,h:26}},wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option2_2",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">12</span>',getBoundingBox:function(a){return{x:a.x+180,y:a.y+66-13,w:100,h:26}},wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option1_3",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">Aug</span>',getBoundingBox:function(a){return{x:a.x+
54,y:a.y+108-13,w:100,h:26}},wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option2_3",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">13</span>',getBoundingBox:function(a){return{x:a.x+180,y:a.y+108-13,w:100,h:26}},wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option1_4",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">Sept</span>',getBoundingBox:function(a){return{x:a.x+54,y:a.y+150-13,w:100,h:26}},
wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option2_4",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">14</span>',getBoundingBox:function(a){return{x:a.x+180,y:a.y+150-13,w:100,h:26}},wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option1_5",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">Oct</span>',getBoundingBox:function(a){return{x:a.x+54,y:a.y+192-13,w:100,h:26}},wantReturn:!1,readOnly:!1,
align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option2_5",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">15</span>',getBoundingBox:function(a){return{x:a.x+180,y:a.y+192-13,w:100,h:26}},wantReturn:!1,readOnly:!1,align:"left"})});d("iOS 6 iPhone Controls","Web Picker","picker_web.png",640,520,{fixed:!0},function(b){lucid.plugin.addBlockTextArea(b,{id:"Option1",value:'<span style="font-weight:bold;font-size:24px;color:#324f85;">Option 1</span>',getBoundingBox:function(a){return{x:a.x+
55,y:a.y+102-13,w:a.w-70,h:26}},wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option2",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">Option 2</span>',getBoundingBox:function(a){return{x:a.x+55,y:a.y+147-13,w:a.w-70,h:26}},wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option3",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">Option 3</span>',getBoundingBox:function(a){return{x:a.x+55,y:a.y+192-
13,w:a.w-70,h:26}},wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Option4",value:'<span style="font-weight:bold;font-size:24px;color:#000000;">Option 4</span>',getBoundingBox:function(a){return{x:a.x+55,y:a.y+237-13,w:a.w-70,h:26}},wantReturn:!1,readOnly:!1,align:"left"});lucid.plugin.addBlockTextArea(b,{id:"Label1",value:'<span style="font-weight:bold;font-size:12px;color:#8f8f8f;">Prev</span>',getBoundingBox:function(a){return{x:a.x+6,y:a.y+23-7,w:54,h:14}},wantReturn:!1,
readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Label2",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Next</span>',getBoundingBox:function(a){return{x:a.x+60,y:a.y+23-7,w:54,h:14}},wantReturn:!1,readOnly:!1,align:"center"});lucid.plugin.addBlockTextArea(b,{id:"Label3",value:'<span style="font-weight:bold;font-size:12px;color:#8f8f8f;">Autofill</span>',getBoundingBox:function(a){return{x:a.x+125,y:a.y+23-7,w:59,h:14}},wantReturn:!1,readOnly:!1,align:"center"});
lucid.plugin.addBlockTextArea(b,{id:"Label4",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">Done</span>',getBoundingBox:function(a){return{x:a.x+256,y:a.y+23-7,w:59,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Icons","Blue Add Icon","add_icon_blue.png",64,64,{fixed:!0});d("iOS 6 iPhone Icons","Green Add Icon","add_icon_green.png",64,64,{fixed:!0});d("iOS 6 iPhone Icons","Remove Icon","remove_icon.png",64,64,{fixed:!0});d("iOS 6 iPhone Icons","Arrow Icon",
"arrow_icon.png",64,64,{fixed:!0});d("iOS 6 iPhone Icons","Arrow","arrow.png",32,32,{fixed:!0});d("iOS 6 iPhone Icons","Checkmark","checkmark.png",32,32,{fixed:!0});d("iOS 6 iPhone Icons","Check","check_off.png",64,64,{fixed:!0},function(b){lucid.plugin.registerProperty(b,"Toggle",0)});d("iOS 6 iPhone Icons","Check On","check_on.png",64,64,{fixed:!0},null,null,!0);d("iOS 6 iPhone Icons","Location","location_dot.png",64,64,{fixed:!0});d("iOS 6 iPhone Icons","Mark As Read","mark_as_read.png",32,32,
{fixed:!0});d("iOS 6 iPhone Icons","Green Pin","pin_green.png",64,80,{fixed:!0});d("iOS 6 iPhone Icons","Red Pin","pin_red.png",64,80,{fixed:!0});d("iOS 6 iPhone Icons","Indicator","indicator.png",64,64,{l:32,r:32},function(b){lucid.plugin.addBlockTextArea(b,{id:"Count",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">2</span>',getBoundingBox:function(a){return{x:a.x+8,y:a.y+.5*a.h+2-7,w:a.w-16,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});d("iOS 6 iPhone Icons","Radio Button",
"radio_off.png",64,64,{fixed:!0},function(b){lucid.plugin.registerProperty(b,"Toggle",0)});d("iOS 6 iPhone Icons","Active Radio Button","radio_on.png",64,64,{fixed:!0},null,null,!0);d("iOS 6 iPhone Icons","Checkbox","checkbox_off.png",64,64,{fixed:!0},function(b){lucid.plugin.registerProperty(b,"Toggle",0)});d("iOS 6 iPhone Icons","Active Checkbox","checkbox_on.png",64,64,{fixed:!0},null,null,!0);d("iOS 6 iPhone Icons","Thread Count","thread_count.png",36,36,!1,function(b){lucid.plugin.addBlockTextArea(b,
{id:"Count",value:'<span style="font-weight:bold;font-size:12px;color:#FFFFFF;">7</span>',getBoundingBox:function(a){return{x:a.x,y:a.y+.5*a.h+1-7,w:a.w,h:14}},wantReturn:!1,readOnly:!1,align:"center"})});lucid.plugin.createToolGroups(v)})();
//# sourceMappingURL=/js/plugins/v2/source-maps/iphone.js.map
};
