pluginFn['/js/plugins/v2/mindmap.js'] = function(lucid, window) {
	(function(){function u(a){a=lucid.plugin.getBlockClassName(a);return null==a?!1:0===a.indexOf("MindMap")}function S(a){var c=C();return c[(a-1)%c.length]}function D(){return lucid.plugin.getProperty(null,"Version")||0}function t(a){E[a.className]=a;lucid.plugin.initBlockClass({className:a.className,name:a.name,searchKeywords:["mindmap","mind","map"].concat(a.searchKeywords),defaultSize:a.defaultSize,getLinkPoints:a.getLinkPoints,allowHiding:!0,onInit:function(c){function b(b,a){function m(){if(1<
D())return!lucid.text.hasOverflowText(c,"Text",!0);h=d(k);M=lucid.text.getSize(c,"Text",h);return!(M.w>=h.w||M.h>=h.h)}var l=lucid.plugin.getProperty(c,"BoundingBox");if(l){var h=d(l),M=lucid.text.getSize(c,"Text",h),k={x:l.x,y:l.y,w:l.w,h:l.h};k.w=Math.max(e,k.w);k.h=Math.max(g,k.h);if(2>D())for(;!m();)k.w*=1.1,k.h*=1.1;else m()||(k.w*=1.1,k.h*=1.1);if(!lucid.plugin.getProperty(c,"HasBeenUserResized")&&2>D()){for(var B=k;k.w>e&&k.h>g&&m();)if(B=lucid.object.clone(k),k.w*=f,k.h*=f,k.w<e||k.h<g){var N;
N=k.w/e<=k.h/g?e/B.w:g/B.h;k.w=B.w*N;k.h=B.h*N}k=B}if(l.w!=k.w||l.h!=k.h)k.x-=.5*(k.w-l.w),k.y-=.5*(k.h-l.h),lucid.plugin.setPropertyIfChanged(c,"HasBeenUserResized",!1),lucid.plugin.setProperty(c,"BoundingBox",k)}}G[c]=!0;lucid.plugin.registerProperty(c,"HideChildren",!1);lucid.plugin.setProperty(c,"TextVAlign","middle");var d=function(b){return 1<D()?{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||0,hideOverflow:!0}:a.getTextBoundingBox(b)};lucid.plugin.addBlockTextArea(c,
{id:"Text",value:"Mind Map",getBoundingBox:d});var e=a.defaultSize.w,g=a.defaultSize.h,f=1/1.1,h,l="Mind Map";lucid.plugin.hookPropertyPostSave(c,"Text",function(a,c){c.t===l||h||(h=setTimeout(function(){b(a,c);h=null},0),l=c.t)});lucid.plugin.hookPropertyPostSave(c,"FillColor",function(b,a){if(U){var d=x(c);0!=d&&(d=S(d),a!=d?lucid.plugin.setPropertyIfChanged(c,"NonStandardColor",!0):lucid.plugin.setPropertyIfChanged(c,"NonStandardColor",!1),lucid.plugin.setPropertyIfChanged(c,"LineColor",lucid.color.darken(a,
.5)))}});1<D()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5));if(a.onInit)a.onInit(c)},onCreate:function(a){lucid.plugin.editBlockTextArea(a,"Text");lucid.plugin.setProperty(a,"NoLighten",!0)},getRenderData:function(c,b){var d=a.getRenderData(c,b),e=c.BoundingBox;if((c.HideChildren||"hover"==b)&&0<A(c.id).length){var g=[{Action:"move",x:e.x+e.w-2,y:e.y+e.h-10},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(e.x+e.w-18,e.y+e.h-18,16,
16,0,2*Math.PI)},{Action:"close"},{Action:"move",x:e.x+e.w-14,y:e.y+e.h-10},{Action:"line",x:e.x+e.w-6,y:e.y+e.h-10}];c.HideChildren&&(g.push({Action:"move",x:e.x+e.w-10,y:e.y+e.h-14}),g.push({Action:"line",x:e.x+e.w-10,y:e.y+e.h-6}));d.push({FillColor:"#FFFFFF",StrokeColor:"#333333",LineWidth:1,Actions:g})}return d},hitTest:function(a,b){var d=lucid.plugin.getProperty(a,"BoundingBox");if(d){var e=lucid.math.Point.rotate(b,lucid.math.Box.center(d),-lucid.plugin.getProperty(a,"Rotation"));if(0!=A(a).length&&
lucid.math.Point.inBox(e,{x:d.x+d.w-20,y:d.y+d.h-20,w:20,h:20}))return{onClick:function(){O(a)},cursor:"pointer"}}},disabledPropertyControls:["FillType","LineWidth","LineColor"],vLock:!1,hLock:!1,renderOnHover:!0,getOffsetProperties:function(a,b,d){var e={};if(0==d.w&&0==d.h){var g=lucid.plugin.getDownstream(a,function(b){return b==a||!lucid.plugin.isSelected(b)});b=b||lucid.plugin.getProperty(a,"BoundingBox");for(var f=0;f<g.length;f++){var h=g[f];e[h]=lucid.plugin.defaultOffsetProperties(h,b,d)[h]}}else return lucid.plugin.setPropertyIfChanged(a,
"HasBeenUserResized",!0),lucid.plugin.defaultOffsetProperties(a,b,d);return e},onDelete:function(a){I=!0;null==a&&V(a);lucid.array.forEach(lucid.plugin.getOutgoingLines(a),function(b){var d=lucid.plugin.getProperty(b,"Endpoint2");d.Block&&d.Block!=a&&u(d.Block)&&(lucid.plugin.deleteItem(d.Block),lucid.plugin.deleteItem(b))});lucid.array.forEach(lucid.plugin.getIncomingLines(a),function(b){lucid.plugin.deleteItem(b)});I=!1},lineDrawnProperties:function(a,b){return{Shape:"diagonal",AutoLink:!0,IgnoreTheme:{LineWidth:!0,
LineColor:!0,Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0},LineColor:"#000000",LineWidth:2,Inset:0,Endpoint1:{Style:"None"},Endpoint2:{Style:"None"}}}})}var y={global:this,provide:function(a){a=a.split(".");y.global[a[0]]=y.global[a[0]]||{};var c=y.global[a[0]];a.slice(1).reduce(function(a,c){a[c]||(a[c]={});return a[c]},c)},require:function(){},inherits:function(a,c){function b(){}b.prototype=c.prototype;a.superClass_=c.prototype;a.prototype=new b;a.prototype.constructor=a;a.base=function(a,b,g){var f=
Array.prototype.slice.call(arguments,2);return c.prototype[b].apply(a,f)}},base:function(a,c,b){var d=arguments.callee.caller;if(y.STRICT_MODE_COMPATIBLE||y.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var e=Array.prototype.slice.call(arguments,2),g=!1,f=a.constructor;f;f=f.superClass_&&
f.superClass_.constructor)if(f.prototype[c]===d)g=!0;else if(g)return f.prototype[c].apply(a,e);if(a[c]===d)return a.constructor.prototype[c].apply(a,e);throw Error("goog.base called from a method of one name to a method of a different name");}};y.provide("plugin.layout.TreeHotKeys");plugin.layout.TreeHotKeys=function(a){var c=this;this.selectedNode=null;lucid.plugin.onSelectionChange(function(b){1==b.length&&a(b[0])?(c.selectedNode=b[0],lucid.hotKeys.enable()):(c.selectedNode=null,lucid.hotKeys.disable())})};
plugin.layout.TreeHotKeys.prototype.initAddChild=function(a){var c=this;lucid.hotKeys.add(["tab"],function(){c.selectedNode&&(lucid.text.isEditorActive()?lucid.text.blurEditor():a(c.selectedNode))})};plugin.layout.TreeHotKeys.prototype.initAddSibling=function(a){var c=this;lucid.hotKeys.add(["enter"],function(){c.selectedNode&&(lucid.text.isEditorActive()?lucid.text.blurEditor():a(c.selectedNode))})};plugin.layout.TreeHotKeys.prototype.initMoveUp=function(a){var c=this;lucid.hotKeys.add(["up"],function(){c.selectedNode&&
(lucid.text.isEditorActive()&&lucid.text.blurEditor(),a(c.selectedNode))})};plugin.layout.TreeHotKeys.prototype.initMoveDown=function(a){var c=this;lucid.hotKeys.add(["down"],function(){c.selectedNode&&(lucid.text.isEditorActive()&&lucid.text.blurEditor(),a(c.selectedNode))})};plugin.layout.TreeHotKeys.prototype.initMoveRight=function(a){var c=this;lucid.hotKeys.add(["right"],function(){c.selectedNode&&(lucid.text.isEditorActive()&&lucid.text.blurEditor(),a(c.selectedNode))})};plugin.layout.TreeHotKeys.prototype.initMoveLeft=
function(a){var c=this;lucid.hotKeys.add(["left"],function(){c.selectedNode&&(lucid.text.isEditorActive()&&lucid.text.blurEditor(),a(c.selectedNode))})};plugin.layout.TreeHotKeys.prototype.getSelected=function(){return this.selectedNode};y.provide("plugin.mindmap");y.require("plugin.layout.TreeHotKeys");var H=null,W,U=!1;lucid.plugin.onDocumentLoaded(function(){function a(a,b,c){g&&!b.nospace&&a.spacer();g=!0;"colorwell"==b.type?(a.addGrid({width:6,content:{text:b.name,classes:"crop ralign"}}),a.openGrid({width:3,
suffix:3}),a.addInput({type:"colorwell",value:b.value,onChange:b.onChange,size:"fullwidth"}),a.close()):"button"==b.type&&(a.openGrid({width:6,prefix:3,suffix:3}),a.addButton({onClick:function(){b.onClick(b.id)},label:b.text}),a.close())}function c(b,c,d){var e=function(a,b){if(!b){W=d;var c=C();c[d-1]=a;H=null;lucid.plugin.setProperty(null,"MindMapColors",c)}},g=function(a,b){if(!b){var c=J(lucid.array.filter(lucid.plugin.getSelectionDetails(),function(a){return a.isBlock})[0].id);c&&(lucid.plugin.setPropertyIfChanged(c,
"FillColor",a),lucid.plugin.setPropertyIfChanged(c,"LineColor","#000000"))}};a(b,{type:"colorwell",name:0==d?"Root Color:":"Level "+d+" Color:",value:c,onChange:0==d?g:e})}function b(){if(!h){h=!0;f=lucid.template.builder();var b=C(),g=lucid.array.filter(lucid.plugin.getSelectionDetails(),function(a){return a.isBlock});if(0<g.length){var w=J(g[0].id),w=lucid.plugin.getProperty(w,"FillColor");c(f,w,0)}lucid.array.forEach(b,function(a,b){c(f,a,b+1)});a(f,{onClick:function(){g[0].id in G&&P(g[0].id)},
text:"Auto Layout",type:"button"});d.getElement(e).setContent(f);f.refreshInputs();h=!1;return f}}var d=lucid.template.builder(),e=d.add(),g=!1,f,h=!1;lucid.plugin.addCustomPanel("Context Panel",null,[{content:d}],null,{isContextPanel:!0,checkShow:function(a){if(lucid.useragent.is_touch())return!1;a=lucid.array.filter(a,function(a){return a.isBlock});a=0<a.length&&lucid.array.every(a,function(a){return a.id in G});g=!1;b();return a&&function(){f&&f.refreshInputs&&f.refreshInputs()}}});lucid.plugin.hookPropertyPostSave(null,
"ColorTheme",function(a){H=lucid.plugin.getDocumentColorTheme();lucid.plugin.setProperty(null,"MindMapColors",H);z=!0;b()});lucid.plugin.suspendUndoHistory(function(){var a=[];lucid.plugin.getAllBlockIds().forEach(function(b){u(b)&&(lucid.plugin.getProperty(b,"NoLighten")||a.push(b))});if(0<a.length){for(var b=C(),c=0;c<b.length;c++)b[c]=lucid.color.lighten(b[c],.5);lucid.plugin.setProperty(null,"MindMapColors",b);a.forEach(function(a){lucid.plugin.setProperty(a,"NoLighten",!0)})}});U=!0});var n=
function(a,c,b,d,e){this.parent=a;this.id=c;this.x=b;this.y=d;this.origX=b;this.origY=d;this.size=e;this.children=[];this.layers=this.leaves=0;this.layer=1;a&&a.children.push(this)};n.prototype.addChild=function(a,c){if(a.parent!=this){a.parent=this;(this.parent||this).cacheSpringSizes();this.updateLeaves();this.layers=Math.ceil(Math.sqrt(.25+2*Math.ceil(this.leaves/6))-.5);this.children.push(a);this.updateLeaves();var b=Math.ceil(Math.sqrt(.25+2*Math.ceil(this.leaves/6))-.5);this.layers==b&&(this.pin=
!0);this.parent&&(this.parent.pin=!0);this.layers=b;a.layer=this.layers;(this.parent||this).applyNewSpringSizeOffset(!!c)}};n.prototype.cacheSpringSizes=function(){this.cachedSpringSize=this.actualSpringSize();for(var a=0;a<this.children.length;a++)this.children[a].cacheSpringSizes()};n.prototype.applyNewSpringSizeOffset=function(a,c,b){var d=0,e=0;this.cachedSpringSize&&this.cachedSpringSize.dist&&(d=this.minSpringSize()/this.cachedSpringSize.dist,a||(d=Math.max(1,d)),e=d-1,d=e*this.cachedSpringSize.dx+
(c||0),e=e*this.cachedSpringSize.dy+(b||0),this.x+=d,this.y+=e);for(c=0;c<this.children.length;c++)this.children[c].applyNewSpringSizeOffset(!!a,d,e)};n.prototype.updateLeaves=function(){for(var a=this.leaves=0;a<this.children.length;a++)this.children[a].isLeaf()&&this.leaves++};n.prototype.ancestorPinned=function(){for(var a=this.parent;a;){if(a.pin)return!0;a=a.parent}return!1};n.prototype.isLeaf=function(){return 0==this.children.length};n.prototype.getRadius=function(){for(var a,c,b=0,d=0,e=0;e<
this.children.length;e++)a=this.children[e],c=a.getRadius(),b+=c,a.isLeaf()&&(d=Math.max(c,d));b&&(b/=6*Math.ceil(this.children.length/6));return Math.max(Math.max(this.size,d)+2*this.layers*d,b)};n.prototype.minSpringSize=function(){if(!this.parent)return 0;if(this.isLeaf())return this.parent.size+this.size*(2*this.layer-1)+10;var a=this.getRadius();this.updateLeaves();this.leaves==this.children.length&&(3>=this.leaves?a*=.33:5>=this.leaves&&(a*=.67));return this.parent.getRadius()+a+10};n.prototype.actualSpringSize=
function(){if(!this.parent)return{dx:0,dy:0,dist:0};var a=this.x-this.parent.x,c=this.y-this.parent.y;return{dx:a,dy:c,dist:Math.sqrt(a*a+c*c)}};n.prototype.countDescendants=function(a,c){if(null!=this.descendants&&!a)return this.descendants;c=c||{};for(var b=0,d=0;d<this.children.length;d++){var e=this.children[d];if(c[e.id])break;b++;b+=e.countDescendants(!!a,c)}return this.descendants=b};n.prototype.sortChildren=function(){for(var a=0;a<this.children.length;a++)this.children[a].countDescendants();
this.children.sort(function(a,c){return a.descendants-c.descendants});if(null==this.parent){for(var a=[],c=!0;0<this.children.length;)c?a.push(this.children.pop()):a.push(this.children.shift()),c=!c;this.children=a}};var I=!0;lucid.plugin.onDocumentLoaded(function(){I=!1;lucid.array.forEach(lucid.plugin.getChildren(),function(a){u(a)&&lucid.array.forEach(lucid.plugin.getConnectedLines(a),function(a){"diagonal"==lucid.plugin.getProperty(a,"Shape")&&lucid.plugin.setPropertyIfChanged(a,"IgnoreTheme",
{LineWidth:!0,LineColor:!0,Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0})})});lucid.plugin.inReadOnlyMode()||setTimeout(function(){for(var a=lucid.plugin.getChildren(),c=0,b=a.length;c<b;c++)if(u(a[c])){a=J(a[c]);lucid.plugin.deselectAllItems();lucid.plugin.selectItem(a);lucid.plugin.showRect(lucid.math.Box.pad(lucid.plugin.getProperty(a,"BoundingBox"),1E3));break}},1E3)});var K={},G={},r=function(a){for(var c=[],b=lucid.plugin.getIncomingLines(a),d=0;d<b.length;d++){var e=lucid.plugin.getProperty(b[d],
"Endpoint1");e.Block&&e.Block!=a&&c.push(e.Block)}return c},A=function(a){for(var c=[],b=lucid.plugin.getOutgoingLines(a),d=0;d<b.length;d++){var e=lucid.plugin.getProperty(b[d],"Endpoint2");e.Block&&e.Block!=a&&c.push(e.Block)}return c},x=function(a,c){if(a in K)return K[a];null==c&&(c=[]);c=c.concat(a);var b,d=r(a);if(0==d.length)b=0;else{b=Number.MAX_VALUE;for(var e=0;e<d.length;e++){var g=d[e];lucid.array.contains(c,g)||(b=Math.min(b,x(g,c)+1))}b==Number.MAX_VALUE&&(b=0)}return K[a]=b},J=function(a){for(var c=
a,b=x(a),d=r(a);0<b&&0<d.length;){for(var e=0;e<d.length;e++){var g=d[e],f=x(g);f<b&&(c=g,b=f,d=r(g));if(0==b)break}b==x(a)&&(b=0)}return c},Q={},X=function(a,c,b){var d=(a+.9|0)+"x"+(c+.9|0);Q[d]||(Q[d]=Math.sqrt(a*a+c*c)/2);return Q[d]+b},Y=function(){if(!I){K={};var a={},c;for(c in G)if(lucid.plugin.isBlock(c)&&u(c)){a[c]=!0;var b=c,d=x(b);lucid.plugin.setPropertyIfChanged(b,"LineWidth",d?2:4);var e;e=0==d||lucid.plugin.getProperty(b,"NonStandardColor")?lucid.plugin.getProperty(b,"FillColor"):
S(d);lucid.plugin.setPropertyIfChanged(b,"FillColor",e);lucid.plugin.setPropertyIfChanged(b,"LineColor",d?lucid.color.darken(e,.5):"#000000")}G=a}};lucid.plugin.onBlockReplaced(function(a){u(a)&&lucid.plugin.getConnectedLines(a).forEach(function(c){lucid.plugin.setPropertyIfChanged(c,"AutoLink",!0);lucid.plugin.setProperty(a,"BoundingBox",lucid.plugin.getProperty(a,"BoundingBox"))})});var z=!1;lucid.plugin.onAction(function(a){a.Action!=lucid.ActionType.SetProperty||"Endpoint1"!=a.Property&&"Endpoint2"!=
a.Property?a.Action==lucid.ActionType.CreateBlock||a.Action==lucid.ActionType.CreateLine?z=!0:a.Action==lucid.ActionType.RemoveBlock||a.Action==lucid.ActionType.RemoveLine||a.Action==lucid.ActionType.RemoveGroup?z=!0:a.Action==lucid.ActionType.SetProperty&&"MindMapColors"==a.Property&&(z="setColors"):z=!0});lucid.plugin.afterCurrentUserNewAction(function(){if(z){Y();if("setColors"==z){var a=lucid.plugin.getAllBlockIds(function(a){return u(a)&&lucid.plugin.getProperty(a,"NonStandardColor")&&x(a)%C().length==
W});0<a.length&&lucid.dialog.confirm(1===a.length?"There is 1 mindmap shape which does not match this level's default color. Would you like to update this shape too?":"There are "+a.length+" mindmap shapes which do not match this level's default color. Would you like to update those shapes too?",function(){a.forEach(function(a){lucid.plugin.setProperty(a,"NonStandardColor",!1)});Y();return!0},function(){},["Yes","No"])}z=!1}});var Z=function(a,c,b){function d(b,c){if(!g[b]){g[b]=!0;var f=lucid.plugin.getProperty(b,
"BoundingBox"),m=f.x+f.w/2,q=f.y+f.h/2,T=A(b),f=new n(c,b,m,q,X(f.w,f.h,10));e.push(f);b==a&&(h=f);for(m=0;m<T.length;m++)d(T[m],f)}}var e=[],g={},f=J(a),h;d(f,null);h&&c&&c(h);b&&b(g);return e},aa=function(a,c,b,d,e,g){var f;f=c.parent?Math.atan2(c.y-c.parent.y,c.x-c.parent.x)+(c.children.length%2*2-1)*(e?.25*(1-(c.children.length+1)/e):.3333333333*((c.children.length+1)/2|0))*Math.PI:(e?c.children.length/e*360:c.children.length%6*60)*Math.PI/180;f+=10*(c.children.length/6|0)*Math.PI/180;e=Math.cos(f);
f=Math.sin(f);b=new n(null,b,0,0,d);c.addChild(b,!!g);g=b.minSpringSize();b.x=c.x+e*g;b.y=c.y+f*g;b.origX=b.x;b.origY=b.y;a.push(b);return b},ba=function(a){for(var c=[],b=[],d=0;d<a.length;d++){var e=a[d];c.push({id:e.id,x:e.x,y:e.y,origX:e.origX,origY:e.origY,r:e.size,pin:!(null!=e.parent&&!e.pin)});if(e.parent){var g=e.x-e.parent.x,f=e.y-e.parent.y;b.push({id1:e.parent.id,id2:e.id,length:Math.sqrt(g*g+f*f)})}}return{circles:c,springs:b}},P=function(a){function c(a,b){h[b]||(h[b]=[]);for(var d=
0;d<a.children.length;d++){var e=a.children[d];h[b].push(e);c(e,b+1)}}function b(a,b){var c=ba(g),d=c.springs,c=c.circles;lucid.physics.createWorldAndSettle(c,d,a,function(a){for(var c=g,d=0;d<a.length;d++){var e=a[d],f=c[d];if(!f||e.id!=f.id)break;f.x=e.newX;f.y=e.newY}b&&b(a)})}var d=Z(a);if(!(1>d.length)){var e=d[0],g=[new n(null,e.id,e.x,e.y,e.size)];a={};a[e.id]=g[0];for(var f=0;f<d.length;f++)0==f&&d[f].countDescendants(!0),d[f].sortChildren();var h=[];c(e,0);for(d=0;d<h.length;d++)for(e=h[d],
f=0;f<e.length;f++){var l=e[f],F=a[l.parent.id];if(!F)break;a[l.id]=aa(g,F,l.id,l.size,l.parent.children.length,!0);b(2)}b(5,function(a){for(var b=0;b<a.length;b++){var c=a[b];lucid.plugin.getConnectedLines(c.id).forEach(function(a){lucid.plugin.resetLine(a)});if(!lucid.plugin.getProperty(c.id,"Lock")){var d=lucid.plugin.getProperty(c.id,"BoundingBox");if(!d)break;var e=c.newX-(d.x+d.w/2),f=c.newY-(d.y+d.h/2);25<e*e+f*f&&(d=lucid.plugin.getProperty(c.id,"BoundingBox"),lucid.plugin.setPropertyIfChanged(c.id,
"BoundingBox",{x:Math.round(d.x+e),y:Math.round(d.y+f),w:Math.round(d.w),h:Math.round(d.h)}))}}var g=function(a){return a.Block&&0==lucid.plugin.getBlockClassName(a.Block).indexOf("MindMap")},l=function(a,b){return lucid.plugin.getProperty(lucid.plugin.getProperty(a,b).Block,"BoundingBox")},h=function(a,b,c,d,e){var f=Math.min(((b.x>c.x?a.x:a.x+a.w)-b.x)/(c.x-b.x),((b.y>c.y?a.y:a.y+a.h)-b.y)/(c.y-b.y)),g=lucid.plugin.getProperty(d,e);g.LinkX=(b.x+f*(c.x-b.x)-a.x)/a.w;g.LinkY=(b.y+f*(c.y-b.y)-a.y)/
a.h;lucid.plugin.setProperty(d,e,g)};a.reduce(function(a,b){return a.concat(lucid.plugin.getConnectedLines(b.id).filter(function(b){return 0<=a.indexOf(b)?!1:g(lucid.plugin.getProperty(b,"Endpoint1"))&&g(lucid.plugin.getProperty(b,"Endpoint2"))}))},[]).forEach(function(a){var b=l(a,"Endpoint1"),c=l(a,"Endpoint2"),d=lucid.math.Box.center(b),e=lucid.math.Box.center(c);0<lucid.math.Point.distance(d,e)&&(h(b,d,e,a,"Endpoint1"),h(c,e,d,a,"Endpoint2"))})})}},R=function(a){var c=E[lucid.plugin.getBlockClassName(a)].defaultSize,
b,d={},e=X(c.w,c.h,10),g="__temp__",f=Z(a,function(a){b=a},function(a){d=a});if(b){for(;d[g];)g+=Math.round(10*Math.random());aa(f,b,g,e);var e=ba(f),f=e.springs,e=e.circles,h,e=lucid.physics.createWorldAndSettle(e,f,null,function(b){lucid.plugin.getProperty(a,"HideChildren")&&O(a);for(var d=lucid.plugin.getItemPageId(a),e=0;e<b.length;e++){var f=b[e];if(f.id==g){f={x:f.newX-c.w/2,y:f.newY-c.h/2,w:c.w,h:c.h};h=lucid.plugin.addBlock(d,{className:lucid.plugin.getBlockClassName(a),BoundingBox:f,Text:"New Idea",
NoLighten:!0});var q=lucid.plugin.getProperty(a,"BoundingBox");lucid.plugin.addLine(d,{Shape:"diagonal",IgnoreTheme:{LineWidth:!0,LineColor:!0,Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0},AutoLink:!0,LineWidth:2,LineColor:"#000000",Endpoint1:{Block:a,LinkX:.5,LinkY:.5,x:q.x+q.w/2,y:q.y+q.h/2,Style:"None"},Endpoint2:{Block:h,LinkX:.5,LinkY:.5,x:f.x+f.w/2,y:f.y+f.h/2,Style:"None"}});lucid.plugin.setProperty(h,"BoundingBox",f)}else if(!lucid.plugin.getProperty(f.id,"Lock")){var q=f.newX-f.origX,n=f.newY-
f.origY;if(25<q*q+n*n){var p=lucid.plugin.getProperty(f.id,"BoundingBox");lucid.plugin.setPropertyIfChanged(f.id,"BoundingBox",{x:Math.round(p.x+q),y:Math.round(p.y+n),w:Math.round(p.w),h:Math.round(p.h)})}}}lucid.plugin.deselectAllItems();lucid.plugin.selectItem(h);lucid.plugin.editBlockTextArea(h,"Text")});return h}},ca=function(a,c){var b=2*Math.PI,d=(c+b)%b-(a+b)%b;return d>Math.PI?d-b:d<-Math.PI?d+b:d},v=function(a){var c=r(a);if(0==c.length)return null;a=lucid.math.Box.center(lucid.plugin.getProperty(a,
"BoundingBox"));c=lucid.math.Box.center(lucid.plugin.getProperty(c[0],"BoundingBox"));return Math.atan2(a.y-c.y,a.x-c.x)},da=function(a){var c=A(a),b=v(a)||0,d=lucid.math.Box.center(lucid.plugin.getProperty(a,"BoundingBox")),e=[];lucid.array.forEach(c,function(a){var c=lucid.math.Box.center(lucid.plugin.getProperty(a,"BoundingBox")),c=ca(Math.atan2(c.y-d.y,c.x-d.x),b);e.push({id:a,theta:c})});e.sort(function(a,b){return a.theta-b.theta});return e},V=function(a){a=r(a);0<a.length&&(lucid.plugin.deselectAllItems(),
lucid.plugin.selectItem(a[0]),lucid.plugin.showRect(lucid.plugin.getProperty(a[0],"BoundingBox")))},ea=function(a,c){var b=da(a),d=1E4,e,g=null;c=c||0;for(var f=0,h=b.length;f<h;f++)e=Math.abs(ca(b[f].theta,c)),e<d&&(d=e,g=b[f].id);g&&(lucid.plugin.deselectAllItems(),lucid.plugin.selectItem(g),lucid.plugin.showRect(lucid.plugin.getProperty(g,"BoundingBox")))},fa=function(a,c){var b=r(a);if(0!=b.length){var b=da(b[0]),d;d=0;for(var e=b.length;d<e;d++)if(b[d].id==a){d=(d+e+c)%e;lucid.plugin.deselectAllItems();
lucid.plugin.selectItem(b[d].id);lucid.plugin.showRect(lucid.plugin.getProperty(b[d].id,"BoundingBox"));break}}},ga=function(a){var c=A(a);a=lucid.plugin.getOutgoingLines(a);lucid.array.forEach(a,function(a){lucid.plugin.setProperty(a,"Hidden",!0)});lucid.array.forEach(c,function(a){lucid.plugin.setProperty(a,"Hidden",!0);ga(a)})},ha=function(a){lucid.plugin.setProperty(a,"Hidden",!1);if(!lucid.plugin.getProperty(a,"HideChildren")){var c=lucid.plugin.getOutgoingLines(a);lucid.array.forEach(c,function(a){lucid.plugin.setProperty(a,
"Hidden",!1)});a=A(a);lucid.array.forEach(a,function(a){ha(a)})}},O=function(a){var c=!lucid.plugin.getProperty(a,"HideChildren");lucid.plugin.setProperty(a,"HideChildren",c);c?ga(a):ha(a)},E={};t({className:"MindMapBlock",name:"Rectangle",searchKeywords:["rectangle"],defaultSize:{w:116,h:42},getTextBoundingBox:function(a){return{x:a.x+10,y:a.y+10,w:a.w-20,h:a.h-20}},getLinkPoints:function(){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},onInit:function(a){lucid.plugin.setProperty(a,"Rounding",
10)},getRenderData:function(a,c){var b=a.BoundingBox;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y},{Action:"line",x:b.x+b.w,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+b.h},{Action:"close"}]}]}});t({className:"MindMapCircle",name:"Circle",searchKeywords:["circle"],defaultSize:{w:120,h:120},getTextBoundingBox:function(a){return{x:a.x+.18*a.w,y:a.y+.18*a.h,w:.64*a.w,h:.64*a.h}},getLinkPoints:function(){return[{x:.5,
y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(a){var c=a.BoundingBox;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:c.x+c.w,y:c.y+c.h/2},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(c.x,c.y,c.w,c.h,0,2*Math.PI)},{Action:"close"}]}]}});t({className:"MindMapDiamondBlock",name:"Diamond",searchKeywords:["diamond"],defaultSize:{w:160,h:120},getTextBoundingBox:function(a){return{x:a.x+.25*a.w,y:a.y+.25*a.h,w:.5*a.w,h:.5*
a.h}},getLinkPoints:function(){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(a,c){var b=a.BoundingBox,d=b.x+b.w/2,e=b.y+b.h/2;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:d,y:b.y},{Action:"line",x:b.x+b.w,y:e},{Action:"line",x:d,y:b.y+b.h},{Action:"line",x:b.x,y:e},{Action:"close"}]}]}});t({className:"MindMapIsoscelesTriangleBlock",name:"Triangle",searchKeywords:["triangle","isosceles"],defaultSize:{w:140,h:120},
getTextBoundingBox:function(a){return{x:a.x+.25*a.w,y:a.y+.5*a.h,w:.5*a.w,h:.4*a.h}},getLinkPoints:function(a){return[{x:.5,y:0},{x:.25,y:.5},{x:.5,y:1},{x:.75,y:.5}]},getRenderData:function(a,c){var b=a.BoundingBox;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y+b.h},{Action:"line",x:b.x+b.w,y:b.y+b.h},{Action:"line",x:b.x+b.w/2,y:b.y},{Action:"close"}]}]}});t({className:"MindMapOctagonBlock",name:"Octagon",searchKeywords:["octagon"],
defaultSize:{w:120,h:120},getTextBoundingBox:function(a){return{x:a.x+.145*a.w,y:a.y+.145*a.h,w:.71*a.w,h:.71*a.h}},getLinkPoints:function(a){return[{x:.145,y:.145},{x:.5,y:0},{x:.855,y:.145},{x:1,y:.5},{x:.855,y:.855},{x:.5,y:1},{x:.145,y:.855},{x:0,y:.5}]},getRenderData:function(a,c){var b=a.BoundingBox;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y+.29*b.h},{Action:"line",x:b.x+.29*b.w,y:b.y},{Action:"line",x:b.x+.71*b.w,y:b.y},{Action:"line",
x:b.x+b.w,y:b.y+.29*b.h},{Action:"line",x:b.x+b.w,y:b.y+.71*b.h},{Action:"line",x:b.x+.71*b.w,y:b.y+b.h},{Action:"line",x:b.x+.29*b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+.71*b.h},{Action:"close"}]}]}});t({className:"MindMapCloud",name:"Cloud",searchKeywords:["cloud"],defaultSize:{w:133,h:100},getTextBoundingBox:function(a){return{x:a.x+.18*a.w,y:a.y+.18*a.h,w:.72*a.w,h:.64*a.h}},getLinkPoints:function(a){return[{x:0,y:.5},{x:.24,y:.07},{x:.6,y:.01},{x:.97,y:.3},{x:.955,y:.85},{x:.6,y:1},{x:.25,
y:.925}]},getRenderData:function(a,c){var b=a.BoundingBox;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x+.15*b.w,y:b.y+.7*b.h},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(b.x,b.y+.3*b.h,.3*b.w,.4*b.h,.5*Math.PI,1.4*Math.PI)},{Action:"curve",Control:[{x1:b.x+.1*b.w,y1:b.y+.05*b.h,x2:b.x+.35*b.w,y2:b.y+0*b.h,x3:b.x+.45*b.w,y3:b.y+.1*b.h},{x1:b.x+.5*b.w,y1:b.y+-.05*b.h,x2:b.x+.75*b.w,y2:b.y+0*b.h,x3:b.x+.75*b.w,y3:b.y+.15*b.h},
{x1:b.x+.9*b.w,y1:b.y+.1*b.h,x2:b.x+1.05*b.w,y2:b.y+.3*b.h,x3:b.x+.95*b.w,y3:b.y+.55*b.h},{x1:b.x+1.05*b.w,y1:b.y+.75*b.h,x2:b.x+.95*b.w,y2:b.y+1*b.h,x3:b.x+.75*b.w,y3:b.y+.9*b.h},{x1:b.x+.7*b.w,y1:b.y+1.03*b.h,x2:b.x+.5*b.w,y2:b.y+1.03*b.h,x3:b.x+.45*b.w,y3:b.y+.9*b.h},{x1:b.x+.35*b.w,y1:b.y+1*b.h,x2:b.x+.15*b.w,y2:b.y+.95*b.h,x3:b.x+.15*b.w,y3:b.y+.7*b.h}]},{Action:"close"}]}]}});t({className:"MindMapPentagonBlock",name:"Pentagon",searchKeywords:["pentagon"],defaultSize:{w:126,h:120},getTextBoundingBox:function(a){return{x:a.x+
.175*a.w,y:a.y+.25*a.h,w:.65*a.w,h:.62*a.h}},getLinkPoints:function(a){return[{x:0,y:.382},{x:.25,y:.191},{x:.5,y:0},{x:.75,y:.191},{x:1,y:.382},{x:.9045,y:.691},{x:.809,y:1},{x:.5,y:1},{x:.191,y:1},{x:.0955,y:.691}]},getRenderData:function(a,c){var b=a.BoundingBox;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y+.382*b.h},{Action:"line",x:b.x+b.w/2,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+.382*b.h},{Action:"line",x:b.x+.809*b.w,y:b.y+b.h},
{Action:"line",x:b.x+.191*b.w,y:b.y+b.h},{Action:"close"}]}]}});t({className:"MindMapCrossBlock",name:"Cross",searchKeywords:["cross"],defaultSize:{w:120,h:120},onInit:function(a){lucid.plugin.registerProperty(a,"Indent",{x:.25,y:.25})},getTextBoundingBox:function(a){return{x:a.x+.1*a.w,y:a.y+.25*a.h,w:.8*a.w,h:.5*a.h}},getLinkPoints:function(){return[{x:0,y:.5},{x:.5,y:0},{x:1,y:.5},{x:.5,y:1}]},getRenderData:function(a,c){var b=a.BoundingBox,d=a.Indent;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,
LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y+b.h*d.y},{Action:"line",x:b.x+b.w*d.x,y:b.y+b.h*d.y},{Action:"line",x:b.x+b.w*d.x,y:b.y},{Action:"line",x:b.x+b.w-b.w*d.x,y:b.y},{Action:"line",x:b.x+b.w-b.w*d.x,y:b.y+b.h*d.y},{Action:"line",x:b.x+b.w,y:b.y+b.h*d.y},{Action:"line",x:b.x+b.w,y:b.y+b.h-b.h*d.y},{Action:"line",x:b.x+b.w-b.w*d.x,y:b.y+b.h-b.h*d.y},{Action:"line",x:b.x+b.w-b.w*d.x,y:b.y+b.h},{Action:"line",x:b.x+b.w*d.x,y:b.y+b.h},{Action:"line",x:b.x+b.w*d.x,y:b.y+b.h-b.h*d.y},
{Action:"line",x:b.x,y:b.y+b.h-b.h*d.y},{Action:"close"}]}]}});t({className:"MindMapHexagonBlock",name:"Hexagon",searchKeywords:["hexagon"],defaultSize:{w:140,h:120},getTextBoundingBox:function(a){return{x:a.x+.2*a.w,y:a.y+.1*a.h,w:.6*a.w,h:.8*a.h}},getLinkPoints:function(a){return[{x:0,y:.5},{x:.125,y:.25},{x:.25,y:0},{x:.5,y:0},{x:.75,y:0},{x:.875,y:.25},{x:1,y:.5},{x:.875,y:.75},{x:.75,y:1},{x:.5,y:1},{x:.25,y:1},{x:.125,y:.75}]},getRenderData:function(a,c){var b=a.BoundingBox;return[{FillColor:a.FillColor,
StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y+b.h/2},{Action:"line",x:b.x+.25*b.w,y:b.y},{Action:"line",x:b.x+.75*b.w,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+b.h/2},{Action:"line",x:b.x+.75*b.w,y:b.y+b.h},{Action:"line",x:b.x+.25*b.w,y:b.y+b.h},{Action:"close"}]}]}});t({className:"MindMapStadiumBlock",name:"Pill",searchKeywords:["stadium","pill"],defaultSize:{w:160,h:80},getTextBoundingBox:function(a){return{x:a.x+.15*a.w,y:a.y,w:.7*a.w,h:a.h}},getLinkPoints:function(){return[{x:.5,
y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(a){var c=a.BoundingBox;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:c.x+.8*c.w,y:c.y},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(c.x+.6*c.w,c.y,.4*c.w,c.h,-.5*Math.PI,.5*Math.PI)},{Action:"line",x:c.x+.2*c.w,y:c.y+c.h},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(c.x,c.y,.4*c.w,c.h,.5*Math.PI,1.5*Math.PI)},{Action:"close"}]}]}});var C=function(){if(H)return H;
var a=lucid.plugin.getProperty(null,"MindMapColors");a||(a=["#f78d1eff","#8cbf3fff","#29aae1ff","#a32385ff","#ea0e8bff"],lucid.plugin.setProperty(null,"MindMapColors",a));return a},L=function(a,c,b){null==c?ea(a,b):(b=(Math.round(180*b/Math.PI)+360)%360,c=(Math.round(180*c/Math.PI)+360+b)%360,45>c||315<=c?ea(a):135>c?fa(a,1):225>c?V(a):315>c&&fa(a,-1))},p=new plugin.layout.TreeHotKeys(u);p.initAddChild(R);p.initAddSibling(function(a){a=r(a);0<a.length&&R(a[0])});p.initMoveLeft(function(a){var c,b=
r(a);0<b.length&&(c=v(b[0]));c||(c=v(a));L(a,c,Math.PI)});p.initMoveRight(function(a){var c,b=r(a);0<b.length&&(c=v(b[0]));c||(c=v(a));L(a,c,0)});p.initMoveUp(function(a){var c,b=r(a);0<b.length&&(c=v(b[0]));c||(c=v(a));L(a,c,Math.PI/2)});p.initMoveDown(function(a){var c,b=r(a);0<b.length&&(c=v(b[0]));c||(c=v(a));L(a,c,-Math.PI/2)});lucid.hotKeys.add(["f2"],function(){p.getSelected()&&lucid.plugin.editBlockTextArea(p.getSelected(),"Text")});lucid.hotKeys.add(["space"],function(){p.getSelected()&&
lucid.plugin.editBlockTextArea(p.getSelected(),"Text")});lucid.hotKeys.add(["z"],function(){p.getSelected()&&0<A(p.getSelected()).length&&(lucid.text.isEditorActive()||O(p.getSelected()))});lucid.plugin.createExchangeGroup("MindMapBlock MindMapStadiumBlock MindMapCloud MindMapCircle MindMapIsoscelesTriangleBlock MindMapDiamondBlock MindMapPentagonBlock MindMapHexagonBlock MindMapOctagonBlock MindMapCrossBlock".split(" "));lucid.plugin.createNextBlockGroup("MindMapBlock MindMapStadiumBlock MindMapCloud MindMapCircle MindMapIsoscelesTriangleBlock MindMapDiamondBlock MindMapPentagonBlock MindMapHexagonBlock MindMapOctagonBlock MindMapCrossBlock".split(" "));
lucid.plugin.onActivate(function(){lucid.physics.init();lucid.plugin.allowShadowSharing("MindMapBlock",!0);lucid.plugin.allowShadowSharing("MindMapStadiumBlock",!0);lucid.plugin.allowShadowSharing("MindMapCloud",!0);lucid.plugin.allowShadowSharing("MindMapCircle",!0);lucid.plugin.allowShadowSharing("MindMapIsoscelesTriangleBlock",!0);lucid.plugin.allowShadowSharing("MindMapDiamondBlock",!0);lucid.plugin.allowShadowSharing("MindMapPentagonBlock",!0);lucid.plugin.allowShadowSharing("MindMapHexagonBlock",
!0);lucid.plugin.allowShadowSharing("MindMapOctagonBlock",!0);lucid.plugin.allowShadowSharing("MindMapCrossBlock",!0)});lucid.plugin.createToolGroups({"Mind Map":["MindMapBlock","MindMapStadiumBlock","MindMapCloud","MindMapCircle","MindMapIsoscelesTriangleBlock","MindMapDiamondBlock","MindMapPentagonBlock","MindMapHexagonBlock","MindMapOctagonBlock","MindMapCrossBlock",{label:"Import",action:function(){function a(a,b){var c,f=lucid.plugin.getActivePageId(),h,l=[];a.forEach(function(a){for(var d=0,
m=0;m<a.length;m++)if(""===a[m]){for(var q=m;q<a.length;q++)a[q]=a[q+1];m--;a.pop();d++}if(0!==a.length)if(a=a.reduce(function(a,b){return a+" "+b}),0===d){c&&P(c);if(c||0<lucid.plugin.getChildren(f).length)f=lucid.plugin.addPage({Title:a});h||(h=f);c=lucid.plugin.addBlock(f,{className:b,BoundingBox:{x:0,y:0,w:E[b].defaultSize.w,h:E[b].defaultSize.h},Text:a});a=lucid.plugin.getPageSize(f);m=lucid.plugin.getProperty(c,"BoundingBox");m.x=a.w/2-m.w/2;m.y=a.h/2-m.h/2;lucid.plugin.setPropertyIfChanged(c,
"BoundingBox",m);l.push({id:c,depth:d})}else{for(;0<l.length&&l[l.length-1].depth>=d;)l.pop();m=R(l[l.length-1].id);q=lucid.text.getStyleFromContent(lucid.plugin.getProperty(m,"Text"));lucid.plugin.setPropertyIfChanged(m,"Text",lucid.text.restyle(a,q));l.push({id:m,depth:d})}});P(c);lucid.plugin.selectPage(h)}function c(c){lucid.CSV.toArrays(c,{separator:" ",delimiter:"\x00"},function(c){c?a(c,b):lucid.dialog.alert("Could not parse the data. Make sure it is formatted correctly and try again.")})}
var b;(function(){var a=lucid.template.builder(),e,g=null;a.add({text:"Step 1: Select Data",classes:"title bold"});a.open();a.add({tag:"span",text:"Select a .txt file"});a.add({tag:"a",text:"Learn More",classes:"link",attr:{href:"http://support.lucidchart.com/entries/21777820-Mind-mapping#importexport",target:"_blank"}});a.close();a.addInput({type:"file",onSuccess:function(a){g=a}});a.add({text:"or",classes:"bold space"});a.add({tag:"div",text:"Paste your mind map outline into the field below."});
var f=a.open({classes:"text-area blur"}),h=a.addInput({type:"text",textArea:!0,allowEnter:!0,value:"Example:\n\nRoot\n Child 1\n  Grandchild 1a\n  Grandchild 1b\n Child 2\n  Grandchild 2a",onFocus:function(){"Example:\n\nRoot\n Child 1\n  Grandchild 1a\n  Grandchild 1b\n Child 2\n  Grandchild 2a"===h.getValue()&&(h.setValue(""),a.getElement(f).removeClass("blur"))},onBlur:function(){0===h.getValue().length&&(h.setValue("Example:\n\nRoot\n Child 1\n  Grandchild 1a\n  Grandchild 1b\n Child 2\n  Grandchild 2a"),
a.getElement(f).addClass("blur"))}});a.close();a.add({text:"Step 2: Choose Style",classes:"title bold"});a.add({text:"Choose the default shape style for your mind map:",classes:"subtext"});for(var l="MindMapBlock MindMapStadiumBlock MindMapCloud MindMapCircle MindMapIsoscelesTriangleBlock MindMapDiamondBlock MindMapPentagonBlock MindMapHexagonBlock MindMapOctagonBlock MindMapCrossBlock".split(" "),F=[{value:-1,label:"- Choose Style -"}],w=0;w<l.length;w++)F.push({value:w,label:E[l[w]].name});a.open({classes:"select"});
a.addInput({type:"select",inDialog:!0,options:F,onChange:function(a){0<=a&&(b=l[a])}});a.close();e=lucid.dialog.custom(a.getTemplate(),{title:"Import Mind Map Outline",classes:"mind-map-dialog import",modal:!0,buttons:[{label:"Cancel",action:function(){e.close()}},{label:"Import Mind Map",action:function(){if(g){if(0<h.getValue().length&&!a.getElement(f).hasClass("blur")){lucid.dialog.alert("Two mind map outlines have been detected. Please remove one of the outlines.");return}}else if(0===h.getValue().length){lucid.dialog.alert("Please either select a file or paste your mind map data into the text area.");
return}b?(e.close(),g||(g=h.getValue()+"\n"),c(g.replace(/\t/g," "))):lucid.dialog.alert("Please select a shape style for your mind map outline.")}}]});e.open()})()}},{label:"Export",action:function(){function a(b,c,d){var e=b.filter(function(a){return a.parentId===c.id});0<e.length&&(-1===c.id?d=e:c.children=e,e.forEach(function(c){a(b,c,[])}));return d}function c(a,b){for(var d="",e=0;e<a.depth;e++)d+=b;d+=a.text+"\n";a.children&&a.children.forEach(function(a){d+=c(a,b)});return d}function b(a){for(var c=
"",d=0;d<a.depth+1;d++)c+="  ";d=c;c+="<li>"+a.text+"</li>\n";a.children&&(c+=d+"<ul>\n",a.children.forEach(function(a){c+=b(a)}),c+=d+"</ul>\n");return c}function d(d){function e(a){var d=lucid.template.builder();if("plainText"===a){d.open({classes:"text-area-container"});var g="";f.forEach(function(a){g+=c(a,"\t")});d.add({tag:"textarea",text:g,classes:"text-area",attr:{readonly:!0}});d.close()}else"bulleted"!==a&&(d.open({classes:"text-area-container"}),g="",f.forEach(function(a){g+="<ul>\n"+b(a)+
"</ul>\n"}),d.add({tag:"textarea",text:g,classes:"text-area",attr:{readonly:!0}}),d.close());h.getElement(n)&&h.getElement(n).setContent(d)}var f=a(d,{id:-1},[]),g="plainText",h=lucid.template.builder();h.add({text:"Select the outline formatting:"});h.addInput({type:"radio",separator:"&nbsp;",buttons:[{value:0,label:"Plain text",checked:function(){return"plainText"===g}},{value:1,label:"HTML",checked:function(){return"HTML"===g}}],onChange:function(a){e(g=0===a?"plainText":"HTML")}});var n=h.open({});
h.close();h.spacer();h.add({text:"Select the text and use "+(lucid.useragent.is_linux()||lucid.useragent.is_win()?"Ctrl+C":"Cmd+C")+" to copy to the clipboard"});var p=lucid.dialog.custom(h.getTemplate(),{title:"Export Mind Map Outline",classes:"mind-map-dialog export",modal:!0,buttons:[{label:"OK",action:function(){p.close()}}]});p.open();e(g)}var e={},g=lucid.plugin.getAllBlockIds().filter(function(a){return lucid.plugin.getItemPageId(a)!==lucid.plugin.getActivePageId()?!1:u(a)?!0:(e.foreignBlock=
"There are non-mind map shapes on this page. Only mind map shapes will be exported to text.",!1)});if(0===g.length)lucid.dialog.alert("There are no mind map shapes to export on this page.");else{var f=[];g.forEach(function(a){var b=r(a);1<b.length&&(e.multiParent="At least one mind map cannot be exported correctly.");var b=b[0],c=x(a),d=lucid.text.plainText(lucid.plugin.getProperty(a,"Text"));f.push({id:a,parentId:b?b:-1,depth:c,text:d})});if(lucid.object.isEmpty(e))d(f);else{g=lucid.template.builder();
e.foreignBlock&&(g.add({tag:"span",text:"Error: "+e.foreignBlock,classes:"warning"}),g.spacer());e.multiParent&&(g.add({tag:"span",text:"Error: "+e.multiParent,classes:"warning"}),g.add({tag:"br"}),g.add({tag:"a",text:"Learn more",attr:{href:"http://support.lucidchart.com/entries/21777820-Mind-mapping#troubleshooting",target:"_blank"}}));var h=lucid.dialog.custom(g.getTemplate(),{modal:!0,preventEsc:!0,classes:"mind-map-dialog",buttons:[{label:"OK",action:function(){h.close();d(f)}}]});h.open()}}}}]})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/mindmap.js.map
};
