pluginFn['/js/plugins/v2/orgchart2.js'] = function(lucid, window) {
	(function(){function I(a,b){var c=0;q.forEach(function(a){b[a]&&c++});for(var d=0;d<a;d++)b["Custom"+d]&&c++;return c}function J(a,b,c,d){var e=y[a];b=lucid.object.clone(b);b.w=e.size.w;"custom"==a?(b.h=30*I(d,c),30>b.h&&(b.h=30),c.Photo&&(b.w+=A(b,c))):b.h=e.size.h;return b}function K(a){var b=lucid.plugin.getProperty(a.id,"Type"),c=lucid.plugin.getAllProperties(a.id);a=t(a.id);a={Type:b,Active:a,NumCustomFields:c.NumCustomFields,BoundingBox:J(b,c.BoundingBox,a,c.NumCustomFields)};for(var d=0;d<
c.NumCustomFields;d++)a["Custom"+d+"Name"]=c["Custom"+d+"Name"],a["Custom"+d]=lucid.text.restyle(c["Custom"+d+"Name"],Q(b,"Custom"+d));return a}function L(a,b){function c(a,b){return lucid.text.restyle(b,Q(d,a))}var d=lucid.plugin.getProperty(a.id,"Type");q.forEach(function(a){lucid.plugin.setPropertyIfChanged(b,a,c(a,lucid.plugin.getProperty(b,a)))})}function t(a){var b=lucid.plugin.getProperty(a,"Type");if(b&&"custom"!=b){var b=W(b),c=lucid.object.clone(F);b.forEach(function(a){c[a]=!0});if(b=lucid.plugin.getProperty(a,
"NumCustomFields"))if(a=lucid.plugin.getProperty(a,"Active"))for(var d=0;d<b;d++)c["Custom"+d]=a["Custom"+d];return c}return lucid.plugin.getProperty(a,"Active")}function M(a,b){for(var c=0,d=0;d<q.length;d++){if(q[d]==a)return c;b[q[d]]&&c++}for(d=0;10>d;d++){if(a==="Custom"+d)return c;b["Custom"+d]&&c++}return-1}function A(a,b){return b.Photo?a.h-8:0}function W(a){return a.split("-").map(function(a){return a.charAt(0).toUpperCase()+a.slice(1)})}function N(a){return"OrgBlock"===a}function Q(a,b){var c=
y[a];return c&&c.style[b]?c.style[b]:{align:"left",bold:!1,italic:!1}}function D(a){return a.filter(function(a){return a.isBlock&&N(a.className)})}function C(){var a=[];lucid.array.forEach(g.roots,function(b){a.push(b.id)});return a}var h={global:this,provide:function(a){a=a.split(".");h.global[a[0]]=h.global[a[0]]||{};var b=h.global[a[0]];a.slice(1).reduce(function(a,b){a[b]||(a[b]={});return a[b]},b)},require:function(){},inherits:function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=
b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,k){var x=Array.prototype.slice.call(arguments,2);return b.prototype[c].apply(a,x)}},base:function(a,b,c){var d=arguments.callee.caller;if(h.STRICT_MODE_COMPATIBLE||h.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,
1));for(var e=Array.prototype.slice.call(arguments,2),k=!1,x=a.constructor;x;x=x.superClass_&&x.superClass_.constructor)if(x.prototype[b]===d)k=!0;else if(k)return x.prototype[b].apply(a,e);if(a[b]===d)return a.constructor.prototype[b].apply(a,e);throw Error("goog.base called from a method of one name to a method of a different name");}};h.provide("plugin.layout.Node");plugin.layout.Node=function(a,b,c){this.id=a||"";this.layoutManager=b;this.bb=c||lucid.plugin.getProperty(this.id,"BoundingBox");
this.children=[];this.parent=null;if(a){var d=this;lucid.plugin.hookPropertyPostSave(a,this.getPrimaryTextArea(),function(a,b){if(d.input){var c=d.input,f=lucid.text.plainText(b);c.getValue()!=f&&c.setValue(f)}})}};plugin.layout.Node.prototype.treeKey=function(){var a=[this.id,"v"];lucid.array.forEach(this.children,function(b){a=a.concat(b.treeKey())});a.push("^");return a.join("-")};plugin.layout.Node.prototype.getAllDescendants=function(){var a=[this];lucid.array.forEach(this.children,function(b){a=
a.concat(b.getAllDescendants())});return a};plugin.layout.Node.prototype.calculateBoundingBox=function(){var a=[];lucid.array.forEach(this.getAllDescendants(),function(b){b.bb&&a.push(b.bb)});return 0==a.length?{x:0,y:0,w:0,h:0}:lucid.math.Box.combine(a)};plugin.layout.Node.prototype.addChildStructureOnly=function(a,b){this.children.push(a);a.parent=this;b||this.reorderChildren()};plugin.layout.Node.prototype.addChild=function(a,b,c,d){var e={x:this.bb.x,y:this.bb.y,w:a.bb.w,h:a.bb.h};d?e=a.bb:c?
(e=c.bb,e={x:e.x,y:e.y-1,w:a.bb.w,h:a.bb.h}):0<this.children.length&&(e=this.children[this.children.length-1].bb,e={x:e.x,y:e.y+1,w:a.bb.w,h:a.bb.h});a.bb=e;lucid.plugin.setPropertyIfChanged(a.id,"BoundingBox",e);this.addChildStructureOnly(a);b&&(b=lucid.plugin.getItemPageId(this.id),lucid.plugin.addLine(b,{Endpoint1:{Block:this.id,Style:"None",LinkX:.5,LinkY:1},Endpoint2:{Block:a.id,Style:"None",LinkX:.5,LinkY:0},Shape:"elbow",AutoLink:!1,Lock:1,IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}))};
plugin.layout.Node.prototype.addNewChild=function(a,b){if(b){var c=a.BoundingBox?a.BoundingBox.w:this.bb.w,d=lucid.plugin.getProperty(b,"Endpoint2");a.BoundingBox={x:d.x-c/2,y:d.y,w:c,h:a.BoundingBox?a.BoundingBox.h:this.bb.h}}else{var e=(new (this.layoutManager.layouts[this.layoutManager.currentLayout()].klass)(this.layoutManager.roots,this.layoutManager)).highestCorrectAncestor(this);e&&this!==e||(e=this.parent)}c=this.createNewNode(a,this);this.addChild(c,!0,null,!!b);b||(this.layoutManager.roots=
this.layoutManager.refreshTree(lucid.plugin.getDetailsForItems(C().concat([c.id]))),this.layoutManager.partialLayout(e));return c.id};plugin.layout.Node.prototype.removeChild=function(a){if(a.parent==this)for(var b=0;b<this.children.length;b++)if(this.children[b]==a){this.children.splice(b,1);a.parent=null;break}};plugin.layout.Node.prototype.offsetBB=function(a,b){this.bb.x+=a;this.bb.y+=b;lucid.array.forEach(this.children,function(c){c.offsetBB(a,b)})};plugin.layout.Node.prototype.getPrimaryTextArea=
function(){this.textId||(this.textId=lucid.plugin.getBlockTextAreas(this.id)[0]);return this.textId};plugin.layout.Node.prototype.isAncestorOf=function(a){for(;a;){if(a.id==this.id)return!0;a=a.parent}return!1};plugin.layout.Node.prototype.isDescendantOf=function(a){return-1!==a.getDescendants().indexOf(this.id)};plugin.layout.Node.prototype.getDescendants=function(){var a=[this.id];this.children&&this.children.forEach(function(b){a=a.concat(b.getDescendants())});return a};plugin.layout.Node.prototype.commit=
function(){""!=this.id&&(lucid.plugin.setPropertyIfChanged(this.id,"BoundingBox",this.bb),lucid.plugin.setPropertyIfChanged(this.id,"Rotation",0));lucid.array.forEach(this.children,function(a){a.commit()})};plugin.layout.Node.prototype.nextSibling=function(){for(var a=this.parent?this.parent.children:this.layoutManager.roots,b=0;b<a.length;b++)if(a[b].id==this.id)return a[b+1];return null};plugin.layout.Node.prototype.prevSibling=function(){for(var a=this.parent?this.parent.children:this.layoutManager.roots,
b=0;b<a.length;b++)if(a[b].id==this.id)return a[b-1];return null};plugin.layout.Node.prototype.lastDescendant=function(){for(var a=this;0<a.children.length;)a=a.children[a.children.length-1];return a};plugin.layout.Node.prototype.childrenAreLeaves=function(){if(2>this.children.length)return!1;var a=!0;lucid.array.forEach(this.children,function(b){0<b.children.length&&(a=!1)});return a};plugin.layout.Node.prototype.next=function(){if(0<this.children.length)return this.children[0];for(var a=this;a&&
!a.nextSibling();)a=a.parent;return a?a.nextSibling():this};plugin.layout.Node.prototype.prev=function(){var a=this.prevSibling();return a?a.lastDescendant():this.parent?this.parent:this};plugin.layout.Node.prototype.getText=function(a){return lucid.text.plainText(lucid.plugin.getProperty(this.id,a||this.getPrimaryTextArea()))};plugin.layout.Node.prototype.setText=function(a,b,c){var d=lucid.plugin.getProperty(this.id,c||this.getPrimaryTextArea()),e=lucid.text.plainText(d);a!=e&&(d=lucid.text.getStyleFromContent(d),
""===a&&lucid.plugin.setProperty(this.id,c+"_style",d,!0),""===e&&(d=(e=lucid.plugin.getProperty(this.id,c+"_style",!0))?e:(e=lucid.plugin.getProperty(this.id,"Type"))&&b[e]?b[e].style[c]:{}),lucid.plugin.setProperty(this.id,c||this.getPrimaryTextArea(),lucid.text.restyle(a,d)))};plugin.layout.Node.prototype.getCustomFieldName=function(a){return lucid.plugin.getProperty(this.id,a+"Name")};plugin.layout.Node.prototype.setCustomFieldName=function(a,b){lucid.plugin.setPropertyIfChanged(this.id,a+"Name",
b)};plugin.layout.Node.prototype.addNewSibling=function(a){var b=(new (this.layoutManager.layouts[this.layoutManager.currentLayout()].klass)(this.layoutManager.roots,this.layoutManager)).highestCorrectAncestor(this);b&&this!==b||(b=this.parent);a=this.createNewNode(a,this.parent);this.addSibling(a,this.nextSibling());this.layoutManager.roots=this.layoutManager.refreshTree(lucid.plugin.getDetailsForItems(C().concat([a.id])));this.layoutManager.partialLayout(b);return a.id};plugin.layout.Node.prototype.addSibling=
function(a,b){this.parent&&""!=this.parent.id?this.parent.addChild(a,!0,b):this.layoutManager.roots.push(a)};plugin.layout.Node.prototype.createNewNode=function(a,b){var c=lucid.plugin.getItemPageId(this.id);lucid.plugin.getAllProperties(this.id);var d=this.layoutManager.isSiteMap?"SMPage":lucid.plugin.getBlockClassName(this.id);a.className=d;a.BoundingBox=a.BoundingBox?{x:a.BoundingBox.x?a.BoundingBox.x:this.bb.x,y:a.BoundingBox.y?a.BoundingBox.y:this.bb.y,w:a.BoundingBox.w,h:a.BoundingBox.h}:this.bb;
this.layoutManager.isSiteMap&&b&&lucid.plugin.getAllProperties(b.id).Future&&(a.Future=!0);c=lucid.plugin.addBlock(c,a);return new plugin.layout.Node(c,this.layoutManager)};plugin.layout.Node.prototype.deleteSelf=function(){var a=this.prev();if(0<this.children.length&&a!=this){for(var b=a,c=this.calculateLayer();b.calculateLayer()>c;)b=b.prev();lucid.plugin.getItemPageId(this.id);lucid.array.forEach(this.children,function(a){b.addChild(a,!0)});this.children=[]}for(var c=this.parent?this.parent.children:
this.layoutManager.roots,d=0;d<c.length;d++)if(c[d].id==this.id){c.splice(d,1);break}lucid.array.forEach(lucid.plugin.getIncomingLines(this.id),function(a){lucid.plugin.deleteItem(a)});lucid.array.forEach(lucid.plugin.getOutgoingLines(this.id),function(a){lucid.plugin.deleteItem(a)});try{lucid.plugin.selectItem((b||this.parent||this.layoutManager.roots[0]).id)}catch(e){}lucid.plugin.deleteItem(this.id);try{return(a.id==this.id?this.layoutManager.roots[0]:a).id}catch(e){return""}};plugin.layout.Node.prototype.moveBeforeOrAfter=
function(a,b){lucid.array.forEach(lucid.plugin.getIncomingLines(this.id),function(a){lucid.plugin.deleteItem(a)});this.parent&&this.parent.removeChild(this);if(a.parent&&""!=a.parent.id){var c=b?a:a.nextSibling();a.parent.addChild(this,!0,c)}else this.layoutManager.roots.push(this);this.layoutManager.isOrgChart&&lucid.help.item.accomplish("orgChart.info")};plugin.layout.Node.prototype.moveAfter=function(a){this.moveBeforeOrAfter(a,!1)};plugin.layout.Node.prototype.moveBefore=function(a){this.moveBeforeOrAfter(a,
!0)};plugin.layout.Node.prototype.calculateLayer=function(){for(var a=0,b=this;b;)a++,b=b.parent;return a};plugin.layout.Node.prototype.indent=function(a){var b=this.parent;if(a){if(!this.parent)return;a=this.parent.parent}else if(a=this.prevSibling(),!a)return;if(b){b.removeChild(this);for(var c=lucid.plugin.getIncomingLines(this.id),d=0;d<c.length;d++)lucid.plugin.getProperty(c[d],"Endpoint1").Block==b.id&&lucid.plugin.deleteItem(c[d])}else for(d=0;d<this.layoutManager.roots.length;d++)if(this.layoutManager.roots[d].id==
this.id){this.layoutManager.roots.splice(d,1);break}a?a.addChild(this,!0):this.layoutManager.roots.push(this)};plugin.layout.Node.prototype.reorderChildren=function(){var a=this.childrenAreLeaves()&&"VerticalLeafLayout"===this.layoutManager.currentLayout();this.children.sort(function(b,c){return a?b.bb.y-c.bb.y||b.bb.x-c.bb.x:b.bb.x-c.bb.x||b.bb.y-c.bb.y})};h.provide("plugin.layout.LayoutAlgorithm");h.require("plugin.layout.Node");plugin.layout.LayoutAlgorithm=function(a,b){this.roots=a;this.layoutManager=
b;this.wPadding=20;this.hPadding=40};plugin.layout.LayoutAlgorithm.prototype.reset=function(a){a=a||this.root;a.layerLeft={};a.layerRight={};a.distanceToNextSibling=0;a.distanceFromParent=0;a.layer=a.calculateLayer();var b=this;lucid.array.forEach(a.children,function(a){b.reset(a)})};plugin.layout.LayoutAlgorithm.prototype.run=function(a){};plugin.layout.LayoutAlgorithm.prototype.isLaidOutCorrectly=function(a){function b(a){var c=[{x:a.bb.x,y:a.bb.y,w:a.bb.w,h:a.bb.h}];lucid.array.forEach(a.children,
function(a){c=c.concat(b(a))});return c}function c(a,b){a.bb=b.shift();lucid.array.forEach(a.children,function(a){c(a,b)})}var d=a.parent,e=b(a);this.roots=[a];this.run(!0);var k=b(a),k=lucid.object.areEqual(e,k);a.parent=d;c(a,e);return k};plugin.layout.LayoutAlgorithm.prototype.highestCorrectAncestor=function(a){for(;a.parent&&this.isLaidOutCorrectly(a.parent);)a=a.parent;if(null==a.parent){for(var b=!0,c=0;c<this.layoutManager.roots.length;c++)if(this.layoutManager.roots[c]!=a&&!this.isLaidOutCorrectly(this.layoutManager.roots[c])){b=
!1;break}b&&(a=null)}return a};plugin.layout.LayoutAlgorithm.prototype.setRootNode=function(){var a=this;this.root=new plugin.layout.Node("",this.layoutManager,this.roots[0].bb);var b=[];lucid.array.forEach(this.roots,function(c){b.push(c.parent);a.root.addChildStructureOnly(c)});this.originalBB=this.root.calculateBoundingBox();this.root.bb={x:this.originalBB.x+this.originalBB.w/2,y:this.originalBB.y-this.hPadding,w:0,h:0};this.reset();this.layerHeights={};this.calculateSize(this.root);return b};
plugin.layout.LayoutAlgorithm.prototype.correctLines=function(a,b,c){var d=this.root.calculateBoundingBox();this.root.offsetBB(this.originalBB.x+this.originalBB.w/2-(d.x+d.w/2),0);a||(this.root.commit(),lucid.array.forEach(this.layoutManager.expandSelection(lucid.plugin.getDetailsForItems(lucid.array.realMap(this.roots,function(a){return a.id}))),function(a){var c=a.id;if(a.isLine){a=lucid.plugin.getProperty(c,"Endpoint1");var d=lucid.plugin.getProperty(c,"Endpoint2");lucid.plugin.isBlock(a.Block)&&
lucid.plugin.isBlock(d.Block)?(lucid.plugin.setPropertyIfChanged(c,"AutoLink",!1),lucid.plugin.setPropertyIfChanged(c,"Shape","elbow"),b(a,d),a.Style="None",d.Style="None",lucid.plugin.setPropertyIfChanged(c,"Endpoint1",a),lucid.plugin.setPropertyIfChanged(c,"Endpoint2",d),lucid.plugin.setPropertyIfChanged(c,"XPlanes",[]),lucid.plugin.setPropertyIfChanged(c,"YPlanes",[]),lucid.plugin.setPropertyIfChanged(c,"IgnoreTheme",{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0})):lucid.plugin.deleteItem(c)}}));
lucid.array.forEach(this.roots,function(a){a.parent=c.shift()})};h.provide("plugin.layout.VerticalCompactLayout");h.require("plugin.layout.LayoutAlgorithm");h.require("plugin.layout.Node");plugin.layout.VerticalCompactLayout=function(a,b){plugin.layout.LayoutAlgorithm.call(this,a,b)};h.inherits(plugin.layout.VerticalCompactLayout,plugin.layout.LayoutAlgorithm);plugin.layout.VerticalCompactLayout.prototype.reset=function(a){plugin.layout.VerticalCompactLayout.superClass_.reset.call(this,a)};plugin.layout.VerticalCompactLayout.prototype.run=
function(a){var b=this.setRootNode();this.arrangeChildren(this.root,this.root.bb.x+this.root.bb.w/2);this.correctLines(a,function(a,b){a.LinkX=.5;a.LinkY=1;b.LinkX=.5;b.LinkY=0},b)};plugin.layout.VerticalCompactLayout.prototype.calculateSize=function(a){var b=this;lucid.array.forEach(a.children,function(a){b.calculateSize(a)});a.layerLeft[a.layer]=-a.bb.w/2;a.layerRight[a.layer]=a.bb.w/2;if(0<a.children.length){for(var c=0,d=0;d<a.children.length-1;d++){var e=0,k=a.children[d],x=a.children[d+1],f;
for(f in k.layerRight)f in x.layerLeft&&(e=Math.max(e,k.layerRight[f]-x.layerLeft[f]+(f==k.layer?this.wPadding:2*this.wPadding)));k.distanceToNextSibling=e;for(f in k.layerRight)x.layerRight[f]=x.layerRight[f]?Math.max(x.layerRight[f]||0,k.layerRight[f]-k.distanceToNextSibling):k.layerRight[f]-k.distanceToNextSibling;c+=e}for(d=0;d<a.children.length;d++){a.children[d].distanceFromParent=0==d?-c/2:a.children[d-1].distanceFromParent+a.children[d-1].distanceToNextSibling;for(f in a.children[d].layerLeft)a.layerLeft[f]=
Math.min(a.layerLeft[f]||0,a.children[d].distanceFromParent+a.children[d].layerLeft[f]);for(f in a.children[d].layerRight)a.layerRight[f]=Math.max(a.layerRight[f]||0,a.children[d].distanceFromParent+a.children[d].layerRight[f])}}this.layerHeights[a.layer]=Math.max(this.layerHeights[a.layer]||0,a.bb.h)};plugin.layout.VerticalCompactLayout.prototype.arrangeChildren=function(a,b){var c=this,d=a.bb.y+(this.layerHeights[a.layer]||0)+this.hPadding;a.reorderChildren();lucid.array.forEach(a.children,function(a){a.bb.x=
b+a.distanceFromParent-a.bb.w/2;a.bb.y=d;c.arrangeChildren(a,b+a.distanceFromParent)})};h.provide("plugin.layout.ContextPanelBuilder");plugin.layout.ContextPanelBuilder=function(a){this.layoutManager=a;this.pendingFocus=null};plugin.layout.ContextPanelBuilder.prototype.buildLayoutSelection=function(a){function b(a){d.push({value:a,dom:{id:a,tag:"img",src:c.layoutManager.layouts[a].icon},hoverProperties:function(){c.applyLayout(a);c.layoutManager.isOrgChart&&lucid.help.item.accomplish("orgChart.layout")}})}
var c=this,d=[],e;for(e in c.layoutManager.layouts)b(e);e=a.addInput({type:"select",options:d,onChange:function(a,b){b||(c.applyLayout(a),c.layoutManager.isOrgChart&&lucid.help.item.accomplish("orgChart.layout"))}});a.spacer();a.addButton({label:"Clean up layout",onClick:function(){c.applyLayout(c.layoutManager.currentLayout())}});a.spacer();return e};plugin.layout.ContextPanelBuilder.prototype.buildSimpleTree=function(a,b,c,d){var e=this;a.open({tag:"ul",classes:"simple-tree"});var k=function(a,
f){function g(){for(var a in e.layoutManager.nodes){var b=f.getElement(e.layoutManager.nodes[a].li);b&&b.removeClass("line-top line-bottom")}}a.li=f.open({tag:"li",classes:"drop-target",data:{blockId:a.id}});a.input=f.addInput({type:"text",value:a.getText(),allChanges:!0,onChange:function(b,c){c||a.setText(b,d||{})},onFocus:function(){b(a)},onKeydown:function(b){if(9==b.keyCode){e.layoutManager.roots=e.layoutManager.refreshTree(lucid.plugin.getSelectionDetails());var d=e.layoutManager.layouts[e.layoutManager.currentLayout()].klass,
d=(new d(e.layoutManager.roots,e.layoutManager)).highestCorrectAncestor(a);a.indent(b.shiftKey);e.pendingFocus=a.id;e.layoutManager.roots=e.layoutManager.refreshTree(lucid.plugin.getSelectionDetails());e.layoutManager.partialLayout(d);return!0}if(38==b.keyCode)a.prev().input.focus(!0);else if(40==b.keyCode)a.next().input.focus(!0);else if(8==b.keyCode||46==b.keyCode){if(""==a.input.getInputValue())return e.layoutManager.roots=e.layoutManager.refreshTree(lucid.plugin.getSelectionDetails()),d=e.layoutManager.layouts[e.layoutManager.currentLayout()].klass,
d=(new d(e.layoutManager.roots,e.layoutManager)).highestCorrectAncestor(a),e.pendingFocus=a.deleteSelf(),e.layoutManager.roots=e.layoutManager.refreshTree(lucid.plugin.getDetailsForItems(C())),e.layoutManager.partialLayout(d),!0}else{if(13==b.keyCode)return e.layoutManager.roots=e.layoutManager.refreshTree(lucid.plugin.getSelectionDetails()),d=e.layoutManager.layouts[e.layoutManager.currentLayout()].klass,d=(new d(e.layoutManager.roots,e.layoutManager)).highestCorrectAncestor(a),c(e,a),e.layoutManager.isOrgChart&&
lucid.help.item.accomplish("orgChart.add.panel"),null==a.parent&&(e.layoutManager.nodes[e.pendingFocus]=new plugin.layout.Node(e.pendingFocus,e.layoutManager),e.layoutManager.nodes[e.pendingFocus].indent()),e.layoutManager.roots=e.layoutManager.refreshTree(lucid.plugin.getSelectionDetails()),e.layoutManager.partialLayout(d),!0;if(b.ctrlKey&&90==b.keyCode)return lucid.plugin.undo(),!0}}});f.addDraggable({dom:{classes:"drag-handle",text:"↕"},dragDomClasses:"no-pointer-events",cursor:"pointer",domDrag:function(b,
c,d,k,h){g();(b=e.layoutManager.nodes[b.blockId])&&!a.isAncestorOf(b)&&null!=b.parent&&(c=f.getElement(b.li))&&(10>d?c.addClass("line-top"):0==b.children.length||20<d?c.addClass("line-bottom"):(d=f.getElement(b.children[0].li))&&d.addClass("line-top"))},domDrop:function(b,c,d,k,g){(b=e.layoutManager.nodes[b.blockId])&&!a.isAncestorOf(b)&&f.getElement(b.li)&&(e.layoutManager.roots=e.layoutManager.refreshTree(lucid.plugin.getSelectionDetails()),10>d?a.moveBefore(b):0==b.children.length||20<d?a.moveAfter(b):
a.moveBefore(b.children[0]),(new (e.layoutManager.layouts[e.layoutManager.currentLayout()].klass)(e.layoutManager.roots,e.layoutManager)).run())},onDragEnd:function(){g()}});a.id==e.pendingFocus&&(e.pendingFocus=null,setTimeout(function(){a.input.focus(!0)},1));0<a.children.length&&(f.open({tag:"ul"}),lucid.array.forEach(a.children,function(a){k(a,f)}),f.close());f.close()};lucid.array.forEach(e.layoutManager.roots,function(b){k(b,a)});a.close()};plugin.layout.ContextPanelBuilder.prototype.applyLayout=
function(a,b){var c=this;c.layoutManager.roots=c.layoutManager.refreshTree(b||lucid.plugin.getSelectionDetails());(new c.layoutManager.layouts[a].klass(c.layoutManager.roots,c.layoutManager)).run(!1);lucid.array.forEach(c.layoutManager.currentTreeSelection,function(b){b.isBlock&&(lucid.plugin.setPropertyIfChanged(b.id,"Layout",a),c.layoutManager.nodes[b.id]&&(c.layoutManager.nodes[b.id].layout=a))})};h.provide("plugin.layout.VerticalLeafLayout");h.require("plugin.layout.LayoutAlgorithm");h.require("plugin.layout.Node");
plugin.layout.VerticalLeafLayout=function(a,b){plugin.layout.LayoutAlgorithm.call(this,a,b)};h.inherits(plugin.layout.VerticalLeafLayout,plugin.layout.LayoutAlgorithm);plugin.layout.VerticalLeafLayout.prototype.reset=function(a){a=a||this.root;plugin.layout.VerticalLeafLayout.superClass_.reset.call(this,a);if(a.childrenAreLeaves())for(var b=1;b<a.children.length;b++)a.children[b].layer+=b};plugin.layout.VerticalLeafLayout.prototype.run=function(a){var b=this,c=this.setRootNode();this.arrangeChildren(this.root,
this.root.bb.x+this.root.bb.w/2);this.correctLines(a,function(a,c){var k=b.layoutManager.nodes[a.Block];k&&k.childrenAreLeaves()?(a.LinkX=b.wPadding/k.bb.w,a.LinkY=1,c.LinkX=0,c.LinkY=.5):(a.LinkX=.5,a.LinkY=1,c.LinkX=.5,c.LinkY=0)},c)};plugin.layout.VerticalLeafLayout.prototype.calculateSize=function(a){var b=this;lucid.array.forEach(a.children,function(a){b.calculateSize(a)});a.layerLeft[a.layer]=-a.bb.w/2;a.layerRight[a.layer]=a.bb.w/2;if(0<a.children.length){for(var c=0,d=0;d<a.children.length-
1;d++){var e=0,k=a.children[d],g=a.children[d+1],f;for(f in k.layerRight)f in g.layerLeft&&(e=Math.max(e,k.layerRight[f]-g.layerLeft[f]+(f==k.layer?this.wPadding:2*this.wPadding)));k.distanceToNextSibling=e;for(f in k.layerRight)g.layerRight[f]=g.layerRight[f]?Math.max(g.layerRight[f]||0,k.layerRight[f]-k.distanceToNextSibling):k.layerRight[f]-k.distanceToNextSibling;c+=e}e=a.childrenAreLeaves();for(d=0;d<a.children.length;d++){0==d?(a.children[d].distanceFromParent=-c/2,e&&(a.children[d].distanceFromParent+=
2*this.wPadding)):a.children[d].distanceFromParent=a.children[d-1].distanceFromParent+a.children[d-1].distanceToNextSibling;for(f in a.children[d].layerLeft)a.layerLeft[f]=Math.min(a.layerLeft[f]||0,a.children[d].distanceFromParent+a.children[d].layerLeft[f]);for(f in a.children[d].layerRight)a.layerRight[f]=Math.max(a.layerRight[f]||0,a.children[d].distanceFromParent+a.children[d].layerRight[f])}}this.layerHeights[a.layer]=Math.max(this.layerHeights[a.layer]||0,a.bb.h)};plugin.layout.VerticalLeafLayout.prototype.arrangeChildren=
function(a,b){var c=this,d=a.bb.y+(this.layerHeights[a.layer]||0)+this.hPadding,e=a.childrenAreLeaves();a.reorderChildren();lucid.array.forEach(a.children,function(a){a.bb.x=b+a.distanceFromParent-a.bb.w/2;a.bb.y=d;e&&(d+=(c.layerHeights[a.layer]||0)+c.hPadding);c.arrangeChildren(a,b+a.distanceFromParent)})};h.provide("plugin.layout.VerticalSimpleLayout");h.require("plugin.layout.LayoutAlgorithm");h.require("plugin.layout.Node");plugin.layout.VerticalSimpleLayout=function(a,b){plugin.layout.LayoutAlgorithm.call(this,
a,b)};h.inherits(plugin.layout.VerticalSimpleLayout,plugin.layout.LayoutAlgorithm);plugin.layout.VerticalSimpleLayout.prototype.reset=function(a){a=a||this.root;a.width=0;a.childWidth=0;plugin.layout.VerticalSimpleLayout.superClass_.reset.call(this,a)};plugin.layout.VerticalSimpleLayout.prototype.run=function(a){var b=this.setRootNode();this.arrangeChildren(this.root,this.root.bb.x+this.root.bb.w/2-this.root.childWidth/2);this.correctLines(a,function(a,b){a.LinkX=.5;a.LinkY=1;b.LinkX=.5;b.LinkY=0},
b)};plugin.layout.VerticalSimpleLayout.prototype.calculateSize=function(a,b){var c=this;b=b||0;var d=this.wPadding*(a.children.length-1);lucid.array.forEach(a.children,function(a){d+=c.calculateSize(a,b+1)});a.childWidth=d;a.width=Math.max(d,a.bb.w);a.layer=b;this.layerHeights[b]=Math.max(this.layerHeights[b]||0,a.bb.h);return a.width};plugin.layout.VerticalSimpleLayout.prototype.arrangeChildren=function(a,b){var c=this,d=b,e=a.bb.y+(this.layerHeights[a.layer]||0)+this.hPadding;a.reorderChildren();
lucid.array.forEach(a.children,function(a){a.bb.y=e;c.arrangeChildren(a,d);if(0==a.children.length)a.bb.x=d+a.width/2-a.bb.w/2;else{var b=a.children[0],f=a.children[a.children.length-1];a.bb.x=(b.bb.x+b.bb.w/2+f.bb.x+f.bb.w/2)/2-a.bb.w/2}d+=a.width+c.wPadding})};h.provide("plugin.layout.LayoutManager");h.require("plugin.layout.VerticalSimpleLayout");h.require("plugin.layout.VerticalCompactLayout");h.require("plugin.layout.VerticalLeafLayout");plugin.layout.LayoutManager=function(a){this.currentTreeSelection=
[];this.roots=[];this.nodes={};this.hasTreesClassName=a;this.layouts={VerticalSimpleLayout:{klass:plugin.layout.VerticalSimpleLayout,icon:lucid.net.cashyURL("/app/webroot/img/layouts/simple.png")},VerticalCompactLayout:{klass:plugin.layout.VerticalCompactLayout,icon:lucid.net.cashyURL("/app/webroot/img/layouts/compact.png")},VerticalLeafLayout:{klass:plugin.layout.VerticalLeafLayout,icon:lucid.net.cashyURL("/app/webroot/img/layouts/leaf.png")}};this.isOrgChart=a("OrgBlock");this.isSiteMap=a("SMPage")};
plugin.layout.LayoutManager.prototype.currentLayout=function(){return 0<this.roots.length?this.roots[0].layout||"VerticalLeafLayout":"VerticalLeafLayout"};plugin.layout.LayoutManager.prototype.partialLayout=function(a){if(0<this.roots.length){var b=this.layouts[this.currentLayout()].klass;a?(new b([a],this)).run():(new b(this.roots,this)).run()}};plugin.layout.LayoutManager.prototype.expandSelection=function(a){var b={};lucid.array.forEach(a,function(a){b[a.id]=!0});var c=[];lucid.array.forEach(a,
function(a){a=lucid.plugin.getUpstream(a.id);lucid.array.forEach(a,function(a){b[a]||(b[a]=!0,c.push(a))})});a=a.concat(lucid.plugin.getDetailsForItems(c));c=[];lucid.array.forEach(a,function(a){a=lucid.plugin.getDownstream(a.id);lucid.array.forEach(a,function(a){b[a]||(b[a]=!0,c.push(a))})});return a=a.concat(lucid.plugin.getDetailsForItems(c))};plugin.layout.LayoutManager.prototype.refreshTree=function(a){var b=this;this.currentTreeSelection=a=function(a){return a.filter(function(a){return a.isBlock&&
b.hasTreesClassName(a.className)})}(this.expandSelection(a));var c={};lucid.array.forEach(a,function(a){a.id in b.nodes||(b.nodes[a.id]=new plugin.layout.Node(a.id,b));var d=lucid.plugin.getAllProperties(a.id);b.nodes[a.id].parent=null;b.nodes[a.id].children=[];b.nodes[a.id].bb=d.BoundingBox;b.nodes[a.id].layout=d.Layout;c[a.id]=b.nodes[a.id]});lucid.array.forEach(a,function(a){var d=lucid.plugin.getOutgoingLines(a.id),g=b.nodes[a.id];lucid.array.forEach(d,function(a){a=lucid.plugin.getProperty(a,
"Endpoint2");!c[a.Block]||c[a.Block].isAncestorOf(g)||g.isDescendantOf(b.nodes[a.Block])||g.addChildStructureOnly(b.nodes[a.Block],!0)})});lucid.array.forEach(a,function(a){b.nodes[a.id].reorderChildren()});a=[];for(var d in c)null==c[d].parent&&a.push(c[d]);a.sort(function(a,b){return a.bb.x-b.bb.x||a.bb.y-b.bb.y});this.nodes=c;return a};plugin.layout.LayoutManager.prototype.initNavigationHotKeys=function(a){var b=this;a.initMoveUp(function(a){b.nodes[a]&&(a=b.nodes[a].parent)&&(lucid.plugin.deselectAllItems(),
lucid.plugin.selectItem(a.id))});a.initMoveDown(function(a){b.nodes[a]&&(a=b.nodes[a].children,0<a.length&&(lucid.plugin.deselectAllItems(),lucid.plugin.selectItem(a[0].id)))});a.initMoveRight(function(a){b.nodes[a]&&(a=b.nodes[a].nextSibling())&&(lucid.plugin.deselectAllItems(),lucid.plugin.selectItem(a.id))});a.initMoveLeft(function(a){b.nodes[a]&&(a=b.nodes[a].prevSibling())&&(lucid.plugin.deselectAllItems(),lucid.plugin.selectItem(a.id))})};h.provide("plugin.layout.TreeHotKeys");plugin.layout.TreeHotKeys=
function(a){var b=this;this.selectedNode=null;lucid.plugin.onSelectionChange(function(c){1==c.length&&a(c[0])?(b.selectedNode=c[0],lucid.hotKeys.enable()):(b.selectedNode=null,lucid.hotKeys.disable())})};plugin.layout.TreeHotKeys.prototype.initAddChild=function(a){var b=this;lucid.hotKeys.add(["tab"],function(){b.selectedNode&&(lucid.text.isEditorActive()?lucid.text.blurEditor():a(b.selectedNode))})};plugin.layout.TreeHotKeys.prototype.initAddSibling=function(a){var b=this;lucid.hotKeys.add(["enter"],
function(){b.selectedNode&&(lucid.text.isEditorActive()?lucid.text.blurEditor():a(b.selectedNode))})};plugin.layout.TreeHotKeys.prototype.initMoveUp=function(a){var b=this;lucid.hotKeys.add(["up"],function(){b.selectedNode&&(lucid.text.isEditorActive()&&lucid.text.blurEditor(),a(b.selectedNode))})};plugin.layout.TreeHotKeys.prototype.initMoveDown=function(a){var b=this;lucid.hotKeys.add(["down"],function(){b.selectedNode&&(lucid.text.isEditorActive()&&lucid.text.blurEditor(),a(b.selectedNode))})};
plugin.layout.TreeHotKeys.prototype.initMoveRight=function(a){var b=this;lucid.hotKeys.add(["right"],function(){b.selectedNode&&(lucid.text.isEditorActive()&&lucid.text.blurEditor(),a(b.selectedNode))})};plugin.layout.TreeHotKeys.prototype.initMoveLeft=function(a){var b=this;lucid.hotKeys.add(["left"],function(){b.selectedNode&&(lucid.text.isEditorActive()&&lucid.text.blurEditor(),a(b.selectedNode))})};plugin.layout.TreeHotKeys.prototype.getSelected=function(){return this.selectedNode};h.provide("plugin.orgchart2");
h.require("plugin.layout.LayoutManager");h.require("plugin.layout.VerticalSimpleLayout");h.require("plugin.layout.VerticalCompactLayout");h.require("plugin.layout.VerticalLeafLayout");h.require("plugin.layout.ContextPanelBuilder");h.require("plugin.layout.TreeHotKeys");var G=["Name","Role","Phone","Email","Photo"],q=G.slice();q.splice(q.indexOf("Photo"),1);var F={};G.forEach(function(a){F[a]=!1});F.Name=!0;var n={},u={},E=function(a,b,c){lucid.plugin.setPropertyIfChanged(a,"Photo",b);u.Photo.refresh();
c?u.ImageUrl.setValue("Image URL"):u.ImageUrl.setValue(b)},g=new plugin.layout.LayoutManager(N),R=new plugin.layout.ContextPanelBuilder(g),O=null,z=new plugin.layout.TreeHotKeys(function(a){return N(lucid.plugin.getBlockClassName(a))});z.initAddChild(function(a){if(a=g.nodes[a]){var b=a.addNewChild(K(a));L(a,b);lucid.plugin.editBlockTextArea(b,"Name");lucid.plugin.deselectAllItems();lucid.plugin.selectItem(b);lucid.plugin.editBlockTextArea(b,"Text")}});z.initAddSibling(function(a){if((a=g.nodes[a])&&
a.parent){var b=a.addNewSibling(K(a));L(a,b);lucid.plugin.editBlockTextArea(b,"Name");lucid.plugin.deselectAllItems();lucid.plugin.selectItem(b);lucid.plugin.editBlockTextArea(b,"Text")}});g.initNavigationHotKeys(z);var y={name:{size:{x:0,y:0,w:200,h:60},style:{Name:{align:"center",bold:!1,italic:!1}}},"name-role":{size:{x:0,y:0,w:200,h:100},style:{Name:{align:"center",bold:!0,italic:!1},Role:{align:"center",bold:!1,italic:!1}}},"name-role-phone-email":{size:{x:0,y:0,w:200,h:120},style:{Name:{align:"left",
bold:!0,italic:!1},Role:{align:"left",bold:!1,italic:!0},Email:{align:"left",bold:!1,italic:!1},Phone:{align:"left",bold:!1,italic:!1}}},custom:{size:{x:0,y:0,w:200,h:120},style:{Name:{align:"left",bold:!0,italic:!1},Role:{align:"left",bold:!1,italic:!0},Phone:{align:"left",bold:!1,italic:!1},Email:{align:"left",bold:!1,italic:!1}}}},z={},v;for(v in y)z[v+"-photo"]=lucid.object.copy(y[v]),z[v+"-photo"].size.w+=A(z[v+"-photo"].size,{Photo:!0});for(v in z)y[v]=z[v];z={};lucid.plugin.onLoad(function(){lucid.user.exists()&&
(lucid.help.section.add("Org Chart",[{id:"orgChart.video",content:{url:"//www.youtube.com/embed/Ww0yNX_Vyac?rel=0&showinfo=0&wmode=transparent"},title:"Watch the overview video",suffix:"org chart",clickToAccomplish:!0},{id:"orgChart.import",content:{lucidUrl:"orgchart/import"},suffix:"org chart",title:"Create org chart from spreadsheet or CSV"},{id:"orgChart.add",content:{lucidUrl:"orgchart/addBlock"},title:"Create org chart from toolbox",suffix:"org chart"},{id:"orgChart.add.line",content:{lucidUrl:"orgchart/addBlockWithLine"},
suffix:"org chart",title:"Add employee from canvas"},{id:"orgChart.add.panel",content:{lucidUrl:"orgchart/addBlockWithPanel"},suffix:"org chart",title:"Add employees from panel"},{id:"orgChart.info",content:{lucidUrl:"orgchart/updateBlock"},suffix:"org chart",title:"Update employee information and location"},{id:"orgChart.layout",content:{lucidUrl:"orgchart/layout"},suffix:"org chart",title:"Try different spacing options"},{id:"orgChart.infoVisibility",content:{lucidUrl:"orgchart/infoVisibility"},
suffix:"org chart",title:"Show/hide employee information"},{id:"orgChart.image",content:{lucidUrl:"orgchart/addImage"},suffix:"org chart",title:"Add photos of each employee"},{id:"orgChart.theme",content:{lucidUrl:"orgchart/theme"},suffix:"org chart",title:"Apply a theme style",accomplish:function(a){lucid.plugin.onCurrentUserAction(function(b){"SetProperty"==b.Action&&"Theme"==b.Property&&null==b.id&&lucid.plugin.getAllBlockIds().some(function(a){return"OrgBlock"==lucid.plugin.getBlockClassName(a)})&&
a()})}}]),lucid.config.editorAccomplishments&&(lucid.user.isDemo()?lucid.help.panel.show("Org Chart"):"0"!=lucid.user.preference.get("ShowOrgChartHelp")&&(lucid.user.preference.set("ShowOrgChartHelp","0"),lucid.help.panel.show("Org Chart"))))});lucid.plugin.initBlockClass({className:"OrgBlock",name:"Org Chart Entry",searchKeywords:["organization","chart","person"],defaultSize:{w:160,h:60},onInit:function(a){function b(a,b,c){return 2<(lucid.plugin.getProperty(null,"Version")||0)?c(a):b(a)}function c(c,
d){lucid.plugin.addBlockTextArea(a,{id:c,value:d||c,getBoundingBox:function(d){var f=lucid.plugin.getAllProperties(a),g=t(a);if(!g||!g[c])return null;var k=A(d,g);0<k&&(k+=8);var h=I(f.NumCustomFields,g);return b(d,function(a){return{x:a.x+k+20,y:a.y+M(c,g)*a.h/h,w:a.w-k-20-20,h:a.h/h}},function(b){var d=lucid.plugin.getProperty(a,"InsetMargin");return{x:b.x+k+d,y:b.y+M(c,g)*b.h/h,w:b.w-k-2*d,h:b.h/h}})}})}function d(b){for(var d=lucid.object.createSet(lucid.plugin.getBlockTextAreas(a)),h=0;h<b;h++){var f=
"Custom"+h;if(!d[f]&&(c(f,lucid.plugin.getProperty(a,f+"Name")||""),g.nodes[a])){var q=g.nodes[a];lucid.plugin.hookPropertyPostSave(a,f,function(a,b){if(q==m){var c=u[f];if(c){var d=lucid.text.plainText(b);c.getValue()!=d&&c.setValue(d)}}})}}}lucid.plugin&&lucid.plugin.registerProperty(a,"Type","name",null,function(b,c){if(c){q.forEach(function(b){lucid.plugin.updateBlockTextArea(a,b,{preferredStyle:y[c].style[b]||{}})});for(var d=lucid.plugin.getProperty(a,"NumCustomFields"),f=0;f<d;f++)lucid.plugin.updateBlockTextArea(a,
"Custom"+f,{preferredStyle:{align:"left",bold:!1,italic:!1}})}});lucid.plugin.registerProperty(a,"Active",F,null,function(b,c){if(c){q.forEach(function(b){lucid.plugin.updateBlockTextArea(a,b,{preferredStyle:y.custom.style[b]})});for(var d=lucid.plugin.getProperty(a,"NumCustomFields"),f=0;f<d;f++)lucid.plugin.updateBlockTextArea(a,"Custom"+f,{preferredStyle:{align:"left",bold:!1,italic:!1}})}});lucid.plugin.registerProperty(a,"Photo","",function(a){return"string"!==typeof a?"":String(a)});lucid.plugin.setProperty(a,
"HasContextPanel",!0,!0);2<(lucid.plugin.getProperty(null,"Version")||0)&&lucid.plugin.registerProperty(a,"InsetMargin",5);lucid.plugin.registerProperty(a,"NumCustomFields",0,null,function(b,c){for(var g=0;g<c;g++)void 0===lucid.plugin.getProperty(a,"Custom"+g+"Name")&&lucid.plugin.setProperty(a,"Custom"+g+"Name","");c>b&&d(c)});lucid.plugin.hookPropertyPostSave(a,"BoundingBox",function(b,c,d,f){!f&&lucid.plugin.isSelected(a)&&(d=(b=g.nodes[a])&&b.parent)&&!lucid.plugin.isSelected(d.id)&&(b.bb=c,
d.reorderChildren(),O())});q.forEach(function(a){c(a)})},lineDrawnProperties:function(a,b){return{Endpoint1:{Style:"None"},Endpoint2:{Style:"None"},Shape:"elbow"}},lineDrawn:function(a,b,c,d){if(d&&(g.roots=g.refreshTree(lucid.plugin.getDetailsForItems([a])),a=g.nodes[a])){c=K(a);if(d=lucid.plugin.getProperty(b,"Endpoint2").Block)for(var e in c){b=c[e];if("BoundingBox"==e){var k=lucid.plugin.getProperty(d,e);b.x=k.x;b.y=k.y}lucid.plugin.setPropertyIfChanged(d,e,b)}else d=a.addNewChild(c,b),lucid.plugin.deleteItem(b);
L(a,d);lucid.help.item.accomplish("orgChart.add.line")}},beforeDelete:function(a,b){if(!b){var c=g.nodes[a];if(c){g.roots=g.refreshTree(lucid.plugin.getDetailsForItems([a]));var d=(new (g.layouts[g.currentLayout()].klass)(g.roots,g)).highestCorrectAncestor(c);c.deleteSelf();g.roots=g.refreshTree(lucid.plugin.getDetailsForItems(C()));g.partialLayout(d);return!1}}},hitTest:function(a,b){var c=lucid.plugin.getAllProperties(a),d=t(a);if(/photo$/.test(c.Type)||d.Photo){var e=c.BoundingBox;if(e&&(c=lucid.math.Point.rotate(b,
lucid.math.Box.center(e),-c.Rotation),d=A(e,d),lucid.math.Point.inBox(c,{x:e.x+4,y:e.y+4,w:d,h:d})))return{onClick:function(){lucid.plugin.showUserImageDialog(function(b){E(a,b[0].url,!0)},{source:"orgchart"})},cursor:"pointer"}}},getOffsetProperties:function(a,b,c){if(c.w||c.h)return lucid.plugin.defaultOffsetProperties(a,b,c);for(var d={},e=lucid.plugin.getDownstream(a,function(b){return b==a||!lucid.plugin.isSelected(b)}),g=0;g<e.length;g++){var h=e[g];d[h]=lucid.plugin.defaultOffsetProperties(h,
b,c)[h]}return d},getLinkPoints:function(){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},onDropImage:function(a,b,c,d){E(a,b,!0)},getRenderData:function(a,b){var c=a.BoundingBox,d="sample"!=b?a.FillColor:{t:"l",x1:1,x2:0,y1:0,y2:0,cs:[{c:"#B2B2B299",t:0},{c:"#FFFFFF99",t:1}]};"sample"==b&&(c.x+=c.w/8,c.h*=.75,c.w*=.75);var d=[{FillColor:d,StrokeColor:a.LineColor,LineWidth:"sample"!=b?a.LineWidth:1.5,Actions:[{Action:"move",x:c.x,y:c.y},{Action:"line",x:c.x+c.w,y:c.y},{Action:"line",x:c.x+c.w,
y:c.y+c.h},{Action:"line",x:c.x,y:c.y+c.h},{Action:"close"}]}],e=t(a.id);if(/photo$/.test(a.Type)||"custom"==a.Type&&e&&e.Photo)e=A(c,e),c={x:c.x+4,y:c.y+4,w:e,h:e},d.push({FillColor:{url:a.Photo||lucid.net.cashyURL("/app/webroot/img/orgchart/head.png"),pos:"fill",bb:c},Actions:[{Action:"move",x:c.x,y:c.y},{Action:"line",x:c.x+c.w,y:c.y},{Action:"line",x:c.x+c.w,y:c.y+c.h},{Action:"line",x:c.x,y:c.y+c.h},{Action:"close"}]});return d}});var m=null,S=null,T;lucid.plugin.onDocumentLoaded(function(){function a(a,
b,c,d,e){if(a in y&&(b=g.expandSelection(b?lucid.plugin.getDetailsForItems(b):lucid.plugin.getSelectionDetails()),b=D(b),0!==b.length)){var f=g.refreshTree(b),h=y[a],X="custom"==a,k=lucid.plugin.getAllProperties(f[0].id),l=t(f[0].id);c=J(c||k.Type,k.BoundingBox,d||l,e||k.NumCustomFields);d=J(a,k.BoundingBox,l,k.NumCustomFields);var m=d.w/c.w,w=d.h/c.h;c=f[0].bb.x+f[0].bb.w/2;var r=c*m-c,q=f[0].bb.y*w-f[0].bb.y;b.forEach(function(b){var c=lucid.plugin.getAllProperties(b.id),d=t(b.id);if(X||a!=c.Type){lucid.plugin.setPropertyIfChanged(b.id,
"Type",a);var e=J(a,c.BoundingBox,d,c.NumCustomFields);e.x=(e.x+c.BoundingBox.w/2)*m-r-e.w/2;e.y=e.y*w-q;lucid.plugin.setPropertyIfChanged(b.id,"BoundingBox",e);for(var f in h.style)lucid.plugin.setPropertyIfChanged(b.id,f,lucid.text.restyle(c[f],h.style[f]));var e=c.NumCustomFields,g={align:"left",bold:!1,italic:!1};for(f=0;f<e;f++)lucid.plugin.setPropertyIfChanged(b.id,"Custom"+f,lucid.text.restyle(c["Custom"+f],g));if(!X){c=W(a);G.forEach(function(a){d[a]=!1});for(f=0;f<e;f++)d["Custom"+f]=!1;
c.forEach(function(a){d[a]=!0});d.Name=!0;lucid.plugin.setPropertyIfChanged(b.id,"Active",d)}}});var u=t(f[0].id);G.forEach(function(a){n[a]&&n[a].setValue(u[a])});b=lucid.plugin.getProperty(f[0].id,"NumCustomFields");for(f=0;f<b;f++)n["Custom"+f]&&n["Custom"+f].setValue(u["Custom"+f])}}function b(a){return function(b,c){c||f(a,b)}}function c(a){return function(b,c){!c&&m&&m.setText(b,y,a)}}function d(a,d,e,f,g){e.add({tag:"td",classes:"label",text:f,attr:{title:f}});e.open({tag:"td",classes:"input"});
u[a]=e.addInput({type:"text",value:f,allChanges:!0,onChange:c(a)});e.close();e.open({tag:"td",classes:"checkbox",title:"Toggle this field"});f=n[a]?n[a].getValue():!1;n[a]=e.addInput({type:"checkbox",value:f,onChange:b(a)});e.close();d&&(e.open({tag:"td"}),e.open({tag:"img",title:"Delete this field",classes:"trash",attr:{src:lucid.net.cashyURL("/app/webroot/img/orgchart/trash_16.png")},onClick:function(){return function(){h(g)}}()}),e.close(),e.close())}function e(a){var b=l.getElement(ba),c=lucid.template.builder();
c.open({tag:"table",classes:"org-chart-details collapsible-content",attr:{cellpadding:"0",cellspacing:"0"}});var e=g.expandSelection(lucid.plugin.getSelectionDetails()),e=D(e);if(0<e.length)for(var f=0;f<a;f++){c.open({tag:"tr"});var k=lucid.plugin.getProperty(e[0].id,"Custom"+f+"Name");d("Custom"+f,!0,c,k,f);c.close()}c.close();b.setContent(c);b=g.refreshTree(lucid.plugin.getSelectionDetails());if(0<b.length){var h=t(b[0].id);G.forEach(function(a){n[a]&&n[a].setValue(h[a])});for(f=0;f<a;f++)n["Custom"+
f]&&n["Custom"+f].setValue(h["Custom"+f])}}function k(){var a=g.expandSelection(lucid.plugin.getSelectionDetails()),a=D(a),b=g.refreshTree(a),c=0;b.forEach(function(a){c=Math.max(c,lucid.plugin.getProperty(a.id,"NumCustomFields"))});10>c?lucid.dialog.prompt("Name this field","",function(a){b.forEach(function(b){c=lucid.plugin.getProperty(b.id,"NumCustomFields");b=b.getAllDescendants();b.forEach(function(b){lucid.plugin.setPropertyIfChanged(b.id,"Custom"+c+"Name",a);lucid.plugin.setPropertyIfChanged(b.id,
"NumCustomFields",c+1);20<a.length&&(a=a.substr(0,20));var d=lucid.text.getStyleFromContent(lucid.plugin.getProperty(b.id,"Email"));lucid.plugin.setPropertyIfChanged(b.id,"Custom"+c,lucid.text.restyle(a,d))});for(var d=0;d<b.length;d++)b[d]=b[d].id;d="Custom"+c;e(c+1);f(d,!0,b)})}):lucid.dialog.alert("You have reached the maximum number of custom fields available")}function h(a){lucid.dialog.confirm("Are you sure you want to delete this field?<br>All data for this field will be lost.",function(){var b=
g.expandSelection(lucid.plugin.getSelectionDetails()),b=D(b),c=g.refreshTree(b),d=lucid.plugin.getProperty(c[0].id,"NumCustomFields"),f;b.forEach(function(b){var c=t(b.id);f=lucid.object.clone(c);for(var e=a;e<d-1;e++)lucid.plugin.setPropertyIfChanged(b.id,"Custom"+e+"Name",lucid.plugin.getProperty(b.id,"Custom"+(e+1)+"Name")),lucid.plugin.setPropertyIfChanged(b.id,"Custom"+e,lucid.plugin.getProperty(b.id,"Custom"+(e+1))),c["Custom"+e]=c["Custom"+(e+1)];c["Custom"+(d-1)]=!1;lucid.plugin.setPropertyIfChanged(b.id,
"Active",c);lucid.plugin.setProperty(b.id,"NumCustomFields",d-1);lucid.plugin.setPropertyIfChanged(b.id,"Custom"+(d-1)+"Name","");lucid.plugin.setPropertyIfChanged(b.id,"Custom"+(d-1),"")});e(d-1);z(b,!1,null,f,d)})}function f(a,b,c){c=g.expandSelection(c?lucid.plugin.getDetailsForItems(c):lucid.plugin.getSelectionDetails());c=D(c);if(0!==g.refreshTree(c).length){var d,e;c.forEach(function(c){var f=lucid.plugin.getAllProperties(c.id),g=t(c.id);d=lucid.object.clone(g);e=f.Type;g[a]=b;lucid.plugin.setPropertyIfChanged(c.id,
"Active",g);lucid.plugin.setPropertyIfChanged(c.id,"Type","custom")});z(c,!1,e,d)}}function z(b,c,d,e,f){g.roots.forEach(function(b){var c=t(b.id),g="";G.forEach(function(a){c[a]&&(g=g+(""==g?"":"-")+a.toLowerCase())});for(var k=lucid.plugin.getProperty(b.id,"NumCustomFields"),h=0;h<k;h++)c["Custom"+h]&&(g=g+(""==g?"":"-")+"custom"+h);g in y||(g="custom");b=b.getAllDescendants();for(h=0;h<b.length;h++)b[h]=b[h].id;a(g,b,d,e,f);T.setValue(g)});if(c){var k=g.layouts[g.currentLayout()].klass,h=[];lucid.array.forEach(g.roots,
function(a){(new k([a],g)).isLaidOutCorrectly(a)&&h.push(a)});h.length==g.roots.length?(new k(g.roots,g)).run():lucid.array.forEach(g.roots,function(a){(new k([a],g)).run()})}}function v(a){m=a;lucid.plugin.invalidateViewport();q.forEach(function(b){var c=u[b];"setValue"in c&&c.setValue(a.getText(b))});for(var b=0;10>b;b++){var c="Custom"+b,d=u[c];d&&"setValue"in d&&d.setValue(a.getText(c))}q.forEach(function(a){if("setValue"in n[a]){var b=t(m.id);n[a].setValue(b[a])}});for(b=0;b<lucid.plugin.getProperty(m.id,
"NumCustomFields");b++)"setValue"in n["Custom"+b]&&(c=t(m.id),n["Custom"+b].setValue(c["Custom"+b]));m&&(b=lucid.plugin.getProperty(m.id,"Photo"),""==b||lucid.string.startsWith(b,"/imageBlocks")?u.ImageUrl.setValue("Image URL"):u.ImageUrl.setValue(b));u.Photo.refresh()}var A=function(a){var b=!0,c=function(b){var c=[{value:null,label:"----"}];b?lucid.array.forEach(a[0]||[],function(a,b){c.push({value:b,label:a})}):lucid.array.forEach(a[0]||[],function(a,b){c.push({value:b,label:"Column "+(b+1)})});
return c},d=function(a,b){var c=null;lucid.array.some(b,function(b){return b.label.replace(/[^a-zA-Z0-9]/gi,"").match(new RegExp(a.replace(/[^a-zA-Z0-9]/gi,""),"i"))?(c=b.value,!0):!1});return c},e=c(!0),f=c(!1),h=function(a,c,g,h,l,aa){h=h||1;a.open();a.open({classes:"left"});a.add({text:g,title:g,classes:"field-label"});a.close();for(var q,n=0;n<h;n++)(function(h){a.open({classes:"left field-select"});q=a.addInput({type:"select",inDialog:!0,options:b?e:f,checkUpdate:function(){return{options:b?
e:f}},onChange:function(a,b){w[c][h]=a;m[c]=a}});if(0==h){var k=d(g,e);q.setValue(null!=m[c]?m[c]:k)}a.close()})(n);l&&a.add({tag:"img",classes:"right field-trash",attr:{src:lucid.net.cashyURL("/app/webroot/img/orgchart/trash_16.png")},title:"Delete this field",onClick:function(){for(var a=aa;a<t-1;a++)k[a].label=k[a+1].label,m["Custom"+a]=m["Custom"+(a+1)];k.pop();delete m["Custom"+(t-1)];delete w["Custom"+(t-1)];v(--t)}});"Reports to:"===g&&(a.open({classes:"left field-select"}),a.addInput({type:"select",
inDialog:!0,options:[{value:0,label:"First Last"},{value:1,label:"Last, First"}],onChange:function(a){u=0===a?"First Last":"Last, First"}}),a.close());a.spacer();a.close()},c=[{key:"name",fields:2,label:"Name:"},{key:"role",fields:1,label:"Role:"},{key:"phone",fields:1,label:"Phone:"},{key:"email",fields:1,label:"Email:"},{key:"photo",fields:1,label:"Image URL"}],k=[],l=[{key:"parent",fields:1,label:"Reports to:"},{key:"pageBy",fields:1,label:"Page by:"}],m={},u="First Last",w={};c.concat(l).forEach(function(a){w[a.key]=
[];for(var b=0;b<a.fields;b++)w[a.key].push(null)});var r=lucid.template.builder(),n=lucid.template.builder();r.add({tag:"h2",text:"Fields"});r.addInput({type:"checkbox",value:!0,onChange:function(a,c){c||(b=a,r.refreshInputs(),n.refreshInputs())}});r.add({tag:"label",classes:"inline",text:"Use top row as headers"});c.forEach(function(a){h(r,a.key,a.label,a.fields)});var t=0,x=r.open();r.close();var v=function(){n=lucid.template.builder();for(var a=0;a<k.length;a++){var b=k[a];h(n,b.key,b.label+":",
b.fields,!0,a)}r.getElement(x).setContent(n)};r.open({tag:"button",classes:"btn btn-sm btn-default add-field",title:"Add new field",onClick:function(){A()}});r.add({tag:"div",classes:"icon-13 icon-13-plus plus"});r.add({text:"Field",classes:"text"});r.close();r.add({tag:"hr"});r.add({tag:"h2",text:"Structure"});l.forEach(function(a){h(r,a.key,a.label,a.fields)});var A=function(){10>t?lucid.dialog.prompt("Name this field","",function(a){var b="Custom"+t;k.push({key:b,fields:1,label:a});w[b]=[null];
v(++t)}):lucid.dialog.alert("You have reached the maximum number of custom fields available")},B=function(){var c={},d=null,e={w:160,h:60,x:0,y:80},f=[],h={},l=[],m=lucid.plugin.getActivePageId(),n=m&&0==lucid.plugin.getChildren(m).length,r="name",r=w.Custom0?"custom":null!=w.phone[0]||null!=w.email[0]?"name-role-phone-email":null!=w.role[0]?"name-role":"name";w.photo&&null!=w.photo[0]&&(r+="-photo");var x=function(a,b,c){b.x=Math.round(lucid.plugin.getPageSize(a).w/2-b.w/2);b.w=y[r].size.w;b.h=y[r].size.h;
var d={className:"OrgBlock",BoundingBox:b,Type:r,Layout:"VerticalLeafLayout"},e={};q.forEach(function(a){var b;b=c[a.toLowerCase()];b=lucid.text.restyle(b,Q(y,a));d[a]=b||"";e[a]=!1;w[a.toLowerCase()]&&null!=w[a.toLowerCase()][0]&&(e[a]=!0)});d.Photo=c.photo||"";w.photo&&null!=w.photo[0]&&(e.Photo=!0);var f={align:"left",bold:!1,italic:!1};k.forEach(function(a){d[a.key]=lucid.text.restyle(c[a.key],f);d[a.key+"Name"]=a.label;e[a.key]=!1;w[a.key]&&null!=w[a.key][0]&&(e[a.key]=!0)});d.NumCustomFields=
t;d.Active=e;return lucid.plugin.addBlock(a,d)};lucid.array.forEach(a,function(g,k){if(!b||0!==k){var p={};lucid.object.forEach(w,function(b,c){p[c]=lucid.array.reduce(b,function(b,c){return b&&a[k][c]?"Last, First"===u?a[k][c]+", "+b:b+" "+a[k][c]:b?b:a[k][c]||""},null)});if(p.name||p.role||p.phone||p.email)p.pageBy=p.pageBy||"default",p.parent=parseInt(p.parent,10)||p.parent||null,c[p.pageBy]||(c[p.pageBy]=n&&!d?m:lucid.plugin.addPage({Title:"default"==p.pageBy?"My Organization":p.pageBy,SkipMultipage:0}),
c[p.pageBy]==m&&lucid.plugin.setPropertyIfChanged(m,"SkipMultipage",0)),d||(d=c[p.pageBy]),p.pageId=c[p.pageBy],p.blockId=x(p.pageId,e,p),l[k+1]=p,p.name&&(h[p.name]=p),f.push(p)}});var v={};lucid.array.forEach(f,function(a){if(a.blockId&&a.parent){var b=h[a.parent]||l[a.parent];if(b&&b.blockId){var c=b.blockId;b.pageId!=a.pageId&&(v[a.pageId]&&v[a.pageId][a.parent]?c=v[a.pageId][a.parent]:(c=x(a.pageId,e,b),v[a.pageId]||(v[a.pageId]={}),v[a.pageId][a.parent]=c));a=lucid.plugin.addLine(a.pageId,{Endpoint1:{Block:c,
Style:"None",LinkX:.5,LinkY:1},Endpoint2:{Block:a.blockId,Style:"None",LinkX:.5,LinkY:0},Shape:"elbow",AutoLink:!1,Lock:1,IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}});lucid.plugin.setProperty(a,"HasContextPanel",!1,!0)}}});var U;lucid.object.forEach(c,function(a){(U=lucid.plugin.getDetailsForItems(lucid.plugin.getChildren(a)))&&0<U.length&&(R.applyLayout(g.currentLayout(),U),lucid.plugin.selectPage(a),lucid.plugin.selectAll(),z(D(lucid.plugin.getSelectionDetails()),!0))});lucid.help.item.accomplish("orgChart.import");
d&&lucid.plugin.selectPage(d)},C=lucid.dialog.custom(r.getTemplate(),{title:"Format Org Chart",classes:"custom-fields-dialog",buttons:[{label:"Cancel",action:function(){C.close()}},{label:"Generate Org Chart",action:function(){C.close();B()}}]});C.open()};S=function(){var a=null,b=lucid.template.builder();b.add({tag:"label",text:"Import from CSV file:"});b.addInput({type:"file",onSuccess:function(b){var c=function(a,c,d,e){lucid.CSV.toArrays(b,a,function(a){a&&(e||a.length&&1<a[0].length)?c(a):d()})};
a.close();c({separator:","},A,function(){c({separator:"\t",delimiter:"\x00"},A,function(){lucid.dialog.alert("Could not parse the file. Make sure the file is formatted correctly and try again.")},!0)})}});b.add({tag:"label",text:"Or paste your spreadsheet data:"});a=lucid.dialog.textAreaPrompt(b.getTemplate(),"",function(a){var b=function(b,c,d,e){lucid.CSV.toArrays(a,b,function(a){a&&(e||a.length&&1<a[0].length)?c(a):d()})};a=a.replace(/\r\n|\r|\n/g,"\r\n");b({separator:"\t",delimiter:"\x00"},A,
function(){b({separator:","},A,function(){lucid.dialog.alert("Could not parse the data. Make sure you pasted it correctly and try again.")},!0)})})};var l=lucid.template.builder();l.open({classes:"context-panel-right-controls"});var F=R.buildLayoutSelection(l),C=[],H=[],B;for(B in y)"custom"!==B&&"custom-photo"!==B&&H.push(B);H.push("custom");for(B=0;B<H.length;B++){var P=lucid.template.builder();P.add({tag:"img",attr:{src:lucid.net.cashyURL("/app/webroot/img/orgchart/"+H[B]+".png")},css:{width:"100px",
"image-rendering":"optimizequality"}});P=P.getTemplate();C.push({value:H[B],dom:P,hoverProperties:function(b){return function(){a(b)}}(H[B])})}T=l.addInput({type:"select",options:C,onChange:function(b,c){c||(a(b),"custom"!=b&&lucid.help.item.accomplish("orgChart.infoVisibility"))}});l.close();var I=l.add({classes:"context-panel-list-container drag-scroll"});l.clear();var M=l.open({classes:"collapsible collapsed"});l.add({classes:"heading",children:[{classes:"icon-13"},"Details"],click:function(){l.getElement(M).toggleClass("collapsed")}});
l.open({tag:"div",classes:"org-chart-details collapsible-content",attr:{style:"position:relative"}});l.open({tag:"table",classes:"org-chart-details",attr:{cellpadding:"0",cellspacing:"0"}});l.open({tag:"tr"});d(q[0],!1,l,q[0]);l.open({tag:"td",classes:"avatar",attr:{rowspan:q.length}});u.Photo=l.addInput({type:"custom",width:107,height:107,getRenderData:function(){m&&(""===lucid.plugin.getProperty(m.id,"Photo")?l.getElement(Y).addClass("hidden"):l.getElement(Y).removeClass("hidden"));return[{FillColor:{url:m&&
lucid.plugin.getProperty(m.id,"Photo")||lucid.net.cashyURL("/app/webroot/img/orgchart/head.png"),pos:"fill"},Actions:[{Action:"move",x:0,y:0},{Action:"line",x:107,y:0},{Action:"line",x:107,y:107},{Action:"line",x:0,y:107},{Action:"close"}]}]},onClick:function(){m&&lucid.plugin.showUserImageDialog(function(a){m&&E(m.id,a[0].url,!0)},{source:"orgchart"})},onDropImage:function(a){m&&E(m.id,a,!0)}});var Y=l.add({tag:"img",classes:"photo-trash",title:"Delete photo",attr:{src:lucid.net.cashyURL("/app/webroot/img/orgchart/trash_16.png")},
onClick:function(){m&&E(m.id,"",!0)}});l.open({tag:"td",classes:"photo-checkbox",title:"Toggle photo"});n.Photo=l.addInput({type:"checkbox",value:!0,onChange:b("Photo")});l.close();l.close();l.close();q.slice(1).forEach(function(a){l.open({tag:"tr"});d(a,!1,l,a);l.close()});l.close();var V=l.open({tag:"div",classes:"org-chart-details collapsible-content default"});u.ImageUrl=l.addInput({type:"text",value:"Image URL",allChanges:!1,onChange:function(a,b){var c=l.getElement(V);!b&&m&&E(m.id,a,!1);b&&
"Image URL"==a?c.addClass("default"):c.removeClass("default")},onFocus:function(){var a=l.getElement(V);"Image URL"==u.ImageUrl.getValue()&&a.hasClass("default")&&(a.removeClass("default"),u.ImageUrl.setValue(""))},onBlur:function(){var a=l.getElement(V);""==u.ImageUrl.getValue()&&(a.addClass("default"),u.ImageUrl.setValue("Image URL"))}});l.close();l.close();var ba=l.open();l.spacer();l.close();l.open({tag:"div",classes:"collapsible-content"});l.open({tag:"button",classes:"button",title:"Add new field",
onClick:function(){k()}});l.add({tag:"div",classes:"icon-13 icon-13-plus"});l.add({text:"Field",classes:"text"});l.close();l.close();l.close();var Z=null;lucid.plugin.addCustomPanel("Context Panel",null,[{content:l}],null,{isContextPanel:!0,adjWidth:2,checkShow:function(a){if(lucid.useragent.is_touch())return!1;var b=0,c=null;g.roots=g.refreshTree(a);if(0===g.roots.length)return!1;var d=D(a);if(0<d.length){var f=lucid.plugin.getProperty(d[0].id,"NumCustomFields");e(f);g.nodes[d[0].id]?v(g.nodes[d[0].id]):
m=null}if(!lucid.array.every(a,function(a){return a.isLine?!0:a.isLocked?!1:a.isBlock&&N(a.className)?(c=lucid.plugin.getProperty(a.id,"Type"),b++,!0):!1})||1>b)return!1;var h=[];lucid.array.forEach(g.roots,function(a){h.push(a.treeKey())});a=h.join(";");if(a==Z)return!0;Z=a;T.setValue(c);F.setValue(g.currentLayout());O||(O=function(){var a=lucid.template.builder();R.buildSimpleTree(a,function(a){var b=lucid.plugin.getProperty(a.id,"NumCustomFields");e(b);v(a);lucid.plugin.deselectAllItems();lucid.plugin.selectItem(a.id)},
function(a,b){a.pendingFocus=b.addNewSibling(K(b));L(b,a.pendingFocus)},y);l.getElement(I).setContent(a)});O();return!0},refreshProperties:["NumCustomFields","Active","Type"],onHide:function(){},contextPanelObstacle:function(){g.roots=g.refreshTree(lucid.plugin.getSelectionDetails());var a=[];lucid.array.forEach(g.roots,function(b){a.push(b.calculateBoundingBox())});return lucid.math.Box.combine(a)}})});lucid.plugin.createNextBlockGroup(["OrgBlock"]);lucid.plugin.createToolGroups({"Org Chart":[{size:"large",
name:"OrgChart-leaf",tooltip:"Org Chart",className:"Group",toolBoxId:"OrgChart-leaf",defaultSize:{w:380,h:360},helperImage:lucid.net.cashyURL("/app/webroot/img/layouts/leaf.png"),defaultProperties:function(){return{ApplyTheme:!0,Objects:[{id:"aUTTeMmq.Xw8",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:49,Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",ControlPoints:{},TextAreas:{IsFullPropSettings:!0},Endpoint1:{x:380,y:920,Style:"None",Block:"aUTTKd4WeFqF",
LinkX:.125,LinkY:1,Line:null,LineP:null},Endpoint2:{x:400,y:1090,Style:"None",Block:"aUTTR0M0.9jP",LinkX:0,LinkY:.5,Line:null,LineP:null},Shape:"elbow",LineOffsets:[0],XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,AutoLink:!1,IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"aUTTDkxl1ZFa",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:47,Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",ControlPoints:{},TextAreas:{IsFullPropSettings:!0},
Endpoint1:{x:380,y:920,Style:"None",Block:"aUTTKd4WeFqF",LinkX:.125,LinkY:1,Line:null,LineP:null},Endpoint2:{x:400,y:990,Style:"None",Block:"aUTTEF1iL8_L",LinkX:0,LinkY:.5,Line:null,LineP:null},Shape:"elbow",LineOffsets:[0],XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,AutoLink:!1,IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"aUTTVIFFwszH",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:45,Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",
ControlPoints:{},TextAreas:{IsFullPropSettings:!0},Endpoint1:{x:350,y:820,Style:"None",Block:"aUTT_Xpbg5x-",LinkX:.5,LinkY:1,Line:null,LineP:null},Endpoint2:{x:440,y:860,Style:"None",Block:"aUTTKd4WeFqF",LinkX:.5,LinkY:0,Line:null,LineP:null},Shape:"elbow",LineOffsets:[0],XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,AutoLink:!1,IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"aUTTNG67aZ3D",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:43,
Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",ControlPoints:{},TextAreas:{IsFullPropSettings:!0},Endpoint1:{x:350,y:820,Style:"None",Block:"aUTT_Xpbg5x-",LinkX:.5,LinkY:1,Line:null,LineP:null},Endpoint2:{x:260,y:860,Style:"None",Block:"aUTTG.l2cL_y",LinkX:.5,LinkY:0,Line:null,LineP:null},Shape:"elbow",LineOffsets:[0],XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,AutoLink:!1,IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"aUTTR0M0.9jP",IsBlock:!0,Action:{Action:"CreateBlock",
Class:"OrgBlock",Properties:{BoundingBox:{x:400,y:1060,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:48,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Judith Ng",m:[{s:0,e:10,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",
m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:19}}},{id:"aUTTEF1iL8_L",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:400,y:960,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:46,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Ruth Marr",m:[{s:0,e:10,n:"c",v:"000000ff"}]},Role:{t:"Role",
m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:18}}},{id:"aUTTKd4WeFqF",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:360,y:860,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:44,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",
Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Wallace Stone",m:[{s:0,e:3,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:17}}},{id:"aUTTG.l2cL_y",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:140,y:860,w:200,h:60},
FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:42,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Peter McGee",m:[{s:0,e:3,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},
Type:"name",DepthOrder:16}}},{id:"aUTT_Xpbg5x-",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:250,y:760,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:41,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:[],Name:{t:"Kevin Peets",m:[{s:0,e:3,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},
Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:15}}}],Base:{x:370,y:940},Page:"ntSTcdRBm6L0",Size:{w:380,h:360},Plugins:["/js/plugins/v2/orgchart2.js"]}}},{size:"large",name:"OrgChart-compact",tooltip:"Org Chart",className:"Group",toolBoxId:"OrgChart-compact",defaultSize:{w:430,h:260},helperImage:lucid.net.cashyURL("/app/webroot/img/layouts/compact.png"),defaultProperties:function(){return{ApplyTheme:!0,
Objects:[{id:"8uUTEOej.VN.",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:140,Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",ControlPoints:{},TextAreas:{IsFullPropSettings:!0},Endpoint1:{x:375,y:1E3,Style:"None",Block:"8uUTkwBomoz6",LinkX:.5,LinkY:1,Line:null,LineP:null},Endpoint2:{x:465,y:1040,Style:"None",Block:"8uUT2PcNEia.",LinkX:.5,LinkY:0,Line:null,LineP:null},Shape:"elbow",LineOffsets:[0],XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,
AutoLink:!1,Layout:"VerticalCompactLayout",IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"8uUTuawiLD0v",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:138,Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",ControlPoints:{},TextAreas:{IsFullPropSettings:!0},Endpoint1:{x:375,y:1E3,Style:"None",Block:"8uUTkwBomoz6",LinkX:.5,LinkY:1,Line:null,LineP:null},Endpoint2:{x:285,y:1040,Style:"None",Block:"8uUTEJ-Ctxut",LinkX:.5,LinkY:0,Line:null,
LineP:null},Shape:"elbow",LineOffsets:[0],XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,AutoLink:!1,Layout:"VerticalCompactLayout",IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"8uUTCm140WPo",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:136,Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",ControlPoints:{},TextAreas:{IsFullPropSettings:!0},Endpoint1:{x:285,y:900,Style:"None",Block:"8uUTt3SpyY3q",LinkX:.5,LinkY:1,Line:null,LineP:null},
Endpoint2:{x:375,y:940,Style:"None",Block:"8uUTkwBomoz6",LinkX:.5,LinkY:0,Line:null,LineP:null},Shape:"elbow",LineOffsets:[0],XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,AutoLink:!1,Layout:"VerticalCompactLayout",IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"8uUTd-ZPG5o1",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:134,Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",ControlPoints:{},TextAreas:{IsFullPropSettings:!0},Endpoint1:{x:285,
y:900,Style:"None",Block:"8uUTt3SpyY3q",LinkX:.5,LinkY:1,Line:null,LineP:null},Endpoint2:{x:195,y:940,Style:"None",Block:"8uUTGQP5kSHr",LinkX:.5,LinkY:0,Line:null,LineP:null},Shape:"elbow",LineOffsets:[0],XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,AutoLink:!1,Layout:"VerticalCompactLayout",IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"8uUT2PcNEia.",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:395,y:1040,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",
FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:139,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Judith Ng",m:[{s:0,e:10,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:19,Layout:"VerticalCompactLayout"}}},
{id:"8uUTEJ-Ctxut",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:175,y:1040,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:137,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Ruth Marr",m:[{s:0,e:10,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",
m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:18,Layout:"VerticalCompactLayout"}}},{id:"8uUTkwBomoz6",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:285,y:940,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:135,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,
InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Wallace Stone",m:[{s:0,e:3,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:17,Layout:"VerticalCompactLayout"}}},{id:"8uUTGQP5kSHr",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:65,y:940,w:200,h:60},
FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:133,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Peter McGee",m:[{s:0,e:3,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},
Type:"name",DepthOrder:16,Layout:"VerticalCompactLayout"}}},{id:"8uUTt3SpyY3q",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:175,y:840,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:132,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:[],Name:{t:"Kevin Peets",m:[{s:0,e:3,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,
n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:15,Layout:"VerticalCompactLayout"}}}],Base:{x:330,y:970},Page:"0_0",Size:{w:430,h:260},Plugins:["/js/plugins/v2/orgchart2.js"]}}},{size:"large",name:"OrgChart-simple",tooltip:"Org Chart",className:"Group",toolBoxId:"OrgChart-simple",defaultSize:{w:520,h:260},helperImage:lucid.net.cashyURL("/app/webroot/img/layouts/simple.png"),
defaultProperties:function(){return{ApplyTheme:!0,Objects:[{id:"8uUTd-ZPG5o1",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:134,Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",ControlPoints:{},TextAreas:{IsFullPropSettings:!0},Endpoint1:{x:285,y:900,Style:"None",Block:"8uUTt3SpyY3q",LinkX:.5,LinkY:1,Line:null,LineP:null},Endpoint2:{x:150,y:940,Style:"None",Block:"8uUTGQP5kSHr",LinkX:.5,LinkY:0,Line:null,LineP:null},Shape:"elbow",LineOffsets:[0],
XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,AutoLink:!1,Layout:"VerticalSimpleLayout",IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"8uUTCm140WPo",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:136,Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",ControlPoints:{},TextAreas:{IsFullPropSettings:!0},Endpoint1:{x:285,y:900,Style:"None",Block:"8uUTt3SpyY3q",LinkX:.5,LinkY:1,Line:null,LineP:null},Endpoint2:{x:420,y:940,Style:"None",
Block:"8uUTkwBomoz6",LinkX:.5,LinkY:0,Line:null,LineP:null},Shape:"elbow",LineOffsets:[0],XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,AutoLink:!1,Layout:"VerticalSimpleLayout",IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"8uUTuawiLD0v",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:138,Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",ControlPoints:{},TextAreas:{IsFullPropSettings:!0},Endpoint1:{x:420,y:1E3,Style:"None",Block:"8uUTkwBomoz6",
LinkX:.5,LinkY:1,Line:null,LineP:null},Endpoint2:{x:330,y:1040,Style:"None",Block:"8uUTEJ-Ctxut",LinkX:.5,LinkY:0,Line:null,LineP:null},Shape:"elbow",LineOffsets:[0],XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,AutoLink:!1,Layout:"VerticalSimpleLayout",IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"8uUTEOej.VN.",IsLine:!0,Action:{Action:"CreateLine",Properties:{LineColor:"#000000",LineWidth:2,ZOrder:140,Lock:0,Opacity:100,StrokeStyle:"solid",Font:"Liberation Sans",ControlPoints:{},
TextAreas:{IsFullPropSettings:!0},Endpoint1:{x:420,y:1E3,Style:"None",Block:"8uUTkwBomoz6",LinkX:.5,LinkY:1,Line:null,LineP:null},Endpoint2:{x:510,y:1040,Style:"None",Block:"8uUT2PcNEia.",LinkX:.5,LinkY:0,Line:null,LineP:null},Shape:"elbow",LineOffsets:[0],XPlanes:[],YPlanes:[],ElbowPoints:null,BG:0,AutoLink:!1,Layout:"VerticalSimpleLayout",IgnoreTheme:{Inset:!0,Shape:!0,Endpoint1:!0,Endpoint2:!0}}}},{id:"8uUTt3SpyY3q",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:175,
y:840,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:132,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:[],Name:{t:"Kevin Peets",m:[{s:0,e:3,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,
e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:15,Layout:"VerticalSimpleLayout"}}},{id:"8uUTGQP5kSHr",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:10,y:940,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:133,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Peter McGee",m:[{s:0,e:3,n:"c",v:"000000ff"}]},Role:{t:"Role",
m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:16,Layout:"VerticalSimpleLayout"}}},{id:"8uUTkwBomoz6",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:340,y:940,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:135,TextAlign:"center",
TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Wallace Stone",m:[{s:0,e:3,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:17,Layout:"VerticalSimpleLayout"}}},{id:"8uUTEJ-Ctxut",IsBlock:!0,Action:{Action:"CreateBlock",
Class:"OrgBlock",Properties:{BoundingBox:{x:230,y:1040,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:137,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Ruth Marr",m:[{s:0,e:10,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},
Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:18,Layout:"VerticalSimpleLayout"}}},{id:"8uUT2PcNEia.",IsBlock:!0,Action:{Action:"CreateBlock",Class:"OrgBlock",Properties:{BoundingBox:{x:450,y:1040,w:200,h:60},FlipX:!1,FlipY:!1,LineColor:"#000000",FillColor:"#ffffff",StrokeStyle:"solid",LineWidth:2,ZOrder:139,TextAlign:"center",TextVAlign:"middle",Font:"Liberation Sans",Link:"",Opacity:100,Lock:0,InsetMargin:5,Rotation:0,BG:0,TextLinks:{},Name:{t:"Judith Ng",
m:[{s:0,e:10,n:"c",v:"000000ff"}]},Role:{t:"Role",m:[{s:0,e:4,n:"s",v:null},{s:0,e:4,n:"c",v:"000000ff"}]},Phone:{t:"Phone",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Email:{t:"Email",m:[{s:0,e:5,n:"s",v:null},{s:0,e:5,n:"c",v:"000000ff"}]},Type:"name",DepthOrder:19,Layout:"VerticalSimpleLayout"}}}],Base:{x:330,y:970},Page:"0_0",Size:{w:520,h:260},Plugins:["/js/plugins/v2/orgchart2.js"]}}},{size:"large",name:"OrgChart-single",tooltip:"Org Chart",className:"OrgBlock"},{label:"Import Data",
action:function(){S&&S()},onlineOnly:!0}]});lucid.plugin.onActivate(function(){lucid.CSV.init();lucid.plugin.allowShadowSharing("OrgBlock",!0)});lucid.plugin.addContextMenuItems([{external:!0,label:"Remove photo",logAction:"chart.viewport.context.orgchart.removePhoto",action:function(a,b){E(b[0],null,!0)},visible:function(a){if(1!=a.length)return!1;var b=lucid.plugin.getBlockClassName(a[0]),c=lucid.plugin.getAllProperties(a[0]);a=t(a[0]);return b&&"orgblock"==b.toLowerCase()&&(/-photo$/.test(c.Type)||
a.Photo)&&c.Photo}}])})();
//# sourceMappingURL=/js/plugins/v2/source-maps/orgchart2.js.map
};
