pluginFn['/js/plugins/v2/orgchart.js'] = function(lucid, window) {
	(function(){function f(a,c,b){lucid.plugin.addContextMenuItems([{external:!0,label:a,logAction:"chart.viewport.context.orgchart."+a,action:function(a,c){function k(b,a,h){c[0]==a.Block&&lucid.plugin.setProperty(b,"Endpoint"+h,{Block:e,x:d.BoundingBox.x+d.BoundingBox.w*a.LinkX,y:d.BoundingBox.y+d.BoundingBox.h*a.LinkY})}var d=lucid.plugin.getAllProperties(c[0]);d.BoundingBox.h="PersonBlock"==b||"RoleBlock"==b?d.BoundingBox.h/2:2*d.BoundingBox.h;var g=lucid.plugin.getItemPageId(c[0]);if(g){d.className=
b;var e=lucid.plugin.addBlock(g,d);if(e){for(var g=lucid.plugin.getConnectedLines(c[0]),l=0;l<g.length;l++)k(g[l],lucid.plugin.getProperty(g[l],"Endpoint1"),1),k(g[l],lucid.plugin.getProperty(g[l],"Endpoint2"),2);lucid.plugin.deleteItem(c[0])}}},visible:function(b){return b&&1!=b.length?!1:(b=lucid.plugin.getBlockClassName(b[0]))&&b==c}}])}var e={global:this,provide:function(a){a=a.split(".");e.global[a[0]]=e.global[a[0]]||{};var c=e.global[a[0]];a.slice(1).reduce(function(b,a){b[a]||(b[a]={});return b[a]},
c)},require:function(){},inherits:function(a,c){function b(){}b.prototype=c.prototype;a.superClass_=c.prototype;a.prototype=new b;a.prototype.constructor=a;a.base=function(b,a,k){var d=Array.prototype.slice.call(arguments,2);return c.prototype[a].apply(b,d)}},base:function(a,c,b){var h=arguments.callee.caller;if(e.STRICT_MODE_COMPATIBLE||e.DEBUG&&!h)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");
if(h.superClass_)return h.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),k=!1,d=a.constructor;d;d=d.superClass_&&d.superClass_.constructor)if(d.prototype[c]===h)k=!0;else if(k)return d.prototype[c].apply(a,f);if(a[c]===h)return a.constructor.prototype[c].apply(a,f);throw Error("goog.base called from a method of one name to a method of a different name");}};e.provide("plugin.orgchart");lucid.plugin.initBlockClass({className:"PersonBlock",
name:"Person (Name)",searchKeywords:["organization","chart","person","name"],defaultSize:{w:160,h:60},onInit:function(a){lucid.plugin.addBlockTextArea(a,{id:"Name",value:"Name",getBoundingBox:function(a){return{x:a.x+20,y:a.y,w:a.w-40,h:a.h}}});lucid.plugin.registerProperty(a,"Role",'<span style="font-size:18px;font-weight:bold;">Role</span>')},getLinkPoints:function(){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(a,c){var b=a.BoundingBox;return[{FillColor:a.FillColor,
StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y},{Action:"line",x:b.x+b.w,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+b.h},{Action:"close"}]}]}});f("Show Role or Title","PersonBlock","PersonRoleBlock");lucid.plugin.initBlockClass({className:"RoleBlock",name:"Role or Title",unthemed:!0,searchKeywords:["organization","chart","role","position","title"],defaultSize:{w:160,h:60},onInit:function(a){lucid.plugin.addBlockTextArea(a,{id:"Role",value:'<span style="font-size:18px;font-weight:bold;">Role</span>',
getBoundingBox:function(a){return{x:a.x+20,y:a.y,w:a.w-40,h:a.h}}});lucid.plugin.registerProperty(a,"Name","Name")},getLinkPoints:function(){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(a,c){var b=a.BoundingBox;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y},{Action:"line",x:b.x+b.w,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+b.h},{Action:"close"}]}]}});f("Show Name","RoleBlock",
"PersonRoleBlock");lucid.plugin.initBlockClass({className:"PersonRoleBlock",name:"Person (Name) With Role or Title",unthemed:!0,searchKeywords:"organization chart person name role position title".split(" "),defaultSize:{w:160,h:120},onInit:function(a){lucid.plugin.addBlockTextArea(a,{id:"Role",value:'<span style="font-size:18px;font-weight:bold;">Role</span>',getBoundingBox:function(a){return{x:a.x+20,y:a.y,w:a.w-40,h:a.h/2}}});lucid.plugin.addBlockTextArea(a,{id:"Name",value:"Name",getBoundingBox:function(a){return{x:a.x+
20,y:a.y+a.h/2,w:a.w-40,h:a.h/2}}})},getLinkPoints:function(){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(a,c){var b=a.BoundingBox;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y},{Action:"line",x:b.x+b.w,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+b.h},{Action:"close"}]},{StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y+b.h/2},{Action:"line",x:b.x+
b.w,y:b.y+b.h/2}]}]}});f("Hide Role or Title","PersonRoleBlock","PersonBlock");f("Hide Name","PersonRoleBlock","RoleBlock");lucid.plugin.initBlockClass({className:"OrgChartTitleBlock",name:"Page Title",unthemed:!0,searchKeywords:["organization","chart","title","header"],defaultSize:{w:160,h:40},onInit:function(a){lucid.plugin.addBlockTextArea(a,{id:"Title",value:"My Organization",getBoundingBox:function(a){return{x:a.x,y:a.y,w:a.w,h:a.h}}})},onAddToPage:function(a,c){function b(a){if(c){var b=lucid.plugin.getProperty(c,
"Margin")*lucid.plugin.getProperty(c,"DPI"),e=lucid.plugin.getPageSize(c);a.x=b;a.y=b;a.w=e.w-2*b;a.h=80}return a}lucid.plugin.setProperty(a,"BoundingBox",b(lucid.plugin.getProperty(a,"BoundingBox")));lucid.plugin.hookPropertyPreSave(a,"BoundingBox",function(a){return b(a)});var e=lucid.plugin.hookPropertyPostSave(c,"Size",function(b,c){b!=c&&lucid.plugin.setProperty(a,"BoundingBox",{})}),f=lucid.plugin.hookPropertyPostSave(c,"Margin",function(b,c){b!=c&&lucid.plugin.setProperty(a,"BoundingBox",{})});
lucid.plugin.setProperty(a,"marginHook",f,!0);lucid.plugin.setProperty(a,"sizeHook",e,!0)},onDelete:function(a){var c=lucid.plugin.getItemPageId(a);if(c){var b=lucid.plugin.getProperty(a,"marginHook",!0);a=lucid.plugin.getProperty(a,"sizeHook",!0);lucid.plugin.unHookPropertyPostSave(c,"Margin",b);lucid.plugin.unHookPropertyPostSave(c,"Size",a)}},getLinkPoints:function(){return[{x:.5,y:1}]},getRenderData:function(a,c){var b=a.BoundingBox;return[{FillColor:a.FillColor,Actions:[{Action:"move",x:b.x,
y:b.y},{Action:"line",x:b.x+b.w,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+b.h},{Action:"close"}]}]}});lucid.plugin.createNextBlockGroup(["PersonBlock","RoleBlock","PersonRoleBlock"]);lucid.plugin.createToolGroups({"Org Chart":["PersonBlock","RoleBlock","PersonRoleBlock","OrgChartTitleBlock"]})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/orgchart.js.map
};
