pluginFn['/js/plugins/v2/shapes.js'] = function(lucid, window) {
	(function(){function r(){return lucid.plugin.getProperty(null,"Version")||0}function w(c,b,a){return 1<r()?a(c):b(c)}var t={global:this,provide:function(c){c=c.split(".");t.global[c[0]]=t.global[c[0]]||{};var b=t.global[c[0]];c.slice(1).reduce(function(a,b){a[b]||(a[b]={});return a[b]},b)},require:function(){},inherits:function(c,b){function a(){}a.prototype=b.prototype;c.superClass_=b.prototype;c.prototype=new a;c.prototype.constructor=c;c.base=function(a,c,l){var g=Array.prototype.slice.call(arguments,
2);return b.prototype[c].apply(a,g)}},base:function(c,b,a){var e=arguments.callee.caller;if(t.STRICT_MODE_COMPATIBLE||t.DEBUG&&!e)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(e.superClass_)return e.superClass_.constructor.apply(c,Array.prototype.slice.call(arguments,1));for(var d=Array.prototype.slice.call(arguments,2),l=!1,g=c.constructor;g;g=g.superClass_&&g.superClass_.constructor)if(g.prototype[b]===
e)l=!0;else if(l)return g.prototype[b].apply(c,d);if(c[b]===e)return c.constructor.prototype[b].apply(c,d);throw Error("goog.base called from a method of one name to a method of a different name");}};t.provide("plugin.common.DocVersionedProps");plugin.common.DocVersionedProps.getValueForDocVersion=function(c,b){var a=lucid.plugin.getProperty(null,"Version")||0,e=lucid.array.findRight(c,function(b){return b.docVersionInstated<=a});return e&&e.value||b};t.provide("plugin.common.TextAreaOverflowUtils");
plugin.common.TextAreaOverflowUtils.getOnOverflowCallback=function(c,b,a){return function(e,d,l,g,v){if("number"!==typeof g||"number"!==typeof v||(g+6)%3!=(v+6)%3)g=lucid.plugin.getProperty(null,"Version")||0,v=Math.abs(lucid.text.getTextAreaRotation(e,d)),d!=(a||"Text")||0!==l||5>g||0!==v||plugin.common.TextAreaOverflowUtils.resizeToFitText(e,d,l,c,b)}};plugin.common.TextAreaOverflowUtils.resizeToFitText=function(c,b,a,e,d){var l=lucid.plugin.getProperty(c,"BoundingBox"),g=e(l,c);e=lucid.text.getTextAreaVAlignment(c,
b);e="middle"==e?{x:.5,y:.5}:"bottom"==e?{x:.5,y:1}:{x:.5,y:0};b=lucid.text.getTextAreaSpaceSize(c,b,a);b=lucid.math.Box.resizeAboutRelativePoint(g,e,b);d=d(b,c);b=d.h>l.h;a=lucid.block.getDefaultSize(c).h;d=lucid.math.Box.resizeAboutRelativePoint(l,e,{w:l.w,h:b?Math.max(d.h,l.h):Math.max(d.h,Math.min(l.h,a))});lucid.plugin.setProperty(c,"BoundingBox",d)};t.provide("plugin.common.Callout");t.require("plugin.common.DocVersionedProps");t.require("plugin.common.TextAreaOverflowUtils");plugin.common.Callout.createBlock=
function(c,b,a){function e(a,b,c,h){b||(b=lucid.plugin.getProperty(a,"Side"));c||(c=lucid.plugin.getProperty(a,"Position"));h||(h=lucid.plugin.getProperty(a,"BoundingBox"));var e,d;switch(b){case 0:e=h.w*c;d=0;break;case 1:e=h.w;d=h.h*c;break;case 2:e=h.w*c;d=h.h;break;case 3:e=0,d=h.h*c}return{x:h.x+e,y:h.y+d}}var d=function(a,b){return{x:a.x+5,y:a.y+5,w:a.w-10,h:a.h-10}};lucid.plugin.initBlockClass({className:c,name:b,searchKeywords:"shape tooltip infotip callout call out tip bubble balloon".split(" "),
defaultSize:{w:120,h:40},minWidth:120,minHeight:40,onInit:function(b){lucid.plugin.addBlockTextArea(b,{id:"Tip",value:a,getBoundingBox:d});lucid.plugin.getProperty(b,"BoundingBox");lucid.plugin.registerProperty(b,"MinLayerPadding",25);lucid.plugin.registerProperty(b,"TailAngle",30);lucid.plugin.registerProperty(b,"TailRadius",25);lucid.plugin.registerProperty(b,"TailWidth",15);lucid.plugin.registerProperty(b,"Side",0);lucid.plugin.registerProperty(b,"Position",.6);lucid.plugin.registerProperty(b,
"RoundCorners",5)},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(d,function(a,b){return{x:a.x-5,y:a.y-5,w:a.w+10,h:a.h+10}},"Tip"),getOffsetProperties:function(a,b,c){b=lucid.plugin.defaultOffsetProperties(a,b,c);b[a].MinLayerPadding=lucid.plugin.getProperty(a,"TailRadius");return b},spatialControls:function(a){function b(c,h,d,g,m){var u=Array.prototype.splice.call(arguments);u.unshift(a);return e.apply(null,u)}if(lucid.plugin.getProperty(a,"BoundingBox"))return[{logAction:"chart.viewport.selection.spatialControls.shapes.calloutTail",
location:function(){var a=b();return{x:a.x-5,y:a.y-5,w:10,h:10}},moved:function(b){var c=lucid.plugin.getProperty(a,"BoundingBox"),e=lucid.plugin.getProperty(a,"RoundCorners"),d=lucid.plugin.getProperty(a,"TailWidth"),g=Math.abs(d),u=lucid.plugin.getProperty(a,"Side");b.y<=c.y&&2*e<c.w?u=0:b.x>=c.x+c.w&&2*e<c.h?u=1:b.y>=c.y+c.h&&2*e<c.w?u=2:b.x<=c.x&&2*e<c.h&&(u=3);var k=.5,f=Math.abs(d);switch(u){case 0:case 2:g+2*e>c.w?(k=.5,f=(c.w-2*e)/2):k=Math.min(Math.max(b.x-c.x,e+g),c.w-e-g)/c.w;break;case 1:case 3:g+
2*e>c.h?(k=.5,f=(c.h-2*e)/2):k=Math.min(Math.max(b.y-c.y,e+g),c.h-e-g)/c.h}.45<k&&.55>k&&(k=.5);lucid.plugin.setPropertyIfChanged(a,"TailWidth",0>d?-f:f);lucid.plugin.setPropertyIfChanged(a,"Side",u);lucid.plugin.setPropertyIfChanged(a,"Position",k)},path:function(){var b=lucid.plugin.getProperty(a,"BoundingBox");return[{x:b.x,y:b.y},{x:b.x+b.w,y:b.y},{x:b.x+b.w,y:b.y+b.h},{x:b.x,y:b.y+b.h},{x:b.x,y:b.y}]}},{location:function(){var c,h;lucid.plugin.getProperty(a,"BoundingBox");var e=lucid.plugin.getProperty(a,
"TailWidth"),d=lucid.plugin.getProperty(a,"Side"),m=b();switch(d){case 0:case 2:c=m.x-e;h=m.y;break;case 1:case 3:c=m.x,h=m.y-e}return{x:c-5,y:h-5,w:10,h:10}},moved:function(c){var h=lucid.plugin.getProperty(a,"BoundingBox"),e=lucid.plugin.getProperty(a,"Position"),d=lucid.plugin.getProperty(a,"Side"),m=lucid.plugin.getProperty(a,"RoundCorners"),f=b(),k;switch(d){case 0:case 2:k=f.x-c.x;c=(Math.abs(e-.5)-.5)*h.w+m;h=(.5-Math.abs(e-.5))*h.w-m;k=k<c?c:k>h?h:k;lucid.plugin.getProperty(a,"RoundCorners");
break;case 1:case 3:k=f.y-c.y,c=(Math.abs(e-.5)-.5)*h.h+m,h=(.5-Math.abs(e-.5))*h.h-m,k=k<c?c:k>h?h:k}lucid.plugin.setPropertyIfChanged(a,"TailWidth",k)},path:function(){var b=lucid.plugin.getProperty(a,"BoundingBox"),c=lucid.plugin.getProperty(a,"Side");return[{x:b.x,y:b.y},{x:b.x+b.w,y:b.y},{x:b.x+b.w,y:b.y+b.h},{x:b.x,y:b.y+b.h},{x:b.x,y:b.y}].splice(c,2)}},{location:function(){var b;b=lucid.plugin.getProperty(a,"Side");var c=lucid.plugin.getProperty(a,"Position"),d=lucid.plugin.getProperty(a,
"BoundingBox"),g=lucid.plugin.getProperty(a,"TailRadius"),m=lucid.plugin.getProperty(a,"TailAngle"),f,k;switch(b){case 0:f=d.w*c;k=0-g;break;case 1:f=d.w+g;k=d.h*c;break;case 2:f=d.w*c;k=d.h+g;break;case 3:f=0-g,k=d.h*c}b=lucid.math.Point.rotate({x:d.x+f,y:d.y+k},e(a,b,c,d),Math.PI/180*m);return{x:b.x-5,y:b.y-5,w:10,h:10}},moved:function(c){var e=b();lucid.plugin.getProperty(a,"BoundingBox");var d=0;switch(lucid.plugin.getProperty(a,"Side")){case 0:d=-1*Math.atan2(e.x-c.x,e.y-c.y);break;case 1:d=
Math.atan2(c.y-e.y,c.x-e.x);break;case 2:d=-1*Math.atan2(c.x-e.x,c.y-e.y);break;case 3:d=Math.atan2(e.y-c.y,e.x-c.x)}d=180*d/Math.PI;90<d?d=90:-90>d?d=-90:-5<d&&5>d&&(d=0);c=lucid.math.Point.distance(c,e);lucid.plugin.setPropertyIfChanged(a,"MinLayerPadding",c);lucid.plugin.setPropertyIfChanged(a,"TailRadius",c);lucid.plugin.setPropertyIfChanged(a,"TailAngle",d)}},{location:function(){var b=lucid.plugin.getProperty(a,"BoundingBox"),c=lucid.plugin.getProperty(a,"Side"),e=lucid.plugin.getProperty(a,
"Position"),d=lucid.plugin.getProperty(a,"RoundCorners"),g=lucid.plugin.getProperty(a,"TailWidth");switch(c){case 0:case 2:d=Math.min(d,b.w/2,b.h/2,b.w*(.5-Math.abs(e-.5))-Math.abs(g));break;case 1:case 3:d=Math.min(d,b.w/2,b.h/2,b.h*(.5-Math.abs(e-.5))-Math.abs(g))}return{x:b.x+b.w-d-5,y:b.y-5,w:10,h:10}},moved:function(b){var c=lucid.plugin.getProperty(a,"BoundingBox");lucid.plugin.setProperty(a,"RoundCorners",c.x+c.w-b.x)},path:function(){var b=lucid.plugin.getProperty(a,"BoundingBox"),c=lucid.plugin.getProperty(a,
"Side"),d=lucid.plugin.getProperty(a,"Position"),e=lucid.plugin.getProperty(a,"TailWidth"),g;switch(c){case 0:case 2:g=Math.min(b.w*(.5-Math.abs(d-.5))-Math.abs(e),b.h/2);break;case 1:case 3:g=Math.min(b.h*(.5-Math.abs(d-.5))-Math.abs(e),b.w/2)}return[{x:b.x+b.w-g,y:b.y},{x:b.x+b.w,y:b.y}]}}]},getRenderData:function(a,b){function c(b,g,k,f,v){var n=e(a.id,a.Side,m,d);if(0>p){var r=k;k=v;v=r}f=lucid.math.Point.rotate(f,{x:n.x,y:n.y},Math.PI/180*u);k.Action="line";f.Action="line";v.Action="line";q.splice(b,
g,k,f,v)}var d=a.BoundingBox,f=a.TailRadius,p=a.TailWidth,m=a.Position,u=a.TailAngle,k=a.RoundCorners;"sample"==b?(k=3,f=6,p=3):"preview"==b&&(d.y+=4,d.h-=6,f=10,p=8);switch(a.Side){case 0:case 2:k=Math.min(k,d.w/2,d.h/2,d.w*(.5-Math.abs(m-.5)-Math.abs(p/d.w)));break;case 1:case 3:k=Math.min(k,d.w/2,d.h/2,d.h*(.5-Math.abs(m-.5)-Math.abs(p/d.h)))}var q=[{Action:"move",x:d.x,y:d.y+k},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(d.x,d.y,2*k,2*k,Math.PI,3*Math.PI/2)},{Action:"line",x:d.x+
d.w-k,y:d.y},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(d.x+d.w-2*k,d.y,2*k,2*k,-Math.PI/2,0)},{Action:"line",x:d.x+d.w,y:d.y+d.h-k},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(d.x+d.w-2*k,d.y+d.h-2*k,2*k,2*k,0,Math.PI/2)},{Action:"line",x:d.x+k,y:d.y+d.h},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(d.x,d.y+d.h-2*k,2*k,2*k,Math.PI/2,Math.PI)},{Action:"close"}];switch(a.Side){case 0:c(2,0,{x:d.x+d.w*m-p,y:d.y},{x:d.x+d.w*m,y:d.y-f},{x:d.x+d.w*m+p,y:d.y});
break;case 1:c(4,0,{x:d.x+d.w,y:d.y+d.h*m-p},{x:d.x+d.w+f,y:d.y+d.h*m},{x:d.x+d.w,y:d.y+d.h*m+p});break;case 2:c(6,0,{x:d.x+d.w*m+p,y:d.y+d.h},{x:d.x+d.w*m,y:d.y+d.h+f},{x:d.x+d.w*m-p,y:d.y+d.h});break;case 3:c(8,0,{x:d.x,y:d.y+d.h*m+p},{x:d.x-f,y:d.y+d.h*m},{x:d.x,y:d.y+d.h*m-p})}return[{NoRounding:!0,FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:q}]}})};t.provide("plugin.shapes");t.require("plugin.common.Callout");t.require("plugin.common.TextAreaOverflowUtils");t.require("plugin.common.DocVersionedProps");
var f=function(c,b){var a=lucid.plugin.getProperty(b,"InsetMargin")||0;return lucid.math.Box.safePad(c,-a)},q=function(c,b){var a=lucid.plugin.getProperty(b,"InsetMargin")||0;return lucid.math.Box.safePad(c,a)};lucid.plugin.initBlockClass({className:"RectangleBlock",name:"Rectangle",searchKeywords:["shape","rectangle"],defaultSize:{w:160,h:120},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:function(b){return f(b,c)}});lucid.plugin.registerProperty(c,"TextWrap",
"fit");lucid.plugin.registerProperty(c,"InsetMargin",5)},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(c){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(c,b){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y+a.h},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x,y:a.y},{Action:"close"}]}]}});
lucid.plugin.initBlockClass({className:"IsoscelesTriangleBlock",name:"Isosceles Triangle",searchKeywords:["shape","triangle","isosceles"],defaultSize:{w:160,h:120},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){return{x:b.x+.2*b.w,y:b.y+.4*b.h,w:.6*b.w,h:.6*b.h}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,
"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(c){return[{x:.5,y:0},{x:.25,y:.5},{x:.5,y:1},{x:.75,y:.5}]},getRenderData:function(c,b){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,
Actions:[{Action:"move",x:a.x,y:a.y+a.h},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x+a.w/2,y:a.y},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"RightTriangleBlock",name:"Right Triangle",searchKeywords:["shape","triangle","right"],defaultSize:{w:160,h:120},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){return{x:b.x,y:b.y+.4*b.h,w:.6*b.w,
h:.6*b.h}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(c){return[{x:.501,y:.499},{x:.5,y:1},{x:0,y:.5}]},getRenderData:function(c,
b){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"PentagonBlock",name:"Pentagon",searchKeywords:["shape","pentagon","polygon"],defaultSize:{w:160,h:152},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,
value:function(b){return{x:b.x+.1*b.w,y:b.y+.2*b.h,w:.8*b.w,h:.8*b.h}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(c){return[{x:0,
y:.382},{x:.25,y:.191},{x:.5,y:0},{x:.75,y:.191},{x:1,y:.382},{x:.9045,y:.691},{x:.809,y:1},{x:.5,y:1},{x:.191,y:1},{x:.0955,y:.691}]},getRenderData:function(c,b){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y+.382*a.h},{Action:"line",x:a.x+a.w/2,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+.382*a.h},{Action:"line",x:a.x+.809*a.w,y:a.y+a.h},{Action:"line",x:a.x+.191*a.w,y:a.y+a.h},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"HexagonBlock",
name:"Hexagon",searchKeywords:["shape","hexagon","polygon"],defaultSize:{w:160,h:138},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){return{x:b.x+.1*b.w,y:b.y,w:.8*b.w,h:b.h}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,
c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(c){return[{x:0,y:.5},{x:.125,y:.25},{x:.25,y:0},{x:.5,y:0},{x:.75,y:0},{x:.875,y:.25},{x:1,y:.5},{x:.875,y:.75},{x:.75,y:1},{x:.5,y:1},{x:.25,y:1},{x:.125,y:.75}]},getRenderData:function(c,b){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,
Actions:[{Action:"move",x:a.x,y:a.y+a.h/2},{Action:"line",x:a.x+.25*a.w,y:a.y},{Action:"line",x:a.x+.75*a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h/2},{Action:"line",x:a.x+.75*a.w,y:a.y+a.h},{Action:"line",x:a.x+.25*a.w,y:a.y+a.h},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"OctagonBlock",name:"Octagon",searchKeywords:["shape","octagon","polygon"],defaultSize:{w:160,h:160},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,
value:function(b){return{x:b.x+.145*b.w,y:b.y+.145*b.h,w:.71*b.w,h:.71*b.h}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(c){return[{x:.145,
y:.145},{x:.5,y:0},{x:.855,y:.145},{x:1,y:.5},{x:.855,y:.855},{x:.5,y:1},{x:.145,y:.855},{x:0,y:.5}]},getRenderData:function(c,b){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y+.29*a.h},{Action:"line",x:a.x+.29*a.w,y:a.y},{Action:"line",x:a.x+.71*a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+.29*a.h},{Action:"line",x:a.x+a.w,y:a.y+.71*a.h},{Action:"line",x:a.x+.71*a.w,y:a.y+a.h},{Action:"line",x:a.x+.29*a.w,y:a.y+a.h},
{Action:"line",x:a.x,y:a.y+.71*a.h},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"CrossBlock",name:"Cross",searchKeywords:["shape","cross"],defaultSize:{w:160,h:160},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){return{x:b.x+.1*b.w,y:b.y+.25*b.h,w:.8*b.w,h:.5*b.h}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,
"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5));lucid.plugin.registerProperty(c,"Indent",{x:.25,y:.25})},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(){return[{x:0,y:.5},{x:.5,y:0},{x:1,y:.5},{x:.5,y:1}]},getRenderData:function(c,b){var a=c.BoundingBox,e=c.Indent;return[{FillColor:c.FillColor,
StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y+a.h*e.y},{Action:"line",x:a.x+a.w*e.x,y:a.y+a.h*e.y},{Action:"line",x:a.x+a.w*e.x,y:a.y},{Action:"line",x:a.x+a.w-a.w*e.x,y:a.y},{Action:"line",x:a.x+a.w-a.w*e.x,y:a.y+a.h*e.y},{Action:"line",x:a.x+a.w,y:a.y+a.h*e.y},{Action:"line",x:a.x+a.w,y:a.y+a.h-a.h*e.y},{Action:"line",x:a.x+a.w-a.w*e.x,y:a.y+a.h-a.h*e.y},{Action:"line",x:a.x+a.w-a.w*e.x,y:a.y+a.h},{Action:"line",x:a.x+a.w*e.x,y:a.y+a.h},{Action:"line",x:a.x+a.w*
e.x,y:a.y+a.h-a.h*e.y},{Action:"line",x:a.x,y:a.y+a.h-a.h*e.y},{Action:"close"}]}]},spatialControls:function(c){return[{logAction:"chart.viewport.selection.spatialControls.shapes.crossIndent",location:function(){var b=lucid.plugin.getProperty(c,"BoundingBox"),a=lucid.plugin.getProperty(c,"Indent");return{x:b.x+b.w*a.x-5,y:b.y+b.h*a.y-5,w:10,h:10}},moved:function(b){var a=lucid.plugin.getProperty(c,"BoundingBox");lucid.plugin.setProperty(c,"Indent",{x:(b.x-a.x)/a.w,y:(b.y-a.y)/a.h})},area:function(){var b=
lucid.plugin.getProperty(c,"BoundingBox");return{x:b.x,y:b.y,w:b.w/2-5,h:b.h/2-5}},snap:2}]}});lucid.plugin.initBlockClass({className:"RightArrowBlock",name:"Arrow",searchKeywords:["shape","arrow"],defaultSize:{w:160,h:80},variants:{RightArrow:{tooltip:"Right Arrow",searchKeywords:["shape","arrow","right","east"]},DownArrow:{tooltip:"Down Arrow",searchKeywords:["shape","arrow","down","south"],defaultProperties:function(){return{Rotation:Math.PI/2,TextRotation:-Math.PI/2}}},LeftArrow:{tooltip:"Left Arrow",
searchKeywords:["shape","arrow","left","west"],defaultProperties:function(){return{Rotation:Math.PI,TextRotation:-Math.PI}}},UpArrow:{tooltip:"Up Arrow",searchKeywords:["shape","arrow","up","north"],defaultProperties:function(){return{Rotation:3*Math.PI/2,TextRotation:3*-Math.PI/2}}}},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){var a=lucid.plugin.getProperty(c,"Notch"),
e=lucid.plugin.getProperty(c,"Head")*b.h;return{x:b.x,y:b.y+a,w:b.w-.5*e,h:b.h-2*a}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5));lucid.plugin.registerProperty(c,"Notch",.25);lucid.plugin.registerProperty(c,"Head",.5);lucid.plugin.registerProperty(c,
"TextRotation",0,null,function(b,a){lucid.plugin.updateBlockTextArea(c,"Text",{rotation:a})})},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(){return[]},getAnchorPoints:function(){return[{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(c,b){var a=c.BoundingBox,e=c.Notch*a.h,d=c.Head*a.h;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y+e},{Action:"line",x:a.x+a.w-d,y:a.y+e},
{Action:"line",x:a.x+a.w-d,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h/2},{Action:"line",x:a.x+a.w-d,y:a.y+a.h},{Action:"line",x:a.x+a.w-d,y:a.y+a.h-e},{Action:"line",x:a.x,y:a.y+a.h-e},{Action:"close"}]}]},spatialControls:function(c){return[{logAction:"chart.viewport.selection.spatialControls.shapes.arrowHead",location:function(){var b=lucid.plugin.getProperty(c,"BoundingBox"),a=lucid.plugin.getProperty(c,"Head")*b.h,e=lucid.plugin.getProperty(c,"Notch")*b.h;return{x:b.x+b.w-a-5,y:b.y+e-5,w:10,h:10}},
moved:function(b){var a=lucid.plugin.getProperty(c,"BoundingBox");lucid.plugin.setProperty(c,"Head",(a.x+a.w-b.x)/a.h);lucid.plugin.setProperty(c,"Notch",(b.y-a.y)/a.h)},area:function(){var b=lucid.plugin.getProperty(c,"BoundingBox");return{x:b.x+10,y:b.y,w:b.w-10,h:b.h/2-5}},snap:4}]}});lucid.plugin.initBlockClass({className:"DoubleArrowBlock",name:"Double Arrow",searchKeywords:["shape","arrow"],defaultSize:{w:160,h:80},variants:{EWArrow:{tooltip:"Double Arrow EW",searchKeywords:"shape arrow right left east west ew eastwest".split(" ")},
NSArrow:{tooltip:"Double Arrow NS",searchKeywords:"shape arrow down up south north ns northsouth".split(" "),defaultProperties:function(){return{Rotation:Math.PI/2,TextRotation:-Math.PI/2}}}},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){var a=lucid.plugin.getProperty(c,"Notch")*b.h,e=lucid.plugin.getProperty(c,"Head")*b.h;return{x:b.x,y:b.y+a,w:b.w-.5*e,h:b.h-2*a}}},
{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5));lucid.plugin.registerProperty(c,"Notch",.25);lucid.plugin.registerProperty(c,"Head",.5);lucid.plugin.registerProperty(c,"TextRotation",0,null,function(b,a){lucid.plugin.updateBlockTextArea(c,
"Text",{rotation:a})})},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(){return[]},getAnchorPoints:function(){return[{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(c,b){var a=c.BoundingBox,e=c.Notch*a.h,d=c.Head*a.h;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y+a.h/2},{Action:"line",x:a.x+d,y:a.y},{Action:"line",x:a.x+d,y:a.y+e},{Action:"line",x:a.x+a.w-d,y:a.y+e},{Action:"line",
x:a.x+a.w-d,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h/2},{Action:"line",x:a.x+a.w-d,y:a.y+a.h},{Action:"line",x:a.x+a.w-d,y:a.y+a.h-e},{Action:"line",x:a.x+d,y:a.y+a.h-e},{Action:"line",x:a.x+d,y:a.y+a.h},{Action:"close"}]}]},spatialControls:function(c){return[{logAction:"chart.viewport.selection.spatialControls.shapes.arrowHead",location:function(){var b=lucid.plugin.getProperty(c,"BoundingBox"),a=lucid.plugin.getProperty(c,"Head")*b.h,e=lucid.plugin.getProperty(c,"Notch")*b.h;return{x:b.x+b.w-a-
5,y:b.y+e-5,w:10,h:10}},moved:function(b){var a=lucid.plugin.getProperty(c,"BoundingBox");lucid.plugin.setProperty(c,"Head",(a.x+a.w-b.x)/a.h);lucid.plugin.setProperty(c,"Notch",(b.y-a.y)/a.h)},area:function(){var b=lucid.plugin.getProperty(c,"BoundingBox");return{x:b.x+b.w/2+10,y:b.y,w:b.w/2-15,h:b.h/2-5}},snap:4}]}});lucid.plugin.initBlockClass({className:"CloudBlock",name:"Cloud",searchKeywords:["shape","cloud"],defaultSize:{w:160,h:120},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",
value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){return{x:b.x+.2*b.w,y:b.y+.1*b.h,w:.6*b.w,h:.8*b.h}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,
q),getLinkPoints:function(c){return[{x:0,y:.5},{x:.24,y:.07},{x:.6,y:.01},{x:.97,y:.3},{x:.955,y:.85},{x:.6,y:1},{x:.25,y:.925}]},getRenderData:function(c,b){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+.15*a.w,y:a.y+.7*a.h},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x,a.y+.3*a.h,.3*a.w,.4*a.h,.5*Math.PI,1.4*Math.PI)},{Action:"curve",Control:[{x1:a.x+.1*a.w,y1:a.y+.05*a.h,x2:a.x+.35*a.w,y2:a.y+0*a.h,
x3:a.x+.45*a.w,y3:a.y+.1*a.h},{x1:a.x+.5*a.w,y1:a.y+-.05*a.h,x2:a.x+.75*a.w,y2:a.y+0*a.h,x3:a.x+.75*a.w,y3:a.y+.15*a.h},{x1:a.x+.9*a.w,y1:a.y+.1*a.h,x2:a.x+1.05*a.w,y2:a.y+.3*a.h,x3:a.x+.95*a.w,y3:a.y+.55*a.h},{x1:a.x+1.05*a.w,y1:a.y+.75*a.h,x2:a.x+.95*a.w,y2:a.y+1*a.h,x3:a.x+.75*a.w,y3:a.y+.9*a.h},{x1:a.x+.7*a.w,y1:a.y+1.03*a.h,x2:a.x+.5*a.w,y2:a.y+1.03*a.h,x3:a.x+.45*a.w,y3:a.y+.9*a.h},{x1:a.x+.35*a.w,y1:a.y+1*a.h,x2:a.x+.15*a.w,y2:a.y+.95*a.h,x3:a.x+.15*a.w,y3:a.y+.7*a.h}]},{Action:"close"}]}]}});
lucid.plugin.initBlockClass({className:"HeartBlock",name:"Heart",searchKeywords:["shape","heart"],defaultSize:{w:160,h:160},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){return{x:b.x+.1*b.w,y:b.y+.15*b.h,w:.8*b.w,h:.55*b.h}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||0,hideOverflow:!0}}},
{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(c){return[{x:.5,y:.2},{x:1,y:.28},{x:.5,y:1},{x:0,y:.28}]},getRenderData:function(c,b){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+.5*a.w,y:a.y+
.2*a.h},{Action:"curve",Control:[{x1:a.x+.52*a.w,y1:a.y+.1*a.h,x2:a.x+.63*a.w,y2:a.y+0*a.h,x3:a.x+.75*a.w,y3:a.y+0*a.h},{x1:a.x+.9*a.w,y1:a.y+0*a.h,x2:a.x+1*a.w,y2:a.y+.1*a.h,x3:a.x+1*a.w,y3:a.y+.28*a.h},{x1:a.x+1*a.w,y1:a.y+.55*a.h,x2:a.x+.65*a.w,y2:a.y+.67*a.h,x3:a.x+.5*a.w,y3:a.y+1*a.h},{x1:a.x+.35*a.w,y1:a.y+.67*a.h,x2:a.x+0*a.w,y2:a.y+.55*a.h,x3:a.x+0*a.w,y3:a.y+.28*a.h},{x1:a.x+0*a.w,y1:a.y+.1*a.h,x2:a.x+.1*a.w,y2:a.y+0*a.h,x3:a.x+.25*a.w,y3:a.y+0*a.h},{x1:a.x+.37*a.w,y1:a.y+0*a.h,x2:a.x+.48*
a.w,y2:a.y+.1*a.h,x3:a.x+.5*a.w,y3:a.y+.2*a.h}]},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"StarBlock",name:"Star",searchKeywords:["shape","star","polygon"],defaultSize:{w:160,h:152},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){return{x:b.x+.1*b.w,y:b.y+.2*b.h,w:.8*b.w,h:.8*b.h}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])})},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,
q),getLinkPoints:function(c){return[{x:0,y:.382},{x:.5,y:0},{x:1,y:.382},{x:.809,y:1},{x:.191,y:1}]},getRenderData:function(c,b){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y+.382*a.h},{Action:"line",x:a.x+.3819*a.w,y:a.y+.382*a.h},{Action:"line",x:a.x+.5*a.w,y:a.y},{Action:"line",x:a.x+.618*a.w,y:a.y+.382*a.h},{Action:"line",x:a.x+a.w,y:a.y+.382*a.h},{Action:"line",x:a.x+.691*a.w,y:a.y+.6181*a.h},{Action:"line",
x:a.x+.809*a.w,y:a.y+a.h},{Action:"line",x:a.x+.5*a.w,y:a.y+.764*a.h},{Action:"line",x:a.x+.191*a.w,y:a.y+a.h},{Action:"line",x:a.x+.309*a.w,y:a.y+.618*a.h},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"ShapeCircleBlock",name:"Circle",searchKeywords:["shape","circle"],defaultSize:{w:160,h:160},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){return{x:b.x,
y:b.y,w:b.w,h:b.h}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(c,
b){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+a.w,y:a.y+a.h/2},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x,a.y,a.w,a.h,0,2*Math.PI)},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"ShapePolyStarBlock",name:"Star",searchKeywords:["shape","star"],defaultSize:{w:160,h:160},onInit:function(c){lucid.plugin.setPropertyIfChanged(c,"InsetMargin",5);lucid.plugin.registerProperty(c,"NumberPoints",
5);lucid.plugin.registerProperty(c,"InnerRadius",.4);lucid.plugin.registerProperty(c,"TextWrap",1);lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){var a=lucid.plugin.getProperty(c,"ShapePolyStarBlock");return{x:b.x+b.w/2*(1-a),y:b.y+b.h/2*(1-a),w:b.w*a,h:b.h*a}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||
0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),spatialControls:function(c){function b(a,b,c,g){var f=c.x+c.w/2,h=c.y+c.h/2;a=1.5*Math.PI+a*Math.PI*2/b;var n=c.w/2;c=c.h/2;null!=g&&(a+=1*Math.PI/b,n*=g,c*=g);return{x:f+Math.cos(a)*n,y:h+Math.sin(a)*c}}function a(a){for(;0>
a;)a+=2*Math.PI;for(;a>2*Math.PI;)a-=2*Math.PI;return Math.min(Math.max(Math.round(1/(a/(2*Math.PI))),3),25)}return[{location:function(){var a=lucid.plugin.getProperty(c,"BoundingBox"),d=lucid.plugin.getProperty(c,"NumberPoints"),a=b(1,d,a);return{x:a.x-5,y:a.y-5,w:10,h:10}},moved:function(b){lucid.plugin.getProperty(c,"NumberPoints");var d=lucid.plugin.getProperty(c,"BoundingBox"),d=lucid.math.Box.center(d);lucid.plugin.setProperty(c,"NumberPoints",a(Math.atan2(b.y-d.y,b.x-d.x)-1.5*Math.PI))},path:function(){for(var a=
lucid.plugin.getProperty(c,"BoundingBox"),d=lucid.plugin.getProperty(c,"NumberPoints"),l=[],g=0;g<d;g++)l.push(b(g,d,a));return l}},{location:function(){var a=lucid.plugin.getProperty(c,"BoundingBox"),d=lucid.plugin.getProperty(c,"NumberPoints"),l=lucid.plugin.getProperty(c,"InnerRadius"),a=b(0,d,a,l);return{x:a.x-5,y:a.y-5,w:10,h:10}},moved:function(a){var d=lucid.plugin.getProperty(c,"NumberPoints"),l=lucid.plugin.getProperty(c,"BoundingBox"),d=b(0,d,l,1),l=lucid.math.Box.center(l),d=lucid.math.Point.distance(l,
d);a=lucid.math.Point.distance(l,a);lucid.plugin.setProperty(c,"InnerRadius",a/d)},path:function(){var a=lucid.plugin.getProperty(c,"BoundingBox"),d=lucid.plugin.getProperty(c,"NumberPoints");return[lucid.math.Box.center(a),b(0,d,a,1)]}}]},getRenderData:function(c,b){var a=c.BoundingBox,e=c.NumberPoints,d=c.InnerRadius,l=[],g=a.x+a.w/2,f=a.y+a.h/2,h=Math.PI/e,n=1.5*Math.PI,p,m=a.w/2,u=a.h/2,k=m*d,d=u*d;l.push({Action:"move",x:g,y:a.y});for(var q=0;q<2*e-1;q++)n-=h,0==q%2?(a=k,p=d):(a=m,p=u),l.push({Action:"line",
x:g+Math.cos(n)*a,y:f+Math.sin(n)*p});l.push({Action:"close"});return[{FillColor:c.FillColor,StrokeLocation:c.StrokeLocation,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:l}]}});lucid.plugin.initBlockClass({className:"ShapeDiamondBlock",name:"Diamond",searchKeywords:["shape","diamond"],defaultSize:{w:160,h:160},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:plugin.common.DocVersionedProps.getValueForDocVersion([{docVersionInstated:0,value:function(b){return{x:b.x,
y:b.y,w:b.w,h:b.h}}},{docVersionInstated:2,value:function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(c,"InsetMargin")||0,hideOverflow:!0}}},{docVersionInstated:5,value:function(b){return f(b,c)}}])});1<r()&&(lucid.plugin.registerProperty(c,"TextWrap","fit"),lucid.plugin.registerProperty(c,"InsetMargin",5))},onTextAreaOverflowChange:plugin.common.TextAreaOverflowUtils.getOnOverflowCallback(f,q),getLinkPoints:function(){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(c,
b){var a=c.BoundingBox,e=a.x+a.w/2,d=a.y+a.h/2;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:e,y:a.y},{Action:"line",x:a.x+a.w,y:d},{Action:"line",x:e,y:a.y+a.h},{Action:"line",x:a.x,y:d},{Action:"close"}]}]}});plugin.common.Callout.createBlock("CalloutSquareBlock","Callout","Callout");q="RectangleBlock IsoscelesTriangleBlock RightTriangleBlock PentagonBlock HexagonBlock OctagonBlock CrossBlock CloudBlock HeartBlock ShapeCircleBlock ShapePolyStarBlock ShapeDiamondBlock".split(" ");
lucid.coreEx.includeCoreExFeatures()&&lucid.plugin.createNextBlockGroup(q);lucid.plugin.createExchangeGroup(q);lucid.plugin.createToolGroups({Shapes:["RectangleBlock","IsoscelesTriangleBlock","RightTriangleBlock","PentagonBlock","HexagonBlock","OctagonBlock","CrossBlock","CloudBlock","HeartBlock",{className:"RightArrowBlock",variant:"RightArrow"},{className:"RightArrowBlock",variant:"DownArrow"},{className:"RightArrowBlock",variant:"LeftArrow"},{className:"RightArrowBlock",variant:"UpArrow"},{className:"DoubleArrowBlock",
variant:"EWArrow"},{className:"DoubleArrowBlock",variant:"NSArrow"},"CalloutSquareBlock","ShapeCircleBlock","ShapePolyStarBlock","ShapeDiamondBlock"]});lucid.plugin.onActivate(function(){lucid.plugin.allowShadowSharing("RectangleBlock",!0);lucid.plugin.allowShadowSharing("IsoscelesTriangleBlock",!0);lucid.plugin.allowShadowSharing("RightTriangleBlock",!0);lucid.plugin.allowShadowSharing("PentagonBlock",!0);lucid.plugin.allowShadowSharing("HexagonBlock",!0);lucid.plugin.allowShadowSharing("OctagonBlock",
!0);lucid.plugin.allowShadowSharing("CloudBlock",!0);lucid.plugin.allowShadowSharing("HeartBlock",!0)});lucid.plugin.initBlockClass({className:"LeftArrowBlock",name:"LeftArrow",defaultSize:{w:160,h:80},noSearch:!0,onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:function(b){var a=.25*b.h,c=.5*(b.h>b.w?b.w:b.h);return{x:b.x+.5*c,y:b.y+a,w:b.w-.5*c,h:b.h-2*a}}})},getLinkPoints:function(c){return[]},getAnchorPoints:function(){return[{x:1,y:.5},{x:0,y:.5}]},getRenderData:function(c,
b){var a=c.BoundingBox,e=.25*a.h,d=.5*(a.h>a.w?a.w:a.h);return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y+a.h/2},{Action:"line",x:a.x+d,y:a.y},{Action:"line",x:a.x+d,y:a.y+e},{Action:"line",x:a.x+a.w,y:a.y+e},{Action:"line",x:a.x+a.w,y:a.y+a.h-e},{Action:"line",x:a.x+d,y:a.y+a.h-e},{Action:"line",x:a.x+d,y:a.y+a.h},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"UpArrowBlock",name:"Up Arrow",defaultSize:{w:80,h:160},noSearch:!0,
onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:function(b){var a=.25*b.w,c=.5*(b.h>b.w?b.w:b.h);return{x:b.x+a,y:b.y+.5*c,w:b.w-2*a,h:b.h-.5*c}}})},getLinkPoints:function(){return[]},getAnchorPoints:function(){return[{x:.5,y:1},{x:.5,y:0}]},getRenderData:function(c,b){var a=c.BoundingBox,e=.25*a.w,d=.5*(a.h>a.w?a.w:a.h);return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+a.w/2,y:a.y},{Action:"line",x:a.x+
a.w,y:a.y+d},{Action:"line",x:a.x+a.w-e,y:a.y+d},{Action:"line",x:a.x+a.w-e,y:a.y+a.h},{Action:"line",x:a.x+e,y:a.y+a.h},{Action:"line",x:a.x+e,y:a.y+d},{Action:"line",x:a.x,y:a.y+d},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"DownArrowBlock",name:"DownArrow",defaultSize:{w:80,h:160},noSearch:!0,onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:function(b){var a=.25*b.w;return{x:b.x+a,y:b.y,w:b.w-2*a,h:b.h-.25*(b.h>b.w?b.w:b.h)}}})},getLinkPoints:function(){return[]},
getAnchorPoints:function(){return[{x:.5,y:0},{x:.5,y:1}]},getRenderData:function(c,b){var a=c.BoundingBox,e=.25*a.w,d=.5*(a.h>a.w?a.w:a.h);return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+e,y:a.y},{Action:"line",x:a.x+a.w-e,y:a.y},{Action:"line",x:a.x+a.w-e,y:a.y+a.h-d},{Action:"line",x:a.x+a.w,y:a.y+a.h-d},{Action:"line",x:a.x+a.w/2,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h-d},{Action:"line",x:a.x+e,y:a.y+a.h-d},{Action:"close"}]}]}});(function(){function c(a){return.3*
1.5*Math.min(a.h,a.w)}function b(a,b,d,l,g,f){b||(b=lucid.plugin.getProperty(a,"Side"));d||(d=lucid.plugin.getProperty(a,"Position")/100);l||(l=lucid.plugin.getProperty(a,"BoundingBox"));g||c(l);f||(f=.2*l.w);var h,n;a=f/2;switch(b){case 0:h=(l.w-f)*d+a;n=0;break;case 1:h=l.w;n=(l.h-f)*d+a;break;case 2:h=(l.w-f)*d+a;n=l.h;break;case 3:h=0,n=(l.h-f)*d+a}return{x:l.x+h,y:l.y+n}}lucid.plugin.initBlockClass({className:"CalloutBlock",name:"Callout",searchKeywords:"shape tooltip infotip callout call out tip".split(" "),
defaultSize:{w:240,h:80},minWidth:120,minHeight:40,noSearch:!0,onInit:function(a){lucid.plugin.addBlockTextArea(a,{id:"Tip",value:"Callout",getBoundingBox:function(b){return w(b,function(a){return{x:a.x+.1*a.w,y:a.y+.1*a.h,w:.8*a.w,h:.8*a.h}},function(b){return{x:b.x,y:b.y,w:b.w,h:b.h,fitShape:lucid.plugin.getProperty(a,"InsetMargin")||0,hideOverflow:!0}})}});1<r()&&(lucid.plugin.registerProperty(a,"TextWrap","fit"),lucid.plugin.registerProperty(a,"InsetMargin",5));var b=lucid.plugin.getProperty(a,
"BoundingBox");lucid.plugin.registerProperty(a,"MinLayerPadding",c(b));lucid.plugin.registerProperty(a,"TailAngle",-40);lucid.plugin.registerProperty(a,"Side",0);lucid.plugin.registerProperty(a,"Position",25)},getOffsetProperties:function(a,b,d){b=lucid.plugin.defaultOffsetProperties(a,b,d);d=c(b[a].BoundingBox);b[a].MinLayerPadding=d;return b},spatialControls:function(a){function e(c,e,g,f,h){var n=Array.prototype.splice.call(arguments);n.unshift(a);return b.apply(null,n)}if(lucid.plugin.getProperty(a,
"BoundingBox"))return[{logAction:"chart.viewport.selection.spatialControls.shapes.calloutTail",location:function(){var a=e();return{x:a.x-5,y:a.y-5,w:10,h:10}},moved:function(b){var c=lucid.plugin.getProperty(a,"BoundingBox"),e=.2*c.w,f=e/2,h=0;b.x>=c.x+c.w?h=1:b.y>=c.y+c.h?h=2:b.x<=c.x&&(h=3);var n=0;switch(h){case 0:case 2:n=(b.x-c.x-f)/(c.w-e);break;case 1:case 3:n=(b.y-c.y-f)/(c.h-e)}n=Math.round(100*Math.min(1,Math.max(0,n)));45<n&&55>n&&(n=50);lucid.plugin.setPropertyIfChanged(a,"Side",h);lucid.plugin.setPropertyIfChanged(a,
"Position",n)},path:function(){var b=lucid.plugin.getProperty(a,"BoundingBox");return[{x:b.x,y:b.y},{x:b.x+b.w,y:b.y},{x:b.x+b.w,y:b.y+b.h},{x:b.x,y:b.y+b.h},{x:b.x,y:b.y}]}},{location:function(){var d;d=lucid.plugin.getProperty(a,"Side");var e=lucid.plugin.getProperty(a,"Position")/100,g=lucid.plugin.getProperty(a,"BoundingBox"),f=c(g),h=.2*g.w,n=lucid.plugin.getProperty(a,"TailAngle"),p,m,q=h/2;switch(d){case 0:p=(g.w-h)*e+q;m=0-f;break;case 1:p=g.w+f;m=(g.h-h)*e+q;break;case 2:p=(g.w-h)*e+q;m=
g.h+f;break;case 3:p=0-f,m=(g.h-h)*e+q}d=lucid.math.Point.rotate({x:g.x+p,y:g.y+m},b(a,d,e,g,f,h),Math.PI/180*n);return{x:d.x-5,y:d.y-5,w:10,h:10}},moved:function(b){var c=e();lucid.plugin.getProperty(a,"BoundingBox");var g=0;switch(lucid.plugin.getProperty(a,"Side")){case 0:g=-1*Math.atan2(c.x-b.x,c.y-b.y);break;case 1:g=Math.atan2(b.y-c.y,b.x-c.x);break;case 2:g=-1*Math.atan2(b.x-c.x,b.y-c.y);break;case 3:g=Math.atan2(c.y-b.y,c.x-b.x)}g=Math.round(180*g/Math.PI);80<g?g=80:-80>g?g=-80:-5<g&&5>g&&
(g=0);lucid.plugin.setPropertyIfChanged(a,"TailAngle",g)}}]},getRenderData:function(a,e){function d(c,d,e,g,k){var n=b(a.id,a.Side,p,f,q,h);r.splice(c,d,e,lucid.math.Point.rotate(g,{x:n.x-f.x,y:n.y-f.y},Math.PI/180*m),k)}var f=a.BoundingBox,g=a.LineWidth,q=c(f),h=.2*f.w,n=h/2,p=a.Position/100,m=a.TailAngle||0,r=[{x:0,y:0},{x:f.w,y:0},{x:f.w,y:f.h},{x:0,y:f.h}];switch(a.Side){case 0:d(1,0,{x:(f.w-h)*p,y:0},{x:(f.w-h)*p+n,y:-q},{x:(f.w-h)*p+h,y:0});break;case 1:d(2,0,{x:f.w,y:(f.h-h)*p},{x:f.w+q,y:(f.h-
h)*p+n},{x:f.w,y:(f.h-h)*p+h});break;case 2:d(3,0,{x:(f.w-h)*p+h,y:f.h},{x:(f.w-h)*p+n,y:f.h+q},{x:(f.w-h)*p,y:f.h});break;case 3:d(4,0,{x:0,y:(f.h-h)*p+h},{x:-q,y:(f.h-h)*p+n},{x:0,y:(f.h-h)*p})}var k=[];lucid.array.forEach(r,function(a,b){k.push({Action:0==b?"move":"line",x:f.x+a.x,y:f.y+a.y})});k.push({Action:"close"});return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:g,Actions:k}]}})})();lucid.plugin.initBlockClass({className:"DogEarNoteBlock",name:"Dog Ear Note",searchKeywords:[],
defaultSize:{w:140,h:140},noSearch:!0,onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:function(b){var a=.2*(b.h>b.w?b.w:b.h);return{x:b.x+.5*a,y:b.y,w:b.w-a,h:b.h-.5*a}}})},getLinkPoints:function(c){return[{x:.5,y:0},{x:1,y:.5},{x:.5,y:1},{x:0,y:.5}]},getRenderData:function(c,b){var a=c.BoundingBox,e=.2*(a.h>a.w?a.w:a.h),d=lucid.color.darken(c.FillColor,.3);return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,
y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h-e},{Action:"line",x:a.x+a.w-e,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]},{FillColor:d,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+a.w,y:a.y+a.h-e},{Action:"line",x:a.x+a.w-e,y:a.y+a.h},{Action:"line",x:a.x+a.w-.8*e,y:a.y+a.h-.8*e},{Action:"close"}]}]}})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/shapes.js.map
};
