pluginFn['/js/plugins/v2/table.js'] = function(lucid, window) {
	(function(){function p(){return lucid.array.filter(lucid.plugin.getSelection(),function(a){return"DefaultTableBlock"==lucid.plugin.getBlockClassName(a)})}function v(a){var e=lucid.plugin.getProperty(a,"SelectedCells",!0),b=lucid.object.some(e,function(a){return a});a=u(a);b&&(a=lucid.object.filter(a,function(a,b){return e[b]}));return a}function M(){var a=p();lucid.array.forEach(a,function(a){var b=v(a),c=null;lucid.object.forEach(b,function(a){null==c?c=a:a.col<c.col&&(c=a)});A(a,lucid.plugin.getAllProperties(a),
c,!0)})}function N(){var a=p();lucid.array.forEach(a,function(a){var b=v(a),c=null;lucid.object.forEach(b,function(a){null==c?c=a:a.col+a.size.w>c.col+c.size.w&&(c=a)});A(a,lucid.plugin.getAllProperties(a),c,!1)})}function B(){var a=p();return lucid.array.every(a,function(a){return 30<=lucid.plugin.getProperty(a,"Cols")})}function O(){var a=p();lucid.array.forEach(a,function(a){var b=v(a),c=null;lucid.object.forEach(b,function(a){null==c?c=a:a.row<c.row&&(c=a)});C(a,lucid.plugin.getAllProperties(a),
c,!0)})}function P(){var a=p();lucid.array.forEach(a,function(a){var b=v(a),c=null;lucid.object.forEach(b,function(a){null==c?c=a:a.row+a.size.h>c.row+c.size.h&&(c=a)});C(a,lucid.plugin.getAllProperties(a),c,!1)})}function D(){var a=p();return lucid.array.every(a,function(a){return 60<=lucid.plugin.getProperty(a,"Rows")})}function Q(){if(G()){var a=p();lucid.array.forEach(a,function(a){var b=lucid.object.getValues(v(a));H(a,lucid.plugin.getAllProperties(a),b[0].row);t(a,{})})}}function G(){var a=
p(),e=!0;lucid.array.forEach(a,function(a){a=lucid.object.getValues(v(a));if(0==a.length)e=!1;else{var c=a[0].row;lucid.array.every(a,function(a){return a.row==c})||(e=!1)}});return e}function R(){if(I()){var a=p();lucid.array.forEach(a,function(a){var b=lucid.object.getValues(v(a));J(a,lucid.plugin.getAllProperties(a),b[0].col);t(a,{})})}}function I(){var a=p(),e=!0;lucid.array.forEach(a,function(a){a=lucid.object.getValues(v(a));if(0==a.length)e=!1;else{var c=a[0].col;lucid.array.every(a,function(a){return a.col==
c})||(e=!1)}});return e}function S(){if(!K()){var a=p();lucid.array.forEach(a,function(a){var b,c;if(T(a)){for(var f=lucid.plugin.getProperty(a,"SelectedCells",!0),h=lucid.plugin.getProperty(a,"Rows"),g=lucid.plugin.getProperty(a,"Cols"),d,k=0;k<h;k++)for(var l=0;l<g;l++)f[k+","+l]&&(d||(d={r:k,c:l}),b=k,c=l);lucid.plugin.setPropertyIfChanged(a,"CellSize_"+d.r+","+d.c,{w:c-d.c+1,h:b-d.r+1})}})}}function K(){var a=p();return!lucid.array.every(a,function(a){return T(a)})}function U(){if(!L()){var a=
p();lucid.array.forEach(a,function(a){for(var b=lucid.plugin.getProperty(a,"SelectedCells",!0),c=lucid.plugin.getProperty(a,"Rows"),f=lucid.plugin.getProperty(a,"Cols"),h=0;h<c;h++)for(var g=0;g<f;g++)if(b[h+","+g]){var d=lucid.plugin.getProperty(a,"CellSize_"+h+","+g);1==d.w&&1==d.h||lucid.plugin.setProperty(a,"CellSize_"+h+","+g,{w:1,h:1})}})}}function L(){var a=p();return!lucid.array.every(a,function(a){return Y(a)})}function Y(a){var e=lucid.plugin.getProperty(a,"SelectedCells",!0);return lucid.object.some(e,
function(b,c){if(b){var f=lucid.plugin.getProperty(a,"CellSize_"+c);return 1<f.w||1<f.h}})}function T(a){var e,b,c=lucid.plugin.getProperty(a,"SelectedCells",!0),f=lucid.plugin.getProperty(a,"Rows"),h=lucid.plugin.getProperty(a,"Cols"),g;if(!lucid.object.some(c,function(a){return a}))return!1;for(var d=0;d<f;d++)for(var k=0;k<h;k++)c[d+","+k]&&(g||(g={r:d,c:k}),e=d,b=k);if(!g||g.r==e&&g.c==b)return!1;a=lucid.plugin.getProperty(a,"CellSize_"+g.r+","+g.c);if(g.r+a.h-1==e&&g.c+a.w-1==b)return!1;for(d=
0;d<f;d++)for(k=0;k<h;k++)if(d>=g.r&&d<=e&&k>=g.c&&k<=b){if(!c[d+","+k])return!1}else if(c[d+","+k])return!1;return!0}function u(a,e){function b(a,d,b){for(var g=0,c=0;c<b;c++)g+=d[c+a];return Math.round(g)}if(y[a])return y[a];e=e||lucid.plugin.getAllProperties(a);if(!e)return{};for(var c=e.ColWidths,f=e.RowHeights,h=e.Rows,g=e.Cols,d={},k=[],l=0;l<h;l++){k.push([]);for(var m=0;m<g;m++)k[l].push(!1)}for(var r=0,q=0,l=0;l<h;l++){for(m=0;m<g;m++){if(!k[l][m]){var n=e["CellSize_"+l+","+m];if(!n)return d;
k[l][m]=!0;if(1<n.w||1<n.h)for(var E=0;E<n.w&&E+m<g;E++)for(var w=0;w<n.h&&w+l<h;w++)k[l+w][m+E]=!0;d[l+","+m]={x:r,y:q,w:b(m,c,n.w),h:b(l,f,n.h),row:l,col:m,size:n}}r+=c[m]}r=0;q+=f[l]}y[a]=d;setTimeout(function(){y[a]=null},0);return d}function Z(){lucid.plugin.getDescendants(lucid.plugin.getActivePageId()).forEach(function(a){if("DefaultTableBlock"==lucid.plugin.getBlockClassName(a)){var e=lucid.plugin.getProperty(a,"SelectedCells",!0);lucid.object.some(e,function(a){return a})&&t(a,{})}})}var z=
{global:this,provide:function(a){a=a.split(".");z.global[a[0]]=z.global[a[0]]||{};var e=z.global[a[0]];a.slice(1).reduce(function(a,c){a[c]||(a[c]={});return a[c]},e)},require:function(){},inherits:function(a,e){function b(){}b.prototype=e.prototype;a.superClass_=e.prototype;a.prototype=new b;a.prototype.constructor=a;a.base=function(a,b,h){var g=Array.prototype.slice.call(arguments,2);return e.prototype[b].apply(a,g)}},base:function(a,e,b){var c=arguments.callee.caller;if(z.STRICT_MODE_COMPATIBLE||
z.DEBUG&&!c)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(c.superClass_)return c.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),h=!1,g=a.constructor;g;g=g.superClass_&&g.superClass_.constructor)if(g.prototype[e]===c)h=!0;else if(h)return g.prototype[e].apply(a,f);if(a[e]===c)return a.constructor.prototype[e].apply(a,
f);throw Error("goog.base called from a method of one name to a method of a different name");}};z.provide("plugin.table");if(!lucid.newEditor||!lucid.abTest.shouldShowAdvancedOptionsDrawer())lucid.plugin.onDocumentLoaded(function(){function a(a,b){a=lucid.array.filter(a,function(a){return"DefaultTableBlock"==lucid.plugin.getBlockClassName(a)});var g=lucid.plugin.getProperty(a[0],b);lucid.array.forEach(a,function(a){lucid.plugin.getProperty(a,b)!=g&&(g=" ")});return g}function e(a){return function(b,
g){if(!g){var d=p();lucid.array.forEach(d,function(d){lucid.plugin.setProperty(d,a,b)})}}}function b(a){return function(b,g){if(!g){var d=p();lucid.array.forEach(d,function(d){lucid.plugin.setProperty(d,a,b);if(!lucid.plugin.getProperty(d,"BandedRows")&&!lucid.plugin.getProperty(d,"BandedCols")){var g=lucid.object.filter(lucid.plugin.getAllProperties(d),function(a,d){return-1<d.indexOf("NoBand")}),c;for(c in g)lucid.plugin.setPropertyIfChanged(d,c,!1)}})}}}var c=lucid.template.builder();c.addGrid({width:5,
content:{text:"Rows:",classes:"crop ralign"}});c.openGrid({width:3});c.addInput({type:"spinner",min:1,max:60,step:1,value:3,defaultVal:" ",onChange:e("Rows"),checkUpdate:function(b,c){return{value:a(b,"Rows")}}});c.close();c.clear();c.spacer();c.addGrid({width:5,content:{text:"Columns:",classes:"crop ralign"}});c.openGrid({width:3});c.addInput({type:"spinner",min:1,max:30,step:1,value:3,defaultVal:" ",onChange:e("Cols"),checkUpdate:function(b,c){return{value:a(b,"Cols")}}});c.close();c.clear();c.spacer();
c.addGrid({width:5,content:{text:"Insert:",classes:"crop ralign"}});c.openGrid({width:6});c.addInput({type:"buttonset",checkUpdate:function(){this.input.refresh()},buttons:[{icon:"add-col-left",action:M,disabled:B,logAction:"plugin.tables.contextPanel.add.col.left",tooltip:"Add Column Left"},{icon:"add-col-right",action:N,disabled:B,logAction:"plugin.tables.contextPanel.add.col.right",tooltip:"Add Column Right"},{icon:"add-row-top",action:O,disabled:D,logAction:"plugin.tables.contextPanel.add.row.above",
tooltip:"Add Row Above"},{icon:"add-row-bottom",action:P,disabled:D,logAction:"plugin.tables.contextPanel.add.row.below",tooltip:"Add Row Below"}]});c.close();c.clear();c.spacer();c.addGrid({width:5,content:{text:"Delete:",classes:"crop ralign"}});c.openGrid({width:6});c.addInput({type:"buttonset",checkUpdate:function(){this.input.refresh()},buttons:[{icon:"del-col",action:R,disabled:function(){return!I()},logAction:"plugin.tables.contextPanel.delete.col",tooltip:"Delete Column"},{icon:"del-row",
action:Q,disabled:function(){return!G()},logAction:"plugin.tables.contextPanel.delete.row",tooltip:"Delete Row"}]});c.close();c.clear();c.spacer();c.addGrid({width:5,content:{text:"Banded:",classes:"crop ralign"}});c.openGrid({width:1});c.addInput({type:"checkbox",defaultVal:!1,onChange:b("BandedRows"),checkUpdate:function(b,c){return{value:a(b,"BandedRows")}},logAction:"plugin.tables.contextPanel.banded.rows"});c.close();c.addGrid({width:2,content:{text:"Rows"}});c.openGrid({width:1});c.addInput({type:"checkbox",
defaultVal:!1,onChange:b("BandedCols"),checkUpdate:function(b,c){return{value:a(b,"BandedCols")}},logAction:"plugin.tables.contextPanel.banded.cols"});c.close();c.addGrid({width:3,content:{text:"Columns"}});c.clear();c.spacer();c.addGrid({width:5,content:{text:"Banded Colors:",classes:"crop ralign"}});c.openGrid({width:2});c.addInput({type:"colorwell",value:null,checkUpdate:function(b,c){return{value:a(b,"BandedColor1")}},onChange:e("BandedColor1")});c.close();c.openGrid({width:2});c.addInput({type:"colorwell",
value:null,checkUpdate:function(b,c){return{value:a(b,"BandedColor2")}},onChange:e("BandedColor2")});c.close();c.clear();c.spacer();c.addGrid({width:5,content:{text:"Grid:",classes:"crop ralign"}});c.openGrid({width:6});c.addInput({type:"buttonset",checkUpdate:function(){this.input.refresh()},buttons:[{icon:"table-grid-full",action:function(){var a=p();lucid.array.forEach(a,function(a){lucid.plugin.setPropertyIfChanged(a,"HideH",!1);lucid.plugin.setPropertyIfChanged(a,"HideV",!1)})},tooltip:"Full Grid",
logAction:"plugin.tables.contextPanel.grid.full",selected:function(a,b){for(var c=p(),d=0;d<c.length;d++)if(lucid.plugin.getProperty(c[d],"HideH")||lucid.plugin.getProperty(c[d],"HideV"))return!1;return!0}},{icon:"table-grid-col",action:function(){var a=p();lucid.array.forEach(a,function(a){lucid.plugin.setPropertyIfChanged(a,"HideH",!0);lucid.plugin.setPropertyIfChanged(a,"HideV",!1)})},tooltip:"Grid Columns Only",logAction:"plugin.tables.contextPanel.grid.columns",selected:function(a,b){for(var c=
p(),d=0;d<c.length;d++)if(!lucid.plugin.getProperty(c[d],"HideH")||lucid.plugin.getProperty(c[d],"HideV"))return!1;return!0}},{icon:"table-grid-row",action:function(){var a=p();lucid.array.forEach(a,function(a){lucid.plugin.setPropertyIfChanged(a,"HideH",!1);lucid.plugin.setPropertyIfChanged(a,"HideV",!0)})},tooltip:"Grid Rows Only",logAction:"plugin.tables.contextPanel.grid.rows",selected:function(a,b){for(var c=p(),d=0;d<c.length;d++)if(lucid.plugin.getProperty(c[d],"HideH")||!lucid.plugin.getProperty(c[d],
"HideV"))return!1;return!0}},{icon:"table-grid-empty",action:function(){var a=p();lucid.array.forEach(a,function(a){lucid.plugin.setPropertyIfChanged(a,"HideH",!0);lucid.plugin.setPropertyIfChanged(a,"HideV",!0)})},tooltip:"Empty Grid",logAction:"plugin.tables.contextPanel.grid.empty",selected:function(a,b){for(var c=p(),d=0;d<c.length;d++)if(!lucid.plugin.getProperty(c[d],"HideH")||!lucid.plugin.getProperty(c[d],"HideV"))return!1;return!0}}]});c.close();c.clear();c.spacer();c.addGrid({width:5,content:{text:"Merge:",
classes:"crop ralign"}});c.openGrid({width:6});c.addInput({type:"buttonset",checkUpdate:function(){this.input.refresh()},buttons:[{icon:"table-merge",logAction:"plugin.tables.contextPanel.merge",wide:!0,action:S,disabled:K,tooltip:"Merge Cells"},{icon:"table-unmerge",logAction:"plugin.tables.contextPanel.unmerge",wide:!0,action:U,disabled:L,tooltip:"Unmerge Cells"}]});c.close();c.clear();c.spacer();c.addGrid({width:12,content:{text:"Shift + click to select multiple cells",classes:"center italic",
css:{color:"#666"}}});lucid.plugin.addCustomPanel("Context Panel",null,[{content:c}],null,{isContextPanel:!0,checkShow:function(a){a=lucid.array.filter(a,function(a){return a.isBlock});if(!lucid.array.every(a,function(a){return-1<a.className.search("DefaultTableBlock")}))return!1;c.refreshInputs();return 0<a.length},refreshProperties:"Rows Cols BandedColor1 BandedColor2 HideV HideH BandedRows BandedCols".split(" ")})});var V=function(a,e){var b,c;if(null==a){var f=lucid.plugin.getSelection();if(1!=
f.length||"DefaultTableBlock"!=lucid.plugin.getBlockClassName(f[0]))return!0;a=f[0]}f=lucid.plugin.getProperty(a,"SelectedCells",!0);if(!e){c=!1;for(var h in f)f[h]&&(lucid.plugin.setPropertyIfChanged(a,"Cell_"+h,""),c=!0);return c?(t(a,{}),!1):!0}h=lucid.plugin.getProperty(a,"Rows");for(var g=lucid.plugin.getProperty(a,"Cols"),d,k=0;k<h;k++)for(var l=0;l<g;l++)f[k+","+l]&&(d||(d={row:k,col:l}),b=k,c=l);if(!d)return!0;if(0==d.row&&b==h-1){for(var m=[],r=!0,l=0;l<g;l++)if(f["0,"+l])for(m.push(l),k=
d.row;k<=b;k++)f[k+","+l]||(r=!1);else for(k=0;k<h;k++)if(f[k+","+l])return!0;if(r&&m.length!=g)return m.reverse(),lucid.array.forEach(m,function(d){J(a,lucid.plugin.getAllProperties(a),d)}),lucid.plugin.setProperty(a,"SelectedCells",{},!0),!1}if(0==d.col&&c==g-1){b=[];m=!0;for(k=0;k<h;k++)if(f[k+",0"])for(b.push(k),l=d.col;l<=c;l++)f[k+","+l]||(m=!1);else for(l=0;l<g;l++)if(f[k+","+l])return!0;if(m&&b.length!=h)return b.reverse(),lucid.array.forEach(b,function(d){H(a,lucid.plugin.getAllProperties(a),
d)}),t(a,{}),!1}return!0},t=function(a,e){for(var b,c,f=lucid.plugin.getProperty(a,"Rows"),h=lucid.plugin.getProperty(a,"Cols"),g,d=!1,k=0;k<f;k++)for(var l=0;l<h;l++)e[k+","+l]&&(g||(g={row:k,col:l}),b=k,c=l);if(g){d=!0;for(k=0;k<f&&d;k++)for(l=0;l<h&&d;l++)k<g.row||k>b||l<g.col||l>c?e[k+","+l]&&(d=!1):e[k+","+l]||(d=!1);if(d){f="";for(k=g.row;k<=b;k++){for(l=g.col;l<=c;l++)f+=lucid.text.plainText(lucid.plugin.getProperty(a,"Cell_"+k+","+l)),l!=c&&(f+="\t");k!=b&&(f+="\n")}x=f}}d||(x="");lucid.plugin.setProperty(a,
"SelectedCells",e,!0);lucid.plugin.refreshBlockView(a);lucid.plugin.proxyPropertyChanged(a,"FillColor");lucid.plugin.filteredTextAreasChanged(a)},x="";lucid.clipboard.beforeCopy(function(){if(x&&0<x.length)return x});lucid.clipboard.beforeCut(function(){if(x&&0<x.length){var a=x;V(null,!1);return a}});var aa=function(a,e){var b=lucid.object.getValues(e);lucid.array.sort(b,function(a,b){return a.row-b.row||a.col-b.col});b=lucid.array.map(b,function(a){return"Cell_"+a.row+","+a.col});lucid.plugin.setBlockTextAreasOrder(a,
b)};lucid.plugin.initBlockClass({className:"DefaultTableBlock",name:"Table",searchKeywords:["tables","table"],defaultSize:{w:240,h:120},rLock:!0,unthemed:!0,defaultProperties:function(){return{LineWidth:1}},disabledPropertyControls:["FlipX","FlipY","AspectRatio"],variants:{BandedCols:{tooltip:"Banded Columns",defaultProperties:function(){return{BandedCols:!0,LineWidth:1}}},BandedRows:{tooltip:"Banded Rows",defaultProperties:function(){return{BandedRows:!0,LineWidth:1}}},Header:{tooltip:"Table with Header",
defaultProperties:function(){return{"CellFill_0,0":"#99ccff","CellFill_0,1":"#99ccff","CellFill_0,2":"#99ccff",LineWidth:1}}}},onCreate:function(a){lucid.text.blurEditor()},onInit:function(a){var e=function(b,c){lucid.plugin.addBlockTextArea(a,{id:"Cell_"+b+","+c,value:"",onFocus:function(){var d={};d[b+","+c]=!0;t(a,d)},getBoundingBox:function(d){return function(e){"Cell_0,0"==d&&(y[a]=null);var f=u(a)[b+","+c];return f?{x:e.x+f.x+5,y:e.y+f.y+5,w:f.w-10,h:f.h-10,hideOverflow:!0}:null}}("Cell_"+b+
","+c)});void 0===lucid.plugin.getProperty(a,"CellFill_"+b+","+c)&&lucid.plugin.registerProperty(a,"CellFill_"+b+","+c,"#ffffff");void 0===lucid.plugin.getProperty(a,"NoBand_"+b+","+c)&&lucid.plugin.registerProperty(a,"NoBand_"+b+","+c,!1);var d=lucid.plugin.getProperty(a,"CellSize_"+b+","+c);void 0===d&&(d={w:1,h:1});lucid.plugin.registerProperty(a,"CellSize_"+b+","+c,d,function(a){a.w=Math.max(1,a.w);a.h=Math.max(1,a.h);return a})},b=function(b,c){for(var d=lucid.plugin.getProperty(a,b);d.length<
c;)d.push(d[d.length-1]);d.splice(c);return d};lucid.text.filterTextAreas(a,function(b){var c=lucid.plugin.getProperty(a,"SelectedCells",!0);return!lucid.object.some(c,function(a){return a})||c[b.split("_")[1]]});lucid.plugin.registerProperty(a,"HideH",!1);lucid.plugin.registerProperty(a,"HideV",!1);lucid.plugin.registerProxyProperty(a,"GridLines",function(){var b=lucid.plugin.getProperty(a,"HideH"),c=lucid.plugin.getProperty(a,"HideV");return b?c?"none":"columns":c?"rows":"all"},function(b){switch(b){case "all":lucid.plugin.setPropertyIfChanged(a,
"HideH",!1);lucid.plugin.setPropertyIfChanged(a,"HideV",!1);break;case "columns":lucid.plugin.setPropertyIfChanged(a,"HideH",!0);lucid.plugin.setPropertyIfChanged(a,"HideV",!1);break;case "rows":lucid.plugin.setPropertyIfChanged(a,"HideH",!1);lucid.plugin.setPropertyIfChanged(a,"HideV",!0);break;case "none":lucid.plugin.setPropertyIfChanged(a,"HideH",!0),lucid.plugin.setPropertyIfChanged(a,"HideV",!0)}});lucid.plugin.hookPropertyPostSave(a,"HideH",function(){lucid.plugin.proxyPropertyChanged(a,"GridLines")});
lucid.plugin.hookPropertyPostSave(a,"HideV",function(){lucid.plugin.proxyPropertyChanged(a,"GridLines")});lucid.plugin.registerProperty(a,"RowHeights",[40,40,40],null,function(b,c){if(lucid.plugin.isPermanentObject(a)){var d=0;lucid.array.forEach(c,function(a){d+=a});var k=lucid.plugin.getProperty(a,"BoundingBox");Math.round(k.h)!=Math.round(d)&&(k.h=d,lucid.plugin.setProperty(a,"BoundingBox",k))}});lucid.plugin.registerProperty(a,"ColWidths",[80,80,80],null,function(b,c){if(lucid.plugin.isPermanentObject(a)){var d=
0;lucid.array.forEach(c,function(a){d+=a});var k=lucid.plugin.getProperty(a,"BoundingBox");Math.round(k.w)!=Math.round(d)&&(k.w=d,lucid.plugin.setProperty(a,"BoundingBox",k))}});lucid.plugin.registerProperty(a,"Rows",3,null,function(c,g){if(lucid.plugin.isPermanentObject(a)&&c!=g){var d=lucid.plugin.getAllProperties(a);lucid.object.createSet(lucid.plugin.getBlockTextAreas(a));for(var k=lucid.plugin.getProperty(a,"Cols"),l=c;l<g;l++)for(var f=0;f<k;f++)e(l,f);l=b("RowHeights",g);lucid.plugin.setProperty(a,
"RowHeights",l);lucid.plugin.setMinHeight(a,20*g);for(l=c;l<g;l++)for(f=0;f<k;f++)d["CellFill_"+l+","+f]||lucid.plugin.setPropertyIfChanged(a,"CellFill_"+l+","+f,lucid.plugin.getProperty(a,"CellFill_"+(c-1)+","+f)),lucid.plugin.setPropertyIfChanged(a,"NoBand_"+l+","+f,lucid.plugin.getProperty(a,"NoBand_"+(c-1)+","+f));lucid.object.forEach(u(a),function(b){b.row+b.size.h>g&&lucid.plugin.setProperty(a,"CellSize_"+b.row+","+b.col,{w:b.size.w,h:Math.max(1,g-b.row)})})}});lucid.plugin.setMinHeight(a,60);
lucid.plugin.registerProperty(a,"Cols",3,null,function(c,g){if(lucid.plugin.isPermanentObject(a)&&c!=g){var d=lucid.plugin.getAllProperties(a);lucid.plugin.getBlockTextAreas(a);for(var k=lucid.plugin.getProperty(a,"Rows"),f=0;f<k;f++)for(var m=c;m<g;m++)e(f,m);var f=lucid.plugin.getProperty(a,"BoundingBox"),m=b("ColWidths",g),r=lucid.array.reduce(m,function(a,b){return a+b},0),q=f.w/r,m=m.map(function(a){return Math.max(a*q,30)});lucid.plugin.setProperty(a,"ColWidths",m);lucid.plugin.setMinWidth(a,
30*g);for(f=0;f<k;f++)for(m=c;m<g;m++)d["CellFill_"+f+","+m]||lucid.plugin.setPropertyIfChanged(a,"CellFill_"+f+","+m,lucid.plugin.getProperty(a,"CellFill_"+f+","+(c-1))),lucid.plugin.setPropertyIfChanged(a,"NoBand_"+f+","+m,lucid.plugin.getProperty(a,"NoBand_"+f+","+(c-1)));lucid.object.forEach(u(a),function(b){b.col+b.size.w>g&&lucid.plugin.setProperty(a,"CellSize_"+b.row+","+b.col,{w:Math.max(1,g-b.col),h:b.size.h})})}});lucid.plugin.setMinWidth(a,90);lucid.plugin.setProperty(a,"SelectedAnchor",
{row:0,col:0},!0);lucid.plugin.setProperty(a,"SelectedCursor",{row:0,col:0},!0);lucid.plugin.setProperty(a,"SelectedCells",{},!0);lucid.plugin.registerProperty(a,"BandedRows",!1);lucid.plugin.registerProperty(a,"BandedCols",!1);lucid.plugin.registerProperty(a,"BandedColor1","#99ccff");lucid.plugin.registerProperty(a,"BandedColor2","#ffffff");lucid.plugin.hookPropertyPostSave(a,null,function(b,c,d){d&&("Rows"!=d&&"Cols"!=d&&"BandedRows"!=d&&"BandedCols"!=d&&"BandedColor1"!=d&&"BandedColor2"!=d&&0!=
d.indexOf("CellFill")&&0!=d.indexOf("NoBand")||lucid.plugin.proxyPropertyChanged(a,"FillColor"))});lucid.plugin.registerProxyProperty(a,"FillColor",function(){var b=lucid.plugin.getAllProperties(a);if(b){for(var c=b.Rows,d=b.Cols,k=lucid.plugin.getProperty(a,"SelectedCells",!0),e=lucid.object.some(k,function(a){return a}),f=void 0,r=0;r<c;r++)for(var q=0;q<d;q++)if(!e||k[r+","+q]){var n=b["CellFill_"+r+","+q];if(!b["NoBand_"+r+","+q])if(b.BandedRows&&0==r%2||b.BandedCols&&0==q%2)n=b.BandedColor1;
else if(b.BandedRows&&1==r%2||b.BandedCols&&1==q%2)n=b.BandedColor2;if(void 0===f)f=n;else if(!lucid.object.areEqual(f,n))return null}return f}},function(b){var c=lucid.plugin.getProperty(a,"Rows"),d=lucid.plugin.getProperty(a,"Cols"),k=lucid.plugin.getProperty(a,"BandedRows"),e=lucid.plugin.getProperty(a,"BandedCols"),f=lucid.plugin.getProperty(a,"SelectedCells",!0),r=lucid.object.some(f,function(a){return a});r||!k&&!e||(lucid.plugin.setPropertyIfChanged(a,"BandedRows",!1),lucid.plugin.setPropertyIfChanged(a,
"BandedCols",!1));for(var q=0;q<c;q++)for(var n=0;n<d;n++)if(!r||f[q+","+n])lucid.plugin.setPropertyIfChanged(a,"CellFill_"+q+","+n,b),r&&(k||e)&&lucid.plugin.setPropertyIfChanged(a,"NoBand_"+q+","+n,!0)});lucid.object.createSet(lucid.plugin.getBlockTextAreas(a));for(var c=0;3>c;c++)for(var f=0;3>f;f++)e(c,f)},pointInShape:function(a,e){var b=lucid.plugin.getProperty(a,"BoundingBox");return b?lucid.math.Point.inBox(e,b):!1},getOffsetProperties:function(a,e,b,c,f,h,g,d){function k(a,b,d){var c=a.w,
k=a.h;a.w=lucid.array.reduce(b,function(a,b){return a+b},0);a.h=lucid.array.reduce(d,function(a,b){return a+b},0);Math.round(a.w)==Math.round(q.w)&&Math.round(c)==Math.round(a.w)||q.x==a.x||(a.x=q.x+(q.w-a.w));Math.round(a.h)==Math.round(q.h)&&Math.round(k)==Math.round(a.h)||q.y==a.y||(a.y=q.y+(q.h-a.h));return a}function l(a,b,d,c){var k=[];a.map(function(a,b){return{size:a,index:b}}).sort(function(a,b){return a.size-b.size}).reduce(function(a,d){var c=Math.max(b,a.target/a.current*d.size);k[d.index]=
c;return{current:a.current-d.size,target:a.target-c}},{current:c,target:d});return k}function m(b){return l(lucid.plugin.getProperty(a,"ColWidths"),30,b.w,q.w)}function r(b){return l(lucid.plugin.getProperty(a,"RowHeights"),20,b.h,q.h)}var q=lucid.plugin.getProperty(a,"BoundingBox"),n=lucid.plugin.getProperty(a,"AspectRatio"),p=30*lucid.plugin.getProperty(a,"Cols"),w=20*lucid.plugin.getProperty(a,"Rows");b=lucid.plugin.defaultOffsetProperties(a,e,b,c,f,h,g,d);e={};b[a]&&b[a].BoundingBox&&(b=b[a].BoundingBox,
n&&(b.w<p&&(b.w=p,b.h=p/n),b.h<w&&(b.h=w,b.w=n*w)),n=m(b),p=r(b),b=k(b,n,p),e[a]={BoundingBox:b,ColWidths:n,RowHeights:p});return e},hitTest:function(a,e){function b(a,b){var d="n ne e se s sw w nw".split(" "),c=d.indexOf(a);0!=b&&(c=(c+Math.round(180*b/Math.PI/45))%d.length);return"url("+lucid.config.assets_base_url+"/app/webroot/img/cursors/"+d[c]+"-resize.png) 16 16, auto"}function c(a,b,d){for(var c=0;c<a.length;c++){if(d>b&&d<=b+a[c])return c;b+=a[c]}}function f(b,d,c,k){if(r[d+","+c])for(var e=
lucid.plugin.getProperty(a,"CellSize_"+d+","+c),g=0;g<e.h;g++)for(var f=0;f<e.w;f++)b[d+g+","+(c+f)]=k?!b[d+g+","+(c+f)]:!0}function h(){var b=lucid.plugin.getProperty(a,"SelectedAnchor",!0),d=lucid.plugin.getProperty(a,"SelectedCursor",!0),c={},k=lucid.plugin.getProperty(a,"CellSize_"+b.row+","+b.col),g=lucid.plugin.getProperty(a,"CellSize_"+d.row+","+d.col),e=lucid.math.Box.from4Points({x:b.row,y:b.col},{x:b.row+k.h-1,y:b.col+k.w-1},{x:d.row,y:d.col},{x:d.row+g.h-1,y:d.col+g.w-1});lucid.object.forEach(r,
function(a){lucid.math.Box.overlap(e,{x:a.row,y:a.col,w:a.size.h-1,h:a.size.w-1})&&f(c,a.row,a.col)});return c}if(!(1<lucid.plugin.getSelection().length||lucid.plugin.getProperty(a,"Lock")||1==lucid.plugin.getSelection().length&&lucid.plugin.getSelection()[0]!=a&&e.shift)){var g=lucid.plugin.getProperty(a,"BoundingBox");if(g){var d=lucid.plugin.getProperty(a,"Rotation"),k=lucid.math.Point.rotate(e,lucid.math.Box.center(g),-d);if(lucid.math.Point.inBox(k,{x:g.x-20,y:g.y-20,h:g.h+20,w:g.w+20})){var l=
lucid.plugin.getProperty(a,"ColWidths"),m=lucid.plugin.getProperty(a,"RowHeights"),r=u(a);if(lucid.math.Point.inBox(k,g)){var q=lucid.math.Point.subtract(k,g),n=lucid.object.findValue(r,function(a){return lucid.math.Point.inBox(q,a)});if(-1<lucid.plugin.getSelection().indexOf(a)){for(var d=g.x,p=0;p<l.length;p++)if(d+=l[p],k.x>d-5&&k.x<d+5)return;d=g.y;for(p=0;p<m.length;p++)if(d+=m[p],k.y>d-5&&k.y<d+5)return;return{onClick:function(){var b=lucid.plugin.getProperty(a,"SelectedCells",!0);if(!e.shift){if(e.ctrl){f(b,
n.row,n.col,!0);t(a,b);return}var d=lucid.plugin.getProperty(a,"SelectedAnchor",!0),c=lucid.plugin.getProperty(a,"SelectedCursor",!0);if(d.row==c.row&&d.col==c.col&&d.row==n.row&&d.col==n.col){d=b[n.row+","+n.col];b=h();d&&f(b,n.row,n.col,!0);t(a,b);return}lucid.plugin.setProperty(a,"SelectedAnchor",{row:n.row,col:n.col},!0)}lucid.plugin.setProperty(a,"SelectedCursor",{row:n.row,col:n.col},!0);b=h();t(a,b)},onDoubleClick:function(){t(a,{});lucid.text.focusEditor(a,"Cell_"+n.row+","+n.col)},cursor:"pointer",
allowCtrl:!0}}}if(k.x>g.x&&k.y<g.y&&-1<lucid.plugin.getSelection().indexOf(a))return{onClick:function(){var b=c(l,g.x,k.x),d;d=e.shift||e.ctrl?lucid.plugin.getProperty(a,"SelectedCells",!0):{};for(var h=0;h<m.length;h++)f(d,h,b);t(a,d)},cursor:b("s",d),allowCtrl:!0,allowSelection:!0};if(k.y>g.y&&k.x<g.x&&-1<lucid.plugin.getSelection().indexOf(a))return{onClick:function(){var b=c(m,g.y,k.y),d;d=e.shift||e.ctrl?lucid.plugin.getProperty(a,"SelectedCells",!0):{};for(var h=0;h<l.length;h++)f(d,b,h);t(a,
d)},cursor:b("e",d),allowCtrl:!0,allowSelection:!0}}}}},beforeDelete:function(a,e,b){return e?!0:V(a,b)},preferredTextArea:function(a){var e;a:{e=v(a);var b=lucid.plugin.getProperty(a,"Rows");a=lucid.plugin.getProperty(a,"Cols");for(var c,f=0;f<b;f++)for(var h=0;h<a;h++)if(c=e[f+","+h]){e=c;break a}e=void 0}if(e)return"Cell_"+e.row+","+e.col},spatialControlsOnSelect:!0,spatialControls:function(a){var e=[],b=lucid.plugin.getProperty(a,"ColWidths"),c=lucid.plugin.getProperty(a,"RowHeights"),f=lucid.plugin.getProperty(a,
"BoundingBox"),h=0;lucid.array.forEach(b,function(d,c){var g=h+d;h+=d;e.push({color:"none",location:function(){return{x:f.x+g-6,y:f.y+5,w:12,h:f.h-10}},moved:function(d){d.x=Math.round(d.x);for(var g=0,e=0;e<c;e++)g+=b[e];d=d.x-g-f.x-b[c];b[c]=Math.round(b[c]+d);c<b.length-1&&(b[c+1]=Math.round(b[c+1]-d));lucid.plugin.setProperty(a,"ColWidths",b)},path:function(){for(var a=0,d=0;d<c;d++)a+=b[d];return[{x:f.x+a+30,y:f.y+f.h/2},{x:c<b.length-1?f.x+a+b[c]+b[c+1]-30:1E4,y:f.y+f.h/2}]},cursor:function(){return"ew-resize"},
snap:2,logAction:"plugin.tables.spatialControls.columnWidth"})});var g=0;lucid.array.forEach(c,function(b,k){var l=g+b;g+=b;e.push({color:"none",location:function(){return{x:f.x+5,y:f.y+l-6,w:f.w-10,h:12}},moved:function(b){for(var d=0,g=0;g<k;g++)d+=c[g];c[k]=Math.round(c[k]+(b.y-d-f.y-c[k]));lucid.plugin.setProperty(a,"RowHeights",c)},path:function(){for(var a=0,b=0;b<k;b++)a+=c[b];return[{x:f.x+f.w/2,y:f.y+a+20},{x:f.x+f.w/2,y:1E4}]},cursor:function(){return"ns-resize"},snap:2,logAction:"plugin.tables.spatialControls.rowHeight"})});
return e},getRenderData:function(a,e){var b=a.BoundingBox;y[a.id]=null;var c=u(a.id,a);aa(a.id,c);if("sample"==e||"preview"==e)var f=a.ColWidths.reduce(function(a,b){return a+b},0),h=a.RowHeights.reduce(function(a,b){return a+b},0),c=lucid.object.map(c,function(a){a.w*=b.w/f;a.x*=b.w/f;a.y*=b.h/h;a.h*=b.h/h;return a});var g=[];lucid.object.forEach(c,function(d){var c=a["CellFill_"+d.row+","+d.col];if(!a["NoBand_"+d.row+","+d.col])if(a.BandedRows&&0==d.row%2||a.BandedCols&&0==d.col%2)c=a.BandedColor1;
else if(a.BandedRows&&1==d.row%2||a.BandedCols&&1==d.col%2)c=a.BandedColor2;g.push({StrokeColor:null,LineWidth:null,NoRounding:!0,FillColor:c,Actions:[{Action:"move",x:b.x+d.x,y:b.y+d.y},{Action:"line",x:b.x+d.x+d.w,y:b.y+d.y},{Action:"line",x:b.x+d.x+d.w,y:b.y+d.y+d.h},{Action:"line",x:b.x+d.x,y:b.y+d.y+d.h},{Action:"close"}]})});g.push({StrokeColor:a.LineColor,LineWidth:a.LineWidth,FillColor:null,NoRounding:!0,Actions:[{Action:"move",x:b.x,y:b.y},{Action:"line",x:b.x+b.w,y:b.y},{Action:"line",x:b.x+
b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+b.h},{Action:"close"}]});a.HideH&&a.HideV||lucid.object.forEach(c,function(d){var c={StrokeColor:a.LineColor,LineWidth:a.LineWidth,NoRounding:!0};a.HideH||a.HideV?a.HideH&&!a.HideV?c.Actions=[{Action:"move",x:b.x+d.x,y:b.y+d.y},{Action:"line",x:b.x+d.x,y:b.y+d.y+d.h},{Action:"move",x:b.x+d.x+d.w,y:b.y+d.y},{Action:"line",x:b.x+d.x+d.w,y:b.y+d.y+d.h}]:a.HideV&&!a.HideH&&(c.Actions=[{Action:"move",x:b.x+d.x,y:b.y+d.y},{Action:"line",x:b.x+d.x+d.w,y:b.y+d.y},
{Action:"move",x:b.x+d.x,y:b.y+d.y+d.h},{Action:"line",x:b.x+d.x+d.w,y:b.y+d.y+d.h}]):c.Actions=[{Action:"move",x:b.x+d.x,y:b.y+d.y},{Action:"line",x:b.x+d.x+d.w,y:b.y+d.y},{Action:"line",x:b.x+d.x+d.w,y:b.y+d.y+d.h},{Action:"line",x:b.x+d.x,y:b.y+d.y+d.h},{Action:"close"}];g.push(c)});"pdf"!=e&&lucid.object.forEach(c,function(c){a.SelectedCells[c.row+","+c.col]&&(g.push({StrokeColor:"#ffffff",LineWidth:3,NoRounding:!0,Actions:[{Action:"move",x:b.x+c.x+3,y:b.y+c.y+3},{Action:"line",x:b.x+c.x+c.w-
3,y:b.y+c.y+3},{Action:"line",x:b.x+c.x+c.w-3,y:b.y+c.y+c.h-3},{Action:"line",x:b.x+c.x+3,y:b.y+c.y+c.h-3},{Action:"close"}]}),g.push(lucid.math.dashLine([{StrokeColor:"#29aae1",LineWidth:2,NoRounding:!0,Actions:[{Action:"move",x:b.x+c.x+3,y:b.y+c.y+3},{Action:"line",x:b.x+c.x+c.w-3,y:b.y+c.y+3},{Action:"line",x:b.x+c.x+c.w-3,y:b.y+c.y+c.h-3},{Action:"line",x:b.x+c.x+3,y:b.y+c.y+c.h-3},{Action:"close"}]}],[5,5])[1]))});return g}});lucid.plugin.registerAdvancedAction("DefaultTableBlock","insertColumnLeft",
M,function(){return!B()});lucid.plugin.registerAdvancedAction("DefaultTableBlock","insertColumnRight",N,function(){return!B()});lucid.plugin.registerAdvancedAction("DefaultTableBlock","insertRowTop",O,function(){return!D()});lucid.plugin.registerAdvancedAction("DefaultTableBlock","insertRowBottom",P,function(){return!D()});lucid.plugin.registerAdvancedAction("DefaultTableBlock","deleteColumn",R,I);lucid.plugin.registerAdvancedAction("DefaultTableBlock","deleteRow",Q,G);lucid.plugin.registerAdvancedAction("DefaultTableBlock",
"mergeCells",S,function(){return!K()});lucid.plugin.registerAdvancedAction("DefaultTableBlock","unmergeCells",U,function(){return!L()});lucid.clipboard.beforePaste(function(a){var e=lucid.plugin.getSelection();if(1==e.length&&"DefaultTableBlock"==lucid.plugin.getBlockClassName(e[0])){var e=e[0],b=lucid.object.getKeys(lucid.object.filter(lucid.plugin.getProperty(e,"SelectedCells",!0),function(a){return a})).map(function(a){a=a.split(",");return{row:parseInt(a[0],10),col:parseInt(a[1],10)}});if(0<b.length){lucid.array.sort(b,
function(a,b){return a.row-b.row||a.col-b.col});a=W(a);if(!a)return!1;X(e,b[0].row,b[0].col,a);return!0}}return!1});var W=function(a){a=a.replace(/\r\n/g,"\n").split("\n");0==a[a.length-1].length&&a.pop();a=a.map(function(a){return a.split("\t")});var e=a[0].length;return lucid.array.every(a,function(a){return a.length==e})?a:!1},X=function(a,e,b,c){var f=c[0].length+b,h=c.length+e,g=lucid.plugin.getProperty(a,"Rows"),d=lucid.plugin.getProperty(a,"Cols");h>g&&lucid.plugin.setProperty(a,"Rows",Math.min(60,
h));f>d&&lucid.plugin.setProperty(a,"Cols",Math.min(30,f));for(f=0;f<c.length&&60>e+f;f++)for(h=0;h<c[f].length&&30>b+h;h++)lucid.plugin.setProperty(a,"Cell_"+(e+f)+","+(b+h),c[f][h]);lucid.text.blurEditor();lucid.log.analytics("tables.pastetsv")};lucid.clipboard.beforeTextPaste(function(a,e,b){if("DefaultTableBlock"==lucid.plugin.getBlockClassName(a)&&(b=W(b)))return e=e.split("_")[1].split(",").map(function(a){return parseInt(a,10)}),X(a,e[0],e[1],b),!1});var F=function(a,e,b,c){lucid.plugin.setPropertyIfChanged(a,
"CellFill_"+b,c["CellFill_"+e]);lucid.plugin.setPropertyIfChanged(a,"CellSize_"+b,c["CellSize_"+e]);lucid.plugin.setPropertyIfChanged(a,"NoBand_"+b,c["NoBand_"+e]);lucid.plugin.setPropertyIfChanged(a,"Cell_"+b,c["Cell_"+e])},C=function(a,e,b,c){var f=e.RowHeights,h=c?b.row:b.row+b.size.h;lucid.plugin.setProperty(a,"Rows",e.Rows+1);f.splice(b.row,0,f[b.row]);lucid.plugin.setProperty(a,"RowHeights",f);for(b=e.Rows;b>h;b--)for(c=0;c<e.Cols;c++)F(a,b-1+","+c,b+","+c,e);for(b=0;b<e.Cols;b++)lucid.plugin.setProperty(a,
"Cell_"+h+","+b,""),lucid.plugin.setProperty(a,"CellSize_"+h+","+b,{w:1,h:1});e=u(a);lucid.object.forEach(e,function(b){b.row<h&&b.row+b.size.h>h&&lucid.plugin.setProperty(a,"CellSize_"+b.row+","+b.col,{w:b.size.w,h:b.size.h+1})})},A=function(a,e,b,c){var f=e.ColWidths,h=c?b.col:b.col+b.size.w;lucid.plugin.setProperty(a,"Cols",e.Cols+1);f.splice(b.col,0,f[b.col]);lucid.plugin.setProperty(a,"ColWidths",f);for(b=e.Cols;b>h;b--)for(c=0;c<e.Rows;c++)F(a,c+","+(b-1),c+","+b,e);for(b=0;b<e.Rows;b++)lucid.plugin.setProperty(a,
"Cell_"+b+","+h,""),lucid.plugin.setProperty(a,"CellSize_"+b+","+h,{w:1,h:1});e=u(a);lucid.object.forEach(e,function(b){b.col<h&&b.col+b.size.w>h&&lucid.plugin.setProperty(a,"CellSize_"+b.row+","+b.col,{w:b.size.w+1,h:b.size.h})})},H=function(a,e,b){if(1==e.Rows)t(a,{}),lucid.plugin.deleteItem(a);else{for(var c=e.RowHeights,f=b;f<e.Rows-1;f++)for(var h=0;h<e.Cols;h++)1<e["CellSize_"+f+","+h].h&&(e["CellSize_"+(f+1)+","+h]=e["CellSize_"+f+","+h],e["CellSize_"+(f+1)+","+h].h--),F(a,f+1+","+h,f+","+
h,e);for(f=0;f<e.Cols;f++)lucid.plugin.setPropertyIfChanged(a,"Cell_"+(e.Rows-1)+","+f,"");f=u(a);lucid.object.forEach(f,function(c){c.row<b&&c.row+c.size.h>b&&lucid.plugin.setProperty(a,"CellSize_"+c.row+","+c.col,{w:c.size.w,h:c.size.h-1})});lucid.plugin.setProperty(a,"Rows",e.Rows-1);c.splice(b,1);lucid.plugin.setProperty(a,"RowHeights",c)}},J=function(a,e,b){if(1==e.Cols)t(a,{}),lucid.plugin.deleteItem(a);else{for(var c=e.ColWidths,f=b;f<e.Cols-1;f++)for(var h=0;h<e.Rows;h++)1<e["CellSize_"+h+
","+f].w&&(e["CellSize_"+h+","+(f+1)]=e["CellSize_"+h+","+f],e["CellSize_"+h+","+(f+1)].w--),F(a,h+","+(f+1),h+","+f,e);for(f=0;f<e.Rows;f++)lucid.plugin.setPropertyIfChanged(a,"Cell_"+f+","+(e.Cols-1),"");f=u(a);lucid.object.forEach(f,function(c){c.col<b&&c.col+c.size.w>b&&lucid.plugin.setProperty(a,"CellSize_"+c.row+","+c.col,{w:c.size.w-1,h:c.size.h})});lucid.plugin.setProperty(a,"Cols",e.Cols-1);c.splice(b,1);lucid.plugin.setProperty(a,"ColWidths",c)}},y={};lucid.plugin.onSelectionChange(function(){Z()});
lucid.plugin.addContextMenuItems(function(){var a=function(a){return lucid.plugin.inReadOnlyMode()||!a||1!=a.length?!1:"DefaultTableBlock"==lucid.plugin.getBlockClassName(a[0])},e=function(a,b){var c=u(b),e=lucid.plugin.getProperty(b,"BoundingBox"),f=lucid.math.Point.subtract(a,e);return lucid.object.findValue(c,function(a){return lucid.math.Point.inBox(f,a)})},b=function(a,b,c){for(var e=0;e<c.length;e++){if(a>=b&&a<=b+c[e])return e;b+=c[e]}return-1},c=function(c,d){var e=c[0];return e&&a(c)&&0<=
b(d.y,lucid.plugin.getProperty(e,"BoundingBox").y,lucid.plugin.getProperty(e,"RowHeights"))},f=function(c,d){var e=c[0];return e&&a(c)&&0<=b(d.x,lucid.plugin.getProperty(e,"BoundingBox").x,lucid.plugin.getProperty(e,"ColWidths"))},h=function(b,c){var f=b[0];return f&&a(b)&&e(c,f)};return[{external:!0,label:"Add Row Above",logAction:"plugin.table.contextMenu.addrow.above",action:function(a,b){var c=b[0],f=lucid.plugin.getAllProperties(c),h=e(a,c);C(c,f,h,!0)},visible:h},{external:!0,label:"Add Row Below",
logAction:"plugin.table.contextMenu.addrow.below",action:function(a,b){var c=b[0],f=lucid.plugin.getAllProperties(c),h=e(a,c);C(c,f,h,!1)},visible:h},{external:!0,label:"Delete Row",logAction:"plugin.table.contextMenu.deleterow",action:function(a,c){var e=c[0],f=lucid.plugin.getAllProperties(e),h=b(a.y,f.BoundingBox.y,f.RowHeights);H(e,f,h)},visible:c},{external:!0,label:"Clear Row",logAction:"plugin.table.contextMenu.clearrow",action:function(a,c){for(var e=c[0],f=lucid.plugin.getAllProperties(e),
f=b(a.y,f.BoundingBox.y,f.RowHeights),h=0;h<lucid.plugin.getProperty(e,"Cols");h++)lucid.plugin.setProperty(e,"Cell_"+f+","+h,"")},visible:c},{external:!0,label:"Add Column Left",logAction:"plugin.table.contextMenu.addcolumn.left",action:function(a,b){var c=b[0],f=lucid.plugin.getAllProperties(c),h=e(a,c);A(c,f,h,!0)},visible:h},{external:!0,label:"Add Column Right",logAction:"plugin.table.contextMenu.addcolumn.right",action:function(a,b){var c=b[0],f=lucid.plugin.getAllProperties(c),h=e(a,c);A(c,
f,h,!1)},visible:h},{external:!0,label:"Delete Column",logAction:"plugin.table.contextMenu.deletecolumn",action:function(a,c){var e=c[0],f=lucid.plugin.getAllProperties(e),h=b(a.x,f.BoundingBox.x,f.ColWidths);J(e,f,h)},visible:f},{external:!0,label:"Clear Column",logAction:"plugin.table.contextMenu.clearcolumn",action:function(a,c){for(var e=c[0],f=lucid.plugin.getAllProperties(e),f=b(a.x,f.BoundingBox.x,f.ColWidths),h=0;h<lucid.plugin.getProperty(e,"Rows");h++)lucid.plugin.setProperty(e,"Cell_"+
h+","+f,"")},visible:f}]}());lucid.plugin.createToolGroups({Tables:["DefaultTableBlock",{className:"DefaultTableBlock",variant:"BandedRows",name:"TableBandedRows"},{className:"DefaultTableBlock",variant:"BandedCols",name:"TableBandedCols"},{className:"DefaultTableBlock",variant:"Header",name:"TableHeader"}]})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/table.js.map
};
