pluginFn['/js/plugins/v2/techclipart.js'] = function(lucid, window) {
	(function(){function a(a,d,l,h,e,g){var c=l.split("/"),c=c[c.length-1],c=c.split(".")[0].replace(/-/g,"_"),c="Image_"+a.split(" ")[0].toLowerCase()+"_"+c;g=g||[];g=g.concat(lucid.string.trim(d.replace(/network/gi,"").replace(/\W/g," ").replace(/\s+/g," ")).split(" "));g.unshift("network");lucid.plugin.initBlockClass({className:c,name:d,searchKeywords:g,defaultSize:{w:e,h:200},disabledPropertyControls:["FillColor","FillType","LineColor","LineWidth"],onInit:function(a){lucid.plugin.setProperty(a,"TextAreaShowing",
!1,!0);lucid.plugin.addBlockTextArea(a,{id:"Title",value:"",getBoundingBox:function(a,b){return b?null:{x:a.x,y:a.y+a.h-20,w:a.w,h:20}}});lucid.plugin.hookPropertyPostSave(a,"BoundingBox",function(f,b){lucid.plugin.setProperty(a,"bb",b,!0)});lucid.plugin.hookPropertyPostSave(a,"Title",function(f,b){if(lucid.text.plainText(f)!=lucid.text.plainText(b))if(0==lucid.text.plainText(f).length){var c=lucid.object.copy(lucid.plugin.getProperty(a,"bb",!0));lucid.plugin.getProperty(a,"AspectRatio")||(c.h+=20);
lucid.plugin.setProperty(a,"BoundingBox",c)&&lucid.plugin.setProperty(a,"bb",c,!0)}else 0==lucid.text.plainText(b).length&&(c=lucid.object.copy(lucid.plugin.getProperty(a,"bb",!0)),lucid.plugin.getProperty(a,"AspectRatio")||(c.h-=20),lucid.plugin.setProperty(a,"BoundingBox",c)&&lucid.plugin.setProperty(a,"bb",c,!0))})},onDblClick:function(a){lucid.plugin.editBlockTextArea(a,"Title")},getLinkPoints:function(){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]},getRenderData:function(a,c){var b;b=
a.BoundingBox;b="sample"!=c?0==lucid.text.plainText(lucid.plugin.getProperty(a.id,"Title")).length?b:{x:b.x,y:b.y,w:b.w,h:b.h-20}:b.w<b.h?{x:b.x,y:b.y,w:1*b.h,h:b.h}:{x:b.x,y:b.y,w:b.w,h:1*b.w};return[{FillColor:{url:"sample"==c?h:l,pos:"fit",bb:b},Actions:[{Action:"move",x:b.x,y:b.y},{Action:"line",x:b.x+b.w,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+b.h},{Action:"close"}]}]}});k[a]?k[a].push(c):k[a]=[c]}var e={global:this,provide:function(a){a=a.split(".");e.global[a[0]]=
e.global[a[0]]||{};var d=e.global[a[0]];a.slice(1).reduce(function(a,f){a[f]||(a[f]={});return a[f]},d)},require:function(){},inherits:function(a,d){function e(){}e.prototype=d.prototype;a.superClass_=d.prototype;a.prototype=new e;a.prototype.constructor=a;a.base=function(a,f,e){var c=Array.prototype.slice.call(arguments,2);return d.prototype[f].apply(a,c)}},base:function(a,d,k){var h=arguments.callee.caller;if(e.STRICT_MODE_COMPATIBLE||e.DEBUG&&!h)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");
if(h.superClass_)return h.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var m=Array.prototype.slice.call(arguments,2),g=!1,c=a.constructor;c;c=c.superClass_&&c.superClass_.constructor)if(c.prototype[d]===h)g=!0;else if(g)return c.prototype[d].apply(a,m);if(a[d]===h)return a.constructor.prototype[d].apply(a,m);throw Error("goog.base called from a method of one name to a method of a different name");}};e.provide("plugin.techclipart");var k={};a("Network","Server",lucid.config.assets_base_url+
"/app/webroot/img/blocks/server.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/server_thumb.png",200);a("Network","File Server",lucid.config.assets_base_url+"/app/webroot/img/blocks/server_file.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/server_file_thumb.png",200);a("Network","Net Server",lucid.config.assets_base_url+"/app/webroot/img/blocks/server_net.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/server_net_thumb.png",200);a("Network","Net Server (Large)",
lucid.config.assets_base_url+"/app/webroot/img/blocks/server_net_large.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/server_net_large_thumb.png",200);a("Network","RAID Device",lucid.config.assets_base_url+"/app/webroot/img/blocks/raid.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/raid_thumb.png",200);a("Network","Large RAID Device",lucid.config.assets_base_url+"/app/webroot/img/blocks/raid_large.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/raid_large_thumb.png",
200);a("Network","Server Rack",lucid.config.assets_base_url+"/app/webroot/img/blocks/rack_server.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/rack_server_thumb.png",300);a("Network","Tape Backup Rack",lucid.config.assets_base_url+"/app/webroot/img/blocks/rack_tape.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/rack_tape_thumb.png",300);a("Network","Small Printer",lucid.config.assets_base_url+"/app/webroot/img/blocks/printer_small.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/printer_small_thumb.png",
200);a("Network","Large Printer",lucid.config.assets_base_url+"/app/webroot/img/blocks/printer_large.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/printer_large_thumb.png",200);a("Network","Multipurpose Printer",lucid.config.assets_base_url+"/app/webroot/img/blocks/printer_multipurpose.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/printer_multipurpose_thumb.png",200);a("Network","Small Copier",lucid.config.assets_base_url+"/app/webroot/img/blocks/copier_small.png",lucid.config.assets_base_url+
"/app/webroot/img/blocks/copier_small_thumb.png",200);a("Network","Large Copier",lucid.config.assets_base_url+"/app/webroot/img/blocks/copier_large.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/copier_large_thumb.png",200);a("Network","Large-Format Printer",lucid.config.assets_base_url+"/app/webroot/img/blocks/printer_largeformat.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/printer_largeformat_thumb.png",200);a("Network","Router",lucid.config.assets_base_url+"/app/webroot/img/blocks/router.png",
lucid.config.assets_base_url+"/app/webroot/img/blocks/router_thumb.png",200);a("Network","Wireless Router",lucid.config.assets_base_url+"/app/webroot/img/blocks/router_wireless.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/router_wireless_thumb.png",200);a("Network","UPS",lucid.config.assets_base_url+"/app/webroot/img/blocks/ups.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/ups_thumb.png",200);a("Electronics","2.0 Speakers",lucid.config.assets_base_url+"/app/webroot/img/blocks/speakers_2.png",
lucid.config.assets_base_url+"/app/webroot/img/blocks/speakers_2_thumb.png",200);a("Electronics","Slide Scanner",lucid.config.assets_base_url+"/app/webroot/img/blocks/scanner_slide.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/scanner_slide_thumb.png",200);a("Electronics","2.1 Speakers",lucid.config.assets_base_url+"/app/webroot/img/blocks/speakers_2-1.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/speakers_2-1_thumb.png",200);a("Electronics","5.1 Speakers",lucid.config.assets_base_url+
"/app/webroot/img/blocks/speakers_5-1.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/speakers_5-1_thumb.png",200);a("Electronics","LCD Monitor",lucid.config.assets_base_url+"/app/webroot/img/blocks/lcd.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/lcd_thumb.png",200);a("Electronics","PDA",lucid.config.assets_base_url+"/app/webroot/img/blocks/pda.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/pda_thumb.png",200);a("Electronics","Memory Card Reader",lucid.config.assets_base_url+
"/app/webroot/img/blocks/drive_cardreader.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/drive_cardreader_thumb.png",200);a("Electronics","Camcorder",lucid.config.assets_base_url+"/app/webroot/img/blocks/camcorder.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/camcorder_thumb.png",200);a("Electronics","Headset",lucid.config.assets_base_url+"/app/webroot/img/blocks/headset.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/headset_thumb.png",200);a("Electronics","Calculator",
lucid.config.assets_base_url+"/app/webroot/img/blocks/calculator_simple.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/calculator_simple_thumb.png",200);a("Electronics","Flatbed Scanner",lucid.config.assets_base_url+"/app/webroot/img/blocks/scanner_flatbed.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/scanner_flatbed_thumb.png",200);a("Electronics","Photo Printer",lucid.config.assets_base_url+"/app/webroot/img/blocks/printer_photo.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/printer_photo_thumb.png",
200);a("Electronics","Photo Scanner",lucid.config.assets_base_url+"/app/webroot/img/blocks/scanner_photo.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/scanner_photo_thumb.png",200);a("Electronics","Projector",lucid.config.assets_base_url+"/app/webroot/img/blocks/projector.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/projector_thumb.png",200);a("Electronics","External Drive (Firewire)",lucid.config.assets_base_url+"/app/webroot/img/blocks/drive_firewire.png",lucid.config.assets_base_url+
"/app/webroot/img/blocks/drive_firewire_thumb.png",200);a("Electronics","External Drive (USB)",lucid.config.assets_base_url+"/app/webroot/img/blocks/drive_usb.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/drive_usb_thumb.png",200);a("Electronics","External Modem",lucid.config.assets_base_url+"/app/webroot/img/blocks/modem_external.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/modem_external_thumb.png",200);a("Electronics","External TV Tuner",lucid.config.assets_base_url+
"/app/webroot/img/blocks/tv_tuner_external.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/tv_tuner_external_thumb.png",200);a("Electronics","MP3 Player",lucid.config.assets_base_url+"/app/webroot/img/blocks/mp3.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/mp3_thumb.png",200);a("Electronics","External Sound Card (Box)",lucid.config.assets_base_url+"/app/webroot/img/blocks/sound_box.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/sound_box_thumb.png",200);a("Electronics",
"Wide-Screen LCD",lucid.config.assets_base_url+"/app/webroot/img/blocks/lcd_wide.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/lcd_wide_thumb.png",200);a("Audio Equipment","2.0 Speakers",lucid.config.assets_base_url+"/app/webroot/img/blocks/speakers_2.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/speakers_2_thumb.png",200);a("Audio Equipment","2.1 Speakers",lucid.config.assets_base_url+"/app/webroot/img/blocks/speakers_2-1.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/speakers_2-1_thumb.png",
200);a("Audio Equipment","5.1 Speakers",lucid.config.assets_base_url+"/app/webroot/img/blocks/speakers_5-1.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/speakers_5-1_thumb.png",200);a("Audio Equipment","Record Player",lucid.config.assets_base_url+"/app/webroot/img/blocks/record_player.png",lucid.config.assets_base_url+"/app/webroot/img/blocks/record_player_thumb.png",200);a("Audio Equipment","Headset",lucid.config.assets_base_url+"/app/webroot/img/blocks/headset.png",lucid.config.assets_base_url+
"/app/webroot/img/blocks/headset_thumb.png",200);lucid.plugin.createToolGroups(k)})();
//# sourceMappingURL=/js/plugins/v2/source-maps/techclipart.js.map
};
