pluginFn['/js/plugins/v2/timeline.js'] = function(lucid, window) {
	(function(){var x={global:this,provide:function(a){a=a.split(".");x.global[a[0]]=x.global[a[0]]||{};var c=x.global[a[0]];a.slice(1).reduce(function(a,c){a[c]||(a[c]={});return a[c]},c)},require:function(){},inherits:function(a,c){function b(){}b.prototype=c.prototype;a.superClass_=c.prototype;a.prototype=new b;a.prototype.constructor=a;a.base=function(a,b,e){var h=Array.prototype.slice.call(arguments,2);return c.prototype[b].apply(a,h)}},base:function(a,c,b){var d=arguments.callee.caller;if(x.STRICT_MODE_COMPATIBLE||
x.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),e=!1,h=a.constructor;h;h=h.superClass_&&h.superClass_.constructor)if(h.prototype[c]===d)e=!0;else if(e)return h.prototype[c].apply(a,f);if(a[c]===d)return a.constructor.prototype[c].apply(a,
f);throw Error("goog.base called from a method of one name to a method of a different name");}};x.provide("plugin.timeline");var q={LINE:"lineTimeline",BLOCK:"blockTimeline"},k={SECOND:"second",MINUTE:"minute",HOUR:"hour",DAY:"day",WEEK:"week",MONTH:"month",QUARTER:"quarter",YEAR:"year"},S=k.DAY,T=q.BLOCK,m={},D=function(a,c,b,d){lucid.plugin.registerProperty(a,c,"",null,function(){lucid.plugin.proxyPropertyChanged(a,b)});lucid.plugin.registerProxyProperty(a,b,function(){return lucid.plugin.getProperty(a,
c)},function(b){var e=lucid.plugin.getAllProperties(a);b&&e.TimelineBlockId?(b=d(lucid.date.utc(b),e.TimelineBlockId),e[c]=b.toISOString(),b=y(lucid.plugin.getBlockClassName(a),e,lucid.plugin.getAllProperties(e.TimelineBlockId)),lucid.plugin.setPropertyIfChanged(a,c,e[c]),lucid.plugin.setPropertyIfChanged(a,"BoundingBox",b)):z(a)})},J=function(a){lucid.plugin.registerProperty(a,"TimelineBlockId","",null,function(c,b){c&&m[c]&&m[c].attachedBlockIds&&delete m[c].attachedBlockIds[a];b&&(m[b]||(m[b]=
{}),m[b].attachedBlockIds||(m[b].attachedBlockIds={}),m[b].attachedBlockIds[a]=!0,c!==b&&lucid.plugin.proxyPropertyChanged(a,"DateFormatOptions"))})},U=function(a){switch(a){case k.SECOND:case k.MINUTE:case k.HOUR:a="h:mm A;h:mm a;h A;h a;D MMMM h:mm A;MMM D h:mm A;MMMM D h:mm A;D MMM h:mm A".split(";");break;default:a="D MMMM YYYY;MMM D;MMMM D, YYYY;MMM D, YYYY;M/D/YYYY;M/D;D-M-YYYY;D MMM;D-M".split(";");break;case k.MONTH:case k.QUARTER:a="MMMM;MMM;MMMM YYYY;MM/YYYY;MMM YYYY;MMM D;MMM D, YYYY;M/D/YYYY;M/D;D-M-YYYY;D MMM;D-M".split(";");
break;case k.YEAR:a="YYYY;MMMM YYYY;MM/YYYY;MMM YYYY;MMM D, YYYY;M/D/YYYY;D-M-YYYY;D MMM YYYY".split(";")}return a.map(function(a){return{label:lucid.date.utc("2016-01-31T01:50:45Z").format(a),value:a}})},E=function(a,c){lucid.plugin.registerProxyProperty(a,"DateFormatOptions",function(){var b=c?a:lucid.plugin.getProperty(a,"TimelineBlockId"),b=U(lucid.plugin.getProperty(b,"TimeUnit")),d=lucid.plugin.getProperty(a,"DateFormat");0<lucid.array.filter(b,function(a){return a.value===d}).length||b.push({label:lucid.date.utc("2016-01-31T01:50:45Z").format(d),
value:d});return b},function(){})},B=function(a,c,b,d){return c.diff(a)/d.diff(b)},C=function(a,c,b,d){return d.x+B(c,a,c,b)*d.w},F=function(a,c,b){b=a.clone().add(1,b);return B(a,b,a,c)},u=function(a,c,b){a=lucid.date.duration(c.diff(a));switch(b){case "second":return a.asSeconds();case "minute":return a.asMinutes();case "hour":return a.asHours();case "day":return a.asDays();case "week":return a.asWeeks();case "month":return a.asMonths();case "quarter":return a.asMonths()/3;default:return a.asYears()}},
V=function(a){lucid.plugin.registerProxyProperty(a,"TimeUnitOptions",function(){var c=lucid.date.utc(lucid.plugin.getProperty(a,"StartDate")),b=lucid.date.utc(lucid.plugin.getProperty(a,"FinishDate"));return[{label:"Seconds",value:"second",disabled:function(){return 75<u(c,b,"second")}},{label:"Minutes",value:"minute",disabled:function(){return 75<u(c,b,"minute")}},{label:"Hours",value:"hour",disabled:function(){return 75<u(c,b,"hour")}},{label:"Days",value:"day",disabled:function(){return 75<u(c,
b,"day")}},{label:"Weeks",value:"week",disabled:function(){return 75<u(c,b,"week")}},{label:"Months",value:"month",disabled:function(){return 75<u(c,b,"month")}},{label:"Quarters",value:"quarter",disabled:function(){return 75<u(c,b,"quarter")}},{label:"Years",value:"year",disabled:function(){return 75<u(c,b,"year")}}]},function(){});lucid.plugin.hookPropertyPostSave(a,"StartDate",function(){lucid.plugin.proxyPropertyChanged(a,"TimeUnitOptions")});lucid.plugin.hookPropertyPostSave(a,"FinishDate",function(){lucid.plugin.proxyPropertyChanged(a,
"TimeUnitOptions")})},K=function(a,c){for(var b=lucid.date.utc(lucid.plugin.getProperty(a,"StartDate")),d=lucid.date.utc(lucid.plugin.getProperty(a,"FinishDate")),f=lucid.plugin.getProperty(a,"TimeUnit"),e=[],h=0,g=0;void 0!==lucid.plugin.getProperty(a,"tickMark_"+g);g++)lucid.plugin.deleteBlockTextArea(a,"tickMark_"+g);var m=function(c){var g=B(b,c,b,d),k="tickMark_"+h;c=c.format(lucid.plugin.getProperty(a,"InterimDateFormat"));var l=F(b,d,f);!0===lucid.plugin.getProperty(a,"DisplayInterimMarks")&&
!0===lucid.plugin.getProperty(a,"DisplayInterimDates")&&(lucid.plugin.addBlockTextArea(a,{id:k,value:c,align:"center",vAlign:"top",readOnly:!0,getBoundingBox:function(a){return{x:a.x+a.w*g-a.w*l/2,y:a.y+a.h-10,w:a.w*l,h:30}}}),lucid.plugin.setText(a,k,c,!0));e.push(g);h++},g=function(a){for(var e=b.clone().startOf(a).add(1,a);e.isBefore(d);)m(e),e.add(1,a)};switch(f){default:g(f);break;case k.WEEK:g=b.clone().day(lucid.plugin.getProperty(a,"StartOfWeek")).day();g<=b.day()&&(g+=7);for(g=b.clone().day(g).startOf("day");g.isBefore(d);)m(g),
g.add(1,"week");break;case k.QUARTER:for(var n=lucid.date.utc(lucid.plugin.getProperty(a,"StartOfFiscalYear")).year(b.year()),l=n.clone(),g=0;l.isAfter(b);)g--,l=n.clone().add(g,"quarters");for(;l.isBefore(d);)l.isAfter(b)&&m(l),l=n.clone().add(g,"quarters"),g++}lucid.plugin.setPropertyIfChanged(a,"tickMarks",e,!0);if(!c){var g=lucid.plugin.getProperty(a,"BoundingBox"),p;for(p in A(a))switch(lucid.plugin.getBlockClassName(p)){case "TimelineMilestoneBlock":n=lucid.date.utc(lucid.plugin.getProperty(p,
"milestoneDate"));0>n.diff(b)||0<n.diff(d)?(z(p),n=lucid.plugin.getProperty(p,"BoundingBox"),n.y=g.y-n.h-50,lucid.plugin.setPropertyIfChanged(p,"BoundingBox",n)):lucid.plugin.setProperty(p,"milestoneDate",n.toISOString());break;case "TimelineIntervalBlock":n=lucid.date.utc(lucid.plugin.getProperty(p,"startDate")),l=lucid.date.utc(lucid.plugin.getProperty(p,"finishDate")),0>n.diff(b)||0<l.diff(d)?(z(p),n=lucid.plugin.getProperty(p,"BoundingBox"),n.y=g.y-n.h-50,lucid.plugin.setPropertyIfChanged(p,"BoundingBox",
n)):(lucid.plugin.setProperty(p,"startDate",n.toISOString()),lucid.plugin.setProperty(p,"finishDate",l.toISOString()))}}},W=function(){return lucid.object.filter(m,function(a,c){return lucid.plugin.isPermanentObject(c)})},A=function(a){return lucid.object.filter(m[a].attachedBlockIds,function(a,b){return lucid.plugin.isPermanentObject(b)})},y=function(a,c,b){var d=b.BoundingBox,f=lucid.date.utc(b.StartDate),e=lucid.date.utc(b.FinishDate);switch(a){case "TimelineMilestoneBlock":switch(b.TimelineType){case q.LINE:b=
d.y+d.h/2-c.BoundingBox.h-5;break;default:b=d.y-c.BoundingBox.h+c.BoundingBox.w-2}a=lucid.date.utc(c.MilestoneDate);return{x:C(a,f,e,d)-c.BoundingBox.w/2,y:b,w:c.BoundingBox.w,h:c.BoundingBox.h};case "TimelineIntervalBlock":switch(b.TimelineType){case q.LINE:a=40;b=d.y+d.h/2-a/2;break;default:b=d.y,a=d.h-40}var h=lucid.date.utc(c.StartDate),g=lucid.date.utc(c.FinishDate);c=C(h,f,e,d);d=B(h,g,f,e)*d.w;return{x:c,y:b,w:d,h:a}}},L=function(a){switch(a){case k.SECOND:return k.SECOND;case k.MINUTE:return k.MINUTE;
case k.HOUR:return k.HOUR;default:return k.DAY}},G=function(a,c,b,d){d.w=0<d.w?d.w:1;return c.clone().add((a-d.x)/d.w*b.diff(c))},v=function(a,c){var b=lucid.date.utc(lucid.plugin.getProperty(c,"StartDate")),d=lucid.date.utc(lucid.plugin.getProperty(c,"FinishDate")),f=lucid.plugin.getProperty(c,"BoundingBox"),b=G(a,b,d,f),d=lucid.date.utc(lucid.plugin.getProperty(c,"StartDate")),f=lucid.date.utc(lucid.plugin.getProperty(c,"FinishDate")),e=lucid.plugin.getProperty(c,"TimeUnit"),h=L(e),e=b.clone().startOf(h),
h=e.clone().add(1,h),e=lucid.date.max(e,d),h=lucid.date.min(h,f);return b.diff(e)<h.diff(b)?e:h},M=function(a){lucid.qualaroo.showSurvey("timeline",!1);lucid.plugin.setPropertyIfChanged(a,"ZOrder",lucid.plugin.getProperty("DragBlock","ZOrder")||lucid.plugin.getProperty(a,"ZOrder"))},N=function(a){switch(a){case "TimelineMilestoneBlock":return{MilestoneDate:"",TimelineBlockId:""};case "TimelineIntervalBlock":return{StartDate:"",FinishDate:"",TimelineBlockId:""}}},z=function(a){var c=lucid.plugin.getBlockClassName(a),
c=N(c),b;for(b in c)lucid.plugin.setPropertyIfChanged(a,b,c[b])},O=function(a,c,b){switch(a.TimelineType){case q.LINE:return b?lucid.math.Box.add(a.BoundingBox,c):{x:a.BoundingBox.x+c.x,y:a.BoundingBox.y,w:a.BoundingBox.w+c.w,h:a.BoundingBox.h};default:return lucid.math.Box.add(a.BoundingBox,c)}},P=function(a,c,b,d,f,e,h){c={};f=lucid.plugin.getAllProperties(a);var g=f.TimelineBlockId,k=lucid.plugin.getBlockClassName(a);if(e&&0<=e.indexOf(g))return d=lucid.plugin.getAllProperties(g),d.BoundingBox=
O(d,b,h),c[a]={BoundingBox:y(k,lucid.plugin.getAllProperties(a),d)},c;a:{h=f.BoundingBox;switch(k){case "TimelineMilestoneBlock":h=lucid.math.Box.add(h,{x:b.x-b.w/2,y:b.y,w:b.w,h:b.h+b.w});break a;case "TimelineIntervalBlock":h=lucid.math.Box.add(h,b);break a}h=void 0}e=lucid.plugin.getProperty(g,"BoundingBox");b=!1;var n;if(!g||!e||!lucid.math.Box.overlap(h,e)){var g=null,l;for(l in W())if(lucid.plugin.getItemPageId(l)===lucid.plugin.getActivePageId()&&lucid.plugin.getParent(l)===lucid.plugin.getParent(a)&&
(e=lucid.plugin.getProperty(l,"BoundingBox"),lucid.math.Box.overlap(h,e))){g=l;b=!0;n=k;l=g;e=void 0;switch(n){case "TimelineMilestoneBlock":e=3;break;case "TimelineIntervalBlock":e=1}e=lucid.plugin.getProperty(l,"ZOrder")+e;var p=e+1,m=void 0;for(m in A(l))lucid.plugin.getBlockClassName(m)===n&&(l=lucid.plugin.getProperty(m,"ZOrder"),l>e&&(e=l));n=e+Math.random()*(p-e);break}}if(g){f.TimelineBlockId=g;f.DateFormat=b?lucid.plugin.getProperty(g,"InterimDateFormat"):lucid.plugin.getProperty(a,"DateFormat");
f.BoundingBox=h;a:{g=f.TimelineBlockId;h=f.BoundingBox;switch(k){case "TimelineMilestoneBlock":f.MilestoneDate=v(h.x+h.w/2,g).toISOString();d={MilestoneDate:f.MilestoneDate,TimelineBlockId:g,BoundingBox:y(k,f,lucid.plugin.getAllProperties(g))};break a;case "TimelineIntervalBlock":l=lucid.date.utc(lucid.plugin.getProperty(g,"StartDate"));e=lucid.date.utc(lucid.plugin.getProperty(g,"FinishDate"));var m=lucid.plugin.getProperty(g,"BoundingBox"),p=L(lucid.plugin.getProperty(g,"TimeUnit")),r,t,q;if(d.left&&
!d.right)r=f.StartDate?lucid.date.utc(f.StartDate):v(h.x,g),t=v(h.x+h.w,g);else if(!d.left&&d.right)r=v(h.x,g),t=f.FinishDate?lucid.date.utc(f.FinishDate):v(h.x+h.w,g);else if(!d.left&&!d.right){r=v(h.x,g);t=v(h.x+h.w,g);q=Math.abs(G(h.x,l,e,m).diff(r));var u=Math.abs(G(h.x+h.w,l,e,m).diff(t));q=q<u?"left":"right"}d.right||"left"===q?(d.right||(t=C(r,l,e,m),t=v(t+h.w,g)),0<=r.diff(e)&&r.subtract(1).startOf(p)):(d.left||(r=C(t,l,e,m),r=v(r-h.w,g)),0<=l.diff(t)&&t.add(1,p).startOf(p));0>=t.diff(r)&&
(d.left||"left"===q?(t.add(1,p),t=lucid.date.min(t,e)):(r.subtract(1,p),r=lucid.date.max(r,l)));f.StartDate=r.toISOString();f.FinishDate=t.toISOString();d={StartDate:f.StartDate,FinishDate:f.FinishDate,TimelineBlockId:g,BoundingBox:y(k,f,lucid.plugin.getAllProperties(g))};break a}d=void 0}c[a]=d;b&&(c[a].DateFormat=f.DateFormat,c[a].ZOrder=n)}else c[a]=N(k),c[a].BoundingBox=h;return c},w=function(a,c,b){return[{Action:"move",x:a,y:c},{Action:"line",x:a,y:b}]},H=function(a,c,b,d){return[{Action:"move",
x:a,y:c},{Action:"line",x:a+b,y:c},{Action:"line",x:a+b,y:c+d},{Action:"line",x:a,y:c+d},{Action:"close"}]},I=function(a){return{StrokeColor:"#00000000",FillColor:"#00000000",Actions:H(a.x,a.y,a.w,a.h)}},Q=function(a){return{TimelineType:a,LineColor:"#3d4752",FillColor:"#3d4752",LineWidth:2}},R=function(a){switch(a){case k.SECOND:return k.MINUTE;case k.MINUTE:return k.HOUR;case k.HOUR:return k.DAY;case k.DAY:return k.WEEK;case k.WEEK:return k.MONTH;case k.MONTH:return k.QUARTER;default:return k.YEAR}};
lucid.plugin.initBlockClass({className:"TimelineBlock",name:"Timeline",searchKeywords:["timeline","line","lapse","gantt","span"],noLines:!0,disabledPropertyControls:"FlipX FlipY left center right justified TextVAlign".split(" "),isTextRotateDisabled:!0,rLock:!0,minHeight:40,variants:{BlockTimeline:{tooltip:"Block Timeline",defaultSize:{w:1120,h:120},defaultProperties:function(){return Q(q.BLOCK)}},LineTimeline:{tooltip:"Line Timeline",defaultSize:{w:1120,h:80},defaultProperties:function(){return Q(q.LINE)}}},
onCreate:function(){lucid.qualaroo.showSurvey("timeline",!1)},onInit:function(a){m[a]||(m[a]={});m[a].attachedBlockIds||(m[a].attachedBlockIds={});var c=lucid.date.utc().startOf("day"),b=lucid.date.utc().startOf("day").clone().add(1,"week"),d=lucid.date.utc().startOf("year"),f=function(a){return!0===a};lucid.plugin.registerProperty(a,"StartDate",c.toISOString(),null,function(){lucid.plugin.proxyPropertyChanged(a,"startDate")});lucid.plugin.registerProperty(a,"FinishDate",b.toISOString(),null,function(){lucid.plugin.proxyPropertyChanged(a,
"finishDate")});lucid.plugin.registerProperty(a,"StartOfWeek","Sunday");lucid.plugin.registerProperty(a,"StartOfFiscalYear",d.toISOString());lucid.plugin.registerProperty(a,"TimeUnit",S,null,function(){lucid.plugin.proxyPropertyChanged(a,"DateFormatOptions");for(var b in A(a))lucid.plugin.proxyPropertyChanged(b,"DateFormatOptions")});lucid.plugin.registerProperty(a,"TimelineType",T,null,function(){lucid.plugin.proxyPropertyChanged(a,"timelineType")});lucid.plugin.registerProperty(a,"DisplayStartFinishMarks",
!0,f);lucid.plugin.registerProperty(a,"DisplayStartFinishDates",!0,f,function(){lucid.plugin.proxyPropertyChanged(a,"DisplayDates")});lucid.plugin.registerProperty(a,"StartFinishDateFormat","M/D",null,function(){lucid.plugin.proxyPropertyChanged(a,"DateFormat")});lucid.plugin.registerProperty(a,"DisplayInterimMarks",!0,f);lucid.plugin.registerProperty(a,"DisplayInterimDates",!0,f,function(){lucid.plugin.proxyPropertyChanged(a,"DisplayDates")});lucid.plugin.registerProperty(a,"InterimDateFormat","M/D",
null,function(){lucid.plugin.proxyPropertyChanged(a,"DateFormat")});lucid.plugin.registerProxyProperty(a,"DisplayDates",function(){return lucid.plugin.getProperty(a,"DisplayStartFinishDates")&&lucid.plugin.getProperty(a,"DisplayInterimDates")},function(b){lucid.plugin.setPropertyIfChanged(a,"DisplayStartFinishDates",b);lucid.plugin.setPropertyIfChanged(a,"DisplayInterimDates",b)});lucid.plugin.registerProxyProperty(a,"DateFormat",function(){return lucid.plugin.getProperty(a,"InterimDateFormat")},
function(b){lucid.plugin.setPropertyIfChanged(a,"StartFinishDateFormat",b);lucid.plugin.setPropertyIfChanged(a,"InterimDateFormat",b)});E(a,!0);V(a);lucid.plugin.hookPropertyPreSave(a,"StartOfWeek",function(a){return lucid.date.utc().day(a).format("dddd")});lucid.plugin.hookPropertyPreSave(a,"StartOfFiscalYear",function(b){b=lucid.date.utc(b);return b.isValid()?b.toISOString():lucid.plugin.getProperty(a,"StartOfFiscalYear")});lucid.plugin.hookPropertyPreSave(a,"TimeUnit",function(b){for(var c in k)if(k[c]===
b)return b;return lucid.plugin.getProperty(a,"TimeUnit")});lucid.plugin.hookPropertyPreSave(a,"StartFinishDateFormat",function(b){return"string"===typeof b?b:lucid.plugin.getProperty(a,"StartFinishDateFormat")});lucid.plugin.hookPropertyPreSave(a,"InterimDateFormat",function(b){return"string"===typeof b?b:lucid.plugin.getProperty(a,"InterimDateFormat")});lucid.plugin.addBlockTextArea(a,{id:"startDateText",value:c.format("M/D"),align:"center",vAlign:"top",readOnly:!0,getBoundingBox:function(b){var c=
lucid.plugin.getAllProperties(a),c=b.w*F(lucid.date.utc(c.StartDate),lucid.date.utc(c.FinishDate),c.TimeUnit);return{x:b.x-c/2,y:b.y+b.h+10,w:c,h:30}}});lucid.plugin.addBlockTextArea(a,{id:"finishDateText",value:b.format("M/D"),align:"center",vAlign:"top",readOnly:!0,getBoundingBox:function(b){var c=lucid.plugin.getAllProperties(a),c=b.w*F(lucid.date.utc(c.StartDate),lucid.date.utc(c.FinishDate),c.TimeUnit);return{x:b.x+b.w-c/2,y:b.y+b.h+10,w:c,h:30}}});c=function(){if(!0===lucid.plugin.getProperty(a,
"DisplayStartFinishMarks")&&!0===lucid.plugin.getProperty(a,"DisplayStartFinishDates")){var b=lucid.date.utc(lucid.plugin.getProperty(a,"StartDate"));lucid.plugin.setText(a,"startDateText",b.format(lucid.plugin.getProperty(a,"StartFinishDateFormat")),!0)}else lucid.plugin.setText(a,"startDateText","",!0)};b=function(){if(!0===lucid.plugin.getProperty(a,"DisplayStartFinishMarks")&&!0===lucid.plugin.getProperty(a,"DisplayStartFinishDates")){var b=lucid.date.utc(lucid.plugin.getProperty(a,"FinishDate"));
lucid.plugin.setText(a,"finishDateText",b.format(lucid.plugin.getProperty(a,"StartFinishDateFormat")),!0)}else lucid.plugin.setText(a,"finishDateText","",!0)};d=function(){K(a,!1)};K(a,!0);lucid.plugin.hookPropertyPostSave(a,"StartDate",c);lucid.plugin.hookPropertyPostSave(a,"DisplayStartFinishMarks",c);lucid.plugin.hookPropertyPostSave(a,"DisplayStartFinishDates",c);lucid.plugin.hookPropertyPostSave(a,"StartFinishDateFormat",c);lucid.plugin.hookPropertyPostSave(a,"FinishDate",b);lucid.plugin.hookPropertyPostSave(a,
"DisplayStartFinishMarks",b);lucid.plugin.hookPropertyPostSave(a,"DisplayStartFinishDates",b);lucid.plugin.hookPropertyPostSave(a,"StartFinishDateFormat",b);lucid.plugin.hookPropertyPostSave(a,"StartDate",d);lucid.plugin.hookPropertyPostSave(a,"FinishDate",d);lucid.plugin.hookPropertyPostSave(a,"StartOfWeek",d);lucid.plugin.hookPropertyPostSave(a,"StartOfFiscalYear",d);lucid.plugin.hookPropertyPostSave(a,"TimeUnit",d);lucid.plugin.hookPropertyPostSave(a,"DisplayInterimMarks",d);lucid.plugin.hookPropertyPostSave(a,
"DisplayInterimDates",d);lucid.plugin.hookPropertyPostSave(a,"InterimDateFormat",d);lucid.plugin.registerProxyProperty(a,"startDate",function(){return lucid.plugin.getProperty(a,"StartDate")},function(b){b=lucid.date.utc(b);var c=lucid.date.utc(lucid.plugin.getProperty(a,"FinishDate")),d=lucid.plugin.getProperty(a,"TimeUnit");if(!b.isValid()||0>=c.diff(b))b=lucid.date.utc(lucid.plugin.getProperty(a,"StartDate"));for(;"year"!==d&&75<u(b,c,d);)d=R(d);75<u(b,c,d)&&(lucid.plugin.setPropertyIfChanged(a,
"DisplayStartFinishDates",!1),lucid.plugin.setPropertyIfChanged(a,"DisplayInterimDates",!1));lucid.plugin.setPropertyIfChanged(a,"TimeUnit",d);lucid.plugin.setPropertyIfChanged(a,"StartDate",b.toISOString())});lucid.plugin.registerProxyProperty(a,"finishDate",function(){return lucid.plugin.getProperty(a,"FinishDate")},function(b){b=lucid.date.utc(b);var c=lucid.date.utc(lucid.plugin.getProperty(a,"StartDate")),d=lucid.plugin.getProperty(a,"TimeUnit");if(!b.isValid()||0>=b.diff(c))b=lucid.date.utc(lucid.plugin.getProperty(a,
"FinishDate"));for(;"year"!==d&&75<u(c,b,d);)d=R(d);75<u(c,b,d)&&(lucid.plugin.setPropertyIfChanged(a,"DisplayStartFinishDates",!1),lucid.plugin.setPropertyIfChanged(a,"DisplayInterimDates",!1));lucid.plugin.setPropertyIfChanged(a,"TimeUnit",d);lucid.plugin.setPropertyIfChanged(a,"FinishDate",b.toISOString())});lucid.plugin.registerProxyProperty(a,"timelineType",function(){return lucid.plugin.getProperty(a,"TimelineType")},function(b){var c,d;for(d in q)q[d]===b&&(c=b);c=c||lucid.plugin.getProperty(a,
"TimelineType");lucid.plugin.setPropertyIfChanged(a,"TimelineType",c);b=lucid.plugin.getAllProperties(a);b.TimelineType=c;switch(c){case q.LINE:b.BoundingBox.y=b.BoundingBox.y+b.BoundingBox.h-80;b.BoundingBox.h=80;break;case q.BLOCK:b.BoundingBox.y=b.BoundingBox.y+b.BoundingBox.h-40-80,b.BoundingBox.h=120}lucid.plugin.setPropertyIfChanged(a,"BoundingBox",b.BoundingBox);for(var f in A(a))c=lucid.plugin.getAllProperties(f),lucid.plugin.setPropertyIfChanged(f,"BoundingBox",y(lucid.plugin.getBlockClassName(f),
c,b))})},getOffsetProperties:function(a,c,b,d,f,e,h){c={};d=lucid.plugin.getAllProperties(a);d.BoundingBox=O(d,b,h);c[a]={BoundingBox:d.BoundingBox};for(var g in A(a))c[g]={BoundingBox:y(lucid.plugin.getBlockClassName(g),lucid.plugin.getAllProperties(g),d)};return c},getRenderData:function(a,c){var b=a.BoundingBox,d=[],f=[],e=a.tickMarks;if(!0===a.DisplayStartFinishMarks)switch(a.TimelineType){case q.LINE:d=w(b.x,b.y,b.y+b.h).concat(w(b.x+b.w,b.y,b.y+b.h));break;default:d=w(b.x,b.y,b.y+b.h).concat(w(b.x+
b.w,b.y,b.y+b.h))}if(!0===a.DisplayInterimMarks)for(var h=0;h<e.length;h++)switch(a.TimelineType){case q.LINE:f=f.concat(w(b.x+b.w*e[h],b.y+b.h/4,b.y+3*b.h/4));break;default:f=f.concat(w(b.x+b.w*e[h],b.y+b.h-40,b.y+b.h-20))}switch(a.TimelineType){case q.LINE:return[I(b),{StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y+b.h/2},{Action:"line",x:b.x+b.w,y:b.y+b.h/2}].concat(d).concat(f)}];default:return[I(b),{StrokeColor:a.LineColor,LineWidth:a.LineWidth,FillColor:a.FillColor,
NoRounding:!0,Actions:H(b.x,b.y,b.w,b.h-40)},{StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:d.concat(f)}]}},beforeDelete:function(a){for(var c in A(a))z(c)},onDelete:function(a){delete m[a]}});lucid.plugin.initBlockClass({className:"TimelineMilestoneBlock",name:"Milestone",searchKeywords:["timeline","milestone"],defaultSize:{w:20,h:80},minWidth:1,noLines:!0,disabledPropertyControls:"FlipX FlipY left center right justified TextVAlign".split(" "),isTextRotateDisabled:!0,rLock:!0,snapSpacing:1,
defaultProperties:function(){return{LineColor:"#ed6058",FillColor:"#ed6058",LineWidth:2}},onCreate:M,onPaste:z,getOffsetProperties:P,onInit:function(a){lucid.plugin.addBlockTextArea(a,{id:"MilestoneText",value:"Milestone",align:"center",vAlign:"bottom",getBoundingBox:function(a){return{x:a.x+a.w/2-80,y:a.y-50,w:160,h:30}}});lucid.plugin.addBlockTextArea(a,{id:"dateText",value:"",align:"center",vAlign:"top",readOnly:!0,getBoundingBox:function(a){return{x:a.x+a.w/2-240,y:a.y-20,w:480,h:30}}});var c=
function(){var b=lucid.plugin.getProperty(a,"MilestoneDate"),c=lucid.plugin.getProperty(a,"DateFormat");b?(b=lucid.date.utc(b),lucid.plugin.setText(a,"dateText",b.format(c),!0)):lucid.plugin.setText(a,"dateText","",!0)};D(a,"MilestoneDate","milestoneDate",function(b,c){var f=lucid.date.utc(lucid.plugin.getProperty(c,"StartDate")),e=lucid.date.utc(lucid.plugin.getProperty(c,"FinishDate"));return!b.isValid()||0>b.diff(f)||0>e.diff(b)?lucid.date.utc(lucid.plugin.getProperty(a,"MilestoneDate")):b});J(a);
lucid.plugin.registerProperty(a,"DateFormat","M/D",function(b){return"string"===typeof b?b:lucid.plugin.getProperty(a,"DateFormat")});E(a,!1);lucid.plugin.hookPropertyPostSave(a,"MilestoneDate",c);lucid.plugin.hookPropertyPostSave(a,"DateFormat",c)},getRenderData:function(a,c){var b=a.BoundingBox;return[I(b),{StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:w(b.x+b.w/2,b.y,b.y+b.h-b.w)},{StrokeColor:a.LineColor,LineWidth:a.LineWidth,FillColor:a.FillColor,NoRounding:!0,Actions:[{Action:"move",
x:b.x,y:b.y+b.h-b.w},{Action:"line",x:b.x+b.w,y:b.y+b.h-b.w},{Action:"line",x:b.x+b.w/2,y:b.y+b.h-0},{Action:"close"}]}]},beforeDelete:function(a){lucid.plugin.setPropertyIfChanged(a,"TimelineBlockId","")}});lucid.plugin.initBlockClass({className:"TimelineIntervalBlock",name:"Interval",searchKeywords:["timeline","interval","task"],defaultSize:{w:160,h:80},minWidth:1,noLines:!0,disabledPropertyControls:"FlipX FlipY left center right justified TextVAlign".split(" "),isTextRotateDisabled:!0,rLock:!0,
snapSpacing:1,defaultProperties:function(){return{FillColor:"#9ed973",LineWidth:0}},onCreate:M,onPaste:z,getOffsetProperties:P,onInit:function(a){lucid.plugin.addBlockTextArea(a,{id:"IntervalText",value:"Interval",align:"center",vAlign:"bottom",getBoundingBox:function(a){return{x:a.x,y:a.y,w:a.w,h:a.h/2}}});lucid.plugin.addBlockTextArea(a,{id:"dateText",value:"",align:"center",vAlign:"top",readOnly:!0,getBoundingBox:function(a){return{x:a.x,y:a.y+a.h/2,w:a.w,h:a.h/2}}});var c=function(){var b=lucid.plugin.getProperty(a,
"StartDate"),c=lucid.plugin.getProperty(a,"FinishDate"),f=lucid.plugin.getProperty(a,"DateFormat");b&&c?(b=lucid.date.utc(b),c=lucid.date.utc(c),lucid.plugin.setText(a,"dateText",b.format(f)+" - "+c.format(f),!0)):lucid.plugin.setText(a,"dateText","",!0)};D(a,"StartDate","startDate",function(b,c){var f=lucid.date.utc(lucid.plugin.getProperty(a,"FinishDate")),e=lucid.date.utc(lucid.plugin.getProperty(c,"StartDate"));return!b.isValid()||0>b.diff(e)||0>=f.diff(b)?lucid.date.utc(lucid.plugin.getProperty(a,
"StartDate")):b});D(a,"FinishDate","finishDate",function(b,c){var f=lucid.date.utc(lucid.plugin.getProperty(a,"StartDate")),e=lucid.date.utc(lucid.plugin.getProperty(c,"FinishDate"));if(!b.isValid()||0>e.diff(b)||0>=b.diff(f))b=lucid.date.utc(lucid.plugin.getProperty(a,"FinishDate"));return b});J(a);lucid.plugin.registerProperty(a,"DateFormat","M/D",function(b){return"string"===typeof b?b:lucid.plugin.getProperty(a,"DateFormat")});E(a,!1);lucid.plugin.hookPropertyPostSave(a,"StartDate",c);lucid.plugin.hookPropertyPostSave(a,
"FinishDate",c);lucid.plugin.hookPropertyPostSave(a,"DateFormat",c)},getRenderData:function(a,c){var b=a.BoundingBox;return[{StrokeColor:a.LineColor,LineWidth:a.LineWidth,FillColor:a.FillColor,NoRounding:!0,Actions:H(b.x,b.y,b.w,b.h)}]},beforeDelete:function(a){lucid.plugin.setPropertyIfChanged(a,"TimelineBlockId","")}});lucid.plugin.createToolGroups({Timeline:[{className:"TimelineBlock",variant:"BlockTimeline"},{className:"TimelineBlock",variant:"LineTimeline"},"TimelineMilestoneBlock","TimelineIntervalBlock"]})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/timeline.js.map
};
