pluginFn['/js/plugins/v2/ui.js'] = function(lucid, window) {
	(function(){var k={global:this,provide:function(c){c=c.split(".");k.global[c[0]]=k.global[c[0]]||{};var e=k.global[c[0]];c.slice(1).reduce(function(a,b){a[b]||(a[b]={});return a[b]},e)},require:function(){},inherits:function(c,e){function a(){}a.prototype=e.prototype;c.superClass_=e.prototype;c.prototype=new a;c.prototype.constructor=c;c.base=function(a,c,f){var g=Array.prototype.slice.call(arguments,2);return e.prototype[c].apply(a,g)}},base:function(c,e,a){var b=arguments.callee.caller;if(k.STRICT_MODE_COMPATIBLE||
k.DEBUG&&!b)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(b.superClass_)return b.superClass_.constructor.apply(c,Array.prototype.slice.call(arguments,1));for(var d=Array.prototype.slice.call(arguments,2),f=!1,g=c.constructor;g;g=g.superClass_&&g.superClass_.constructor)if(g.prototype[e]===b)f=!0;else if(f)return g.prototype[e].apply(c,d);if(c[e]===b)return c.constructor.prototype[e].apply(c,
d);throw Error("goog.base called from a method of one name to a method of a different name");}};k.provide("plugin.ui");lucid.plugin.initBlockClass({className:"UIAreaBlock",name:"UIArea",searchKeywords:[],defaultSize:{w:320,h:240},container:!0,getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox;return[{StrokeColor:c.LineColor,LineWidth:1,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+
a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"UIWindowBlock",name:"UIWindow",searchKeywords:[],defaultSize:{w:320,h:240},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Title",value:"Window Title",getBoundingBox:function(c){return{x:c.x+20,y:c.y,w:c.w-140,h:40}}})},container:!0,getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox,b=40,d=c.LineWidth;"sample"==
e&&(d=1,b=a.h/4);return[{StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]},{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+b},{Action:"line",x:a.x,y:a.y+b},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:d,Actions:[{Action:"move",
x:a.x+a.w-b+2*d,y:a.y+2*d},{Action:"line",x:a.x+a.w-2*d,y:a.y+2*d},{Action:"line",x:a.x+a.w-2*d,y:a.y+b-2*d},{Action:"line",x:a.x+a.w-b+2*d,y:a.y+b-2*d},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:d,NoRounding:!0,Actions:[{Action:"move",x:a.x+a.w-.8*b+2*d,y:a.y+.2*b+2*d},{Action:"line",x:a.x+a.w-.2*b-2*d,y:a.y+.8*b-2*d},{Action:"move",x:a.x+a.w-.2*b-2*d,y:a.y+.2*b+2*d},{Action:"line",x:a.x+a.w-.8*b+2*d,y:a.y+.8*b-2*d}]},{StrokeColor:c.LineColor,LineWidth:d,Actions:[{Action:"move",x:a.x+
a.w-2*b+4*d,y:a.y+2*d},{Action:"line",x:a.x+a.w-b,y:a.y+2*d},{Action:"line",x:a.x+a.w-b,y:a.y+b-2*d},{Action:"line",x:a.x+a.w-2*b+4*d,y:a.y+b-2*d},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:d,NoRounding:!0,Actions:[{Action:"move",x:a.x+a.w-1.8*b+4*d,y:a.y+.2*b+2*d},{Action:"line",x:a.x+a.w-1.2*b,y:a.y+.2*b+2*d},{Action:"line",x:a.x+a.w-1.2*b,y:a.y+.8*b-2*d},{Action:"line",x:a.x+a.w-1.8*b+4*d,y:a.y+.8*b-2*d},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:d,Actions:[{Action:"move",
x:a.x+a.w-3*b+6*d,y:a.y+2*d},{Action:"line",x:a.x+a.w-2*b+2*d,y:a.y+2*d},{Action:"line",x:a.x+a.w-2*b+2*d,y:a.y+b-2*d},{Action:"line",x:a.x+a.w-3*b+6*d,y:a.y+b-2*d},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:d,Actions:[{Action:"move",x:a.x+a.w-2.2*b+2*d,y:a.y+.8*b-2*d},{Action:"line",x:a.x+a.w-2.8*b+6*d,y:a.y+.8*b-2*d}]}]}});lucid.plugin.initBlockClass({className:"UIDialogBlock",name:"UIDialog",searchKeywords:[],defaultSize:{w:320,h:240},onInit:function(c){lucid.plugin.addBlockTextArea(c,
{id:"Title",value:"Window Title",getBoundingBox:function(c){return{x:c.x+20,y:c.y,w:c.w-60,h:40}}});lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:function(c){return{x:c.x+.1*c.w,y:c.y+.1*c.h,w:.8*c.w,h:.8*c.h}}})},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox,b=40,d=c.LineWidth;"sample"==e&&(d=1,b=a.h/4);return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",
x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]},{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+a.w,y:a.y+b},{Action:"line",x:a.x,y:a.y+b}]},{StrokeColor:c.LineColor,LineWidth:d,Actions:[{Action:"move",x:a.x+a.w-b+2*d,y:a.y+2*d},{Action:"line",x:a.x+a.w-2*d,y:a.y+2*d},{Action:"line",x:a.x+a.w-2*d,y:a.y+b-2*d},{Action:"line",x:a.x+a.w-b+2*d,y:a.y+b-2*d},{Action:"close"}]},
{StrokeColor:c.LineColor,LineWidth:d,Actions:[{Action:"move",x:a.x+a.w-.8*b+2*d,y:a.y+.2*b+2*d},{Action:"line",x:a.x+a.w-.2*b-2*d,y:a.y+.8*b-2*d},{Action:"move",x:a.x+a.w-.2*b-2*d,y:a.y+.2*b+2*d},{Action:"line",x:a.x+a.w-.8*b+2*d,y:a.y+.8*b-2*d}]}]}});lucid.plugin.initBlockClass({className:"UIElementBlock",name:"UIElement",searchKeywords:[],defaultSize:{w:320,h:240},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:function(c){return{x:c.x+.1*c.w,y:c.y+.1*c.h,w:.8*
c.w,h:.8*c.h}}})},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"UIImageBlock",name:"UIImage",searchKeywords:[],defaultSize:{w:320,h:240},onInit:function(c){lucid.plugin.addBlockTextArea(c,
{id:"Text",value:"",getBoundingBox:function(c){return{x:c.x+.1*c.w,y:c.y+.5*c.h,w:.8*c.w,h:.4*c.h}}})},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:c.LineWidth,
Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"move",x:a.x+a.w,y:a.y},{Action:"line",x:a.x,y:a.y+a.h}]}]}});lucid.plugin.initBlockClass({className:"UIVideoBlock",name:"UIVideo",searchKeywords:[],defaultSize:{w:320,h:240},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:function(c){return{x:c.x+.1*c.w,y:c.y+.65*c.h,w:.8*c.w,h:.3*c.h}}})},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,
e){var a=c.BoundingBox,b=lucid.color.darken(c.FillColor,.5);return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]},{FillColor:b,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+.4*a.w,y:a.y+.35*a.h},{Action:"line",x:a.x+.6*a.w,y:a.y+.5*a.h},{Action:"line",x:a.x+.4*a.w,y:a.y+.65*a.h},{Action:"close"}]}]}});
lucid.plugin.initBlockClass({className:"UIMapBlock",name:"UIMap",searchKeywords:[],defaultSize:{w:320,h:240},onInit:function(c){lucid.plugin.setProperty(c,"TextAlign","right");lucid.plugin.addBlockTextArea(c,{id:"Text",value:"",getBoundingBox:function(c){return{x:c.x+.4*c.w,y:c.y+.65*c.h,w:.55*c.w,h:.3*c.h}}})},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox,b=8,d=2;"sample"==e&&(b=c.LineWidth,d=1);var f=1.5*(a.h<a.w?a.h:
a.w),g=a.x+.3*a.w,h=a.y+.4*a.h;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:b,Actions:[{Action:"move",x:a.x+.2*a.w,y:a.y+a.h},{Action:"line",x:a.x+.4*a.w,y:a.y},{Action:"move",x:a.x,y:a.y+.6*a.h},{Action:"line",x:a.x+a.w,y:a.y+.1*a.h},{Action:"move",x:a.x,y:a.y+.8*a.h},{Action:"line",
x:a.x+.2*a.w,y:a.y+.8*a.h},{Action:"curve",Control:[{x1:a.x+.4*a.w,y1:a.y+.8*a.h,x2:a.x+.7*a.w,y2:a.y+.6*a.h,x3:a.x+.8*a.w,y3:a.y+.55*a.h}]},{Action:"line",x:a.x+a.w,y:a.y+.5*a.h},{Action:"move",x:a.x+.5*a.w,y:a.y},{Action:"line",x:a.x+.55*a.w,y:a.y+.1*a.h},{Action:"curve",Control:[{x1:a.x+.6*a.w,y1:a.y+.2*a.h,x2:a.x+.8*a.w,y2:a.y+.3*a.h,x3:a.x+.8*a.w,y3:a.y+.55*a.h}]}]},{FillColor:"#0088FF",StrokeColor:c.LineColor,LineWidth:d,Actions:[{Action:"move",x:g-.1*f,y:h-.1*f},{Action:"curve",Control:[{x1:g-
.05*f,y1:h-.08*f,x2:g-.05*f,y2:h-.08*f,x3:g,y3:h-.1*f},{x1:g+.05*f,y1:h-.08*f,x2:g+.05*f,y2:h-.08*f,x3:g+.1*f,y3:h-.1*f},{x1:g+.15*f,y1:h-.05*f,x2:g+.15*f,y2:h+.1*f,x3:g,y3:h+.15*f},{x1:g-.15*f,y1:h+.1*f,x2:g-.15*f,y2:h-.05*f,x3:g-.1*f,y3:h-.1*f}]},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"UIButtonBlock",name:"UIButton",searchKeywords:[],defaultSize:{w:160,h:40},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"Button",getBoundingBox:function(c){return{x:c.x+
.2*c.w,y:c.y+.2*c.h,w:.6*c.w,h:.6*c.h}}})},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox,b=.3*(a.h>a.w?a.w:a.h);return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+b,y:a.y},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x,a.y,2*b,2*b,1.5*Math.PI,Math.PI)},{Action:"line",x:a.x,y:a.y+a.h-b},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x,
a.y+a.h-2*b,2*b,2*b,Math.PI,.5*Math.PI)},{Action:"line",x:a.x+a.w-b,y:a.y+a.h},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x+a.w-2*b,a.y+a.h-2*b,2*b,2*b,.5*Math.PI,0)},{Action:"line",x:a.x+a.w,y:a.y+b},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x+a.w-2*b,a.y,2*b,2*b,2*Math.PI,1.5*Math.PI)},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"UICheckBoxBlock",name:"UICheckBox",searchKeywords:[],defaultSize:{w:40,h:40},getLinkPoints:function(c){return[{x:0,
y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox,b=8;"sample"==e&&(a={x:Math.round(a.x+.25*a.w),y:Math.round(a.y+.25*a.h),w:Math.round(.5*a.w),h:Math.round(.5*a.h)},b=4);return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:b,NoRounding:!0,Actions:[{Action:"move",
x:a.x+.2*a.w,y:a.y+.4*a.h},{Action:"line",x:a.x+.4*a.w,y:a.y+.7*a.h},{Action:"line",x:a.x+.8*a.w,y:a.y+.3*a.h}]}]}});lucid.plugin.initBlockClass({className:"UIRadioBlock",name:"UIRadio",searchKeywords:[],defaultSize:{w:40,h:40},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox;"sample"==e&&(a={x:Math.round(a.x+.25*a.w),y:Math.round(a.y+.25*a.h),w:Math.round(.5*a.w),h:Math.round(.5*a.h)});return[{FillColor:c.FillColor,StrokeColor:c.LineColor,
LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+a.w,y:a.y+a.h/2},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x,a.y,a.w,a.h,0,2*Math.PI)},{Action:"close"}]},{FillColor:"#000000",StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+.75*a.w,y:a.y+a.h/2},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x+.25*a.w,a.y+.25*a.h,.5*a.w,.5*a.h,0,2*Math.PI)},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"UISelectBlock",name:"UISelect",searchKeywords:[],
defaultSize:{w:200,h:40},onInit:function(c){lucid.plugin.addBlockTextArea(c,{id:"Text",value:"Option",getBoundingBox:function(c){return{x:c.x+.1*c.w,y:c.y+.1*c.h,w:.8*c.w-(c.h<c.w?c.h:c.w),h:.8*c.h}}})},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox,b=c.LineWidth;"sample"==e&&(b=1);var d=(a.h>a.w?a.w:a.h)-4*b;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y},
{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:b,Actions:[{Action:"move",x:a.x+a.w-d-2*b,y:a.y+2*b},{Action:"line",x:a.x+a.w-2*b,y:a.y+2*b},{Action:"line",x:a.x+a.w-2*b,y:a.y+a.h-2*b},{Action:"line",x:a.x+a.w-d-2*b,y:a.y+a.h-2*b},{Action:"close"}]},{FillColor:"#000000",StrokeColor:c.LineColor,LineWidth:b,NoRounding:!0,Actions:[{Action:"move",x:a.x+a.w-.8*d-2*b,y:a.y+.3*d+2*b},{Action:"line",
x:a.x+a.w-.2*d-2*b,y:a.y+.3*d+2*b},{Action:"line",x:a.x+a.w-.5*d-2*b,y:a.y+.7*d+2*b},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"UIVSliderBlock",name:"UIVSlider",searchKeywords:[],defaultSize:{w:40,h:240},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox,b=c.LineWidth,d=a.w>a.h?a.h:a.w;"sample"==e&&(b=1);return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,NoRounding:!0,Actions:[{Action:"move",
x:a.x+.5*a.w-b,y:a.y},{Action:"line",x:a.x+.5*a.w-b,y:a.y+a.h},{Action:"line",x:a.x+.5*a.w+b,y:a.y+a.h},{Action:"line",x:a.x+.5*a.w+b,y:a.y},{Action:"close"}]},{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x+a.w,y:a.y+.3*a.h},{Action:"line",x:a.x,y:a.y+.3*a.h},{Action:"line",x:a.x,y:a.y+.3*a.h+.6*d},{Action:"line",x:a.x+a.w,y:a.y+.3*a.h+.6*d},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"UIHSliderBlock",name:"UIHSlider",searchKeywords:[],
defaultSize:{w:240,h:40},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox,b=c.LineWidth,d=a.w>a.h?a.h:a.w;"sample"==e&&(b=1);return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,NoRounding:!0,Actions:[{Action:"move",y:a.y+.5*a.h-b,x:a.x},{Action:"line",y:a.y+.5*a.h-b,x:a.x+a.w},{Action:"line",y:a.y+.5*a.h+b,x:a.x+a.w},{Action:"line",y:a.y+.5*a.h+b,x:a.x},{Action:"close"}]},{FillColor:c.FillColor,StrokeColor:c.LineColor,
LineWidth:c.LineWidth,Actions:[{Action:"move",y:a.y+a.h,x:a.x+.3*a.w},{Action:"line",y:a.y+.3*d,x:a.x+.3*a.w},{Action:"line",y:a.y,x:a.x+.3*a.w+.3*d},{Action:"line",y:a.y+.3*d,x:a.x+.3*a.w+.6*d},{Action:"line",y:a.y+a.h,x:a.x+.3*a.w+.6*d},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"UIVScrollBlock",name:"UIVScroll",searchKeywords:[],defaultSize:{w:40,h:240},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox,
b=c.LineWidth;"sample"==e&&(b=1);var d=(a.h>a.w?a.w:a.h)-4*b;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:b,Actions:[{Action:"move",x:a.x+2*b,y:a.y+2*b},{Action:"line",x:a.x+d+2*b,y:a.y+2*b},{Action:"line",x:a.x+d+2*b,y:a.y+d+2*b},{Action:"line",x:a.x+2*b,y:a.y+d+2*b},{Action:"close"}]},
{FillColor:"#000000",StrokeColor:c.LineColor,LineWidth:b,NoRounding:!0,Actions:[{Action:"move",x:a.x+.2*d+2*b,y:a.y+.7*d+2*b},{Action:"line",x:a.x+.8*d+2*b,y:a.y+.7*d+2*b},{Action:"line",x:a.x+.5*d+2*b,y:a.y+.3*d+2*b},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:b,Actions:[{Action:"move",x:a.x+2*b,y:a.y+d+4*b},{Action:"line",x:a.x+d+2*b,y:a.y+d+4*b},{Action:"line",x:a.x+d+2*b,y:a.y+(a.h-2*d-4*b)/2+d+4*b},{Action:"line",x:a.x+2*b,y:a.y+(a.h-2*d-4*b)/2+d+4*b},{Action:"close"}]},{StrokeColor:c.LineColor,
LineWidth:b,Actions:[{Action:"move",x:a.x+4*b,y:a.y+(a.h-2*d-4*b)/4+d+2*b},{Action:"line",x:a.x+d,y:a.y+(a.h-2*d-4*b)/4+d+2*b},{Action:"move",x:a.x+4*b,y:a.y+(a.h-2*d-4*b)/4+d+4*b},{Action:"line",x:a.x+d,y:a.y+(a.h-2*d-4*b)/4+d+4*b},{Action:"move",x:a.x+4*b,y:a.y+(a.h-2*d-4*b)/4+d+6*b},{Action:"line",x:a.x+d,y:a.y+(a.h-2*d-4*b)/4+d+6*b}]},{StrokeColor:c.LineColor,LineWidth:b,Actions:[{Action:"move",x:a.x+2*b,y:a.y+a.h-2*b},{Action:"line",x:a.x+d+2*b,y:a.y+a.h-2*b},{Action:"line",x:a.x+d+2*b,y:a.y+
a.h-d-2*b},{Action:"line",x:a.x+2*b,y:a.y+a.h-d-2*b},{Action:"close"}]},{FillColor:"#000000",StrokeColor:c.LineColor,LineWidth:b,NoRounding:!0,Actions:[{Action:"move",x:a.x+.2*d+2*b,y:a.y+a.h-.7*d-2*b},{Action:"line",x:a.x+.8*d+2*b,y:a.y+a.h-.7*d-2*b},{Action:"line",x:a.x+.5*d+2*b,y:a.y+a.h-.3*d-2*b},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"UIHScrollBlock",name:"UIHScroll",searchKeywords:[],defaultSize:{w:240,h:40},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,
y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox,b=c.LineWidth;"sample"==e&&(b=1);var d=(a.w>a.h?a.h:a.w)-4*b;return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",y:a.y,x:a.x},{Action:"line",y:a.y+a.h,x:a.x},{Action:"line",y:a.y+a.h,x:a.x+a.w},{Action:"line",y:a.y,x:a.x+a.w},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:b,Actions:[{Action:"move",y:a.y+2*b,x:a.x+2*b},{Action:"line",y:a.y+d+2*b,x:a.x+2*b},{Action:"line",y:a.y+
d+2*b,x:a.x+d+2*b},{Action:"line",y:a.y+2*b,x:a.x+d+2*b},{Action:"close"}]},{FillColor:"#000000",StrokeColor:c.LineColor,LineWidth:b,NoRounding:!0,Actions:[{Action:"move",y:a.y+.2*d+2*b,x:a.x+.7*d+2*b},{Action:"line",y:a.y+.8*d+2*b,x:a.x+.7*d+2*b},{Action:"line",y:a.y+.5*d+2*b,x:a.x+.3*d+2*b},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:b,Actions:[{Action:"move",y:a.y+2*b,x:a.x+d+4*b},{Action:"line",y:a.y+d+2*b,x:a.x+d+4*b},{Action:"line",y:a.y+d+2*b,x:a.x+(a.w-2*d-4*b)/2+d+4*b},{Action:"line",
y:a.y+2*b,x:a.x+(a.w-2*d-4*b)/2+d+4*b},{Action:"close"}]},{StrokeColor:c.LineColor,LineWidth:b,Actions:[{Action:"move",y:a.y+4*b,x:a.x+(a.w-2*d-4*b)/4+d+2*b},{Action:"line",y:a.y+d,x:a.x+(a.w-2*d-4*b)/4+d+2*b},{Action:"move",y:a.y+4*b,x:a.x+(a.w-2*d-4*b)/4+d+4*b},{Action:"line",y:a.y+d,x:a.x+(a.w-2*d-4*b)/4+d+4*b},{Action:"move",y:a.y+4*b,x:a.x+(a.w-2*d-4*b)/4+d+6*b},{Action:"line",y:a.y+d,x:a.x+(a.w-2*d-4*b)/4+d+6*b}]},{StrokeColor:c.LineColor,LineWidth:b,Actions:[{Action:"move",y:a.y+2*b,x:a.x+
a.w-2*b},{Action:"line",y:a.y+d+2*b,x:a.x+a.w-2*b},{Action:"line",y:a.y+d+2*b,x:a.x+a.w-d-2*b},{Action:"line",y:a.y+2*b,x:a.x+a.w-d-2*b},{Action:"close"}]},{FillColor:"#000000",StrokeColor:c.LineColor,LineWidth:b,NoRounding:!0,Actions:[{Action:"move",y:a.y+.2*d+2*b,x:a.x+a.w-.7*d-2*b},{Action:"line",y:a.y+.8*d+2*b,x:a.x+a.w-.7*d-2*b},{Action:"line",y:a.y+.5*d+2*b,x:a.x+a.w-.3*d-2*b},{Action:"close"}]}]}});lucid.plugin.initBlockClass({className:"UIProgressBarBlock",name:"UIProgressBar",searchKeywords:[],
defaultSize:{w:240,h:40},getLinkPoints:function(c){return[{x:0,y:.5},{x:.5,y:1},{x:1,y:.5},{x:.5,y:0}]},getRenderData:function(c,e){var a=c.BoundingBox,b=c.LineWidth;"sample"==e&&(b=1);var d=lucid.color.darken(c.FillColor,.5);return[{FillColor:c.FillColor,StrokeColor:c.LineColor,LineWidth:c.LineWidth,Actions:[{Action:"move",y:a.y,x:a.x},{Action:"line",y:a.y+a.h,x:a.x},{Action:"line",y:a.y+a.h,x:a.x+a.w},{Action:"line",y:a.y,x:a.x+a.w},{Action:"close"}]},{FillColor:d,StrokeColor:c.LineColor,LineWidth:b,
Actions:[{Action:"move",x:a.x+2*b,y:a.y+2*b},{Action:"line",x:a.x+2*b,y:a.y+a.h-2*b},{Action:"line",x:a.x+.4*a.w,y:a.y+a.h-2*b},{Action:"line",x:a.x+.4*a.w,y:a.y+2*b},{Action:"close"}]}]}});lucid.plugin.createToolGroups({"User Interface":"UIAreaBlock UIWindowBlock UIDialogBlock UIElementBlock UIImageBlock UIVideoBlock UIMapBlock UIButtonBlock UICheckBoxBlock UIRadioBlock UISelectBlock UIVSliderBlock UIHSliderBlock UIVScrollBlock UIHScrollBlock UIProgressBarBlock".split(" ")})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/ui.js.map
};
