pluginFn['/js/plugins/v2/userimage.js'] = function(lucid, window) {
	(function(){function m(){function a(a){p&&!1===p(a)||255<=c++||b[h].push({className:"UserImage2Block",name:"UserImage-"+a.id,toolBoxId:"UserImage-"+a.id,imageId:a.id,tooltip:a.name||"Unnamed Image",defaultSize:{w:a.defaultSize.width,h:a.defaultSize.height},defaultProperties:function(){return{Text:"",FillColor:{pos:config.defaultImageFillPos,url:a.url},LineWidth:0,AspectRatio:a.defaultSize.width/a.defaultSize.height}},menuItems:a.isTeamImage?[]:[{label:"Delete",action:function(){lucid.plugin.deleteUserImage(a.id)}}]})}
var c=0,b={};b[h]=[];var e=function(a){var b=a.tags[0],c=!0;a.children.length&&(c=lucid.array.every(a.children,e));return c?!lucid.object.some(n,function(a){return lucid.array.some(a.tags,function(a){return b.key==a.key})}):!1},u=function(a){p=a&&"__all__"!=a?"__itd__"==a?function(a){return a.inDocument}:"__untagged__"==a?function(a){return 0===a.tags.length}:function(b){return lucid.array.some(b.tags,function(b){return b.key==a})}:t;q=a;lucid.localStorage.set("userImageSelectedFilter",a)};u(q);var g=
!1,f=function(){if(!g){g=!0;var a=lucid.template.builder();a.clear();a.add({classes:"heading",text:"Team Images"});b[h].push({template:a.getTemplate()})}},d=lucid.plugin.getTagTree(),l=[{label:"All Images",value:"__all__"},{label:"In this Document",value:"__itd__"},{label:"Untagged",value:"__untagged__"},{label:"Archived",value:"archived"},{separator:!0}];lucid.config.on_premise&&l.splice(2,2);var r=[{separator:!0}],k=function(a,b){for(var c="",d=0;d<b;d++)c=d==b-1?c+"- ":c+"--";d=a.tags[0].key;"archived"==
d||"private"==d||e(a)||((lucid.array.some(a.tags,function(a){return a.thirdParty})?r:l).push({label:c+a.tags[0].name,value:d}),lucid.array.forEach(a.children,function(a){k(a,b+1)}))};lucid.array.forEach(d,function(a){k(a,0)});1<r.length&&(l=l.concat(r));d=lucid.template.builder();d.open({css:{padding:"4px 6px 2px 4px"}});lucid.array.forEach(l,function(a){a.value==q&&(a.selected=!0)});d.addInput({type:"select",options:l,onChange:function(a,b){b||(u(a),m())}});d.clear();d.close();b[h].push({template:d.getTemplate()});
b[h].push({template:{classes:"tool-box-block left add-button",title:"Add Image",click:function(){lucid.plugin.showUserImageDialog(function(a){m()},{refreshImagesInDocument:!0,useDefaultSuccess:!0,source:"add image in toolbar"})}},onlineOnly:!0});d=v(n);lucid.array.forEach(d.userImages,a);d.teamImages.length&&(f(),lucid.array.forEach(d.teamImages,a));lucid.plugin.inDemoMode()||lucid.plugin.createToolGroups(b)}var g={global:this,provide:function(a){a=a.split(".");g.global[a[0]]=g.global[a[0]]||{};var c=
g.global[a[0]];a.slice(1).reduce(function(a,c){a[c]||(a[c]={});return a[c]},c)},require:function(){},inherits:function(a,c){function b(){}b.prototype=c.prototype;a.superClass_=c.prototype;a.prototype=new b;a.prototype.constructor=a;a.base=function(a,b,g){var f=Array.prototype.slice.call(arguments,2);return c.prototype[b].apply(a,f)}},base:function(a,c,b){var e=arguments.callee.caller;if(g.STRICT_MODE_COMPATIBLE||g.DEBUG&&!e)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");
if(e.superClass_)return e.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var h=Array.prototype.slice.call(arguments,2),k=!1,f=a.constructor;f;f=f.superClass_&&f.superClass_.constructor)if(f.prototype[c]===e)k=!0;else if(k)return f.prototype[c].apply(a,h);if(a[c]===e)return a.constructor.prototype[c].apply(a,h);throw Error("goog.base called from a method of one name to a method of a different name");}};g.provide("plugin.userimage");var n={},t=function(a){return!a.hidden&&
lucid.array.every(a.tags,function(a){return"archived"!=a.key})},q=lucid.localStorage.get("userImageSelectedFilter"),p=t,k=function(a,c){return(a.created<c.created)-(a.created>c.created)},v=function(a){var c=[],b=[],e;for(e in a)a[e].isTeamImage?b.push(a[e]):c.push(a[e]);c.sort(k);b.sort(k);return{userImages:c,teamImages:b}};lucid.plugin.initBlockClass({className:"UserImage2Block",name:"User Image",searchKeywords:[],defaultSize:{w:160,h:120},getLinkPoints:function(){return[{x:.5,y:0},{x:.5,y:1},{x:0,
y:.5},{x:1,y:.5}]},getRenderData:function(a,c){var b=a.BoundingBox;return[{FillColor:a.FillColor,StrokeColor:a.LineColor,LineWidth:a.LineWidth,Actions:[{Action:"move",x:b.x,y:b.y},{Action:"line",x:b.x+b.w,y:b.y},{Action:"line",x:b.x+b.w,y:b.y+b.h},{Action:"line",x:b.x,y:b.y+b.h},{Action:"close"}]}]}});var h=lucid.config.on_premise?lucid.i18n("toolbox.userimages.title.onprem"):lucid.i18n("toolbox.userimages.title");lucid.i18n("toolbox.teamimages.title");lucid.plugin.inDemoMode()||lucid.plugin.createToolGroups({"User Images":[]});
lucid.plugin.onActivate(function(){m()});lucid.plugin.onUserImagesChanged(function(a){n=a;for(var c in n);setTimeout(function(){m()},100)});lucid.plugin.initBlockClass({className:"URLImageBlock",name:"User Image (URL)",searchKeywords:[],defaultSize:{w:120,h:120},isImageBlock:function(){return!0},disabledPropertyControls:["FillColor","FillType","LineColor","LineWidth"],onInit:function(a){lucid.plugin.registerProperty(a,"URL","")},getRenderData:function(a,c){return[{Image:a.URL,BoundingBox:a.BoundingBox}]}});
lucid.plugin.initBlockClass({className:"UserImageBlock",name:"User Image",searchKeywords:[],defaultSize:{w:160,h:120},isImageBlock:function(){return!0},disabledPropertyControls:["FillColor","FillType","LineColor","LineWidth"],onInit:function(a){lucid.plugin.registerProperty(a,"URL","")},getRenderData:function(a,c){return[{Image:a.URL,BoundingBox:a.BoundingBox}]},getLinkPoints:function(a){return[{x:.5,y:0},{x:.5,y:1},{x:0,y:.5},{x:1,y:.5}]}})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/userimage.js.map
};
