pluginFn['/js/plugins/v2/video.js'] = function(lucid, window) {
	(function(){function l(b,f,a,c){lucid.dialog.prompt("Enter a YouTube or Vimeo URL:",(c?"http://vimeo.com/":"http://youtube.com/watch?v=")+f,function(h){var d=lucid.video.getVideoProps(h);if(d){var e=d.id;lucid.video.videoExists(d.type,e,function(){lucid.plugin.setProperty(b,"VideoId",e);"vimeo"==d.type?(lucid.plugin.setProperty(b,"VideoSource","vimeo"),lucid.video.getVimeoThumbnail(e,function(a){lucid.plugin.setProperty(b,"VideoThumb",a[0].thumbnail_large)})):(lucid.plugin.setProperty(b,"VideoSource",
"youtube"),lucid.plugin.setProperty(b,"VideoThumb","null"))},function(){lucid.dialog.alert("The video id doesn't appear to be valid: "+e,function(){a?null==lucid.plugin.getProperty(b,"VideoId")&&lucid.plugin.deleteItem(b):l(b,f,!0,c)})})}else lucid.dialog.alert("Failed to parse video ID from url: "+h,function(){a?null==lucid.plugin.getProperty(b,"VideoId")&&lucid.plugin.deleteItem(b):l(b,f,!0,c)})},function(){null==lucid.plugin.getProperty(b,"VideoId")&&lucid.plugin.deleteItem(b)},{title:lucid.i18n("dialogs.video.title")})}
var k={global:this,provide:function(b){b=b.split(".");k.global[b[0]]=k.global[b[0]]||{};var f=k.global[b[0]];b.slice(1).reduce(function(a,b){a[b]||(a[b]={});return a[b]},f)},require:function(){},inherits:function(b,f){function a(){}a.prototype=f.prototype;b.superClass_=f.prototype;b.prototype=new a;b.prototype.constructor=b;b.base=function(a,b,d){var e=Array.prototype.slice.call(arguments,2);return f.prototype[b].apply(a,e)}},base:function(b,f,a){var c=arguments.callee.caller;if(k.STRICT_MODE_COMPATIBLE||
k.DEBUG&&!c)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(c.superClass_)return c.superClass_.constructor.apply(b,Array.prototype.slice.call(arguments,1));for(var h=Array.prototype.slice.call(arguments,2),d=!1,e=b.constructor;e;e=e.superClass_&&e.superClass_.constructor)if(e.prototype[f]===c)d=!0;else if(d)return e.prototype[f].apply(b,h);if(b[f]===c)return b.constructor.prototype[f].apply(b,
h);throw Error("goog.base called from a method of one name to a method of a different name");}};k.provide("plugin.video");lucid.plugin.initBlockClass({className:"YouTubeVideoBlock",name:"Youtube Video",defaultSize:{w:460,h:280},textLinking:!1,disabledPropertyControls:"FillColor FillType LineColor LineWidth FlipX FlipY".split(" "),rLock:!0,noDropBackground:!0,video:!0,defaultProperties:function(){return{AspectRatio:460/280}},onCreate:function(b){l(b,"")},onInit:function(b){lucid.plugin.setProperty(b,
"showVideo",!1,!0);"viewer"==lucid.plugin.getClientRole()&&lucid.plugin.setProperty(b,"showVideo",!0,!0);lucid.plugin.registerProperty(b,"VideoSource","youtube")},onDblClick:function(b){l(b,lucid.plugin.getProperty(b,"VideoId"),!1,"vimeo"==lucid.plugin.getProperty(b,"VideoSource"))},getRenderData:function(b,f){var a=b.BoundingBox,c=null;"sample"==f||"preview"==f?c=lucid.config.assets_base_url+"/app/webroot/img/video/lucid_youtube.png":"vimeo"==b.VideoSource&&b.VideoThumb&&"null"!=b.VideoThumb?c=b.VideoThumb:
"youtube"==b.VideoSource&&b.VideoId&&(c="https://img.youtube.com/vi/"+b.VideoId+"/0.jpg");var h="#000000";c&&(h={pos:"fill",url:c});var c=Math.min(.4*a.w,.25*a.h),d=2*c/3,e=.2*d,g=2*e;return[{FillColor:h,StrokeColor:null,LineWidth:null,NoRounding:!0,Actions:[{Action:"move",x:a.x,y:a.y},{Action:"line",x:a.x+a.w,y:a.y},{Action:"line",x:a.x+a.w,y:a.y+a.h},{Action:"line",x:a.x,y:a.y+a.h},{Action:"close"}]},{FillColor:"vimeo"==b.VideoSource?"#1ab7ea":"#d41e20",StrokeColor:null,LineWidth:0,Actions:[{Action:"move",
x:a.x+.5*a.w-c/2,y:a.y+.5*a.h-d/2},{Action:"line",x:a.x+.5*a.w-c/2,y:a.y+.5*a.h+d/2-e},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x+.5*a.w-c/2,a.y+.5*a.h-d/2+d-g,g,g,Math.PI,.5*Math.PI)},{Action:"line",x:a.x+.5*a.w-c/2+c-e,y:a.y+.5*a.h-d/2+d},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x+.5*a.w-c/2+c-g,a.y+.5*a.h-d/2+d-g,g,g,.5*Math.PI,0)},{Action:"line",x:a.x+.5*a.w-c/2+c,y:a.y+.5*a.h-d/2+e},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x+.5*a.w-
c/2+c-g,a.y+.5*a.h-d/2,g,g,0,-.5*Math.PI)},{Action:"line",x:a.x+.5*a.w-c/2+e,y:a.y+.5*a.h-d/2},{Action:"curve",Control:lucid.math.ellipseArcControlPoints(a.x+.5*a.w-c/2,a.y+.5*a.h-d/2,g,g,-.5*Math.PI,-Math.PI)},{Action:"close"}]},{FillColor:"#FFFFFF",StrokeColor:null,LineWidth:0,NoRounding:!0,Actions:[{Action:"move",x:a.x+.5*a.w-.15*c,y:a.y+.5*a.h-.25*d},{Action:"line",x:a.x+.5*a.w+.2*c,y:a.y+.5*a.h},{Action:"line",x:a.x+.5*a.w-.15*c,y:a.y+.5*a.h+.25*d},{Action:"close"}]}]}});lucid.plugin.onContextChanged(function(b){"viewer"!=
lucid.plugin.getClientRole()&&(lucid.array.contains(b,"presentation")?(b=lucid.plugin.getAllBlockIds(),lucid.array.forEach(b,function(b){"YouTubeVideoBlock"==lucid.plugin.getBlockClassName(b)&&lucid.plugin.setProperty(b,"showVideo",!0,!0)})):(b=lucid.plugin.getAllBlockIds(),lucid.array.forEach(b,function(b){"YouTubeVideoBlock"==lucid.plugin.getBlockClassName(b)&&lucid.plugin.setProperty(b,"showVideo",!1,!0)})))});lucid.plugin.createToolGroups({Video:[{className:"YouTubeVideoBlock",size:"large"}]})})();
//# sourceMappingURL=/js/plugins/v2/source-maps/video.js.map
};
